### PR TITLE
Add Baofeng DM-5R support to bin2sgl and firmware_loader tools

### PR DESCRIPTION
**Pull request by ew1adg**
Add Baofeng DM-5R support to bin2sgl and firmware_loader tools

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Is the DM-5R the same as the RD-5R?

Some DM-5R's were only Tier1 and used an older DMR chip (C5000), but I think there may have been multiple versions of DM-5R

Do you plan to attempt to port the firmware?
If so you'd need to write a new display driver and the display type is unknown.

Do you have a link to the latest RD-5R and DM-5R firmwares ?

**Comment by rogerclarkmelbourne** [comment]
One other thing. Your .cproject has changed. 

As this is not a firmware change, the .cproject should not have changed, and you commit and push a version which does not change the .cproject.

**Comment by ew1adg** [comment]
This is a Baofeng DM-5R (mk2). this radio have a HRC6000 chip inside.
At this moment i have RX-TX already working from this radio.

**Comment by rogerclarkmelbourne** [comment]
@ew1adg 

Do you mean you have a OpenGD77 build target which you remapped all the pins for the C6000 and LED's and keypad, and RF control etc ?
So that DMR Tx and Rx is possible?

Did you write a display driver ?

**Comment by ew1adg** [comment]
Yes. at this time i am working with this.
This radio using the same display driver, but display have 128x48px resolution

**Comment by rogerclarkmelbourne** [comment]
OK

Can you do a PR even though its not complete. I can pull your PR into a separte branch

**Comment by ew1adg** [comment]
Ok. for next 2-3 day i will commit other parts of code as separate PR.

IMG_20200328_073738
IMG_20200328_073826
IMG_20200328_073859

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks

I have a RD-5R. Perhaps its the same type of radio.

**Comment by rogerclarkmelbourne** [comment]
@ew1adg 

Unrelated question, but can you remember which PCB pads are connected to the speaker.

I re-assembled my RD-5R but the speaker is not working, so perhaps I connected to the wrong pads

**Comment by ew1adg** [comment]
> @ew1adg
> 
> Unrelated question, but can you remember which PCB pads are connected to the speaker.
> 
> I re-assembled my RD-5R but the speaker is not working, so perhaps I connected to the wrong pads

IMG_20200215_232909_crop

**Comment by rogerclarkmelbourne** [comment]
Thsnkyou

**Comment by rogerclarkmelbourne** [comment]
Note. 
I had to revert the linux exe and rebuild the Windows exe, as there was a merge conflict with Daniel's subsequent PRs

Daniel can you pull and then rebuild the Linux exe and submit a PR for it, as I don't think I have the toolchain installed on any of my machines to build the linux exe

**Comment by f1rmb** [comment]
No Problem.

**Comment by rogerclarkmelbourne** [comment]
@f1rmb 

Thankyou

**Comment by rogerclarkmelbourne** [comment]
@ew1adg 

BTW. My PCB has the same text 5R-DMR , so I think the RD-5R and DM-5R are identical except perhaps or the original official firmware and also the model number on the outside of the radio

@f1rmb 

Can you change the text as well in the UI to read DM-5R / RD-5R

**Comment by f1rmb** [comment]
Okay.

**Comment by f1rmb** [comment]
Roger,

done, and PR raised ;-)

Cheers.
...
Daniel

**Pull request merged**
