### PR TITLE
Default squelch settings for 3 bands, and also changed the way band c…

### PR DESCRIPTION
**Pull request by rogerclarkmelbourne**
I'm doing this a pull request to myself as its quite a complicated change and will be easier to review.

The initial purpose was to add squelch defaults in the Options for VHF, 220Mhz and UHF bands.

But I realised that the squelch code would need to constantly check which band was in use, so I added a new variable to old the current Rx and Tx band etc, and modified the code which used code that does a band lookup from the frequency.

This ended up being a much bigger change than I anticipated, but I think does improve things, as there is not so much need to lookup the band from the frequency.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
No comments?

**Comment by f1rmb** [comment]
Not tested yet :-(

**Comment by alexernst** [comment]
Didn't have time today. But will try to find some tomorrow.

**Comment by rogerclarkmelbourne** [comment]
Its OK.

I've reviewed it a few times myself

I will merge.  But at least there is a record of what has been merged.

**Pull request merged**
