### PR TITLE
Reverse logic of gMenusCurrentItemIndex value managment: the system k…

### PR DESCRIPTION
**Pull request by f1rmb**
…eeps track of it, and it's up to the menuFunction() to override it.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
umm. OK. Is this method better?

**Comment by f1rmb** [comment]
It moves the gMenusCurrenItemIndex init outside the menuFunction()s, by default, get rid of repetitive init of that variable, and remove the extra function parameter.
At least, the menuFunction()s don't handle this variable init by default. It's cleaner I think, and it's still possible to change gMenusCurrenItemIndex if required (two menuFunctions already does that, actually).

**Comment by f1rmb** [comment]
In fact, I was thinking doing that way at the beginning, but changed my mind because I'm always skeptical to put revolution. ;-)

**Comment by rogerclarkmelbourne** [comment]
OK. 

Sometimes revolution is necessary.  My change for default squelch needed a revolution because I thought it was inefficient if I did not make a lot of changes.

**Comment by f1rmb** [comment]
Yeah, but it's your project / code. I've been there, then the guy (s) just starts being ... silent. Even if the goal is to make it better, for everyone.
Lucky me, **you're not like that**, and I wasn't obliged to maintain a parallel fork.

**Comment by rogerclarkmelbourne** [comment]
LOL

I'm pragmatic, but I don't accept all PR's ;-)

**Comment by f1rmb** [comment]
Yeah, and I understand that you don't accept everything. I've also being part of some other projects, where we had to do the same, sometimes rejecting patches because it was just too specific/personnal, or completely crazy (or simply ugly) ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I've tested and merged, because its a cleaner implementation.

**Pull request merged**
