### PR TITLE
Contact details + New contact

### PR DESCRIPTION
**Pull request by alexernst**
This adds the ability to edit Contacts and to save new Contacts.
In this version the contact name is not editable, as this requires the possibility to enter letters. 
I'll add that next.

Usage:
- Open 'Contact List' either with Blue+# or from menu.
- Select a Contact and long press GREEN to go to details.
- Save with GREEN, leave without saving RED.

This uses some new parts of the keypad code. The new features are only enabled for MENU_CONTACT_LIST and MENU_CONTACT_DETAILS (fw_main.c l.182ff)

I'm not sure about the long press GREEN, tried Blue+GREEN or RIGHT but didn't really like both. 
Perhaps we should make an extra version before pulling and ask the forum?

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks I will download and test later today

**Comment by rogerclarkmelbourne** [comment]
@alexernst 

Thanks.

I've done some tests and I have found some problems

The function to convert from buf to data is writing beyond the end of the buffer and should also fill the unused characters with 0xff

This is a fix for that problem

```
void codeplugUtilConvertStringToBuf(char *inBuf,char *outBuf,int len)
{
	memset(outBuf,0xff,len);// prefill with 0xff like the CPS does.
	for (int i = 0; i < len; i++)
	{
		if (inBuf[i] != 0x00)
		{
			outBuf[i] = inBuf[i];
		}
		else
		{
			break;
		}
	}
	return;
}
```

Also.

I think it is better if the Channel name gets set to "TG xxx" where xxx is the number, as its better than just naming them Contactxxx

Hence in uiMenuContactDetails in handle event, change the code to sprintf the "TG %d"

```
else if (KEYCHECK_SHORTUP(keys,KEY_GREEN))
		{
			char buf[17];
			if (tmpContact.callType == CONTACT_CALLTYPE_ALL) {
				tmpContact.tgNumber = 16777215;
			}
			if (contactListContactIndex > 0 && contactListContactIndex <= 1024) {
				tmpContact.tgNumber = atoi(digits);

				sprintf(buf,"TG %d",tmpContact.tgNumber);
				codeplugUtilConvertStringToBuf(buf, tmpContact.name, 16);

				codeplugContactSaveDataForIndex(contactListContactIndex, &tmpContact);
				contactListContactIndex = 0;
				menuSystemPushNewMenu(MENU_SAVED_SCREEN);
			}
			return;
		}
```

Also.

The function to find the Contact does not seem to be working correctly.

I loaded a codeplug with only 1 channel in it, them made 2 new contacts, but when I tried to select any of the new contacts, it didn't work.

I'm not sure of the operation of this function, but index of 0 can be passed, hence index--; makes the index number negative

```
int codeplugContactGetDataForNumber(int index, int callType, struct_codeplugContact_t *contact)
{
	int pos = 0;
	for (int i = 1; i <= 1024; i++)
	{
		codeplugContactGetDataForIndex(i, contact);
		if (contact->name[0] != 0xff && contact->callType == callType) {
			index--;
		}
		if (index == 0) {
			pos = i;
			break;
		}
	}
	return pos;
}
```

Perhaps add a property to the struct_codeplugContact to store the index number when its loaded from Flash
E.g. in the RxGroup struct, I added an int for 

NOT_IN_MEMORY_numTGsInGroup

I should have actually called this

NOT_IN_CODEPLUGDATA_numTGsInGroup


```
typedef struct struct_codeplugRxGroup
{
	char name[16];
	uint16_t contacts[32];
	int	NOT_IN_MEMORY_numTGsInGroup;// NOT IN THE
} struct_codeplugRxGroup_t;
```

Hence

```
typedef struct struct_codeplugContact
{
	char 		name[16];
	uint32_t 	tgNumber;
	uint8_t		callType;
	uint8_t		callRxTone;
	uint8_t		ringStyle;
	uint8_t		reserve1;
        int                    NOT_IN_CODEPLUGDATA_indexNumber;
} struct_codeplugContact_t;
```

But some changes would need to be made, so that references to sizeof(struct_codeplugContact_t) would need to be changed when writing to Flash, so that the additional data is not saved.

In this way, there would not need to be a function to search for the index.

Thanks

Roger

**Comment by rogerclarkmelbourne** [comment]
Can you tell me when it is ready for me to merge again?

**Comment by alexernst** [comment]
I changed codeplugUtilConvertStringToBuf() to use memset and avoid the appended 0x00.

Finding a contact seems to work, but saving a Contact if it involves two flash sectors had an error.

Function codeplugContactGetDataForNumber() searches for a contact with the given callType.
So if there is a codeplug with 2 Contacts one Group Call, one Private Call and an unused empty Contact between those. This results in an index of 1 for the Group Call, 3 for the Private Call.
After
```
idx = codeplugContactGetDataForNumber(1, CONTACT_CALLTYPE_PC, &contact);
```
I have
`idx=3` and `contact`contains the 'Private Call' contact. So I have the first Private Call.

I added `NOT_IN_CODEPLUGDATA_indexNumber` even if I am not using this right now as it might be useful anyway.

And I changed the name of new contacts to include the TG.

There is another problem displaying the contactlist if there is only one Contact in the codeplug.
But that is related to the menuSystem. Displaying a menu with 2 entries works, but not only one entry.

**Comment by alexernst** [comment]
Try it now.

**Comment by rogerclarkmelbourne** [comment]
OK.

I will pull again

**Comment by rogerclarkmelbourne** [comment]
I did not have time to pull this. I will do it tomorrow.  Its too late for me. I need my sleep ;-)

**Comment by alexernst** [comment]
OK.

Do you think we could remove access to the contacts from uiTxTgPcContactOwnId.c as it is available through Blue+HASH?

**Comment by rogerclarkmelbourne** [comment]
I think blue + # is not a problem.
It would possibly be confusing to use blue + # for a completely different function

**Comment by rogerclarkmelbourne** [comment]
There is still some problem selecting channels from the list.

I made a codeplug with only 1 contact in it , using the CPS.
That contact is TG1 (default from the CPS)
In the radio I added 4 new TG's (I think the bug also occurs if there are 3 contacts)

After you add the 4th Contact, go to the Contacts List and select it.

The Contact that is then found by 

codeplugContactGetDataForNumber(gMenusCurrentItemIndex, contactCallType, &contact);

is not correct

gMenusCurrentItemIndex  for the new contact is 0
so 
codeplugContactGetDataForNumber returns 0, but the index of the contact is not 0. I think its probably index 4

Is contact 0 a valid index ?

Perhaps if the contact number selected you need to change it to the total number of contacts ?

**Comment by alexernst** [comment]
Got it. 
I will fix that and create a new commit.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thankyou

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks...

I will pull again and re-test

**Comment by alexernst** [comment]
Now it should work as intended.

Indices for contacts are from 1 to 1024. 
Indices for menu items start at 0. 
I did map gMenusCurrentItemIndex 0 to last contact of calltype, but only in updateDisplay(). So it looks good but didn't work for the last contact.

Also fixed the display of contact list with only 1 contact.

**Comment by rogerclarkmelbourne** [comment]
I think it is OK now.

Thankyou I will merge and update the Tier2_latest.sgl and ask people to test.

BTW. Perhaps we should now create a function to add a Contact to the Rx Group list of the current channel.

**Comment by rogerclarkmelbourne** [comment]
umm

Did I pull too soon.

I've merged and pushed.

I'll need to check if I have this latest change

**Comment by rogerclarkmelbourne** [comment]
umm

Looks like this is another change that was not in my last pull

I will wait until you are ready

**Comment by alexernst** [comment]
That version works too, just changed one function to be consistent within other codeplug functions.

**Comment by alexernst** [comment]
No more changes now.

**Comment by rogerclarkmelbourne** [comment]
OK..

**Comment by alexernst** [comment]
Adding a new contact to the actual Rx Group is definitely useful. But where to put?
Extra menu 'RX Group' or while creating a new contact?

**Comment by rogerclarkmelbourne** [comment]
I'll retest

**Comment by rogerclarkmelbourne** [comment]
Seems OK

I'll merge etc etc

**Comment by rogerclarkmelbourne** [comment]
Probably on the Channel extra menu.  

If the user has manually entered an override it would need to make a contact for the TG first.

Actually it would need to first search the contacts for the same TG in case the TG already exists.

**Comment by rogerclarkmelbourne** [comment]
One other nice feature...

When entering a PC. Check the DMR ID database, and if the ID is in the DMR ID database use the details (callsign and name) as the Contact name

**Comment by rogerclarkmelbourne** [comment]
Also.

We need to enhance the LastHeard, so that entries can be selected, and show more details, and also on this new screen to show the TG and time elapsed, there could be an option to add to Contacts

**Comment by alexernst** [comment]
Using the DMR ID database is easy. It just truncates dmrIdDataStruct.text to 16 chars.
Did a commit for this.

There is also a commit to delete private contacts from the contact list with Function+RED.

I looked already on the Last Heard screen. It works different than all other lists. That's an issue for its own.

**Comment by rogerclarkmelbourne** [comment]
Hi Alex

I originally wrote the LastHeard system for another project.
It uses a double linked list so that items can be moved in the list without needing to copy the item, only the pointers need to be changed, albeit several pointers.

**Pull request merged**
