### PR TITLE
Add a workaround for BlueDV as it doesn't setMode to DMR if a QSO is …

### PR DESCRIPTION
**Pull request by f1rmb**
…already running, when connecting the Master.

Bump FW version info.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I will merge this, 

But I think we should contact the author of BlueDV, as it would be better if BlueDV more closely mimicked what MMVMHost does

**Comment by rogerclarkmelbourne** [comment]
I am trying to contact David via youtube, as I can't find his email listed anywhere and his site does not not seem to have a Contact Me page

**Comment by f1rmb** [comment]
Hi Roger,

   Okay, hope he will reply.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Yes. I hope so.  As it would be better if we did not have to work-arounds for BlueDV

**Comment by f1rmb** [comment]
Yeah, I would be happy too also. Then it's presence could be detected as it's done with MMDVMHost (like calling getStatus when ideling, which is quite normal).

**Comment by f1rmb** [comment]
I'm afraid about Android version (and Linux too) as they haven't be updated for **quite** some time...

**Comment by rogerclarkmelbourne** [comment]
OK.

I found BlueDV was not very stable even on the PC, so I don't use it.

I compiled MMDVMHost from sources to Exe, and its much more reliable, but it doesnt have a nice UI that people want.

If I had time, I'm sure I could make a C# wrapper for MMDVMHost, but its very low on my priorities list and will probably never happen

**Comment by f1rmb** [comment]
Okay.
  Well, in the past, I tried BlueDV on Linux (mono), just for fun.
I never use the Windows version, as you can imagine, and about the Android version, I used it in the past with a DVMega + bluestack, in the car.
Since then, I built a lot of small and extra small MMDVM HS, and I'm happy with it.

But since OpenGD77, it raised from the dark...

**Pull request merged**
