### PR TITLE
Add simple VOX support, see "Sounds options".

### PR DESCRIPTION
**Pull request by f1rmb**
I didn't try on the 1801 yet.

Here, a Threshold of 3..4 looks fine.
The code avoid using 1, as it's way too low, and just trigger the vox all the time.
So, except for threshold value of zero (which turn the vox feature off), all other values are what is on option screen + 1, internally.
I set a default tail value of 2 seconds, as it looks fine. The tail values are units of 0.5 seconds.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks. 

It works well, but  I made some changes ;-)

I added code to use the VOX setting of the Channel or VFO (which is a channel), and changed the lower limit of the VOX threshold etc

Can you retest.


BTW.

I think we should add "Rx only" to the Channel details screen. I thought we had this, but its not present now, so perhaps it got removed somehow.
The flag bits are partially documented in the codeplug header.

**Comment by f1rmb** [comment]
Hi Roger,

  ;-)

Okay, I will re-test. Is the VOX a per-channel option ? (never use or used before).

**Comment by f1rmb** [comment]
To answer myself, yup, it is.

**Comment by rogerclarkmelbourne** [comment]
Yes. ;-)

**Comment by rogerclarkmelbourne** [comment]
The VFOs are also separate channels, they have the same data struct

I only tested in the VFO but it should work fine in for channels

**Comment by f1rmb** [comment]
Okay, I retested, it works.
Now, I need to check the HS mode, as I disable/reenable entering/leaving the hotspot.

**Comment by rogerclarkmelbourne** [comment]
OK.

The VOX enabled control is via the same function, but I didnt look at the HS code.

**Comment by rogerclarkmelbourne** [comment]
Ah.

Yes
It will be a problem

Setting threshold to zero no longer turns VOX off.

**Comment by rogerclarkmelbourne** [comment]
Can't we just check whether the radio is in hotspot mode in the VOX  check

**Comment by rogerclarkmelbourne** [comment]
settingsUsbMode == USB_MODE_HOTSPOT

like in HR-C6000

**Comment by rogerclarkmelbourne** [comment]
```
bool voxIsEnabled(void)
{
	return ((currentChannelData->flag4 & 0x40) && (settingsUsbMode != USB_MODE_HOTSPOT));
}
```

**Comment by rogerclarkmelbourne** [comment]
The VOX lines in hotspot.c mode could then be removed

**Comment by rogerclarkmelbourne** [comment]
I can do the fix for this if you want.

**Comment by rogerclarkmelbourne** [comment]
OK. I pushed a fix

**Comment by f1rmb** [comment]
Yup, I just raised a PR about the hotspot and vox thing.

**Comment by rogerclarkmelbourne** [comment]
Yes. I just noticed.

I already pushed a fix.

I'm now merging the other change.

I don't think you need to check for hotspot mode Off do you.

If its in that mode, i don't think that the CPS mode can be set to Hotspot mode

**Comment by f1rmb** [comment]
Hummmm

**Comment by f1rmb** [comment]
BlueDV is really special (and annoying to manage), as it could be still running, even it usbmode is not in hotspot mode.
Also, hotspot mode check will just stop at the first == HOTSPOT_TYPE_OFF is HS is turned OFF.

**Pull request merged**
