### PR TITLE
Code style clean pass.

### PR DESCRIPTION
**Pull request by f1rmb**
Found 2 bitwise AND usage instead of logical ones (in _EEPROM_Write() and EEPROM_Read()).
Use typedefed values instead of meaningless numbers for uiCPSUpdate()'s command.

I'm sending you a diff file where space/tabs changes are ignored.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I don't think its going to be possible for me to check every single change in 90 files.

So if it compiles OK, I will release it as a development version , and the users can test it.

BTW

Let me know when its ready to merge.....

**Comment by f1rmb** [comment]
Okay. Yeah, it's ready for mrege (I'm working on possible settings improvements).

**Comment by f1rmb** [comment]
Once you merged this PR, I will raise another one which get rid of SETTINGS_PLATFORM_SPECIFIC_SAVE_SETTINGS macro.

**Comment by rogerclarkmelbourne** [comment]
I did some basic tests and things seem to be working OK.
Thanks

**Pull request merged**
