### PR TITLE
Implement backlight modes Auto/Manual/None.

### PR DESCRIPTION
**Pull request by f1rmb**
Since SK1 is the obvious button to press in auto mode to trigger the backlight, I chose it also as toggle button in Manual mode.

#80

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel

I think using SK1 only for the blacklight is a not the best use for this important button.

Alex and I have discussed on github and in the forum how to make user definable buttons by using the Function + NUMBER buttons but this would also include the SK1 button.

Alex was going to add a new set of events to handle the user defined functions.

I think we need backlight mode options but they probably need to initially, only be set via the Display options screen and perhaps when the User Defined buttons system is working, people could assign SK1 for this function if they wanted.

**Comment by f1rmb** [comment]
Hi Roger,

   I chose it as a temporary solution (since I know about the new ongoing shortcut stuff).

Cheers.

**Comment by f1rmb** [comment]
Reassign it later to a real shortcut won't be too much work, it's handled in a single place.

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

This works well, but we will need to decide how to turn the backlight on and off using another button.

BTW. 
I think another useful feature for button SK1 during Tx would be display the Last Heard list while the SK1 remains pressed, instead of the Tx screen, so that people could see the callsign of the stations they are in the QSO with.

**Comment by rogerclarkmelbourne** [comment]
Just a thought...

I wonder if long press on Blue could be used instead of the Black key to toggle the backlight.

However, it may require changes elsewhere to make this work in places where the Blue key is used on its own, and not as a modifier.

**Comment by rogerclarkmelbourne** [comment]
BTW.

I'm implementing the Last Heard during Tx now.

**Comment by f1rmb** [comment]
Hi Roger,

   Yes, I saw the new feature on the forum.
About the backlight toggle, I don't know if it worth the effort to make some changes in the buttons 
code now, as Alex is probably working on the new shortcut code.

But, it could bis possible to detect long press of SK1 or SK2, as a temporary solution.

IIRC, SK2 only event is just used to copy override TS/TG on RX.

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

I don't think its a big problem using SK1 for the backlight we can find a better solution later.

**Pull request merged**
