### PR TITLE
Shame on me and my last second changes...

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Ah. Yes.

That would cause problems ;-)

**Comment by f1rmb** [comment]
Slight one...

**Comment by f1rmb** [comment]
I changed the array from char to uint32_t, yeah, nice Daniel, didn't you missed something ?

**Comment by rogerclarkmelbourne** [comment]
OK. Its not crashing now


Thanks....

**Comment by rogerclarkmelbourne** [comment]
Time for me to stop now.

Its not been a very productive day, with my PC problems.

Hopefully my PC will boot again tomorrow, but I  have already installed MCUExpesso and git etc onto the new PC.

**Comment by f1rmb** [comment]
Okay Roger. Yeah, sometimes we can't be productive, but it not always our fault...

Ah, already part of the tools ;-)

Cheers.

**Pull request merged**
