### PR TITLE
Enable internal Pull-up resistors in MCU for keypad

### PR DESCRIPTION
**Pull request by alexernst**
This should enable the internal pull-up resistors in the MCU for the keypad pins.
I don't know what to do with SlewRate and DigitalFilter right now, but will investigate.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi Alex,

   Checking the document NXP_K22P121M120SF7RM.pdf, in Radioddity_GD-77/docs, page 250, the SlewRate and PassiveFilter is explained.
Slew Rate Enable only apply if the pin is configured as digital output.
Passive Filter Enable if the pin is configured as digital input

Cheers.

**Comment by f1rmb** [comment]
Passive filter is maybe just a capacitor to ground, maybe worth to enable them.

**Comment by alexernst** [comment]
Look at that document, but did miss that slew rate is only for output pins.
And now I have found in the same document page 138, that passive filter is only for PORTA.
So not usable here as the keypad is connected to PORTC.

**Comment by f1rmb** [comment]
Okay. I didn't look in details, but that answer the questions ;-)

I never really looked at the keyboard code, but if I'm right, it's polling, right.
But, what about the time to stabilize between setting PORTC low, and reading GPIOB state ?

**Comment by alexernst** [comment]
I have to dig in the complete timings. More or less I took the original code for that part.
I did a short look at the code and wonder why PORTC pins are always set as input ports after each read.

**Comment by f1rmb** [comment]
Yeah, I noticed that strange thing too. But since I don't know the reason (power consumption ?)

Cheers.

**Comment by rogerclarkmelbourne** [comment]
I agree with Daniel

It would be better if some time was allowed to the voltage to settle.

If I have time, I will try to understand why Kai wrote the code in this way.

**Comment by rogerclarkmelbourne** [comment]
I don’t think there would be much power consumption. The pull-ups are approximately 15k, and the input impedance will be 50k or more.

Total current would be perhaps 0.25mA when the MCU is running.

And in low power sleep mode, the current will be almost zero

**Comment by f1rmb** [comment]
So no need to change pin direction then, less noise, less hysteresis, but maybe I'm wrong.

**Comment by rogerclarkmelbourne** [comment]
BTW. I will ask my father to test the version after I pull the PR, because his radio definitely had the problem when he turned it in.

But like the other people who reported the problem, once his radio was rebooted a few times with the current firmware, it worked fine, even though he left it in his garage in the UK, which was only about 5 deg C today.

Anyway, I think pull-ups are a good idea, and we should possibly consider reversing the way the lines are strobed to 0V ( low ) and instead use pull down and strobe the lines high.

As perhaps that may take less current. But perhaps it does not make any difference

**Comment by rogerclarkmelbourne** [comment]
It depends if pull down resistors are fitted

**Comment by alexernst** [comment]
Reversing the pins depend of R14-R17 of the keypad board? If these pull-up resistors are on the board pull-down in the MCU would work?

**Comment by f1rmb** [comment]
As it's marked as Not Connected, I guess it's just placeholder.
But tomorrow I will check that (I bet they are under the flat-flex on the picture we have in the GD's docs directory).

**Comment by alexernst** [comment]
I took a deeper look at the picture. There are 4 emtpy places for resistors. 3 between the connectors and 1 left.  Pins 6-9 of the lower connector are the columns of the keypad. And the empty spaces are connected to these pins. At least for pin 7-9 this is obvious.

So I think no external pull-up resistors.

**Comment by alexernst** [comment]
There is a photo on Jason's website without the flat-flex cable.

http://members.optuszoo.com.au/jason.reilly1/ribbonfix.jpg

**Comment by f1rmb** [comment]
Yeah, cool. Probably the capacitors

Humm, according to the VIAs on the 3.3V line (center of the LCD FF connector, can see the connections on the other side picture), the 4 non fitted components are the pullup resistors.

**Comment by alexernst** [comment]
Exactly. I will add a slight delay between setting PORTC pin and reading PORTB and remove the switch back to input ports for PORTC.

@Roger 
Is your fathers GD77 only locking at power on?

**Comment by rogerclarkmelbourne** [comment]
Testing this now

**Comment by alexernst** [comment]
Is there any function to delay for some time other than vTaskDelay() in the SDK? 
I didn't find something like delay().

**Comment by rogerclarkmelbourne** [comment]
vTaskDelay(portTICK_PERIOD_MS * 10);

**Comment by rogerclarkmelbourne** [comment]
Sorry

**Comment by rogerclarkmelbourne** [comment]
Whats wrong with vTaskDelay ?

**Comment by rogerclarkmelbourne** [comment]
If not just use a

` for(volatile int i=0;i<SOMEVALUE;i++);`

You can also use

`__asm volatile( "nop" );`

or
```
for(volatile int i=0;i<SOMEVALUE;i++)
{
__asm volatile( "nop" );
}
```

**Comment by alexernst** [comment]
vTaskDelay() is fine. 

I'm just not used enough to FreeRTOS. So not sure what's 'best practice'.

**Comment by rogerclarkmelbourne** [comment]
It probably depends on how long you want to delay for.

If its quite short, you should probably use __asm volatile( "nop" ); etc

**Comment by rogerclarkmelbourne** [comment]
BTW. Keys seem to to be fine with the pullups enabled

I think I"ll merge and push

**Comment by rogerclarkmelbourne** [comment]
Something strange is going on.  I've merged this, but github has not updated this PR

**Comment by alexernst** [comment]
I added another commit 45 minutes ago, but that is lost between the commits.
But sometimes git and github is working 'interessting'.
Perhaps that's the problem. 
But if everything works, ignore that commit.

**Comment by rogerclarkmelbourne** [comment]
OK

I think I'll try without the delay.

1mS to settle is probably to long.  I will get my dad to test it tomorrow morning

BTW. One thought I had, was perhaps the problem happens when the battery voltage is high.

People leave their radios on charge over night and then in the morning the voltage will be at its highest and this is probably causing the problem

**Comment by rogerclarkmelbourne** [comment]
I will close this because I have merged the Pull-up part of this PR.

Please can you pull again and update your repo and resubmit another PR for anything that is missing.

But I think 1mS is too long for for the lines to settle . It probably just needs 10 nops etc

**Comment by rogerclarkmelbourne** [comment]
FYI. This did not fix the problem on my fathers radio :-(. I will need to use the USB debug print code to try to understand what his radio is doing.

It has the same symptoms as the other radios, where after a while it starts working.

**Comment by rogerclarkmelbourne** [comment]
Alex.

I'm going to close this, as I think the PR is now out of sync with the codebase.

**Pull request closed without merging**
