### PR TITLE
Disable beep when VOICE is enabled.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

I don't think this is a good idea, because I think the voice prompts will not play all the time, and visually impaired operators will probably use a combination of the FIRST beep functionality augmented by the voice prompt system.

**Comment by f1rmb** [comment]
Ah, yes true, I forgot about that.

**Comment by f1rmb** [comment]
Close, useless.

**Comment by rogerclarkmelbourne** [comment]
OK. 

No worries

**Comment by rogerclarkmelbourne** [comment]
BTW. The beep does not seem to be causing many problems even if it is playing when the voice prompt is playing.

I have heard some short bursts of FM unsquelched hiss sometimes during the voice prompt playback, which may possibly be caused when perhaps the beep playback stops.
Or it may be another problem

I should add some code to terminate the beep when the voice prompt is played or perhaps terminate the voice prompt when a beep is played (or both)

Announcing the channel name etc can take a long time, and the operator may press the Up or Down buttons to change channel while the prompt is playing.

I already added some code to terminate the existing prompt if a new prompt is setup etc

**Pull request closed without merging**
