### PR TITLE
Update Dutch translations

### PR DESCRIPTION
**Pull request by on7lds**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
You seem to have added some formatting e.g. tabs to this file

**Comment by on7lds** [comment]
It was to have proper formatting in the MCUXpresso IDE but now I see this is not the case when opening the file on the command line. As seems to be the case with several other language files.
Tabs are really a PITA working with different editors :-ç
Do you want me to remove them and create a new PR ?

**Comment by rogerclarkmelbourne** [comment]
The language files can't be edited in the MCUExpresso IDE because it uses the wrong encoding.

On Windows I use NotePad++ to edit the files with it set to ANSI encoding

Do not use UTF8 as it breaks the encoding.

I don't know the exact settings to use for Linux editors, possibly

/* -*- coding: windows-1252-unix; -*- */

As per the header line at the top of the file.


I think you may need to do a new PR as it may not be possible to easily fix the formatting changes you made to the file.

**Comment by on7lds** [comment]
No problem. I'll restart and do a new PR. 
And I'll try to think not to touch the tabs in the future :-)
Thanks for your patience.

**Comment by rogerclarkmelbourne** [comment]
No worries

The main problem is the file encoding, but even non visible changes like tabs are tracked by Git as changes, so in general they should be avoided when making changes, unless the change is specifically with regards to the formatting of the file.

In the case of the language files, unfortunately they can't be edited in MCUExpresso for technical reasons related to the character encoding

**Pull request closed without merging**
