### PR TITLE
Typos and Contact 1|2 lines translation

### PR DESCRIPTION
**Pull request by EA3BIL**
Typos and Contact 1|2 lines translation

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
There are merge conflicts with the existing file.  

Did you pull the latest copy before making your change.

BTW. 

Because of a mistake in the New Channel function from EA3IHI, I need to modify all the translation files.

So please wait until I have done this before submitting a new PR, otherwise there will be another merge conflict

**Comment by EA3BIL** [comment]
Yes,
As far as I saw, I took the last one from MASTER...

Anyway, I'll wait for the new file before PR, so you can dismiss that PR.

Thanks for letting me know !!!


Cheers,
Rafa.

**Comment by rogerclarkmelbourne** [comment]
Actually, its OK, I can fix this in the header that defines the localisation structure, its not technically necessary to move the .new_channel item in headers were the actual texts are defined

So go head and pull from the Master and then submit a new PR when you made your changes

**Comment by rogerclarkmelbourne** [comment]
I still can't merge this because it still has conflicts. Please pull the master version again.

**Comment by rogerclarkmelbourne** [comment]
Re-open when the merge conflicts are fixed

**Pull request closed without merging**
