### PR TITLE
GD77S and PLATFORM target cleanup + bin2sgl with GD-77S support, untested (Linux & Windows)

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
Don't merge it, there is a .... glitch :-D

**Comment by f1rmb** [comment]
Okay Fixed.

Platform CPP should be used like this
```
#if defined(PLATFORM_GD77)
or
#if ! defined(PLATFORM_GD77)
```
instead of 

`#if (PLATFORM == GD77)`

The current platforms are; PLATFORM_GD77, PLATFORM_GD77S and PLATFORM_DM1801

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Fantastic...

Thankyou for all the work on this.

Even though neither of us have a GD-77S ;-)

**Comment by f1rmb** [comment]
;-) true

Le dim. 8 mars 2020 à 23:26, Roger Clark <notifications@github.com> a
écrit :

**Comment by rogerclarkmelbourne** [comment]
BTW. The GD-77S version is crashing all the time at the moment and USB is not working.

I think possibly the WDT is rebooting the radio, but I'm not sure

I think I'll go though the code and disable things one by one and see what causes the problem as it may not be the WDT.

**Comment by f1rmb** [comment]
Roger,

   Okay. I didn't tried to flash the 77S version (didn't had time).
Maybe there is some disabled code (like screen init) that trigger that of
reboot afterward.


Cheers

Le lun. 9 mars 2020 à 00:08, Roger Clark <notifications@github.com> a
écrit :

**Comment by rogerclarkmelbourne** [comment]
No worries

I will check later today. I should be easy to find

**Pull request merged**
