### PR TITLE
Use any non alpha-numeric char as divider in TA...

### PR DESCRIPTION
**Pull request by alexernst**
…between callsign and text.

I received the following:

IMG_1857

TA from MMDVMHost was 'KK3J-JIM'.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi Alex,

   I saw that too, but there is a problem here, the dash is perfectly valid in a call (listen to TG 9504).
Here the guy is wrong, and it's the first time I see someone coupling his call with his first name.

GD-77_screengrab-2020-01-01_17_16_03

Cheers.

**Comment by alexernst** [comment]
But that is only an echlink callsign not an ITU callsign?

**Comment by alexernst** [comment]
So a better solution might be to remove the 'chainsaw' at char 6. Then 'KK3J-JIM' would be in the first line.

**Comment by f1rmb** [comment]
What do you nean by ITU callsign ?
```
M: 2020-01-02 13:54:18.425 DMR Slot 2, received network voice header from KK3J to TG 91
M: 2020-01-02 13:54:19.045 DMR Talker Alias (Data Format 1, Received 6/8 char): 'KK3J-J'
M: 2020-01-02 13:54:19.045 DMR Slot 2, Embedded Talker Alias Header
M: 2020-01-02 13:54:19.045 0000:  04 00 50 4B 4B 33 4A 2D 4A                         *..PKK3J-J*
M: 2020-01-02 13:54:19.754 DMR Talker Alias (Data Format 1, Received 8/8 char): 'KK3J-JIM'
M: 2020-01-02 13:54:19.754 DMR Slot 2, Embedded Talker Alias Block 1
M: 2020-01-02 13:54:19.754 0000:  05 00 49 4D 00 00 00 00 00                         *..IM.....*

```
And his name is James:
https://www.qrz.com/db/KK3J

At the moment, if no space is found in the TA, first part is cut after the 6th char. It's not that efficient, but works for 99.99% of time. Guessing callsign can be PITA, since you have 4 (e.g. F2VI0 to 7 (e.g VK4FNTH), and perhaps more. And since we can fine some '-<something>', like in Echolink, I don't know how it can work 100% of the time (for TA without space) .

**Comment by alexernst** [comment]
Callsigns defined in the ITU Radio Regulations don't include any suffix. As far as I know.

**Comment by f1rmb** [comment]
suffix like '-L' is SSID, -JIM is user's fun ;-)

**Comment by alexernst** [comment]
I will set an ISO-Layer-8 Filter in my brain for things like that and ignore it :-)

**Comment by f1rmb** [comment]
Not, that not the point. Maybe we can pre/post process the TA, if no space is found, then search for a dash +, let say, three char or NULL, and if if matches, replace the dash by a space, and return the new space offset.

What do you think about that ?

**Comment by f1rmb** [comment]
Or, if a dash is found, and the TA is < 10 or 11, then keep it as callsign.

**Comment by alexernst** [comment]
I would simply break at first space and make a hard break at char 16 instead of 6.
That would not break up any callsigns. 'KK3J-JIM' would be complete in the callsign line.
It's not perfect. 
But as you wrote in 99.99% it's no problem.

**Comment by f1rmb** [comment]
But what about the above stuff, if no space found, search for a dash, and if NULL is at offset +2 or +3, and keep it as is, otherwise replace the dash with a space, and split TA there ?.

**Comment by alexernst** [comment]
That is possible, but this is some code just to fix a special TA format. 
If I had realized the problem with the dash, I wouldn't did the change.

I wonder how other radios handle the TA?

**Comment by f1rmb** [comment]
It collect HEADER, BLOCK1..3, once for each, and process the TA each time a new block is collected, IF header is already there (as encoding and length informations are in the first byte).
In an ongoing PR, we will support whole TA length (up to 28 char in 7bit encoding) + embedded GPS coords (as maidenhead). The second TA line is dynamic:
if TA (without callsign) <= 16, display it as it's now, but centered
if TA >16 <= 21, switch to 6x8 font, center H/V
if TA > 21 < 42, use 6x8 font, two lines, centered.

It works quite nicely, even if I didn't get too much BLOCK 0x08 (GPS).

Cheers.

**Comment by f1rmb** [comment]
I forgot, and it's stored in the contact TA if it grows, only.

**Comment by alexernst** [comment]
Yes, I've seen that in the code, but I wonder how Anytone, Hytera or Motorola display the TA?

**Comment by f1rmb** [comment]
I don't know, I'm not sure if my Hytera PD365 displays the BM's TA at all.

The only other DMR HTs I own are TYT MD-380/390, with md380tools modded
firmware installed. But the screen is larger, and I don't know it they
display the whole TA.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Currently there are 7 character VK callsigs

e.g. 

VK3FABC

Because the foundation license holders were recently allowed to digital modes.

This has caused a lot of problems with the DMD IR data bases because HamDigital.org doesn't seem to support 7 character callsigns, and I have reverted to using CSV files from www.radioid.net for the DMR ID database uploads into the radio

I think in the long term they will have to re-issue all the 'F' callsigns and give them 6 character callsigns, but it could be months if not years before this situation is resolved for VK stations.

**Pull request closed without merging**
