### PR TITLE
More translations.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
Hold one with this one, I forgot a little thing.

**Comment by f1rmb** [comment]
Yes, more size_t bufferLen, buf that will be part of the next PR, about resizing and datatype change.

**Comment by f1rmb** [comment]
Okay, I think it's fine.
I'll start changing buffer length stuff after this one is merged (if you agree).

**Comment by rogerclarkmelbourne** [comment]
I'm being pedantic, but can't text like this

`snprintf(buf, bufferLen, "%s:%s", "Rx CTCSS", currentLanguage->n_a);`

Be simplified to 

`snprintf(buf, bufferLen, "Rx CTCSS":%s", currentLanguage->n_a);`

**Comment by f1rmb** [comment]
I'm doing this because I remember something I read long ago about using fmt as fmt. I don't know if I can find that text.

**Comment by rogerclarkmelbourne** [comment]
OK.

I thought it was a legacy from when the static text "Rx CTCSS" was from the current language, but now its static, I'm not sure of the benefit of passing it as %s

**Comment by f1rmb** [comment]
I'll try to find the text giving the reason, but I can't remember where I read that.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by f1rmb** [comment]
That's true.
I'll modify that. Listening you and Luis, drinking morning coffee ATM ;-)

**Comment by rogerclarkmelbourne** [comment]
(LOL)

OK. I never think of how many people are listening,

**Comment by rogerclarkmelbourne** [comment]
BTW.

Perhaps in the case of these snprintf() with just strings, its quicker to use strcat()

**Comment by rogerclarkmelbourne** [comment]
BTW. You probably heard. I experimented with the scan delay time , reduced from 50 to 30 (ticks of 1ms) and the scan still seems to work OK.

**Comment by f1rmb** [comment]
There is already few strcat, but I can double check.

I didn't heard everything, wife and kids were awake, I had to prepare more coffee :-)

**Comment by f1rmb** [comment]
Is there any reason  why filter DMR_FILTER_CC_TS_TG is never used ATM ? (code stops at DMR_FILTER_CC_TS of the enum).

**Comment by rogerclarkmelbourne** [comment]
TG filtering isn't implemented yet.

It only filters by CC and optionally by TS , hence the only available options are "CC" and "CC,TS"

Actually, it looks like its impossible to remove CC filtering as its an internal function of the C6000, so the only options will probably be "TS" and "TS, TG" or perhaps "TS & TG"

I'll need to remove some code code I added to HR-C6000.c in an attempt to not filter on CC. As this now looks like its not technically possible :-(

**Comment by f1rmb** [comment]
Ah, I see (I saw that on the forum, about CC filtering).

**Comment by f1rmb** [comment]
About scanning, I need to add some contacts in my codeplug. But there isn't so much to listen around here.

**Comment by f1rmb** [comment]
Hold on, I found something...

**Comment by rogerclarkmelbourne** [comment]
OK.

I'm lucky, Melbourne is a major shipping port. Lots of traffic to listen to.

**Comment by f1rmb** [comment]
That's sounds pretty cool.

**Comment by rogerclarkmelbourne** [comment]
From where we are, the main docks are 25km north, but we do see the shipping going down the main channel, at a distance of about 10km away (or perhaps a bit less) but we live 1km from the bay, so its not the view from my window ;-)

I found this website to that tracks the ships via their transponder. 

https://www.marinetraffic.com/en/ais/home/centerx:144.9/centery:-38.0/zoom:10

 I think one guy at the local radio club has receiver for the beacons

**Comment by f1rmb** [comment]
Nice, I will check that.

Okay I think the cleanup is done now.  I will have to leave for 2 hours.

**Comment by f1rmb** [comment]
You can also see boats on aprs.fi, IIRC

**Comment by f1rmb** [comment]
Wow, that's surrounded with zillion of boats...

**Comment by rogerclarkmelbourne** [comment]
OK

I'll pull it soon

**Comment by rogerclarkmelbourne** [comment]
I will need to pull this tomorrow. I had to spend all evening trying to updated the radio club website :-(

**Comment by f1rmb** [comment]
No problem Roger.
Maybe I will have the time to do the size_t and bufferLen things meanwhile.

**Comment by rogerclarkmelbourne** [comment]
Yes. No rush

I have been working on the CPS to do the auto update to the 80 channels zone, and that is now working, but I realised that the Contacts  export and import (CSV) is not exporting the TS override.

I've almost got that working, but the import is not working correctly yet.

I also had to spend 2 hours discussing and changing the radio club website.

Anyway. Tomorrow is another day   (an English saying ....)

**Comment by f1rmb** [comment]
I've merged danish and german updates from the forum (plus somes fixes).

**Comment by rogerclarkmelbourne** [comment]
Thanks

Tested and seems OK.

**Comment by f1rmb** [comment]
Cool. Thanks Roger.

Le mer. 4 déc. 2019 à 21:31, Roger Clark <notifications@github.com> a
écrit :

**Comment by rogerclarkmelbourne** [comment]
I'll merge and test Colin's PR before releasing the SGL

**Comment by f1rmb** [comment]
Sure!

Le mer. 4 déc. 2019 à 21:34, Roger Clark <notifications@github.com> a
écrit :

**Pull request merged**
