### PR TITLE
Slowdown flash access

### PR DESCRIPTION
**Pull request by f1rmb**
This is WIP, and untested yet (need to fill my userDB).

ATM, lookups are still there while renderering QSO info, that will come later.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Does this use caching of the contact data  as proposed by Colin and David (on the forum).
I know it will take around 6k to cache the contacts, but I think its the simplest and fastest option.

**Comment by rogerclarkmelbourne** [comment]
Oops.  Sorry. I did not mean to close it. I pressed the wrong button

**Comment by f1rmb** [comment]
LOL

No. there is no caching (i'm not sure if it worse all that memory usage).
Seems to work. Maybe there is one or two display bugs, but with and without userDB works, now I'm checking with TA enabled hotspot.

**Comment by rogerclarkmelbourne** [comment]
I think there is enough RAM for the cache

```
SRAM_UPPER:       42756 B        64 KB     65.24%
SRAM_LOWER_BOTTOM:         604 B      27488 B      2.20%
SRAM_LOWER_TOP:          8 KB      29304 B     27.96%
```

As there is 20k in the UPPER and also around 40k in the LOWER sections.
(Though i don't know why the linker seems to prefer using the UPPER for most things)

**Comment by f1rmb** [comment]
TA seems to still works :-)

Okay about the RAM. I would like to track bug first, then see about caching.
ATM, i've reduced the flash read size on lookups. It stops to read the whole contact, whatever information source.

**Comment by alexernst** [comment]
The linker uses the bottom lower ram as the data region for initialized variables.
Top lower ram contains heap and stack. 
The upper ram is used as the bss region for all uninitialized variables.

As far as I know it is not possible to build one region containing top lower and upper ram. 
There is a technical difference between lower and upper ram. I think accessing the lower ram needs one extra cpu cycle.

There are some macros in fw_main.h to move a single var to a specific ram region.

**Comment by rogerclarkmelbourne** [comment]
Alex

Thanks

I'll look at the macros as it would be useful to put some larger item caches in the lower memory

**Comment by rogerclarkmelbourne** [comment]
Daniel

I've pulled you code and it is working, but I have seen a few small problems.

I think the caching is causing the old TG to be displayed. If I change TG, and receive  a signal on the new TG, the display shows the old TG.

I'm not sure the "fast" functions will be much faster.  Reading separate parts of the contact data will not save much time, because the overhead to setup each read is quite long,  because I think before each transfer the code requests the status of the Flash chip and it also has to send the address, which is several bytes etc.

I think caching is a better method to fix the time to access the Contact, and I have written the functions to do this (I'll email the code to you).

Also, looking at the code which calls the Contact lookup, in the original code, I think this also needs to be changed, or we need to store the contact type as part of the cache (actually we can do this as I'm using a uint32_t for the TG/PC number and this only takes 24 of the 32 bits.

I'm not sure if you already changed this, but in uiChannelMode it looks up the PC and the TG details differently.

`contactIndex = codeplugContactIndexByTGorPC((trxTalkGroupOrPcId & 0x00FFFFFF), `CONTACT_CALLTYPE_TG, &contact);

vs

`contactIndex = codeplugContactIndexByTGorPC((trxTalkGroupOrPcId & 0x00FFFFFF), CONTACT_CALLTYPE_PC, &contact);`


But I think the CONTACT_TYPE is not relevant, because the range of numbers for DMR ID's and for TG's do not overlap for amateur radio use, and I think the official firmware allows a TG and PC to have the same number in the Contacts

The only time I see this is necessary is on the contacts screen when listing either TG or PC.

Anyway. I'll modify my cache to also hold the call type flag, as it will not take any more memory and I will post the functions as the lookup function is a direct replacement for the original non-cached version

**Comment by rogerclarkmelbourne** [comment]
I call initCodeplugContactsCache from fw_main.c just after lastheardInitList();

I'll try integrating this into your PR code

```
typedef struct
{
	uint32_t tgOrPCNum;
	uint16_t index;
} codeplugContactCache_t;
int codeplugNumTGContacts;
int codeplugNumPCContacts;
codeplugContactCache_t codeplugContactsLookupCache[1024];

int codeplugContactIndexByTGorPC(int tgorpc, int callType, struct_codeplugContact_t *contact)
{
	int numContacts =  codeplugNumTGContacts + codeplugNumPCContacts;
	for (int i = 0; i < numContacts; i++)
	{
		if ((codeplugContactsLookupCache[i].tgOrPCNum&0xFFFFFF) == tgorpc && (codeplugContactsLookupCache[i].tgOrPCNum>>24) == callType)
		{
			codeplugContactGetDataForIndex(codeplugContactsLookupCache[i].index, contact);
			return i;
		}
	}
	return 0;
}

void initCodeplugContactsCache(void)
{
	struct_codeplugContact_t contact;
	int codeplugNumContacts=0;
	codeplugNumTGContacts=0;
	codeplugNumPCContacts=0;

	for(int i=0;i<1024;i++)
	{
		SPI_Flash_read((CODEPLUG_ADDR_CONTACTS + (i * CODEPLUG_CONTACT_DATA_LEN)), (uint8_t *)&contact, 16+4+1);// Name + TG/ID + Call type
		if (contact.name[0]!=0xFF)
		{
			codeplugContactsLookupCache[codeplugNumContacts].tgOrPCNum = bcd2int(byteSwap32(contact.tgNumber));
			codeplugContactsLookupCache[codeplugNumContacts].index=i+1;// Contacts are numbered from 1 to 1024
			codeplugContactsLookupCache[codeplugNumContacts].tgOrPCNum |= (contact.callType<<24);// Store the call type in the upper byte
			if (contact.callType == CONTACT_CALLTYPE_PC)
			{
				codeplugNumPCContacts++;
			}
			else
			{
				codeplugNumTGContacts++;
			}
			codeplugNumContacts++;
		}
	}
}
```

**Comment by rogerclarkmelbourne** [comment]
More updates

This code replaces some of the other codeplug contact functions so that the cache is used

I also moved the cache to the bottom of the LOWER bank of RAM and the linker output at the end of the build seems to show that it has been moved

```
typedef struct
{
	uint32_t tgOrPCNum;
	uint16_t index;
} codeplugContactCache_t;
int codeplugNumTGContacts;
int codeplugNumPCContacts;
__attribute__((section(".data.$RAM2"))) codeplugContactCache_t codeplugContactsLookupCache[1024];

int codeplugContactsGetCount(int callType) // 0:TG 1:PC
{
	if (callType == CONTACT_CALLTYPE_PC)
	{
		return codeplugNumPCContacts;
	}
	else
	{
		return codeplugNumTGContacts;
	}
}

int codeplugContactGetDataForNumber(int number, int callType, struct_codeplugContact_t *contact)
{
	int pos = 0;

	for (int i = 0; i < 1024; i++)
	{
		if ((codeplugContactsLookupCache[i].tgOrPCNum>>24) == callType)
		{
			number--;
		}

		if (number == 0)
		{
			codeplugContactGetDataForIndex(codeplugContactsLookupCache[i].index, contact);
			pos = i+1;
			break;
		}
	}
	return pos;
}

int codeplugContactIndexByTGorPC(int tgorpc, int callType, struct_codeplugContact_t *contact)
{
	int numContacts =  codeplugNumTGContacts + codeplugNumPCContacts;
	for (int i = 0; i < numContacts; i++)
	{
		if ((codeplugContactsLookupCache[i].tgOrPCNum&0xFFFFFF) == tgorpc && (codeplugContactsLookupCache[i].tgOrPCNum>>24) == callType)
		{
			codeplugContactGetDataForIndex(codeplugContactsLookupCache[i].index, contact);
			return i;
		}
	}
	return 0;
}

void initCodeplugContactsCache(void)
{
	struct_codeplugContact_t contact;
	int codeplugNumContacts=0;
	codeplugNumTGContacts=0;
	codeplugNumPCContacts=0;

	for(int i=0;i<1024;i++)
	{
		SPI_Flash_read((CODEPLUG_ADDR_CONTACTS + (i * CODEPLUG_CONTACT_DATA_LEN)), (uint8_t *)&contact, 16+4+1);// Name + TG/ID + Call type
		if (contact.name[0]!=0xFF)
		{
			codeplugContactsLookupCache[codeplugNumContacts].tgOrPCNum = bcd2int(byteSwap32(contact.tgNumber));
			codeplugContactsLookupCache[codeplugNumContacts].index=i+1;// Contacts are numbered from 1 to 1024
			codeplugContactsLookupCache[codeplugNumContacts].tgOrPCNum |= (contact.callType<<24);// Store the call type in the upper byte
			if (contact.callType == CONTACT_CALLTYPE_PC)
			{
				codeplugNumPCContacts++;
			}
			else
			{
				codeplugNumTGContacts++;
			}
			codeplugNumContacts++;
		}
	}
}
```

**Comment by rogerclarkmelbourne** [comment]
OK. More caching code

```
int codeplugContactGetFreeIndex(void)
{
	int i;
	int lastIndex=0;

	int numContacts =  codeplugNumTGContacts + codeplugNumPCContacts;

	for (i = 0; i < numContacts; i++)
	{
		if (codeplugContactsLookupCache[i].index!=lastIndex+1)
		{
			return lastIndex+1;
		}
		lastIndex = codeplugContactsLookupCache[i].index;
	}

	if (i < 1023)
	{
		return codeplugContactsLookupCache[i].index+1;
	}

	return 0;
}
```

also when a new contact is saved the cache needs to be reloaded.

So one extra line just before the function returns.
(Yes. there would be a way to update the cache without reloading it, but its probably not worth wasting time on it at the moment)


```
int codeplugContactSaveDataForIndex(int index, struct_codeplugContact_t *contact)
{
	int retVal;
	int flashWritePos = CODEPLUG_ADDR_CONTACTS;
	int flashSector;
	int flashEndSector;
	int bytesToWriteInCurrentSector = CODEPLUG_CONTACT_DATA_LEN;

	index--;
	contact->tgNumber = byteSwap32(int2bcd(contact->tgNumber));


	flashWritePos += index*CODEPLUG_CONTACT_DATA_LEN;// go to the position of the specific index

	flashSector 	= flashWritePos/4096;
	flashEndSector 	= (flashWritePos+CODEPLUG_CONTACT_DATA_LEN)/4096;

	if (flashSector!=flashEndSector)
	{
		bytesToWriteInCurrentSector = (flashEndSector*4096) - flashWritePos;
	}

	SPI_Flash_read(flashSector*4096,SPI_Flash_sectorbuffer,4096);
	uint8_t *writePos = SPI_Flash_sectorbuffer + flashWritePos - (flashSector *4096);
	memcpy( writePos,
			contact,
			bytesToWriteInCurrentSector);

	retVal = SPI_Flash_eraseSector(flashSector*4096);
	if (!retVal)
	{
		return false;
	}

	for (int i=0;i<16;i++)
	{
		retVal = SPI_Flash_writePage(flashSector*4096+i*256,SPI_Flash_sectorbuffer+i*256);
		if (!retVal)
		{
			return false;
		}
	}

	if (flashSector!=flashEndSector)
	{
		uint8_t *channelBufPusOffset = (uint8_t *)contact + bytesToWriteInCurrentSector;
		bytesToWriteInCurrentSector = CODEPLUG_CONTACT_DATA_LEN - bytesToWriteInCurrentSector;

		SPI_Flash_read(flashEndSector*4096,SPI_Flash_sectorbuffer,4096);
		memcpy(SPI_Flash_sectorbuffer,
				(uint8_t *)channelBufPusOffset,
				bytesToWriteInCurrentSector);

		retVal = SPI_Flash_eraseSector(flashEndSector*4096);

		if (!retVal)
		{
			return false;
		}
		for (int i=0;i<16;i++)
		{
			retVal = SPI_Flash_writePage(flashEndSector*4096+i*256,SPI_Flash_sectorbuffer+i*256);

			if (!retVal)
			{
				return false;
			}
		}

	}
	initCodeplugContactsCache();// Update the cache
	return retVal;
}
```

**Comment by f1rmb** [comment]
Hi Roger,

   I'll take at you code once I got enough coffee to get out of the mist.

About the cache, I had the idea of something like this:

```
typedef struct
{
     uint16_t maxEntries;

     struct
     {
	  uint16_t index;
	  uint32_t tgOrPC;
     } entries[1024];

} contactsCache_t;

```
To have a unique structure to embed data and max counter.
IMHO, adding and deleting contact shouldn't re-read the flash, as just adding values to maxEntries is enough, and shift values n-1 after matching index + decreasing maxEntries do the job.

Well, coffee ;-)

**Comment by rogerclarkmelbourne** [comment]
Yes. The counters can be part of the struct.

I agree adding and deleting is just shifting the entries upwards or downwards, which could be done using memcpy();

**Comment by rogerclarkmelbourne** [comment]
BTW.

I just realised initCodeplugContactsCache() is not a good function name, as it does not conform to the naming convention

It should probably be

`codeplugInitContactsCache()`

**Comment by rogerclarkmelbourne** [comment]
I need to test it, but I think this should remove an item from the cache

```
void codeplugContactsCacheRemoveContactAt(int index)
{
	int numContacts =  codeplugNumTGContacts + codeplugNumPCContacts;
	for(int i=0;i<numContacts;i++)
	{
		if(codeplugContactsLookupCache[i].index == index)
		{
			if ((codeplugContactsLookupCache[i].tgOrPCNum>>24) == CONTACT_CALLTYPE_PC)
			{
				codeplugNumPCContacts--;
			}
			else
			{
				codeplugNumTGContacts--;
			}
			memcpy(&codeplugContactsLookupCache[i],&codeplugContactsLookupCache[i+1],(numContacts-1)-1 *sizeof(codeplugContactCache_t));
			return;
		}
	}
}
```

**Comment by rogerclarkmelbourne** [comment]
I think I found a small mistake in the contact delete code. The callType should be set to 0xFF not 0x00 when deleting


```
			memset(contact.name, 0xff, 16);
			contact.tgNumber = 0;
			contact.callType = 0;
			codeplugContactSaveDataForIndex(contactListContactIndex, &contact);
```

**Comment by rogerclarkmelbourne** [comment]
There seems to be some bugs in my contact removal code.

Don't use it yet.

**Comment by rogerclarkmelbourne** [comment]
OK.

Time for me to stop, before my neck pain starts again ;-)

```
void codeplugContactsCacheInsertContactAt(int index, struct_codeplugContact_t *contact)
{
	if (contact->callType == CONTACT_CALLTYPE_PC)
	{
		codeplugNumPCContacts++;
	}
	else
	{
		codeplugNumTGContacts++;
	}
	int numContacts =  codeplugNumTGContacts + codeplugNumPCContacts;
	for(int i = 0;i < numContacts - 1;i++)
	{
		if(codeplugContactsLookupCache[i].index < index && codeplugContactsLookupCache[i+1].index > index)
		{
			// Note . Need to use memmove as the source and destination overlap.
			memmove(&codeplugContactsLookupCache[i+2],&codeplugContactsLookupCache[i+1],(numContacts - 2 - i) *sizeof(codeplugContactCache_t));

			codeplugContactsLookupCache[i+1].tgOrPCNum = bcd2int(byteSwap32(contact->tgNumber));
			codeplugContactsLookupCache[i+1].index=index;// Contacts are numbered from 1 to 1024
			codeplugContactsLookupCache[i+1].tgOrPCNum |= (contact->callType<<24);// Store the call type in the upper byte
			return;
		}
	}
}

void codeplugContactsCacheRemoveContactAt(int index)
{
	int numContacts =  codeplugNumTGContacts + codeplugNumPCContacts;
	for(int i=0;i<numContacts;i++)
	{
		if(codeplugContactsLookupCache[i].index == index)
		{
			if ((codeplugContactsLookupCache[i].tgOrPCNum>>24) == CONTACT_CALLTYPE_PC)
			{
				codeplugNumPCContacts--;
			}
			else
			{
				codeplugNumTGContacts--;
			}
			// Note memcpy should work here, because memcpy normally copys from the lowest memory location upwards
			memcpy(&codeplugContactsLookupCache[i],&codeplugContactsLookupCache[i+1],(numContacts - 1 - i) *sizeof(codeplugContactCache_t));
			return;
		}
	}
}
```

and at the end of   codeplugContactSaveDataForIndex()



```
	if (contact->name[0]==0xff || contact->callType == 0xFF)
	{
		codeplugContactsCacheRemoveContactAt(index+1);// index was decremented at the start of the function
	}
	else
	{
		codeplugContactsCacheInsertContactAt(index+1,contact);
	}
        return retVal;
```

I tested a little and I think its working, but there may be some edge cases e.g. 1023 contacts where its possible the code doesn't work correctly

Goodnight...

**Comment by f1rmb** [comment]
Hi Roger,

> Daniel
> 
> I've pulled you code and it is working, but I have seen a few small problems.
> 
> I think the caching is causing the old TG to be displayed. If I change TG, and receive a signal on the new TG, the display shows the old TG.

Yeah, noticed that too, that's one of the remaining bugs ;-)

> 
> I'm not sure the "fast" functions will be much faster. Reading separate parts of the contact data will not save much time, because the overhead to setup each read is quite long, because I think before each transfer the code requests the status of the Flash chip and it also has to send the address, which is several bytes etc.

Is just to avoid reading tons of bytes for nothing, and unfortunately the name byte array is the first structure member. Anyway, with caching stuff, that wouldn't impact too much, as cache will be build once at startup.

> 
> I think caching is a better method to fix the time to access the Contact, and I have written the functions to do this (I'll email the code to you).
> 
> Also, looking at the code which calls the Contact lookup, in the original code, I think this also needs to be changed, or we need to store the contact type as part of the cache (actually we can do this as I'm using a uint32_t for the TG/PC number and this only takes 24 of the 32 bits.
> 
> I'm not sure if you already changed this, but in uiChannelMode it looks up the PC and the TG details differently.
> 
> `contactIndex = codeplugContactIndexByTGorPC((trxTalkGroupOrPcId & 0x00FFFFFF), `CONTACT_CALLTYPE_TG, &contact);
> 
> vs
> 
> `contactIndex = codeplugContactIndexByTGorPC((trxTalkGroupOrPcId & 0x00FFFFFF), CONTACT_CALLTYPE_PC, &contact);`
> 
> But I think the CONTACT_TYPE is not relevant, because the range of numbers for DMR ID's and for TG's do not overlap for amateur radio use, and I think the official firmware allows a TG and PC to have the same number in the Contacts

In fact, I didn't modified that, I've just reused existing functions.
But, you can still define TG4000 or PC4000, by example.

> 
> The only time I see this is necessary is on the contacts screen when listing either TG or PC.
> 
> Anyway. I'll modify my cache to also hold the call type flag, as it will not take any more memory and I will post the functions as the lookup function is a direct replacement for the original non-cached version

Okay. I don't know if I will have too much time today, but I'll try to fix the bugs in the current modifications of this PR, in the evening.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
No worries

**Comment by rogerclarkmelbourne** [comment]
Daniel
I have pushed my Contacts cache system.

It does not seem to have caused any merge conflicts with your existing changes, but you can delete your "fast" versions of the Contact functions, as the cache does work better.

PS. I looked at it with the logic analyser and it is definitely working and has drastically reduced the amount of accesses to the Flash memory

**Comment by rogerclarkmelbourne** [comment]
arrrghh

I just realised that the Contacts can be  edited and the TG can be changed as can the Call type.

So I"ll need to do a fix for this.  But I may not be able to get it fixed today.

**Comment by rogerclarkmelbourne** [comment]
OK.

I think I've fixed that bug, and I also tidied up the code and put it all inside a struct.

**Comment by f1rmb** [comment]
Hi Roger,

   Okay, I hope I will have time to work on this today. I need to fix the wrong TG/PC stuff first (I know why that happens), then I will merge the cache stuff, and fix conflicts.

Thanks.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
Is this stable yet ?

**Comment by f1rmb** [comment]
Hi Roger,

I've just played with, and it seems so. If you have time to try it out.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK

I pulled about 30 mins ago, to test.

I'll pull again and continue testing

**Comment by f1rmb** [comment]
Thanks Roger.

**Comment by rogerclarkmelbourne** [comment]
Seems to be working OK.

I loaded it onto the radio that has the logic analyser attached and its definitely not doing many accesses to the Flash memory. 

With a QSO with one person, it only looked up the data once, and did not lookup any more data.

I will merge this and release a test version with this and the other PR.

**Comment by f1rmb** [comment]
Yeah, lookups can only happen if the callsign isn't part of the 16 entries of the lastheard list, or if it's part, but PC/TG has changed.
I need to update Hotspot's screen update to use this (currenlty, it triggers lookups on every RX, but since it already updates the LH list, that will be trivial to update the code).

Cheers.

**Pull request merged**
