### PR TITLE
Navigating in menu restores position in parent menu when pressing RED…

### PR DESCRIPTION
**Pull request by f1rmb**
… key.

All saved indexes are resetted when current menu is exited.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Good idea.

Just one question.

Why is it necessary to pass previous item index.
Isn’t this just the stack index - 1 ?

**Comment by f1rmb** [comment]
Hi Roger,

   Errr, I don't understand the question.

**Comment by f1rmb** [comment]
To quickly summarize this stuff, once you push a new menu, the gMenusCurrentItemIndex value is stored in the current menu stack position, the new menu is pushed.
when you pop the menu, stored gMenusCurrentItemIndex is restored (well, passed to the menu function, it's up to that function to restore gMenusCurrentItemIndex if needed).

**Comment by rogerclarkmelbourne** [comment]
Ok.

Thanks.

**Comment by rogerclarkmelbourne** [comment]
I've merged because it works, but I think there may be a more simple solution.

I don't know if you really need to pass prevItemIndex because virtually all functions just  do

gMenusCurrentItemIndex=prevItemIndex;

And even the functions which don't do this, could probably do this without any problems.

It may be possibly simply to set

gMenusCurrentItemIndex   to the correct value before calling the function, and to remove the code in the functions that does gMenusCurrentItemIndex=prevItemIndex;

However I don't have time at the moment to change this and make it work 

Of course there may be some technical reason why this can't be done

**Comment by f1rmb** [comment]
Hi Roger,

   Yes, at the beginning I was think doing like this, but I found some special cases where that will collide:
menuZoneList:  it sets it to  nonVolatileSettings.currentZone
menuNumericalEntry: it sets to ENTRY_TG (which is 0)
and I was thinking if someday a list, contact or whatever, that could be listed and edited. If an entry is deleted (e.g the last one), then the stored offset will be out of bounds.

Or, to get rid of this, I can just remove the extra menu function parameter, all the gMenusCurrentItemIndex default initialisation, and specify the system keeps track of gMenusCurrentItemIndex, and could possibly be overwritten if needed.

Just tell me, and I will change the code accordingly.

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

I will think about this a bit more. ;-)

But for now your solution works OK.

**Comment by f1rmb** [comment]
I'm already modifying the code ;-)

**Pull request merged**
