### PR TITLE
Force redraw if battery level < 15%, blinking the level.

### PR DESCRIPTION
**Pull request by f1rmb**
This bug was introduced when I make it stop refreshing for nothing.

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Why is it 66.7 rather than 66?

**Comment by f1rmb** [comment]
Hi Roger,

Because it's 15% sharp.



---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
