### PR TITLE
add Dutch language

### PR DESCRIPTION
**Pull request by on7lds**

### CODE REVIEW

**Comment by f1rmb** [comment]
Sorry to be a pain, but your dev branch looks not made out of the development branch from Roger's repo.

I don't know if you have already added the upstream remove (Roger's repo)
`git remote add upstream https://github.com/rogerclarkmelbourne/OpenGD77.git`

then fetch it
`git fetch upstream`

then merge it to your 'dev' branch
`git checkout dev`
`git merge upstream/development`

once everything is fine, push it to your branch
`git push origin dev`

**Comment by f1rmb** [comment]
Ah, I just noticed it's even worse, your asking to merge into master branch, but that's wrong, you have to choose 'development' instead.

**Comment by rogerclarkmelbourne** [comment]
I guess, I'll need to manually add this file

**Comment by f1rmb** [comment]
Hi Roger,

   Yup, the last 3 entries are still missing.


Cheers.
...-
Daniel

**Comment by rogerclarkmelbourne** [comment]
Yes. :-(

I can use Google translate for them, and as the code is experimental at the moment its not a big problem.

**Comment by rogerclarkmelbourne** [comment]
I'll also need to make a voice prompt file for this

**Comment by rogerclarkmelbourne** [comment]
I've had to manually download your file and update it and add it to the repo, because of the problems as explained in the other comments.

You will need to pull from my repo again to update your local clone, and update the file with translations for the 2 lines which were missing, and then commit that change.

You should then create a PR with the Development branch of my repo as the target, rather than the master branch which you targetted in this PR.

I have also created a voice prompt file using the translations in the dutch.h however I also had to add translations using google translate and the translations in the voice prompts should not be abbreviations

https://github.com/LibreDMR/voice-prompts/tree/master/languages/dutch

**Comment by on7lds** [comment]
Sorry I had the wrong branch for the PR. And sorry I read your comments a little bit late.
I'll try to do the missing translations today.

I 'm also working on the voice files, I already have them working here. But there is still some work to do.
The Dutch TTS voice is not that good. Is it possible to use other TTS sources, like espeak ?

**Comment by rogerclarkmelbourne** [comment]
OK.

I did listen to the TTS output and it didn't sound that good, but I don't speak Dutch, so it was just an impression of it not sounding much like any Dutch people I have heard.

If you have another speech synthesiser you can access, then you could use it to generate the MP3 files , and then change the config file to only encode your MP3 files rather than downloading TTS form TTSMP3.com or VoicePolly, which are the 2 only TTS which I wrote into the Python script.
BTW. Both TTSMP3 and VoicePolly use Amazon Polly as their TTS engine, but both have a different private API, with slighly different functionality.

VoicePolly can use SSML, but the quota on that site is very low, so the Python script uses TTSMP3 unless the prompt needs SSML

However if you look at the french worklist you'll see Daniel F1RMB has made multiple overrides using SSML and those prompts will be sent to VoicePolly my the Python script.

**Pull request closed without merging**
