### PR TITLE
doc update as per issue 696

### PR DESCRIPTION
**Pull request by Neon22**
Four changes made to sections:
3 as per issue 696 and one image(svg) attached

- Added doc in Installation about Transferring data
- Added docs in OpenGD77 Menu re the boot tune as morse code
- Added in same are re notes and melodies
- Added cheatshet for DM1801 under the GD77 image

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I saw your note about squashed commits. 

You're correct in saying, I can't accept a PR that does 17 commits just because of editing.

I'd need to pull you changes, and then copy the file somewhere, and then switch back to the development branch and manually copy the file with your changes in it.

As I don't merge on Github unless its a simple one line change to the language files and even then I've been caught out with errors in the language files which screwed up the build

**Comment by Neon22** [comment]
I'm perfectly happy you doing it anyway that works for you.
In the future I'll try to make it a single commit by doing what you're suggesting.

Is it useful to try to make a GD77S cheatsheet as well ?
If so which forum discussion do you think I should do it in ?
I'd be aiming to get feedback from GD77S owners as I don't have one :)

P.S. I made the md inclusion an svg - I'm hoping the html and pdfs will accept it directly during your conversion. But if not then there is a redundant png already in the media folder.

**Comment by Neon22** [comment]
Oh yeah - you could just grab the raw file from my repo - to save you time ?
- https://github.com/Neon22/OpenGD77/tree/master/docs

**Comment by rogerclarkmelbourne** [comment]
I doubt a GD-77 graphic cheat sheet would be worth doing. The majority of GD-77S operators are blind, and they bought the GD-77S because the official firmware has a simple speech synth in it.

**Comment by Neon22** [comment]
replacing with cleaner commit

**Pull request closed without merging**
