### PR TITLE
Disable CC detection while hotspot is running.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

Sorry I didn't do it earlier. I forgot that there was one last PR to check and merge

**Comment by f1rmb** [comment]
;-)

No problem Roger. I was wondering if you didn't like it :-D

**Comment by rogerclarkmelbourne** [comment]
Well... 

I think perhaps it would be better to do this without adding extra code into HR-C6000 as the ISR's are already quite large.

Perhaps save nonVolatileSettings.dmrFilterLevel when entering hotspot mode, and set to TS and CC filtering.

Then when exiting hotspot mode or shutdown when in hotspot mode, restore the nonVolatileSettings.dmrFilterLevel with the setting that was saved.

Probably more code, but less load on the ISRs 

What do you think .

**Comment by f1rmb** [comment]
Hi Roger,

Hummm, yes. In that case I will create a dedicated function which is called when final power off stage is reached, from withing menuPowerOff menu.
This function will also be used when low battery happens,  and it will also manage to save the settings, otherwise turning off / on quickly might save wrong settings.


Cheers.
...
Daniel

**Pull request merged**
