### PR TITLE
Handle inter-band scanning. Swap defined freq if Lower > Upper.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

What bug does this change fix?

**Comment by f1rmb** [comment]
Hi Roger,

Well, if you set lower and upper freq from different bands, once the scanning reach the band limit it will hang and just sending error beeps.
Now you can scan from 2m to 70cm, the freq jumps from one band to the next.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Ah OK, I noticed scanning from 2m and 70cm in the same scan was not possible.

**Comment by f1rmb** [comment]
Okay.now it's possible 😉

**Comment by f1rmb** [comment]
Hi Roger,

   I will raised another PR about VFO scanning, UI related.

image

The arrow display the scan direction.


image

It's not yet finished (cursor is still missing).

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll wait, and probably pull it tomorrow if its ready

**Comment by f1rmb** [comment]
Okay, so should I merge PR both into a single one ?

**Comment by rogerclarkmelbourne** [comment]
I can only see one PR 

https://github.com/rogerclarkmelbourne/OpenGD77/pull/505

**Comment by f1rmb** [comment]
Yeah, the one about UI isn't raised yet. I meant, preparing for tomorrow.

**Comment by rogerclarkmelbourne** [comment]
OK
Is this PR OK to pull and merge

**Comment by f1rmb** [comment]
Yes.

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've tested it, and its working.

I'm not sure anyone will use it, because it takes a long time to scan 2m and the 200Mhz and also 70cm, but it does work across all 3 bands

**Comment by f1rmb** [comment]
True, it could take some time to scan the bands, but since it's allowed to enter any freq from any valid band, that avoids the error beeps of death at a given time 😉

**Pull request merged**
