### PR TITLE
Rework getNextContact().

### PR DESCRIPTION
**Pull request by f1rmb**
Introduce and use CODEPLUG_CONTACTS_MIN/MAX constants.
Fix VFO -> New Channel: valid indexes were 1..1023, which was wrong.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
What was the problem with getNextContact()

Obviously your code is more concise.

**Comment by rogerclarkmelbourne** [comment]
BTW.

If we change

void codeplugUtilConvertBufToString(char *inBuf, char *outBuf, int len)

to

void codeplugUtilConvertBufToString(char *codeplugBuf, char *outBuf, int len)

i.e change  inBuf to codeplugBuf

Then people don't complain we are changing the input buffer ;-)

**Comment by f1rmb** [comment]
LOL

About this, I would vote to check if the "modified" input buffer isn't used at all, for which I'm doubtful.
 


> BTW.
> 
> If we change
> 
> void codeplugUtilConvertBufToString(char *inBuf, char *outBuf, int len)
> 
> to
> 
> void codeplugUtilConvertBufToString(char *codeplugBuf, char *outBuf, int len)
> 
> i.e change inBuf to codeplugBuf
> 
> Then people don't complain we are changing the input buffer ;-)

**Comment by f1rmb** [comment]
old getNextContact was dangerous, index <= 0, and asking for previous contact might crash.

**Comment by f1rmb** [comment]
Well, it don't really crash, as codeplugContactGetDataForIndex() check the boundaries, but some nice stuff will happen, like popping TG9 ;-)

**Comment by f1rmb** [comment]
Okay, argument renamed.;-)

**Comment by f1rmb** [comment]
Commit added (it's the last one in this PR related to codeplug):
- Remove unneded return in codeplugUtilConvertStringToBuf().
- Rename codeplugDTMFContactGetDataForIndex() to codeplugDTMFContactsGetList(), as the name was misleading, and fix it. It's unused yet, but no need to have buggy functions anyway ;-)

**Pull request merged**
