### PR TITLE
Support TA in format 7bit, 8bit, UTF8 and UTF16.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I only did a little testing, on TG 91 etc, and it looks OK.

**Comment by f1rmb** [comment]
I'm on TG91 too, since I need some TA data ;-)

**Comment by rogerclarkmelbourne** [comment]
I noticed sometimes it takes a long time until TA data is displayed e.g. W9THC

**Comment by f1rmb** [comment]
It depends on the order TA blocks are received.
To be able to decode, we need block 0 (header), and sometimes blocks arrives in random order.
But once the TA is complete and stored, it's not updated anymore and displayed in a breeze.

**Comment by f1rmb** [comment]
e.g this one that just happened:

M: 2019-12-29 07:24:02.236 DMR Slot 1, received network voice header from W5HWZ to TG 91
M: 2019-12-29 07:24:23.797 DMR Talker Alias (Data Format 0, Received 0/0 char): ''
M: 2019-12-29 07:24:23.797 DMR Slot 1, Embedded Talker Alias Block 1
M: 2019-12-29 07:24:23.797 0000:  05 00 44 4D 52 20 49 44 3A                         *..DMR ID:*
M: 2019-12-29 07:24:24.538 DMR Talker Alias (Data Format 0, Received 0/0 char): ''
M: 2019-12-29 07:24:24.539 DMR Slot 1, Embedded Talker Alias Block 2
M: 2019-12-29 07:24:24.539 0000:  06 00 20 33 31 30 38 39 32                         *.. 310892*
M: 2019-12-29 07:24:25.248 DMR Talker Alias (Data Format 0, Received 0/0 char): ''
M: 2019-12-29 07:24:25.248 DMR Slot 1, Embedded Talker Alias Block 3
M: 2019-12-29 07:24:25.248 0000:  07 00 38 00 00 00 00 00 00                         *..8......*
M: 2019-12-29 07:24:25.953 DMR Talker Alias (Data Format 1, Received 21/21 char): 'W5HWZ DMR ID: 3108928'

**Comment by rogerclarkmelbourne** [comment]
When I was listening to W9THC. It just displayed the ID for at least 10 seconds. 

I don't think its a bug in your code, I think that BM simply does not always send the TA data.

**Pull request merged**
