### PR TITLE
Screen render / C6000 ISR mutex

### PR DESCRIPTION
**Pull request by f1rmb**
Introduce simple mutex, trying to prevent screen corruption.
Problem is, even detect if C6000 ISR has been called or not, once display is corrupted, there is no way to fix this, as the buffer rendering has been made out of the given row.

I just noticed a little code cleanup of HS code was pushed at the same time, it wasn't intended to be part of this PR, my bad.

### CODE REVIEW

**Comment by f1rmb** [comment]
Until now, I don't get any display corruption (it's triggered on reception stuttering).

**Comment by f1rmb** [comment]
RSSI meter (in header) was also prone to display some white pixels, as it's redrawn quite often.

**Comment by f1rmb** [comment]
Locally, I changed the code, only the UC commands block is mutexed. Lets see.

**Comment by rogerclarkmelbourne** [comment]
Will the mutex delay the C6000 ISR If the display is updating?
Because you must not delay the ISR as the timing is critical e.g.. the Tx ISR turns on the Tx hardware

**Comment by rogerclarkmelbourne** [comment]
BTW. 

I don't think using a mutex to block the only the display code would work. Because the RTOS will not switch from the middle of the ISR code to run the display render code.


I think what you are saying is that simply re-rendering does not fix the problem ?
This seems strange, because normally if the display get corrupted, the problem is fixed when the screen renders again. e.g. in Tx when the next 1 second update occurs.

Perhaps if there is a ISR during a the screen render it needs to force a complete re-render of the entire display, not just the rows that were being rendered.

Also.
Perhaps the problem occurs only if the ISR interrupts the "command" to the display, and not the data, and perhaps the "command" can be resent, hence the display is not actually corrupted and hence the whole display would not need to be re-rendered ?


Or..

Another possibly option is to synchronise the display render with the ISRs, 

I would need to look at the logic analyser data, but we could possibly get the display render to wait until just after a ISR has finished and then run, as possibly there is always at least a few mS gap between ISRs.  
However I would need to check.

The problem is a full screen render is quite slow, I think around 1mS or possibly even slower.
I'll double check the data sheet, but I think from what I remember the maximum clock rate is not very fast :-(

**Comment by f1rmb** [comment]
Well, about rerendering the current row doesn't work, because if ISR call is detected, the screen is already corrupted, but most of the time, in another row, so a full rendering from first row should be done. And if that happens again, in a next row, rendering could take ages (and watchdog could kicks in).

I know ISR are critical, I'm also quite surprised to see huge function called inside that ISR (like HRC6000TimeslotInterruptHandler() and HRC6000SysInterruptHandler()).

> Perhaps the problem occurs only if the ISR interrupts the "command" to the display, and not the data, and perhaps the "command" can be resent, hence the display is not actually corrupted and hence the whole display would not need to be re-rendered ?

I could try that.

I noticed a side effect with the mutex, some small gaps in the sound, even with buffering two DMR frames.

**Comment by rogerclarkmelbourne** [comment]
Re: Large functions in the ISR

Although the TS ISR is a lot of code, its really just one big switch statement, so the CPU cycles required to process the ISR are very small

The SYS interrupt is more complex, and I don't know how long it takes to run the SYS interrupt, but probably not all the code is run depending on the various conditions.


Originally with the Tier1 version, Kai just set a flag in each of the TS, and ran the code to process the interrupts in the RTOS task, but he told me that it would not work for Tier2 because the RTOS did not respond fast enough.

Kai ran all the RTOS tasks on the same priority, but I have changed this, so that the HRC6000 task has the highest priority.

I think the RTOS "tick" value is 1mS. Kai tried to change this to 100 uS to improve the DMR handling but the CPU is not fast enough to run the RTOS at that speed.

I don't think the SYS ISR does any intensive processing, e.g. the AMBE encode and decode is not run in the ISR, I just set a flag and the HRC6000 RTOS task handles the decode.


Its difficult to profile the time taken by the ISR's unless hardware timers are used another method is to  toggling GPIO pins use a logic analyser to look at the GPIO lines.

I'm not sure even if the PIT counter runs when there is an ISR.

I know on some other MCU's e.g. STM32, there are hardware timers which run regardless of the CPU and ISR etc, and I'm sure the MK22 must have the same internal hardware, but I don't know enough about the MK22 to easily program them.

**Comment by f1rmb** [comment]
Ticks from RTOS is unusable, as it's task oriented (I had a lot of time calculation issues with LH menu, this is why I switched fw_millis() using PIT ticks counter instead). About strong accuracy, I don't kown.

Yeah, for time critical stuff, RTOS tasks is problematic, because of the scheduler.

**Comment by rogerclarkmelbourne** [comment]
Yes. I initially used the RTOS counter for the Tx screen counter but it was very inaccurate, and I had to add the PITCounter for the Tx screen so that the count-down / count-up timer was correct

**Comment by f1rmb** [comment]
Closing it, but not the discussion ;-)

**Pull request closed without merging**
