### PR TITLE
Before TXing, check if VFO is scanning before blindly stopping it.

### PR DESCRIPTION
**Pull request by f1rmb**
Since menuVFOModeIsScanning() exists, use it.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I've made some changes.

I don't think the radio should immediately transmit if the PTT is pushed during VFO or Channel scan.

So I have modified the Channel mode as well, so that pressing the PTT during a scan simply stops the scan on both screens

**Comment by f1rmb** [comment]
Okay Roger.

**Comment by rogerclarkmelbourne** [comment]
I think the main problem was not the VFO CC scan etc, but the Channel mode scan would immediately Tx and even when the channel was not paused etc

**Comment by f1rmb** [comment]
Originally, when scanning in vfo, you were able to xmit, then when
switching back to RX, the scanning been resumed.

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Pull request merged**
