### PR TITLE
Updates to Scanning

### PR DESCRIPTION
**Pull request by g4eml**
Two New Scan modes, 'Hold' and 'Pause' in channel mode quick menu.
New Option Setting 'Scan Delay' in options menu.
New Skip flags 'Zone Skip' and 'All Skip' in channel details menu.

Hold waits for 'Scan Delay' after carrier drops before continuing scan. 
Pause pauses for 'Scan Delay' then continues regardless. 
Zone Skip skips the channel when scanning in a Zone. 
All Skip skips the channel when scanning in all channels mode. 

New strings in localisation files. Probably need translating correctly.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

Seems to work.  

One thing that perhaps should be changed is the text for Pause / Hold , as now looks like this is just an option control rather than starting the scan in specific mode.

But I can't think of an ideal way to do this.

**Comment by g4eml** [comment]
Hi Roger, 

I did it like that as a way of making both scan types easily available. But I agree it might not be obvious what it is doing. 
The only other way of doing it I could think of was to have a separate ‘scan mode’ setting somewhere.  I didn’t think that was right in the quick menu. Maybe people would prefer it in the options menu. It depends on how they use the scanning I guess. 

Colin. 


On 29 Nov 2019, at 21:39, Roger Clark <notifications@github.com> wrote:

Thanks

Seems to work.

One thing that perhaps should be changed is the text for Pause / Hold , as now looks like this is just an option control rather than starting the scan in specific mode.

But I can't think of an ideal way to do this.

**Comment by rogerclarkmelbourne** [comment]
I presumed that the Scan:Hold and Scan:Pause are a temporary thing rather than a permanent option.

I don't really know how people using scanning and whether they are constantly changing this.

Perhaps it would be OK as a setting in the Options

**Comment by g4eml** [comment]
Yes, the setting reverts back to ‘Off’ when the scan is stopped. So it is a one time trigger that has to be selected each time. 

It could equally be a permanent setting in options. Maybe we need to get some feedback to see what people prefer. 

Colin. 




On 29 Nov 2019, at 23:33, Roger Clark <notifications@github.com> wrote:

I presumed that the Scan:Hold and Scan:Pause are a temporary thing rather than a permanent option.

I don't really know how people using scanning and whether they are constantly changing this.

Perhaps it would be OK as a setting in the Options

**Pull request merged**
