### PR TITLE
Change Location of VFO Indication

### PR DESCRIPTION
**Pull request by g4eml**
The new VFO Indicator subscript after T and R looks cluttered to me.

Here is my suggestion to display the (small)  A or B at the start of the line like this..

A> R 433.30000 MHz
      T 434.90000 MHz

Reject it if you don't like it.

Colin.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin

I think I personally prefer Daniels submission, but I can ask the forum and post alternative screen grabs

**Comment by g4eml** [comment]
Roger, 

No problem either way.
(I actually don’t really think the VFO A/B needs to be shown at all) 

Colin. 



On 23 Dec 2019, at 21:41, Roger Clark <notifications@github.com> wrote:

Colin

I think I personally prefer Daniels submission, but I can ask the forum and post alternative screen grabs

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

An indication of VFO A/B has been requested by a few people but its hard to fit it on the display

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

Is your last push just to bring your repo back into sync with the Master ?

I think possibly I should close this issue and post a question to the forum about Daniels change to the VFO indication and get some feedback

**Comment by g4eml** [comment]
Hi Roger, 

Yes, I should be back in sync again. You should not have to change anything in the master.  I will probably delete my fork and re-fork it again. That’s the only way I have found of getting truly back into sync. 

I would’t worry about the vfo indication. You won’t get a clear decision one way or the other and the current one is OK.  It will always be impossible to please everybody! 

The firmware seems to have reached a fairly stable state now. If you have any suggestion as to what still needs looking at let me know and I will direct my efforts in that direction. I was thinking of looking at the talkgroup filtering. I don’t think that should be too difficult to implement. 
On a ‘normal’ radio filtering would pass the currently selected TX talkgroup, any talkgroup in the RX list and the radios own ID for incoming private call. 

However in amateur use RX lists were effectively used as a way of listening to all traffic before ‘promiscuous mode’ was introduced. So I don’t think there is now really a need to use them for their original purpose. 

So I would propose to just have three levels of filtering. 

1. Only receive group calls to the currently selected TX talkgroup or private calls to the radios ID. (Filter CC TS TG)
2. Receive all Group calls and all Private Calls, single slot. (Filter CC TS)
3. Receive all Group calls and all Private Calls, dual slot. (Filter CC)

We are probably not going to be able to remove the CC filter so whether it needs to be displayed or not is debatable. 

The receiving of all private calls might be an issue with some. Especially on repeaters where they are commonly used.   Maybe there needs to be a separate option setting to include them in levels 2 and 3 or not. 


73 
Colin. 











On 27 Dec 2019, at 06:31, Roger Clark <notifications@github.com> wrote:

Hi Colin

Is your last push just to bring your repo back into sync with the Master ?

I think possibly I should close this issue and post a question to the forum about Daniels change to the VFO indication and get some feedback

**Comment by rogerclarkmelbourne** [comment]
Colin

I don’t really understand why people want to filter on a TG, but I agree that it’s something that needs to be implemented 

I see what you mean about the TS filter and the TG filter actually being separate, but I think for ease of use , that we should initially have the TG filter only for when the TS filter is on.

I think we can disregard the CC option, as I have removed it from the filter list a while ago, once it became clear that it’s part of the hardware settings in the C6000

Cheers

Roger

**Comment by rogerclarkmelbourne** [comment]
I'm going to close this as its not been used.

**Pull request closed without merging**
