### PR TITLE
Fix bugs with setConfig (CC).

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I saw that bug report on the forum

Do you know why the CC was 3 an not 0 ?

I see this fix just checked for invalid CC numbers

**Comment by rogerclarkmelbourne** [comment]
Actually,

Was this a bug caused by the POCSAG changes ?

**Comment by f1rmb** [comment]
No, it was introduced by me, with POCSAG or CWID changes, I've added some stupid modemState check.

Maybe once he set CC to 3, but with the bug, if it start in MMDVM_IDLE state, codecolor wasn't defined. If CC was set to 3, and MMDVMHost setConfig() with MMDVM_DMR, it was sets.

**Comment by f1rmb** [comment]
It was just a real by idea to filter config values according to mode.

**Comment by f1rmb** [comment]
The CC > 15 was already there, before I started working on the HS code.

**Comment by rogerclarkmelbourne** [comment]
OK
I didn't notice this bug. But I only tested with MMDVMHost on the PC.

Testing with PiStar takes more time

**Comment by f1rmb** [comment]
Everyone use CC1, it seems ;-)

**Comment by f1rmb** [comment]
So I didn't noticed either.

**Pull request merged**
