### PR TITLE
Fix showing TG0 on some repeaters

### LINKED ISSUE #193: Some radios on some repeaters, constantly report ID or TG 0
As a bit of background this is how the ID system works.

The HR-C6000 DRM has 4 separate interrupt lines into the MK22, but all of them are handled by the same ISR, (because of the limitations of the MK22 hardware)

https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/firmware/source/hardware/fw_HR-C6000.c#L347

The interrupt lines  System Interrupt, TimeSlot Interrupt, Tx Interrupt, and Rx Interrupt.

The Tx and Rx interrupts from the C6000 tell the MK22 that the radio now needs to Transmit or to Receive.

The TimeSlot interrupt tells the MK22 that the C6000 is ready to be setup with the data for the next DMR frame. See https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/firmware/source/hardware/fw_HR-C6000.c#L818

The System Interrupt is the one used to process the incoming DMR data during Rx.

https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/firmware/source/hardware/fw_HR-C6000.c#L697

The first block of code reads the Link Connect data 

https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/firmware/source/hardware/fw_HR-C6000.c#L706

Which contains the Source and Destination IDs'. AFIK the C6000 does not have a flag to indicate there is new data in the LC data memory buffer (in the C6000).

So to check whether there is new data, I have to compare a saved LC buffer with the current LC buffer and also to check the current TimeSlot (by reading register 0x52)

I should also have been checking the Colour Code at this point in the code but I wasn't and I noticed today in testing that I could trigger TG 0 to be displayed by transmitting on another Color Code, but I didn't get any audio.

So I've now fixed that omission. 

In my second commit, as the first fix for it didn't use the correct variable (doh!)

However, I don't think this bug fix will necesarily fix the problem that people are seeing with TG 0

### PR DESCRIPTION
**Pull request by alexernst**
Add CRC check to received LC header frames, remove checking for empty FID field in header frame.
Also ensure that last heard list is only filled if a valid TG or PC ID is received.

If a QSO is started and no TG or ID is received the screen displays 'Waiting...'. This needs to be localized or perhaps simple removed and a screen without ID's could be displayed.
If the Voice Start LC header is not received but the following Voice Frames after at least 360ms (6 Voice Data Frames) an embedded Grp_V_Ch_Usr frame with source and destination ID's is received. After that the last heard list and the display should have correct ID's to show.

Fixes #193

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex

This PR seems to contain an unrelated change in fw_main.c

**Comment by alexernst** [comment]
I'll fix it, wait a minute.

**Comment by alexernst** [comment]
Please try again. 
I merged master in my branch but did not check in the other direction. I have accidently resetted fw_main.c to an older version. Sorry!

**Comment by rogerclarkmelbourne** [comment]
no worries

**Comment by rogerclarkmelbourne** [comment]
I'm still seeing some other changes.

I'll manually merge it

**Comment by alexernst** [comment]
Arrgh, reset fw_main completely. There is nothing related to this in it. 
Seems like I did only revert the first hunk.

**Comment by rogerclarkmelbourne** [comment]
Its OK I've manually merged and used fw_main.c from the master branch

**Pull request merged**
