### PR TITLE
Fix scanning and button/key press. While scanning, the first full key…

### PR DESCRIPTION
**Pull request by f1rmb**
…press or button event cycle stops the scanning.
Playing melody on keypress just stopped the scanning process, as it enable the AMP.

I will check Channels mode.

### CODE REVIEW

**Comment by f1rmb** [comment]
The Channel mode does not have this problem, so it's all fine.

**Comment by rogerclarkmelbourne** [comment]
OK

Thanks.

**Comment by rogerclarkmelbourne** [comment]
Tested etc.. Thanks

**Comment by f1rmb** [comment]
😉

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
BTW. I just sent you another email. 

But I'm stopping now, and will continue to clean up the CPS code tomorrow

**Pull request merged**
