### PR TITLE
Fix output frequency swipe

### PR DESCRIPTION
**Pull request by f1rmb**
Fix some backlight problems, like keeping setting the PWM while it's not needed (while TXing). Now it's just doing it once when starting TXing.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
If the problem is unnecessary changes to percentage, another simpler solution is to store the last percentage and only change the PWM if there is actually a change

I added this code to your PR and its still reporting many times when the percentage is being changed unnecessarily 

Would this be a better solution ?

```
int lastPercentage=-1;
#if ! defined(PLATFORM_GD77S)
#ifdef DISPLAY_LED_PWM
void fw_displaySetBacklightIntensityPercentage(uint8_t intensityPercentage)
{
	if (intensityPercentage!=lastPercentage)
	{
		lastPercentage = intensityPercentage;
		FTM_UpdateChnlEdgeLevelSelect(BOARD_FTM_BASEADDR, BOARD_FTM_CHANNEL, kFTM_NoPwmSignal); // Disable channel output before updating the dutycycle
		FTM_UpdatePwmDutycycle(BOARD_FTM_BASEADDR, BOARD_FTM_CHANNEL, kFTM_CenterAlignedPwm, intensityPercentage); // Update PWM duty cycle
		FTM_SetSoftwareTrigger(BOARD_FTM_BASEADDR, true); // Software trigger to update registers
		FTM_UpdateChnlEdgeLevelSelect(BOARD_FTM_BASEADDR, BOARD_FTM_CHANNEL, kFTM_HighTrue);    // Start channel output with updated dutycycle
	}/*
	else
	{
		SEGGER_RTT_printf(0, "Unnecessary percentage change to %d\n",intensityPercentage);
	}*/
}
#endif
#endif // ! PLATFORM_GD77S
```

**Comment by f1rmb** [comment]
It could be added, but calling thus function every single second is not that effective ;-)
I will add and check this.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK

We can have both. I agree we should not all it every second, but there are lots of other places which cause the PWM to change when its not necessary

I'll merge your code and then add my additional code, so that it only updates the PWM if there is a change in the value

**Comment by f1rmb** [comment]
I'm currently modifying, I'm also removing the fw_ prefix.

**Comment by f1rmb** [comment]
Just hold a second ;-)

**Comment by rogerclarkmelbourne** [comment]
OK. No rush

Have a coffee first ;-)

**Comment by f1rmb** [comment]
Already got 2 :-D But a third is a good idea :-D

**Comment by rogerclarkmelbourne** [comment]
(LOL)

**Comment by f1rmb** [comment]
Okay, done, now coffee ;-)

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll pull it soon.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
