### PR TITLE
Git hash in info

### PR DESCRIPTION
**Pull request by f1rmb**
Hi Roger,

Here is the modification to display git hash. I think that could prevent confusion when someone reports a build date from a firmware *not officially* built. 

At least, with the hash, it could be clear if the user is using the latest build.

This has been tested under Linux and Windows.

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel
I just get the # character

What do i need to do to generate the hash

Perhaps i have to be on the master branch. I guess I should try that

**Comment by rogerclarkmelbourne** [comment]
No. I merged into my main branch and I still only get a # character

**Comment by f1rmb** [comment]
Hummm, I think it's better to close the project and reopen it, I guess.
It's part if the project properties.

**Comment by rogerclarkmelbourne** [comment]
OK.
I did initially do that. But I'll try it again on the master branch
I tried git rev-parse --short HEAD and it does work on my machine

**Comment by f1rmb** [comment]
Yeah, it should.

But if MCUXPresso saved the .cproject on top of the freshly pulled one... ;-)

**Comment by rogerclarkmelbourne** [comment]
No. Still not working :-(

I'll try pushing

**Comment by rogerclarkmelbourne** [comment]
Ah, In the messages I see streaming up my screen, I think I can see 'git not found'

**Comment by f1rmb** [comment]
In XPresso: Project -> Properties -> C/C++ Build -> Settings, and in the Tool Settings, in the "All options of GCC, that should starts with this:
-DSDK_DEBUGCONSOLE=0 -DGITVERSION=\"`git rev-parse --short HEAD`\" -DUSE_SEGGER_RTT -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -DFSL_RTOS_FREE_RTOS -DSDK_OS_FREE_RTOS -DCPU_MK22FN512VLL12

**Comment by rogerclarkmelbourne** [comment]
Git is installed, I use the CLI all the time

**Comment by rogerclarkmelbourne** [comment]
But the IDE can't find it :-(

**Comment by f1rmb** [comment]
That's weird !

**Comment by rogerclarkmelbourne** [comment]
Yep.
c:/nxp/mcuxpressoide_11.0.0_2516/ide/plugins/com.nxp.mcuxpresso.tools.win32_11.0.0.201905131304/buildtools/bin/sh: git: not found

**Comment by rogerclarkmelbourne** [comment]
I'm using Github's git CLI

**Comment by rogerclarkmelbourne** [comment]
It runs in powershell I think

**Comment by rogerclarkmelbourne** [comment]
What git are you using on Windows ?

**Comment by f1rmb** [comment]
Ah, I have, in my Window 7 VM, I'm using the CLI from here (it's quite official):
https://gitforwindows.org/

**Comment by rogerclarkmelbourne** [comment]
OK
I'll install that version in addition to the client I already have

**Comment by f1rmb** [comment]
Okay.
... I'm updating the git version on the Win7...

**Comment by rogerclarkmelbourne** [comment]
arrgghh

Installed that git version, but it still does not work on the windows command prompt
I'll investigate whether it needs to be added to the PATH

**Comment by f1rmb** [comment]
Maybe you need to logout/login.

**Comment by rogerclarkmelbourne** [comment]
The file is called git-cmd.exe not git   and its also deprecated :-(

**Comment by f1rmb** [comment]
Let me check on my Win7

**Comment by rogerclarkmelbourne** [comment]
I just rebooted
I think it may work now

**Comment by f1rmb** [comment]
git-cmd is a shell

git.exe is Program\ Files\Git\bin

**Comment by f1rmb** [comment]
It seems I added that in the PATH (long ago)

C:\Program Files\Git\cmd

**Comment by rogerclarkmelbourne** [comment]
yes
Thanks
Its finally working now

**Comment by f1rmb** [comment]
Cool :-)

**Comment by rogerclarkmelbourne** [comment]
And my old git client is still working .....

**Comment by rogerclarkmelbourne** [comment]
I'll update the Tier2Latest SGL

**Comment by f1rmb** [comment]
Is that special client does anything specific ?

**Comment by rogerclarkmelbourne** [comment]
No. Its just the one I have been using for years. Its github's CLI version

**Comment by f1rmb** [comment]
Okay. I need to check that (even if I will continue to stick to official git's versions).

**Comment by rogerclarkmelbourne** [comment]
Yep. Its my problem, and its now fixed ;-)

**Comment by f1rmb** [comment]
;-)

Anyway it's the same version 2.2.4.0-windows.2.

**Comment by rogerclarkmelbourne** [comment]
Yes

**Pull request merged**
