### PR TITLE
Modify glyphs for V, W, X, Y, m, y and w.

### PR DESCRIPTION
**Pull request by f1rmb**
Modifyed the glyphs:
font_gd77_8x16-modded

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel

I think we cross posted.

Did you see my suggestion for V and U  on the forum ?

**Comment by f1rmb** [comment]
Yep, we did.
I'm merging your U and  V, and will push that to this PR

**Comment by f1rmb** [comment]
Done, Roger.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'll pull and merge

**Comment by rogerclarkmelbourne** [comment]
(LOL). Looks good. 

I especially like the V   ;-)

**Comment by f1rmb** [comment]
:-D

**Comment by f1rmb** [comment]
FYI, next pass will be getting rid of the "gd77" word in font identifiers, and harmonize the 'x' between width and height ;-)

**Comment by rogerclarkmelbourne** [comment]
OK.

One thing I did consider changing is getting rid of the font number enum and directly using the pointer to the font from the print calls. 

But its not a big overhead to lookup the font, and it does allow the font pointer to be isolated from the higher levels of code, and it also allows the CPS to specify a font size by using the number

The CPS can display any message including changing the font size etc, so I guess perhaps its better to retain the lookup

**Pull request merged**
