### PR TITLE
Feature revised backlight modes

### PR DESCRIPTION
**Pull request by oh4va**
Hello,

I have revised the Backlight modes. They are now: Auto, Manual, On and Off.
In the Manual mode the light is swicthed totally OFF and back ON again using the Brightness setting.

If you like this take this into the upstream code.

73 de VA

### CODE REVIEW

**Comment by f1rmb** [comment]
As I wrote in the comment on your fork, I've fixed a bug with togggle and minimum brightness value.
Manual mode is just the way backlight is toggled, and it should respect the minimum brightness value.

A fix for the problem is in PR #529 

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
I don't see the point of ON / OFF.

To have the backlight always ON, just to timeout to 'No'. For no backlight at all, set mode to 'None', or brighness to 0%.

Cheers.
...
Daniel

**Comment by oh4va** [comment]
Hi,

Yes, I agree the functionality is achieved using Timeout: No setting. In point of usability my approach is more intuitive.

73 de VA

**Comment by f1rmb** [comment]
Sorry to tell, but I'm still not convinced.

e.g. timeout value is still displayed (and you set the min value to 5s), even on modes where it is meaningless.

The default firmware behaviour is designed on purpose, as Roger clearly stated, most of the Ham are aged, with eyesight problems, at various levels. This is why fonts are big, and backlight is always on, by default. It's up to the user to tweak the default setttings to fit its whishes..


Anyway, the decision is up to Roger.


Cheers.
...
Daniel

**Comment by oh4va** [comment]
> 
> 
> Sorry to tell, but I'm still not convinced.
> 
> e.g. timeout value is still displayed (and you set the min value to 5s), even on modes where it is meaningless.
> 

Did you reset your radio after downloading my firmware? I forgot to mention that. The timeout value is N/A in all modes except Auto.

73 de VA

**Comment by oh4va** [comment]
> The default firmware behaviour is designed on purpose, as Roger clearly stated, most of the Ham are aged, with eyesight problems, at various levels. This is why fonts are big, and backlight is always on, by default. It's up to the user to tweak the default setttings to fit its whishes..

Hi Daniel and Roger,

I see that you are concerned of the usability of the OpenGD77 user interface. For me it is not obvious to set the backlight timeout setting to zero (0) to keep the backlight continuos ON. Instead of setting the mode ON or OFF are clear without reading the user manual.

Anyway, Roger makes the decision of including these modifications to the master branch or not.

73 de VA

**Pull request closed without merging**
