### PR TITLE
No need to return that early.

### PR DESCRIPTION
**Pull request by f1rmb**
Just to cleanup the quick fix.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

I saw that return, and thought it did cause any problems.

But now I look again, I see the function will return at the end of the switch statement, so the return is unnecessary.

**Comment by f1rmb** [comment]
Yup, now I had time to test it, and found my diff wasn't that clean ;-)

**Comment by rogerclarkmelbourne** [comment]
OK. I just recompiled and tested it and its OK.

I won't bother posting an update to the forum as its only a small technical change

**Comment by f1rmb** [comment]
Yeah, no, it won't change anything, I just wanted to fix the fix I (too quickly) posted ;-)

**Pull request merged**
