### PR TITLE
Partial revert of .brightnessOff entry (except for English, Spanish and Catalan).

### PR DESCRIPTION
**Pull request by f1rmb**
These entries were made by concatenating brightness + min words, which is plain wrong, it also messed up special Polish case.
French translation of this entry.

Once this PR is merged, I will ask guys on the forum to check this entry (as it's now untranslated, lost in the middle of the file ;-) ).

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I think it was a bit strange that they had managed to already to do all the translations.

I think in future, developers should probably only update English and their own native language

**Comment by f1rmb** [comment]
Yeah. I'm doing that way, since I know next to nothing about other languages (even my English sucks)...
The string length was quite ignored, for few languages it simply doesn't fit the screen (with setting's value).

**Comment by rogerclarkmelbourne** [comment]
I should have checked the string lengths.

They probably translated using Google

**Comment by f1rmb** [comment]
Errrrr, I don't think so :-D (e.g. the french entry use non standard shortenings).
Bah! nevermind, it's fixed now, and I asked people on the forum.

**Pull request merged**
