### PR TITLE
Update menuChannelDetails.c

### PR DESCRIPTION
**Pull request by vk7js**
SK1 now repeats the current field in the Channel Details screen as it does on the main standby screen.

### CODE REVIEW

**Comment by f1rmb** [comment]
That one will break the channel details feature, I guess.

**Comment by vk7js** [comment]
What do you mean?

Joe

**Comment by f1rmb** [comment]
Nevermind Joe, it was a mistake then I deleted the message immediately.

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
Sorry Joe, but this PR changes 2 different things

A code change for the menuChannelDetails.c and also a documentation change to the User Guide.

These need to be submitted as separate PR's by using 2 separate local branches when you make the changes, otherwise its not possible to revert the code change without reverting the documentation changes and vice versa.

Even if the documentation changes were linked to the code change, which I don't think they are, we still don't mix code and documentation changes in the same PR.

**Comment by vk7js** [comment]
Ok, I’ve reverted the documentation change so you should be able to pull just the code changes now.

Sorry about that.

Thanks

Joe

**Comment by f1rmb** [comment]
Hi Joe,

   I don't know what Roger think about the following, but I think all the calls to Speak{Char,CSSCode,Squelch}() functions calls must be surrounded with the audioPromptMode checking, instead of jumping into the given functions then return early if that level doesn't match (in performances regards).


Cheers.
---
Daniel

**Comment by vk7js** [comment]
It clutters the call site. There is almost no overhead in calling a function.

Joe

**Comment by vk7js** [comment]
Besides there are other examples where this is already the case.

Even the voice prompt functions themselves do their own checks.

Joe

**Comment by f1rmb** [comment]
Hi Joe,

  Sorry to disagree, but there is already lot of such checking, were related prompt levels are checked before jumping to the according functions.

Anyway, it was just an advice, and the decision is up to Roger.


Cheers.
...
Daniel

**Comment by vk7js** [comment]
Hi Daniel,

 

Honestly, the time it takes to run after a key press is in the thousandths of a second. Whether it is one thousandth or 2 thousandths, who would notice? What makes a difference is the maintainability of the code. Huge complex functions made larger by extra checks which could instead be made part of the helper functions, make the code harder to maintain and refactor.

Of course Roger has the final say, but I’ve been a software engineer for 25 years plus and had many such discussions.

Joe

**Comment by f1rmb** [comment]
Err, yeah, cycles matters. Don't forget that there are ISR, tasks etc. The UI has to avoid eating cycles for nothing (there are many other tasks). This is an MCU, not a dozen core frying pan, with gigabytes of RAM :-D

So, there are two cases, voice prompt is ON or OFF. When it's ON, the MCU will spend more time for that feature, that's a fact. But when it's OFF, there is no reason to spend extra cycles jumping in useless functions (those Speak*() functions won't be inlined by the compiler).

It's not a matter how long you've been programming (I don't see the point of that sentence here), what I'm concerned about is to not waste too much cycles for nothing. The code is not yet optimal, but there is no reason to not take care of this when adding/modifying things.

I won't comment on this PR any longer.

Daniel

**Comment by rogerclarkmelbourne** [comment]
Its ultimately a space versus speed issue.

Some of the voice prompts core has checks in the functions which are probably redundant.

Some of the code checks before calling the functions, if the voice prompt is enabled.

I'd need to look at the surrounding code to see if there is a precedence, in this specific are off code.

But I've only been coding for around 40 years, so what would I know ;-)

**Comment by vk7js** [comment]
Ok, guys, I’m working on it.

Joe

**Comment by vk7js** [comment]
Ok,

 

I’ve pulled out the voice level tests from my helper functions and surrounded the call sites with the appropriate tests.

Certainly if these were in a tight loop, the cycles would be critical but never mind, I’ve fixed it now. I’ll keep this in mind for future check-ins.

Joe

**Comment by vk7js** [comment]
Without belabouring this, as I’ve already changed it to how Daniel requested, it does make it harder to change the level at which prompts are spoken since you have to find every call site, rather than just changing it once in the helper functions.

Joe

**Comment by rogerclarkmelbourne** [comment]
It looks generally OK.

However you have created a duplicate copy of main.c in the user_interface folder

firmware/source/user_interface/main.c 

(Thanks Daniel for noticing this, as I may not have noticed it, if the compiler didn't give a an error)

**Comment by vk7js** [comment]
Thanks, sorry about the duplicate. I’ve deleted it.

Yes, the only reason I have taken on improving accessibility of the firmware is for my fellow blind hams as I really don’t have time or energy either.

I so much appreciate what you and others have done. It is huge! It really is. And now that I can contribute to it, we really can make the world’s most accessible radio at a fraction of the cost of its nearest competitor the Kenwood TH-D74a which still has heaps of menus which don’t speak.

Joe

Vk7js

Ps something funny happened. Actually it was scary. I accidentally changed the language on my radio and wondered why the “non” CTCSS and DCS codes were reading weird letters like nem and tyhj, etc. I thought it might have been a nasty memory overwrite. It then occurred to me that it might be a language issue and so I tried changing the language back. If it wasn’t for the fact that the beeps were different at the first entry, It probably would have taken me a bit to figure out. I think I’ll make that menu speak also so it doesn’t happen to someone else.

**Comment by vk7js** [comment]
Hi Daniel,

 

I want to thank you for the incredible job you, Roger and others have done on this project in terms of accessibility. I appreciate also your attention to detail when checking my diffs etc.

Sometimes when I finish my day job I’m just so tired, that the thought of changing code to save an ms (if that) and to retest etc, is just the last straw. There is always a delicate balance between performance, space saving, code clarity and maintainability, and development time.

I just wanted to apologize if I came across frustrated the other day.

We’re all in the same boat in terms of wanting a functional, accessible, and reliable alternative to the stock firmware.

 

Joe

**Comment by f1rmb** [comment]
Hi Joe,

    Thanks. Yeah, that's a really nice project, and I'm very happy to be part of it (the work that was done long before I arrived is enormous).
I always check the diffs, even mine, and sometimes it allows me to see my own mistakes.
No need to apologize, really.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
This PR implements multiple unrelated changes.

As discussed in a previous PR. I do not accept multiple unrelated changes in one PR, as its more difficult to revert changes when they are in the same PR.

You must make separate local branches for each change, and then push each branch separately and then submit a PR for each change.

I also do not accept PRs that change the credits.

**Comment by vk7js** [comment]
They’re all voice prompt related.  If I do this as all separate pull requests it will take weeks.

Joe

**Comment by vk7js** [comment]
Ok, so I’ll go through the whole painful exercise one change at a time. You should now have the first pull request for the holding down hash key while powering on to turn on voice prompts fix.

Joe

**Pull request closed without merging**
