### PR TITLE
Latest update from DG3GSP and IU4LEG.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Arrrggh

These have merge conflicts with your PTT toggle function.  I"ll need to manually merge

**Comment by f1rmb** [comment]
Give me a second, I'll fix this.

**Comment by f1rmb** [comment]
Fixed.

**Comment by rogerclarkmelbourne** [comment]
I also manually fixed it ;-)

**Comment by rogerclarkmelbourne** [comment]
Hopefully I edited OK

**Comment by f1rmb** [comment]
;-)

**Pull request closed without merging**
