### PR TITLE
Add Carrier Squelch to CTCSS Logic

### PR DESCRIPTION
**Pull request by g4eml**
Fix problem where spurious CTCSS decodes were causing audio to briefly unmute.
Now needs Carrier Squelch AND CTCSS before audio Unmutes.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin

Thanks

I actually implemented exactly the same fix in my local copy, but I was not sure whether it would re introduce the original bug, where reducing the squelch during Rx of the fm signal would result in unquelched noise after the received signal ended

I will retest that scenario

**Comment by rogerclarkmelbourne** [comment]
Colin

Unfortunately this fix re-introduces the previous bug.

If reduce the squelch threshold in the Rx while its receiving. When the signal finishes the squelch stays open and you get the usual hiss.

I'll see if I can find why this is happening

**Comment by g4eml** [comment]
Roger, 

Not in my version it doesn’t. 

The PR I submitted is a modification to my previous PR.  You need both for it to work. 

If you have reverted back to the old squelch code then it is not going to work. 


Colin. 



On 10 Apr 2020, at 23:44, Roger Clark <notifications@github.com> wrote:

Colin

Unfortunately this fix re-introduces the previous bug.

If reduce the squelch threshold in the Rx while its receiving. When the signal finishes the squelch stays open and you get the usual hiss.

I'll see if I can find why this is happening

**Comment by rogerclarkmelbourne** [comment]
Sorry Colin

I had  fault in my debugger setup, and it had not actually uploaded the new version to the radio

Very long story, but I managed to screw up my local repo by directly pulling your change into my local master, and then made the mistake of removing the last 2 commits, which was unrecoverable.

So I had to re-clone the whole repo from the server, but the GDB debug lunch config is not part of the repo, and somehow when I tied to launch the debugger it didn't work correctly.

Anyway.  I managed to upload and test and I can see its fixed. 

Thanks again

**Comment by g4eml** [comment]
Hi Roger, 

No problems. Maybe I should have updated my local copy with you recent changes first. It gets confusing when there are so many changes in a short time. 

73 
Colin. 





On 10 Apr 2020, at 23:52, Roger Clark <notifications@github.com> wrote:

Sorry Colin

I had fault in my debugger setup, and it had not actually uploaded the new version to the radio

Very long story, but I managed to screw up my local repo by directly pulling your change into my local master, and then made the mistake of removing the last 2 commits, which was unrecoverable.

So I had to re-clone the whole repo from the server, but the GDB debug lunch config is not part of the repo, and somehow when I tied to launch the debugger it didn't work correctly.

Anyway. I managed to upload and test and I can see its fixed.

Thanks again

**Pull request merged**
