### PR TITLE
Change "Split Cc" options:

### PR DESCRIPTION
**Pull request by f1rmb**
Call it "Contact" with 3 option values:
- Crop: crop to 16 characters, single line display
- Narrow: display contact on a single line until its length is <= 16. If it goes longer, two lines rules apply.
- Span: display callsign on the first line, rest of the TA/Cc/DB on the 2nd line.

Crop is the default value.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I compiled it.

But I think the terminology may be confusing?

When does 'Narrow' occur. Is this when its TA but no custom APRS data?, hence when we remove the "DMR ID: xxx" its always less than 16 characters ?


I think perhaps the naming could be 
"1 line" = Crop
"2 lines" = Span
"auto" = Narrow

But this still does not describe very well the functionality.

**Comment by f1rmb** [comment]
Hi Roger,

   In fact, in this PR, contact and TA are handled the same way. In narrow and span, this info can be displayed on one or two lines, depending it their length is <= or > 16.
So, Narrow tries to display TA/Contact on a single line, and use two if len > 16, and Span always display the callsign on the first line, and remaining TA/Contact on the second.

I agree the naming isn't that intuitive. I will change this in this PR later today.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK

I am testing it now. But there is no taffic on 91

I need to wait for someone who has entered a lot of text in their APRS data in SelfCare

**Comment by f1rmb** [comment]
Try the 9504, there are large TA.

Cheers

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
I eventually heard some traffic on 91...

**Pull request merged**
