### PR TITLE
Fix 1750 and DTMF keys when PTT Latch is used (ANALOG only).

### PR DESCRIPTION
**Pull request by f1rmb**
Tested on GD-77, DM-1801 and RD-5R.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks .

I'll check it tomorrow.

**Comment by rogerclarkmelbourne** [comment]
BTW. 

What are the steps to create the problem in the current firmware version

**Comment by f1rmb** [comment]
Just enable the PTT Latch (and ensure TOT is set on the channel).
In ANALOG mode, SK2 (1750) or any DTMF key won't work (as any key event but SK1 cancels the PTT).

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
