### PR TITLE
Typo: DMR-5R -> DM-5R + buttons picture update + PDF update.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
I just pushed the updated picture from F1CXG.

**Comment by f1rmb** [comment]
And if you have few secs, I will also push the updated PDF.

**Comment by f1rmb** [comment]
Okay. I won't touch this PR anymore (I got to leave the house for an hour :-D )

**Comment by f1rmb** [comment]
Errr, don't merge it, I messed up the PDF, links are wrong. I will fix it when I will get back home.

**Comment by f1rmb** [comment]
Okay, the PDF is fixed.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
