### PR TITLE
Temporarily open squelch

### PR DESCRIPTION
**Pull request by vk7js**
In Analog FM mode, in channel and VFO screen, hash will open squelch even if frequency has a css code on it. The logic of this keystroke is that in DMR mode it is used to change talkgroup or private call, i.e. what is heard. There is no direct equivalent in FM mode, however since there is no way of opening squelch if there is a code on the channel or frequency, this creates a quick shortcut. This is similar to the Monitor feature of many radios.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi,

   About the user experience, having two keys to toggle ON/OFF is bad.
On all the HTs I had in my hands, implementing this feature, they were all use a single key for this, and squelch is remaining open as long as you keep that key down.

Having to press '#' to open and <GREEN> to close is really weird and clumsy.

I would be way better to open the squelch when long press is detected, and close it when that key is released.


Cheers.
...
Daniel

**Comment by f1rmb** [comment]
It's even worse, GREEN or RED or RIGHT or LEFT or STAR could close the squelch.

**Comment by vk7js** [comment]
Hi Daniel,

 

Actually on my Uniden radios, you press and the squelch is opened, then you press again and it is restored. I do know that the Kenwood’’s are as you say, you hold and the squelch is held open only as long as you hold the button. I can change this if others also feel strongly about it. 

I have very sore wrists after programming for so long and so for me it is less painful on my wrists if I don’t have to hold a button down.

 

Joe

**Comment by f1rmb** [comment]
Hi Joe,

   Uniden ? They are building scanners, CB radio and Marine radios.

The FW is tailored for Ham, so it needs to follow the "rules". I never saw any Ham HT having a squelch **toggle**, but a lot with **temporary** squelch opening button, working the way I described.(I owned many Kenwood/Icom/Yaesu/Chinese HTs, and all are working the same).


Cheers
...
Daniel

**Comment by f1rmb** [comment]
Also, I will have rather seen this feature linked to, maybe, the long press of the SK1 or SK2 key, taking care to not break the current UI.

Cheers
...
Daniel

**Comment by vk7js** [comment]
I did think about that, too. Ok, working on it. Which would you prefer? 

Joe

**Comment by f1rmb** [comment]
I don't know, the one that introduces less problems, as both SK keys are already doing a lot of things.


Cheers.
...
Daniel

**Comment by vk7js** [comment]
Which is why I chose hash, also because hash does nothing in analog mode but has a kind of similar function in DMR in that it changes what is potentially heard.

**Comment by rogerclarkmelbourne** [comment]
Joe.

I've already indicated that I don't accept new functionality, or changes to the existing functionality without review by of the forum.

The process is.

- You post a proposal to the forum.
- If there is generally positive feedback and no negative feedback, then bother writing it.
- If not and you still want the feature, write it yourself, but don't send it as a PR. 
However you would then need to maintain 2 different code bases.
- Other people have their own custom versions, which they post links to on the forum.
However, this is also proving to be a problem, as I get emails about problems and bugs in other people's custom versions, because there was a post to this on the forum.

So I will also not be promoting custom versions on the forum, as its just causes additional headaches for me.

I can't however stop people writing custom versions and then promoting them on their own blog or via social media.

Also. 

You'll find that people do not want the squelch to be open-able if CTCSS is enabled. I already proposed something similar to this, and was told this should definitely not be an option.

**Comment by HegrJan** [comment]
Well, and I'd wote for this feature. Monitor Should be one of the basic radio features supporting the "listen first, transmit next" ham spirit habit. I'd love to see it in the GD77S support as well, I'd vote for SK2 long press to activate (FM only), SK2 release to deactivate.

**Pull request closed without merging**
