### PR TITLE
Get rid of 'DMR ID:' in TA, and don't split LH item->contact.

### PR DESCRIPTION
**Pull request by f1rmb**
About the LH item's contact on one line, I think an option is needed.

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

I'm not sure if anyone needs this information.  Do you think an option  is needed.
Or perhaps we can simply remove it.?

**Comment by rogerclarkmelbourne** [comment]
BTW.,
I think we will need to split the options screen soon, as its getting quite large.

**Comment by f1rmb** [comment]
Hi Roger,

   About the option, it's about the contact information (from DMRIDs, it
will fit since its length is <= 16), about codeplug, I need to check that.
In the beginning, we tried to extract callsign to print it on the first
line. Since then, same rule was applied for TA and contact Infos.

I fully agree that DMR ID:xxx is completely useless, who cares about that
number anyway?.

Cheers.
---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
Ah, OK.

I thought you were saying we need an option about whether the DMR ID is removed ;-)

Re: Option where to display the contact info.

If the data is from the Contact or the DMR ID, ideally the text should just be displayed on a single line, as this allows the channel name e.g. repeater to be seen on the bottom line.

For TA, I know its more difficult :-(

**Comment by f1rmb** [comment]
Don't merge it now, I'm trying to avoid dancing TA ;-)

**Comment by f1rmb** [comment]
TG 91 is quiet by now.

**Comment by f1rmb** [comment]
Looks fine. The only question is max contact length in CPS. I'm starting it.

**Comment by f1rmb** [comment]
Okay, digital contact max len is 6, channel name is 15, that fits.

**Comment by rogerclarkmelbourne** [comment]
AFIK both the Digital Contact and DMR ID are max length of 16.

It is possible to make the DMR ID longer as its variable length, but I think 16 is ideal and I won't change it

**Comment by f1rmb** [comment]
I'm adding the optional split for contact.

About the length, yeah, I was just checking. Humm, but the input widget for digital contact seems to limits the field to 15 chars, if I didn't missed something.

**Comment by f1rmb** [comment]
Okay, this PR is done, IMHO.

**Comment by f1rmb** [comment]
Oops, I mixed the max length, it's channel name that it's limited to 15.

**Comment by f1rmb** [comment]
Testing if not splitting TA (uncommited yet) is working as expected...

**Comment by f1rmb** [comment]
Expect one more commit ;-)

**Comment by f1rmb** [comment]
Okay, looks like it work as expected, even for TA (in the limit of TA max length, as if it's longer that 16 chars, it will be spanned over two 8x16 lines (plus the already present 'two 6x8 lines' in that second line, if needed).

**Comment by rogerclarkmelbourne** [comment]
I checked in the CPS and the Digital Contact can be 16.
Its padded with 0xff rather than being terminated.

I'd need to check the code to confirm, but I though there was a function to convert to a string, probably the buffer size is 17 to allow 16 + terminator

**Comment by rogerclarkmelbourne** [comment]
BTW. I wonder if these options should be in the Display Options section.

I know that the Display options is currentl just used for the physical aspect of the display and the backlight, but perhaps we can stretch this definition

**Comment by f1rmb** [comment]
Yes, I had the same hesitation to put the Cc/DB/TA there, as it's related to display, but not related to hardware. I think it would be better and logical, IMHO too.

**Pull request merged**
