### PR TITLE
Ability to set backlight timeout in SQUELCH mode, but minimum value is 5s.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK. I've just seen this.

I'll test....

**Comment by rogerclarkmelbourne** [comment]
Works well...

Thanks.

I will now need to update the User Guide ;-)

**Comment by f1rmb** [comment]
The most annoying part of the job (at least for me) ;-)

**Comment by rogerclarkmelbourne** [comment]
I now have my machine configured for the User Guide.

I use Atom to edit, and have a markdown preview plugin installed. I also have the  Markdown-TOC plugin installed to generate the Table Of Contents.

And I also installed "Markdown-pdf" as a global command using NPM, so I can use this to generate the PDF.

There is a small problem with Markdown-pdf because it does not ignore the comment tag used by Markdown-TOC.
But the only fix is to always remove the tags manually before creating the PDF, but its too much work, so I don't bother ;-)
Its only a small thing in the PDF and most people probably wont even notice it.

**Comment by f1rmb** [comment]
Oh, okay.

About the comments, maybe you can used Powershell for that, it seems there is a sed or grep like feature.

Cheers.

**Pull request merged**
