### PR TITLE
Only trigger Private Call Accept if Destination matches Radio ID. 

### PR DESCRIPTION
**Pull request by g4eml**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Strangely the line numbers don't match with my source code, so I think you may not have the latest original, but I'll try pulling and see what happens

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I tested on my local DMR+ repeater and I do get the echo, but it does not trigger the incoming PC alert

**Comment by g4eml** [comment]
On most radios you wouldn’t see the echo because the DMR spec doesn't allow private calls to be heard unless they are addressed to your radio. The echo is addressed to the distant station so wouldn't normally be received by the originating station. 
Open GD77 is different because it receives everything.

**Comment by rogerclarkmelbourne** [comment]
Colin

I did contemplate adding code to ignore PC's if the origin was your own radio, but I thought it was better not to do that, as otherwise it masks traffic where someone else is using your ID

**Comment by testbird** [comment]
You could only drop any traffic coming from the same ID of the **currently active, AND emitting TX ID**, so "same ID" emissions from other devices at are still heard at any other time.

On a similar note, to avoid another source of audio garbling, it may make sense to make sure to drop any duplicate frames (completely identical) data frames that were received on another time slot (e.g. due to longer distance reflections).

**Comment by rogerclarkmelbourne** [comment]
@testbird

If it ignored your own ID you would not know if someone else is using your ID

**Comment by testbird** [comment]
I might be missing something. If the own ID is *only* ignored while the local device is in the transmitting state (TX), why would one not be able to still know (i.e. hear) if someone else is transmitting using the same ID while the local device is in the regular RX state?

**Comment by rogerclarkmelbourne** [comment]
It will be ignored when its transmitting, as it can't transmit and receive at the same time.

Rx is already inhibited on the other TS even in DMR Passive mode, because there were issues with Tx audio if the radio received on alternate TS when transmitting

**Comment by testbird** [comment]
Ok, sorry, so I gather by "echo" maybe you were referring to receiving only the last bits of the own emissions after stoping TX, as they come back from some repeater?

In that case, maybe only a short "RX mute-time after TX" for the own ID (like an inverse to a TG hang-time) might help?

**Comment by rogerclarkmelbourne** [comment]
I did have a go at implementing that, and I think it would probably work, I've just not had time to get it working

**Comment by testbird** [comment]
Thanks for explaining, that mute-time made me think of the direct path + second refection-path problem again.
Do data frames have some sort of sequence number?
Then maybe some type of time buffered list holding the current ID+sequence numbers could be used to deduplicate the reception in both cases.

**Comment by rogerclarkmelbourne** [comment]
Yes. Frames have a sequence number but only 1 to 6.

There is some other data at the end of the Link Connect buffer as well, but I'm not sure what it represents

**Comment by testbird** [comment]
Sounds good, spanning 6 or even some less frames might already be sufficient to for effective deduplication. Don't you think?

**Comment by rogerclarkmelbourne** [comment]
Probably just put in a short "inhibit" timeout.

As the DMR ID is not sent in every fame.

The source and destination and some other data is only sent in a single frame at the start of transmissions , known as Link Connect Voice Header frames

After that, during the rest of the transmission, the source and destination and other data is sent spanned over 6 frames in the "embedded" portion of the data, which is in the middle the data bytes.

The HR-C6000 DMR DSP does not report the source and destination all the time, it only changes its Link Connect data when there is a change in source (or possibly destination) ID in the LCVH frame or during the embedded data.

So the whole process of determining the current LC data for both timeslots is not as straight forward as it could be, if the C6000 did a better implementation of its LC data handling

**Comment by g4eml** [comment]
I am pretty sure the ‘echo’ that people are seeing is actually the repeater sending repeated ‘voice call terminator with LC’ frames during the call hang time. This is normal behaviour and can be for several seconds after the incoming transmission stops depending on how the repeater has been configured.  Radios that are involved in the call (same Talkgroup or same private IDs) are allowed to transmit during this time. Other radios must treat the channel as busy. 

I think the radio should probably not display the LC data from a terminator frame. However I  am not sure how easy it would be to inhibit this. 

Colin. 



On 4 Dec 2019, at 23:16, Roger Clark <notifications@github.com> wrote:

Probably just put in a short "inhibit" timeout.

As the DMR ID is not sent in every fame.

The source and destination and some other data is only sent in a single frame at the start of transmissions , known as Link Connect Voice Header frames

After that, during the rest of the transmission, the source and destination and other data is sent spanned over 6 frames in the "embedded" portion of the data, which is in the middle the data bytes.

The HR-C6000 DMR DSP does not report the source and destination all the time, it only changes its Link Connect data when there is a change in source (or possibly destination) ID in the LCVH frame or during the embedded data.

So the whole process of determining the current LC data for both timeslots is not as straight forward as it could be, if the C6000 did a better implementation of its LC data handling

**Comment by testbird** [comment]
Thanks, I see.
Well, maybe the DSP already filters out duplicates in the sequence (filtering based on current LC data). That might solve the reflection case already.

Otherwise, yes merging and deduplicating frames from two timeslots does not seem that straight forward.

Maybe along these lines:
status data: current ID + sequence ring bitmap + bitmap ring pointer
RXed Frames can set an unset bitmap sequence bit, or get droped, then unset the oldest bit in the ring, and increase the pointer.

**Comment by rogerclarkmelbourne** [comment]
Colin

I think the echo may include your own audio in extreme cases (I think I've heard this on Brandmeisiter via my duplex hotspot)

The simplest way to do this is just to have a inhibit timer after the PTT is released and then ignore any LC's that contain ones own ID as the source, during this inhibit timeout.

In the HR-C6000 code, at then end of the Tx shutdown code, set a counter, and in the main part of the RTOS code, decrement that timer if its >0

Then in the ISR that handles sending the LC ID etc to the UI, don't allow it to happen if the inhibit timer > 0


We could initially try this at 1 second and see if thats long enough.

**Comment by g4eml** [comment]
Roger, 

Hearing your own voice would need quite a long delay. The local repeating is handled by the repeater not the network and commercial repeaters have a delay of only a few frames in doing this. However I suspect MMDVM based repeaters may well introduce longer delays due to the buffering and transfer times between modem and MMDVMHost. 
To be honest it’s not a big issue anyway. The main problem was the unwanted triggering of the private call alert which has now been fixed. 

Colin. 


On 4 Dec 2019, at 23:51, Roger Clark <notifications@github.com> wrote:

Colin

I think the echo may include your own audio in extreme cases (I think I've heard this on Brandmeisiter via my duplex hotspot)

The simplest way to do this is just to have a inhibit timer after the PTT is released and then ignore any LC's that contain ones own ID as the source, during this inhibit timeout.

In the HR-C6000 code, at then end of the Tx shutdown code, set a counter, and in the main part of the RTOS code, decrement that timer if its >0

Then in the ISR that handles sending the LC ID etc to the UI, don't allow it to happen if the inhibit timer > 0

We could initially try this at 1 second and see if thats long enough.

**Comment by rogerclarkmelbourne** [comment]
Yes.
Its no longer a big issue and people have reported other radios sometimes display their own ID's due to the digital echo

**Comment by testbird** [comment]
> After [LCVH link connection], during the rest of the transmission, the source and destination and other data is sent spanned 
> over 6 frames in the "embedded" portion of the data, which is in the middle the data bytes.

> The HR-C6000 DMR DSP does not report the source and destination all the time, it only changes its 
> Link Connect data when there is a change in source (or possibly destination)

So, the DSP may check if the data embedded in the frames do correspond to the LCVH, but only per timeslot. So the reported link connection data may be trustable, but only in conjuction with a single timeslot. Thus a custom promiscuous `TS*` mode might need to sort the timeslot streams again based on id+sequence or even that "embeded" data before passing it to the voice decoder?

**Comment by testbird** [comment]
> source and destination and other data is sent spanned over 6 frames in the "embedded" portion of the data

So the LCVH link conection info and the sequence number of a particular frame should allow to know what embedded data is to be expect for frame verification. (Even without all frames containing the full IDs.)

**Pull request merged**
