### PR TITLE
TX PTT sound

### PR DESCRIPTION
**Pull request by EA5SW**
Sound as release the  PTT button in TX.
Options MENU Enables and disables.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Please can you explain what this function is intended to do?

Why do you have melody for Tx and Rx?

I think this option needs to be disabled by default, as most people will not want it.

Probably you should have the setting as uint8_t and then have an enum to define the various options e.g. for Tx Start, Tx End and both

I don't know if you intended the sound to only be played through the speaker or whether this is supposed to play via the transmission

On DMR you should not transmit tones like this at all. There are special AMBE byte patterns that must be used in order to send tones, because AMBE does not correctly handle single frequency modulation.

The AMBE codec in the GD-77 is non standard and does encode some frequency tones, but its not guaranteed that the radio which receives the signal will decode these beeps.

On FM, if you want to transmit the tone, you should not play the tone using the melody.
You should use the FM tone generator which is used by the DTMF and 1750Hz systems, as this results in a clean tone.

If you did not intend to transmit the tone, I think perhaps this should be an option on FM, after the PTT is released, the Tx is held for perhaps 0.25 or 0.5 sec while the tone is transmitted.

**Comment by EA5SW** [comment]
This is only a PTT beep via speaker (no RF) to indicate that you as released a transmission.
Useful when you have the talky in belt and put a external microphone.
The  original firmware have a similar tone beep as another Radiodity models,

I tried to put the beep in some parts of code and the best place appears to be this.

it's only a reminder that you have the PTT pressed and on release sound the beep, not ambe encode, not modulation  encoded.. only a reminder sound.

**Comment by rogerclarkmelbourne** [comment]
OK.

I will test and probably make some changes ;-)

**Comment by rogerclarkmelbourne** [comment]
Where is this option in the original CPS, as I want to compare the official firmware function for this

**Comment by EA5SW** [comment]
In original CPS the "TX exit Tone" setting are in General settings, and when you release the PTT the beep sounds (same as those PR)

Also have a entry in MENU Radio Set:

10 Beep

1.- All Tone 2.- Call permit 3.- Key Beep

That sounds when  press PTT.

**Comment by longjos** [comment]
Along this feature. Having a melody to indicate the DMR handshake is complete and ready to transmit is also handy.

Just a suggestion that I'm playing with locally:
https://github.com/EA5SW/OpenGD77/pull/1

**Comment by rogerclarkmelbourne** [comment]
VK4APF also requested the handshake complete beep

I think the MD-380 tools beeps a low tone each time the transmitter sends a wake-up pulse and then when the repeater responds, the MD-380 emits a short higher pitch tone.

This should not be too hard to implement.

**Comment by rogerclarkmelbourne** [comment]
BTW. Somehow this PR now has a merge conflict with the finnish language file.

This should not be possible unless the finnish file was also changed during this PR or the master branch was not pulled prior to making the changes to the fork

**Comment by longjos** [comment]
I noticed today that the audio stream has already started by the time the melody plays in my patch so some of the chirp gets transmitted. :/

**Comment by EA5SW** [comment]
> BTW. Somehow this PR now has a merge conflict with the finnish language file.
> 
> This should not be possible unless the finnish file was also changed during this PR or the master branch was not pulled prior to making the changes to the fork

Yes, the fininish file are changed those days...

**Comment by rogerclarkmelbourne** [comment]
@longjos   What patch ??

**Comment by rogerclarkmelbourne** [comment]
I can't accept this in its current form.

The finnish language file does merge, but shows a load of diffs, which it should not.

You seem to have added entries into the top level menu system for this option, whereas the change is confined to the Options screen.

The setting should probably be a uint8_t as some people will want to transmit the tone not just hear it through the speaker, so we should allow for this enhancement in the original programming.

**Comment by longjos** [comment]
> @longjos What patch ??

I opened a PR on the forked repo here: https://github.com/EA5SW/OpenGD77/pull/1/files so that my changes would be obvious from the original changes. This doesn't work well as the audio from the chirp gets picked up by the mic and gets transmitted. I'll tinker around with it some more. Would likely need to look at "muting" the mic during any melody being played during TX.

**Comment by rogerclarkmelbourne** [comment]
@longjos 

This is strange, how come you appear as both @longjos  and also @EA5SW  ?

**Comment by longjos** [comment]
We are different people. :) I saw EA5SW's PR and built on top of it.

**Comment by longjos** [comment]
Feel free to ignore me. I'll monitor the progress of PR 446 and continue local experiments.

**Comment by EA5SW** [comment]
> I can't accept this in its current form.
> 
> The finnish language file does merge, but shows a load of diffs, which it should not.
> 
> You seem to have added entries into the top level menu system for this option, whereas the change is confined to the Options screen.
> 
> The setting should probably be a uint8_t as some people will want to transmit the tone not just hear it through the speaker, so we should allow for this enhancement in the original programming.

Thanks 

Close PR.

**Comment by rogerclarkmelbourne** [comment]
I think we need to split the options into separate sub screens

Probably have

Options 
-----Display options
-----Tx options
-----Rx options

I will modify my master to have this

Then these options can be added to the appropriate section

**Comment by rogerclarkmelbourne** [comment]
@longjos 

Using DMR_STATE_TX_START_1 is better, because this still does not get reached until the repeater is awake.

Also. If you start playing the tone on DMR_STATE_TX_START_5 you will hear the tone on the transmitted signal

I think if the tone is very short, and is stared on DMR_STATE_TX_START_1 then perhaps the tone will not get transmitted, 

Possibly when this is enabled, the first few audio frames need to be filled with silence to prevent the beep being heard.

but I need to do some more tests.

**Comment by longjos** [comment]
Got some pretty good results with a short TX start melody and triggering the melody start on DMR_STATE_TX_START_1. When the repeater is first waking the melody plays correctly and is not heard in the TX audio.
If the repeater is already awake, the melody gets interrupted and stops short. I'll continue to experiment.
Do you know off hand of a place in the code that generates silence so I can see an example?

**Comment by rogerclarkmelbourne** [comment]
This is already working for me.

I've published a version to the opengd77 forum which includes that feature and responses have been positive, and no one reported the problem if the repeater is already awake.

**Pull request closed without merging**
