### PR TITLE
GD-77S: Make it blinking in Orange. Fixed, I hope, the LEDs state management in trx.c.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
Updates:

GD-77S: Fix blinking, and LEDs management (I hope, once again).

trx.c:
  Rename and Change prototype of int trx_carrier_detected(void) to bool trxCarrierDetected(bool). Make it handling Digital and Analog like trx_check_analog_squelch() a$
  Rename trx_check_analog_squelch() and trx_check_digital_squelch() to trxCheck{Analog,Digital}Squelch().

HD-C6000.c:
  Use renamed above functions. Some reindentations.

UI: Fix Green LED (in digital): when releasing the PTT and a signal is already there, lit the LED.

**Comment by rogerclarkmelbourne** [comment]
Sorry Daniel. 

Its still got the same bug(s)

If I press and hold the PTT when the yellow LED is illuminated, the LED changes to green for me.
When the PTT is then released the green LED goes out.

However, if you press and release the PTT during the heartbeat, the green LED illuminates and then does not turn off until the next heartbeat

**Comment by f1rmb** [comment]
Hi Roger,

   That's really strange, I don't have any of this problem.
Could you share the codeplug ?.

Cheers.

**Comment by f1rmb** [comment]
Okay, now it seems to work correctly with Out of Band and RX Only channels.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I re-tested, and the heartbeat seems to be working fine, and the green LED problem is gone

**Comment by f1rmb** [comment]
Cool. Thanks Roger.

**Pull request merged**
