### PR TITLE
Fix BW/TS/CC/RxGrpList in Analog.

### PR DESCRIPTION
**Pull request by f1rmb**
Force 12.5kHz when selecting DIGITAL.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Can you rebase, now that I merged Alex's fix

Thanks

**Comment by f1rmb** [comment]
Yup

**Comment by f1rmb** [comment]
Okay, conflicts fixed.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

No one has noticed these problems, but they were obvious bugs

**Comment by f1rmb** [comment]
Yeah, but once you stumble on it... :-D

**Comment by f1rmb** [comment]
And I'm afraid some people (me included) may have saved bad parameters in their codeplug.

**Comment by rogerclarkmelbourne** [comment]
OK. I don't think I've had this problem.

**Pull request merged**
