### PR TITLE
Small cleanup, no need the handle dot units, as it's always 1.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel

Why did you enable the audio amp and the rx audio mux ?
```

			GPIO_PinWrite(GPIO_audio_amp_enable, Pin_audio_amp_enable, 1);
			GPIO_PinWrite(GPIO_RX_audio_mux, Pin_RX_audio_mux, 1);
```

I've noticed I'm getting some 50Hz mains hum on the CW ID audio.

I tired turning off at audio amp, and also change the mux so that the input to the AT1836 is the C6000, but it didnt seem to help.

I think possibly the mic gain may need to be turned off during CW transmission.

**Comment by f1rmb** [comment]
Hi Roger,

    Well, I didn't noticed any hum here (i'm powering the GD from battery, only), plus I won't give much credits to my ears...
I'll try to turn off MIC gain.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
I just tried that, and it didn't seem to make any difference

**Comment by rogerclarkmelbourne** [comment]
I did some testing, and the 50Hz mains hum seems to be from the charger.

This is surprising as its a switch mode charger, but it does not have an earth connection, so it will be floating with capacity coupling to the mains.

I think there is also pickup via the USB cable, and also possibly via the debugger USB connection, which will earth the radio to the PC via the USB  ground connection.

Strangely, I seem to have much more hum on 2m than I have on 70cm

I have an external speaker mic, which I made from some PC speakers, and also some speaker mics which I cut the cables etc, and this also has a lot of hum. 

But there is less hum if I disconnect the speaker mic

I think its generally interesting, that for people who run their GD-77 in a charger as a Hotspot, the there may be 50Hz mains noise on the 4FSK transmissions.
This would also apply to normal DMR operation

I'll post to the forum to see if anyone else has this issue

**Pull request merged**
