### PR TITLE
Remove factory reset option.

### PR DESCRIPTION
**Pull request by f1rmb**
This PR also has the fix in (now closed) PR #860

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by jg1uaa** [comment]
Maybe this related problem, I cannot build development branch with this error (using arm-none-eabi-gcc-10.2 by Arch Linux, not MCUXpresso sorry).

```
[CC ] ../source/user_interface/menuOptions.c
../source/user_interface/menuOptions.c: In function 'updateScreen':
../source/user_interface/menuOptions.c:91:48: error: 'stringsTable_t' has no member named 'factory_reset'
   91 |     leftSide = (char * const *)&currentLanguage->factory_reset;

```

And I grep'ed include/user_interface/languages directory, only japanese.h has factory_reset entry. It will be deleted.

**Comment by rogerclarkmelbourne** [comment]
OK.

The code for that uses this string should also have been removed.  I'll do a fix for this.

**Comment by rogerclarkmelbourne** [comment]
I have fixed this. See the development branch

**Comment by jg1uaa** [comment]
building development branch with no problem. thank you.

**Pull request merged**
