### PR TITLE
VOX: take care of the hotspot running status.

### PR DESCRIPTION
**Pull request by f1rmb**
HS: revert to previous version, removing vox enable/disable code.
HS Mode: write mode in bold even on analog mode.

### CODE REVIEW

**Comment by f1rmb** [comment]
Okay, lets fix the conflict :-D

**Comment by f1rmb** [comment]
Fixed ;-)

**Comment by f1rmb** [comment]
Argglll again...
:-D

**Comment by f1rmb** [comment]
Fixed

**Comment by f1rmb** [comment]
Hummmm

**Comment by rogerclarkmelbourne** [comment]
I manually merged the change to the scan blink.

My commit already made most of the other changes

Why did you decrease the Hotspot version?

**Comment by f1rmb** [comment]
Yup, I did decrease, since the bump the version when I added the VOX things.

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll merge it, but I think its basically the same as whats in the master, and I don't think its necessary to check  nonVolatileSettings.hotspotType

Because  in usb_com.c  checks nonVolatileSettings.hotspotType

```
					if ((nonVolatileSettings.hotspotType != HOTSPOT_TYPE_OFF) && (com_requestbuffer[0] == 0xE0U /* MMDVM_FRAME_START */))
					{
						settingsUsbMode = USB_MODE_HOTSPOT;
						menuSystemPushNewMenu(UI_HOTSPOT_MODE);
						return;
					}
```

**Comment by f1rmb** [comment]
Yup, you can drop that one.

**Comment by f1rmb** [comment]
PR updated.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by rogerclarkmelbourne** [comment]
BTW. Perhaps the VOX threshold could be converted to % somehow.

I'll look at the code

**Pull request merged**
