### PR TITLE
Display QSO Information when switching contacts

### PR DESCRIPTION
**Pull request by f1rmb**
Was stuck to channel informations.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hold on a sec, I've found something...

**Comment by f1rmb** [comment]
Okay:
- Call clearDMRID() when loading a channel settings as switching from DMR to FM won't clear them up.
- Fix Zone switching when RXing DMR: old QSO info was stuck on screen.

PR is ready, I think ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've seen this bug.


I have merged and I will do some more testing when there is more activity on my local DMR

**Comment by f1rmb** [comment]
Hi Roger,

   Okay.
There is still another bug: sometimes, when you jump to a channel where a QSO is already running, the QSOData aren't displayed, the RSSI bar blinks 3 times, then goes blank and the whole thing stops trying to display these informations (but audio is present), and that until another station key up.
I didn't found the procedure to reproduce this one 100% of the time.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
I think there is also another bug, when both TS1 and TS2 are in use, with TS filtering disabled, and you switch between TS1 and TS2, sometimes the TS seems to be filtered and I don't hear anything.

I need to check if this happens only if TS filtering is disabled or whether the problem can also occur if filtering is enabled

**Comment by f1rmb** [comment]
Oh, okay.
I mostly use simplex. I should use my dual board instead 😉

**Pull request merged**
