### PR TITLE
GCC 9 Warnings

### PR DESCRIPTION
**Pull request by ajorg**
I gave the GCC / Makefile build a try and found that it wasn't building correctly so I asked it to complain a lot (`-Werror`) and fixed all the warnings.

There are some other improvements I want to make to the Makefile, but I have to re-learn how to do some things with it before I can get there.

Builds cleanly with toolchain from https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads on Linux. I haven't actually tried flashing this build just yet - and I know it's not officially supported right now, but this is a little step toward setting up CI/CD, so I wanted to take that step.

Regardless of any desire to support not using MCUXpresso these changes all appear to me to be correct.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Generally its not a good idea on a 32 bit processor to use 8 bit variables. So if there are warnings because 32 bit vars are being passed into functions that use 8 bit vars then the functions should be reviewed to determine whether an 8 bit value should be used at all.

Even using 8 bit vars in structs is generally a waste of time, because the compiler won't pack structs unless you specifically tell it to, because its causes a performance hit to do so.

Similarly with this

```
-			snprintf(buffer, bufferLen, "PC %d", trxTalkGroupOrPcId & 0x00FFFFFF);

+			snprintf(buffer, bufferLen, "PC %ld", trxTalkGroupOrPcId & 0x00FFFFFF);
```
trxTalkGroupOrPcId  is not a "long" its a 32 bit value, so I don't see why you would need to specify %ld for a int not a long.





Also, you say you've not actually flashed it to the radio and confirmed that all of these changes has made no difference to the operation?

So its possible that these changes actually cause problems ??

**Comment by ajorg** [comment]
The `soundBeepVolumeDivider` change matches it to its size in the non-volatile settings.
I did review each change to determine if it was correct.

 The `gMenusCurrentItemIndex` change is interesting. The compiler needed it, because it was discerning between `int` and `int32_t` possibly on the basis that this code could get compiled on other architectures, but it occurs to me now that I'm unsure if what's going on is that the compiler is confused and issuing warnings for 64bit because it's on a 64bit Linux or if it's issuing warnings because it's possible we could want to compile it on a 64bit system. I know it gave warnings about char indexes because on some architectures char may be signed, so the latter seems more likely.

The `snprintf` changes should be no-ops. As long as the value going into the function is smaller than the format it will print the same thing.

> Also, you say you've not actually flashed it to the radio and confirmed that all of these changes has made no difference to the operation?
>
> So its possible that these changes actually cause problems ??

No, I meant that I didn't flash the GCC build, because I figured if I found some problem with it I'd never know if the problem was some subtle bug that was always there in that build and has nothing to do with my changes.

To my knowledge these changes cannot possibly introduce new problems, but I take your point and I will test the areas that changed anyway, just to be sure. I'll also try to find out if GCC is being stupid or if it's trying to help us avoid multiarch bugs (more likely). I'll also give the GCC build a try.

**Comment by rogerclarkmelbourne** [comment]
I'm not sure about the sprintf thing, I've had problems passing vars of the wrong size to printf because its varags and it ended up crashing the code

And I still can't see why you should print it as Long Int when its Int.

A lot of these warnings seem erroneous 

Changing the code to please a compiler that is not the compiler specified by NXP seems to be asking for trouble.

I recommend just using the same version of compiler that the IDE uses, as after all it is GCC ARM, just an older version.

**Comment by ajorg** [comment]
> I recommend just using the same version of compiler that the IDE uses, as after all it is GCC ARM, just an older version.

I've tried that just now (meaning I've pointed it at the toolchain that came with MCUXpresso), and I'm getting the same errors and warnings that I've addressed here, so there must be some difference in the compiler flags. I'm going to dig a bit deeper and get back to you.

**Comment by ajorg** [comment]
I haven't solved it yet, but this does look like it's an environment setup problem. It seems like it's pulling integer definitions from somewhere weird when compiled with newlib instead of redlib.

I'll withdraw this PR for now. If I manage to figure out how to make my cross-compile environment better I might send a new one.

**Pull request closed without merging**
