### PR TITLE
Fixes to Catalan

### PR DESCRIPTION
**Pull request by EA3BIL**
#23, version number updated
#108, used T.O.T., it's higly specific. Also "de temps" + ":" + .both = 18 !!!
#149, placed missing tilde
#151, Capitals to beep

73'Rafa.
EA3BIL.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
This won't merge automatically.

Did you pull from my master repo first?

**Comment by EA3BIL** [comment]
I directly copied the Raw from the Master and used as base.

Please, let me know if any afditional actions needed.

Thank you.

**Comment by f1rmb** [comment]
I merged the file from the forum and this conflicting PR (#481 )

**Comment by EA3BIL** [comment]
Closed

**Pull request closed without merging**
