### PR TITLE
HS: Display 'TX CW' while beaconning.

### PR DESCRIPTION
**Pull request by f1rmb**
And reduce CW buffer (300 to 64)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Its not keying the CW ID after uploading this version.

"Received a NAK from the MMDVM, command = 0x0A, reason = 4"

**Comment by rogerclarkmelbourne** [comment]
I just recompiled my master branch and CW ID worked again. So there is something in this PR which broke it :-(

**Comment by f1rmb** [comment]
Wow. Okay, I'll check this in a second.

**Comment by f1rmb** [comment]
Okay, I know why.

**Comment by rogerclarkmelbourne** [comment]
OK

BTW. There are VK stations with 7 character callsigns and and some overseas stations with even longer callsigns.

**Comment by rogerclarkmelbourne** [comment]
I guessed that may be the case ;-)

**Comment by f1rmb** [comment]
here, the longest symbol is ',' (22 bits), minus 2 * 6 bits for begin and end silences, that leaves around 22 comma to be keyked ;-)

**Comment by rogerclarkmelbourne** [comment]
OK. Its working now.

Do you think perhaps the text should be "Tx CW ID", but perhaps this would require a translation string :-(

**Comment by f1rmb** [comment]
and we save 236 bytes :-D

**Comment by f1rmb** [comment]
Well, I had some hesitation about putting the ID or nox ;-)
Free free to change it, but I think it's really not necessary to translate it, as TX CW are international acronyms, and for ID... well, no ;-)

**Comment by rogerclarkmelbourne** [comment]
OK
I will just merge it.

**Comment by f1rmb** [comment]
Add the 'ID' if you want, that doesn't matters.

**Pull request merged**
