### PR TITLE
Fix the bug reported by F6GVE: switching from VFO to Channel when RXing keeps the QSO info on screen.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

I've noticed several occasions when the ID display was held.  I don't know if its just this instance, but I'll pull and merge, because it will at least me a partial fix.

**Comment by f1rmb** [comment]
I introduced the code that created this problem. Originally, leaving a menu, whis a running QSO, had a bad behavior as it was waiting for the next QSO_DATA_UPDATE event, and it could be really long before getting it.
The problem here is since we stop the process by hand (switchng VFO/Channel), the PC/TG/ID in the HR6000 code aren't cleared, and the RF amp is still open for the next ms. Clearing the PC/TG/ID my hand fix this.
BTW, I didn't checked (it was late, I had to leave the keyboard) if it happens the other way around, from Channel to VFO.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK. Do you think its all fixed now ?

**Comment by f1rmb** [comment]
I need to check from Channel to VFO, in the next 30 mins.

**Comment by f1rmb** [comment]
Okay, I checked, there is no problem switching from Channel to VFO mode.

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

**Pull request merged**
