### PR TITLE
Don't override the display with QSO data when displaying channel details

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
I need to add something else, please wait.

**Comment by f1rmb** [comment]
Okay. Added.
Unfortunately, TG91 is quite silent right now...

**Comment by f1rmb** [comment]
Okay, tested now, it works as expected.

**Comment by f1rmb** [comment]
Hmmm, I need to make a function for the last thing I've added, this piece of code is repeated 4 times in total...

**Comment by f1rmb** [comment]
Okay, done.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I tested it, and it seems to have fixed the bug.

BTW. I'm currently trying to re-assemble my Baofeng RD-5R now that that someone has ported the firmware to that radio. But currently the speaker is not making a sound :-(
So I'm taking the radio apart again.

**Comment by f1rmb** [comment]
Okay. Cool.

I search in google, but unable to find a PCB picture.
I'm currently charging my DSLR battery as I will disassemble my 77S this afternoon, and take some hires/macro pictures of the internals.

Cheers.
...
Daniel

**Pull request merged**
