### PR TITLE
Sound options + TX Start/Stop beep options.

### PR DESCRIPTION
**Pull request by f1rmb**
Move related sound options to new "Sound options" menu. Move DMR Mic Gain in the same menu.
Add TX Beep option: None/Start(default)/Stop(unimplemented yet)/Both.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I renamed Tx Beep to DMR beep, in case some people expected it to work on FM as well as DMR.

I think people will want some other options for FM, e.g. Tone that is transmitted when the  PTT is released, which is sometimes called a "Roger Beep", but this is completely different functionality

**Comment by f1rmb** [comment]
Hi Roger,

   Okay. Yes, I hesitate about the name, I thought it wasn't that clear.

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
Ah. OK. I think DMR Tx beep would be too long.

We could perhaps split the sound options into 2 sub menus.

I designed the menu structure to handle this, but I have not tried to use it for a long time.

**Comment by f1rmb** [comment]
Well, We could add Analog and DMR submenus (if it's what you have in mind), when Analog chimes ;-) will be added.

**Pull request merged**
