### PR TITLE
Update from DG3GSP + fix italian.h file ending.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I will merge this tomorrow when also hopefully the Turkish version will be stable.

**Comment by f1rmb** [comment]
Okay.

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

Le dim. 16 févr. 2020 10:46, Roger Clark <notifications@github.com> a
écrit :

**Comment by rogerclarkmelbourne** [comment]
Thanks.

BTW.
I won't release a new version until later today (17th Feb) as there are some bugs with the audio amp enable / disable which I would like to fix.

**Comment by f1rmb** [comment]
Okay Roger.

**Pull request merged**
