### PR TITLE
[Hotspot] Cleanup in Serial comm (some commands should be ignored, some others …

### PR DESCRIPTION
**Pull request by f1rmb**
…are only used in answer frames).

### CODE REVIEW

**Comment by f1rmb** [comment]
I also need to check if available space returned by getStatus() is correct (e.g USB buffer).

**Comment by f1rmb** [comment]
The switch statement is still messy, I left the comments just as informations.

**Comment by f1rmb** [comment]
About available space returned by getStatus(), what do you think about that:

```
diff --git a/firmware/source/user_interface/uiHotspot.c b/firmware/source/user_interface/uiHotspot.c
index 89731c0..2aa344d 100644
--- a/firmware/source/user_interface/uiHotspot.c
+++ b/firmware/source/user_interface/uiHotspot.c
@@ -988,7 +988,7 @@ static void getStatus(void)
 
        buf[6U] =       0U;// No DSTAR
        buf[7U] =       10U;// DMR
-       buf[8U] =       HOTSPOT_BUFFER_COUNT - wavbuffer_count;
+       buf[8U] =       MIN((HOTSPOT_BUFFER_COUNT - wavbuffer_count), ((COM_BUFFER_SIZE - (usbComSendBufWritePosition - usbComSendBufReadPosition)) / (DMR_FRAME_LENGTH_BYTES + 2U))) ;
        buf[9U] =       0U;// No YSF
        buf[10U] = 0U;// No P25
        buf[11U] = 0U;// no NXDN

```

**Comment by f1rmb** [comment]
> About available space returned by getStatus(), what do you think about that:
> 
> ```
> diff --git a/firmware/source/user_interface/uiHotspot.c b/firmware/source/user_interface/uiHotspot.c
> index 89731c0..2aa344d 100644
> --- a/firmware/source/user_interface/uiHotspot.c
> +++ b/firmware/source/user_interface/uiHotspot.c
> @@ -988,7 +988,7 @@ static void getStatus(void)
>  
>         buf[6U] =       0U;// No DSTAR
>         buf[7U] =       10U;// DMR
> -       buf[8U] =       HOTSPOT_BUFFER_COUNT - wavbuffer_count;
> +       buf[8U] =       MIN((HOTSPOT_BUFFER_COUNT - wavbuffer_count), ((COM_BUFFER_SIZE - (usbComSendBufWritePosition - usbComSendBufReadPosition)) / (DMR_FRAME_LENGTH_BYTES + 2U)));
>         buf[9U] =       0U;// No YSF
>         buf[10U] = 0U;// No P25
>         buf[11U] = 0U;// no NXDN
> ```

Hmmmm, that won't even work, read/write are set to buffer[0] only when bumping on the end...

**Comment by f1rmb** [comment]
> > About available space returned by getStatus(), what do you think about that:
> > ```
> > diff --git a/firmware/source/user_interface/uiHotspot.c b/firmware/source/user_interface/uiHotspot.c
> > index 89731c0..2aa344d 100644
> > --- a/firmware/source/user_interface/uiHotspot.c
> > +++ b/firmware/source/user_interface/uiHotspot.c
> > @@ -988,7 +988,7 @@ static void getStatus(void)
> >  
> >         buf[6U] =       0U;// No DSTAR
> >         buf[7U] =       10U;// DMR
> > -       buf[8U] =       HOTSPOT_BUFFER_COUNT - wavbuffer_count;
> > +       buf[8U] =       MIN((HOTSPOT_BUFFER_COUNT - wavbuffer_count), ((COM_BUFFER_SIZE - (usbComSendBufWritePosition - usbComSendBufReadPosition)) / (DMR_FRAME_LENGTH_BYTES + 2U)));
> >         buf[9U] =       0U;// No YSF
> >         buf[10U] = 0U;// No P25
> >         buf[11U] = 0U;// no NXDN
> > ```
> 
> Hmmmm, that won't even work, read/write are set to buffer[0] only when bumping on the end...

Geee, woke up too early. that may work.... or not... or. COFFEE ;-)

**Comment by f1rmb** [comment]
Do not merge it, I'm still on this ;-)

**Comment by rogerclarkmelbourne** [comment]
OK

I have been investigating the data to the C6000 ;-)

**Comment by f1rmb** [comment]
Yeah, I read all the emails about that, nice investigation BTW ;-)

**Comment by rogerclarkmelbourne** [comment]
Reading the forum, I presume this is not ready to merge yet ??

**Comment by f1rmb** [comment]
Hi Roger,
  No, not yet (the lockup I fixed isn't commited yet, but it looks like there is another one I need to check too).

If you prefer, I can close this PR and reopen it when it will be ready.

**Comment by rogerclarkmelbourne** [comment]
Its OK.  Leave it open.  I won't merge until you tell me its ready

**Comment by f1rmb** [comment]
Oops, I renamed the branch, and it got closed...

**Pull request closed without merging**
