### PR TITLE
Split VFO tone scan modes: All, CTCSS, DCS and iDCS.

### PR DESCRIPTION
**Pull request by f1rmb**
In the orange menu, select (Right/Left) the tone scan mode, then hit Green to start.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks. I'll download and test later today.

**Comment by f1rmb** [comment]
I didn't made changes about the other issue #721 as it needs to be discussed.
I mean, does the CSS tone should be kept if Green button is hit, and previous tone is restored on any other cases ?

... Sorry, I'm using Github for emails, GMail looks borked ATM ...

**Comment by rogerclarkmelbourne** [comment]
I'll reply to #721 in #721

**Comment by rogerclarkmelbourne** [comment]
Do we need to store this in the Non volatile settings?

I think just a global variable in settings should be enough, I don't think it is necessary for the radio to remember this between reboots, as its just wasting space in the non-volatile settings.

**Comment by f1rmb** [comment]
Yeah, I had some doubts here. Okay, I will remove the nonVolatile setting.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I don't want to add too much bloat to the settings

**Comment by f1rmb** [comment]
Okay, done. I reverted the nonVolatile storage, and added the tone value restore when scan is canceled.

**Comment by rogerclarkmelbourne** [comment]
Ok. Thanks 

I will check it now.

**Comment by rogerclarkmelbourne** [comment]
Thanks. Fixes bugs #721 and #722

**Pull request merged**
