### PR TITLE
Slight modification of glyph for '5', as it's too similar to 'S' (8x16 font only).

### PR DESCRIPTION
**Pull request by f1rmb**
I've got confused with the 5 glyph too many times, so here a slightly modified one.

Here is the old '5' next to the 'S' 
image

And the new '5' next to the 'S'
image

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel

BTW.

I think the upper case  O and D characters are also very similar

**Comment by f1rmb** [comment]
Hi Roger,

  Okay, I will take a look at this, but tomorrow.

Cheers.
---
Daniel

**Comment by f1rmb** [comment]
Yeah, okay, I took 5 minutes:

image

On the left is the old D, on the right the new one.

**Comment by f1rmb** [comment]
Do you like it ? I could make it part of this PR.

**Comment by rogerclarkmelbourne** [comment]
Thanks. The new "D" is better. Can you include it.

**Comment by f1rmb** [comment]
Yeah, sure.

**Comment by f1rmb** [comment]
done ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks.

**Comment by rogerclarkmelbourne** [comment]
Now I look at the "D" actually on the radio, I think perhaps the old version is better

I will just merge the change for the 5

**Comment by f1rmb** [comment]
Okay 😉

**Comment by rogerclarkmelbourne** [comment]
Sorry.

The new "D" looked OK in the image you posted but things look slightly different on the radio.

**Comment by f1rmb** [comment]
Yeah, no problem Roger, anyway that's was a 5 minutes job, and if the old D
is better on GD's screen, that's the goal.

Cheers.

Le mer. 29 janv. 2020 à 23:03, Roger Clark <notifications@github.com> a
écrit :

**Pull request merged**
