### PR TITLE
Add Scanning to Channel Mode Screen. 

### PR DESCRIPTION
**Pull request by g4eml**
Scanning started by Quick Menu Entry. Set as the default selection so Orange followed by Green will start scanning.

Stopped by PTT or most key presses. (including Orange followed by Red)
Scan Skip for each channel using existing 'Auto Scan' bit in the codeplug. 
Scan Skip setting added to Channel Details Menu.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin

The hold time seems too short, and also I got a reboot when I left it scanning.

**Comment by rogerclarkmelbourne** [comment]
I'll merge anyway

**Comment by g4eml** [comment]
Hi Roger, 

The hold time is 5 seconds which seems about right to me. It is hard coded at the moment but could probably also be taken from the code plug somewhere.  
I did see reboots while testing.  It seemed to be due to changing channel too soon after the Key Event or menu updates. After adding a pause before starting scanning it seemed to fix it.  I don't think that is anything directly to do with my code, I suspect it has uncovered a problem somewhere else that hasn't shown up before.
I suspect the screen updates and the channel changes are clashing somewhere.

No more time to look at it tonight. I will be taking my radio out with me tomorrow to the coast so it will be doing a lot of marine band scanning, a good test. 


73 
Colin.

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

No worries

Thanks for sending the PR before you head off to the coast.

I agree the reboot is probably unrelated.

**Pull request merged**
