### PR TITLE
Remove 2 GCC warnings.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
umm.

Not sure which PR put those lines in again ..

**Comment by f1rmb** [comment]
I don't know either...

**Comment by f1rmb** [comment]
Weird thing, it was already there...

**Comment by rogerclarkmelbourne** [comment]
Perhaps somehow in Colin's PR

**Comment by f1rmb** [comment]
Maybe, I checked the log -p history of the file without finding something noticeable. Anyway... ;-)

**Pull request merged**
