### PR TITLE
Alternative CC detection method. 

### PR DESCRIPTION
**Pull request by g4eml**
Alternative CC detection method when Filter is set to None. 

Uses my simple method but adds a flag ccHold. 
ccHold is set when valid voice packets are received which is a good indicator that the CC is correct. 
ccHold is cleared after 1 second in the DMR Idle state. This prevents inadvertent changes of CC due to the noise at the end of received signals. So if a voice packet is received the CC will not change again until the state machine has dropped back to DMR Idle for one second. That seems to lock onto the CC pretty well. 
ccHold is also set when transmitting to prevent CC change at the end of transmission. 

Seems to work well with both repeaters and simplex. Needs testing with Hotspots.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin
I've loaded it into my radio, but the local DMR repeater network is completely silent this evening. 

Its been a public holiday in parts of Australia today, and the network has been very quiet all day.

I can try checking the simplex detection, but I think I'll need to try the duplex detection tomorrow.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

This seems to work better than the previous versions, including my histogram system.

I can still get it to go wrong if I blip the Tx on the other radio, on simplex, but recovers fine when I re-transmit a longer over.

**Comment by g4eml** [comment]
Roger, 

A quick blip probably doesn’t generate voice packets so the latch doesn’t get set. I have noticed similar on repeater beacons which are long transmissions but don’t contain voice packets. 
Maybe the latch needs to be set on a different trigger with all the logic for valid received data but excluding the voice part.  

Colin. 



On 10 Mar 2020, at 05:04, Roger Clark <notifications@github.com> wrote:

Thanks.

This seems to work better than the previous versions, including my histogram system.

I can still get it to go wrong if I blip the Tx on the other radio, on simplex, but recovers fine when I re-transmit a longer over.

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

I don't think its worth spending any more time on this, as it works well enough for people to detect unknown CC's as long as the station is actually transmitting some audio

I don't think we need to attempt to build the functionality of a high end scanner radio, as the premise of the firmware is just for Amateur Radio use, and this will work well enough to detect the CC of an unknown repeater.

**Pull request merged**
