### PR TITLE
Update menuChannelDetails.c

### PR DESCRIPTION
**Pull request by vk7js**
SK1 on Channel Details screen will repeat current field (as it does in menus and in channel/vfo mode). This is useful when editing the channel name and you wish to hear the entire field.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'm confused about this PR.

Pressing SK1 already re-voices the last change made on the channel, or if you just changed channel, the channel name is voiced.

What does this PR do thats different to the existing functionality which already provides this functionality

**Comment by rogerclarkmelbourne** [comment]
Opps.

Sorry.

I was looking at the wrong screen.

I thought this was the Channel screen, not Channel Details.
Getting up at 7am to do this before starting work was perhaps not the best idea

I'll recompile and re-test.

**Comment by vk7js** [comment]
Hi Roger,

 

In the Menu Channel Details screen, blue+menu, (or chosen from the menu, you can edit the channel name, change the mode from fm to dmr, change the codes etc. If you were editing a name or changing a field and wanted to revoice the whole field, it would previously not do it on sk1. Now it will.

Joe

**Comment by rogerclarkmelbourne** [comment]
Redrawing the whole screen to re-voice the last line is not the correct way to do this.

The system is already implemented elsewhere e.g. the Channel and VFO screens.

I have put the code from the Channel screen into the Channel Details screen

https://github.com/rogerclarkmelbourne/OpenGD77/commit/b8a1914260b2410e5ae61a1af89102c3b64cfc1d

This change needs to be applied to all menu screens, however I have to start my day job now, so can't do this now.

**Pull request closed without merging**
