### PR TITLE
Fix Windows binary (the previous one was the Mono build).

### PR DESCRIPTION
**Pull request by f1rmb**
I think you need to put this new binary into the latest development release.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've merged the PR and also uploaded the exe to the latest Development  Release

https://github.com/rogerclarkmelbourne/OpenGD77/releases/tag/D20200507

**Comment by f1rmb** [comment]
Cool. Thanks Roger.

**Comment by rogerclarkmelbourne** [comment]
I'm not sure why this didnt crash for me. I think perhaps I didn't actually upload the file. 
But I thought I run the exe and downloaded the file.

Or perhaps did the build for Linux overwrite the windows exe and I didn't notice

**Comment by f1rmb** [comment]
I don't know. You rebuilt the previous Windows version after the 'D' fix, maybe using the wrong solution file, but I didn't noticed either as I don't use this version at all.
Strangely, except the current issue report, none of the other users reported the problem :-D

**Pull request merged**
