### PR TITLE
Updated with link to undocumented features and ToDo

### PR DESCRIPTION
**Pull request by jangelor**
* Added some information on work-in-progress and still-to-be-documented features in my Wiki.
* Added link to opengd77 forum for discussion.
* Updated Thierry F1CXG button image.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
There seem to be merge conflicts with the "OpenGD77 User Guide.md" 
I think you need to pull my master back onto your repo and recommit your change

**Comment by jangelor** [comment]
I'll do that.

**Comment by jangelor** [comment]
Roger, the main conflict is basically my removal of the (17 December 2019) line after the title. I expanded on this in the description, to tell people that after this major edit, other new/undocumented features are listed on the Wiki and on the forum.

Do we still need a new pull?

**Comment by rogerclarkmelbourne** [comment]
Github is still indicating that I need to manually merge the change.

So the easiest thing is probably just for me to copy the new line and paste it onto the master version, then I'll close this PR

**Comment by rogerclarkmelbourne** [comment]
I've manually updated the User Guide with this change.

**Comment by jangelor** [comment]
Thank you Roger. I tried doing it another way but couldn't figure out how.

**Pull request closed without merging**
