### PR TITLE
Add Tone Scan and CC Scan to VFO Mode.

### PR DESCRIPTION
**Pull request by g4eml**
Add Tone Scan for FM and CC Scan for DMR to VFO Mode. 
New Entry in Quick Access Menu either 'Tone scan' or 'CC scan' depending on radio mode. 
When selected radio scans all CTCSS tones or all CCs on current frequency. 
If a match is found the scan stops and the channel is updated with the found setting. 
Pressing any button stops the scan.

Two new entries will need adding to Language files. Currently hard coded. 
'Tone scan'  and 'CC scan'

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin

I think I'll move the Tone values into a common file somewhere.  I tend to be using the uiUtilityQSOData files for this of things, and I'll probably end up renaming that file to uiUtilities.c

**Comment by g4eml** [comment]
The tone values are used in channel details as well. It would make sense to move them to a common location. 

Colin. 


On 7 Dec 2019, at 22:41, Roger Clark <notifications@github.com> wrote:

Colin

I think I'll move the Tone values into a common file somewhere. I tend to be using the uiUtilityQSOData files for this of things, and I'll probably end up renaming that file to uiUtilities.c

**Comment by rogerclarkmelbourne** [comment]
Colin

I found the Tone scan didn't work unless the channel rx ctcss was ready set to a value.

I've made some changes, and its working except for one problem which I don't have time to fix, as its taken me quite a while to work out why the tone scan wasn't working.

The problems were
1. When the screen loads it needed to check if it was scanning and if so, to not load the RxCTCSS assigned to the VFO
2. The audio amp needed to be turned off when the scan starts, otherwise the detection code immediately stops, because it uses the status of the audio amp enable as the detection flag.
3. If the scan fails to detects a tone there is no way to stop it.  So I've changed the code to stop when it has scanned all Tones. If someone things the frequency really has a tone, they can scan again,

There is however still 1 bug.

I don't know why, but I can't get the scan to work on the very last tone in the list. The tone is being configured, but its not detected.

I tried changing the code that sets the sampling time, as I saw it reduced for higher frequencies, but that didn't seem to fix it.

I added some debug print statements and checked that the last freq in the list , 2541, was being sent to the hardware and it did appear to be.

However even when I let the scan loop back to the first index, it didn't detect 2541 

But if I set that value in the Channel Details screen, everything seemed to work OK.
 
So at the moment I don't understand why its not working during the tone scan

I'll commit my changes to my master branch, but can you take a look at why 254.1 isn't being detected.

PS. I checked the CC scan and that appears to be working OK.  But interestingly, it did show up a bug in the DMR ID code, because when transmitting on a different CC to the CC I setup for the Rx, it was triggering the QSOData display.
This may be related to the bug where the repeater Ident stuff turns on the backlight, but I think this is potentially a different bug

**Comment by g4eml** [comment]
Hi Roger, 

That’s odd, I had already added code specifically to address the three points you mention. I wonder if the PR was somehow not the final version. Or if you were testing in a different way to me. 

When activating the scan it first turns on the CTCSS decode which turns off the audio. 
The scan is stopped when there is a key event. 

I deliberately left it running continuously so it could be left on a frequency waiting for a signal.  One pass would not be enough for channels with low activity, I think it needs to run until stopped. Pressing any key stopped the scan. 

As for the last tone not decoding, I did see that as well a couple of times but I couldn’t see any reason for it. It didn’t always fail though, occasionally it did seem to work. It is almost as if the decoder doesn’t work properly when incremented from the previous tone. I will take another look as I have just had an idea, I wonder if setting CTCSS to none before setting the required tone might reset something. 

Colin. 



On 8 Dec 2019, at 06:22, Roger Clark <notifications@github.com> wrote:

Colin

I found the Tone scan didn't work unless the channel rx ctcss was ready set to a value.

I've made some changes, and its working except for one problem which I don't have time to fix, as its taken me quite a while to work out why the tone scan wasn't working.

The problems were

When the screen loads it needed to check if it was scanning and if so, to not load the RxCTCSS assigned to the VFO
The audio amp needed to be turned off when the scan starts, otherwise the detection code immediately stops, because it uses the status of the audio amp enable as the detection flag.
If the scan fails to detects a tone there is no way to stop it. So I've changed the code to stop when it has scanned all Tones. If someone things the frequency really has a tone, they can scan again,
There is however still 1 bug.

I don't know why, but I can't get the scan to work on the very last tone in the list. The tone is being configured, but its not detected.

I tried changing the code that sets the sampling time, as I saw it reduced for higher frequencies, but that didn't seem to fix it.

I added some debug print statements and checked that the last freq in the list , 2541, was being sent to the hardware and it did appear to be.

However even when I let the scan loop back to the first index, it didn't detect 2541

But if I set that value in the Channel Details screen, everything seemed to work OK.

So at the moment I don't understand why its not working during the tone scan

I'll commit my changes to my master branch, but can you take a look at why 254.1 isn't being detected.

PS. I checked the CC scan and that appears to be working OK. But interestingly, it did show up a bug in the DMR ID code, because when transmitting on a different CC to the CC I setup for the Rx, it was triggering the QSOData display.
This may be related to the bug where the repeater Ident stuff turns on the backlight, but I think this is potentially a different bug

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

umm.  Did you commit everything before pushing. 

It definitely was not working for me because of the problems I mentioned.

Re: Scanning more than once.

Ah OK. I tried pressing the orange button but it didnt stop the scan, so perhaps that code didnt get into github either.

You could try pulling an merging and then sending another PR.

Re: Not detecting the last tone.

Yes. Its a strange one. It never detected it for me, but if I set the tone in the channel details I could definitely see it filtering.

BTW. I also noticed with strong signals that the detection in the AT1846 is not that good and it was opening the squelch on adjacent tones.

Thanks...

**Comment by g4eml** [comment]
Hi Roger, 

I am pretty sure I committed all,  I think it may be down to differences in the way you and I were testing, on reflection I may not have tested the case where a signal is already present when you start the scan, I can see how that might fail. I was always first starting the scan then keying up the test signal. 
  Not sure why it didn’t stop on pressing a key though, it was definitely working for me. 
I did however have to merge several updates before creating the PR as my fork had got a long way behind yours in the two days I was working on it. I guess that could have messed something up. 

Yes the chip does sometimes seem to decode one tone either side of the correct one especially on strongly signals. That’s not unusual, I have seen it before on other radios. Many manufacturers advise against using adjacent tones.  I am not sure if the official firmware does the same but I suspect it does.  It might be possible to improve it by adjusting the detection threshold but that might need to be individually tuned for each radio. Currently it is calculated using the formula from the 1846 data sheet. I guess the code could possibly be expanded to test several tones and pick the one in the middle. Or maybe run one test incrementing and one decrementing. However the function is still useful because it will get someone close to the correct tone, they may just have to change it by one. 

Colin. 






On 8 Dec 2019, at 10:16, Roger Clark <notifications@github.com> wrote:

Hi Colin

umm. Did you commit everything before pushing.

It definitely was not working for me because of the problems I mentioned.

Re: Scanning more than once.

Ah OK. I tried pressing the orange button but it didnt stop the scan, so perhaps that code didnt get into github either.

You could try pulling an merging and then sending another PR.

Re: Not detecting the last tone.

Yes. Its a strange one. It never detected it for me, but if I set the tone in the channel details I could definitely see it filtering.

BTW. I also noticed with strong signals that the detection in the AT1846 is not that good and it was opening the squelch on adjacent tones.

Thanks...

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

OK.

No worries.

Anyway, the only thing that needs to be fixed is why the last code can't be scanned for ;-)

**Pull request merged**
