### PR TITLE
 Remove beep related settings checkings.

### PR DESCRIPTION
**Pull request by f1rmb**
As STORAGE_MAGIC_NUMBER has been changed few times since then. Was introduced on Sep 7 2019.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Actually, some people only update every 6 months.

But I think that they will have to put up with any problems caused by not updating very often.

**Comment by f1rmb** [comment]
Okay, but to get this new code into their GD, they have to flash it, hence they will get a settings reset (MAGIC was increased again last week or the week before)  ;-)

**Comment by rogerclarkmelbourne** [comment]
Honestly I know people who flashed a version last year and have not updated it yet.

But there are not too many people like this, so I think its better to remove these work-arounds

So I will merge this PR later

**Comment by f1rmb** [comment]
Wow, they are really far behind, they are missing a lot of fixes and improvements.

**Pull request merged**
