### PR TITLE
Access specific tasks with quickkeys (Function+Number)

### PR DESCRIPTION
**Pull request by alexernst**
Access the contacts set in the CPS in dialog 'Number Key Assign' with long pressing number keys.

There is still a bug which results in saving an overrideTG on power off even if it is not needed. But this is related to private call handling and should be handled in one of the private call screen issues.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex

There has been a discussion on the forum about the use of the number keys, and the consensus was that they should be used  with the Function key to access specific menu's or functionality.

I don't know if long press on the keys to access specific contacts would confuse users.

Perhaps Function + Number is still compatible, however I was hoping to re-use the codeplug area used for the number key assignment of contacts to hold the Function key + Number function, by changing the CPS a little

**Comment by alexernst** [comment]
Ok, missed that thread. 
I could change this to use Function+Number and prepare the source for permitting other functions.

For each number key is a 16bit int stored in the codeplug which is representing the contact. 
The CPS stores the contact numbers from 1 to 1024 with 0 meaning not used.

So the function could be coded in the upper 5 bits:
0: call contact stored in lower 11 bits if not 0
1: goto channel stored in lower bits with zone
2: goto menu entry
...

**Comment by rogerclarkmelbourne** [comment]
Hi Alex

I think Angelo and someone else were discussing it, but perhaps it didn't have its own thread.

I think its a small change to your code, to use the Codeplug function which you wrote, and use that as a menu number, rather than a TG or PC number

I looked at the CPS code and I will need to hard code the menu names into the combobox / drop-down menu, (and eventually handle the localisation of those names)

In the longer term we will probably need to support more complex functionality than just accessing specific menu's e.g. perhaps start the scan or change VFO, but initially access just the menus.

**Comment by rogerclarkmelbourne** [comment]
I'll start a new thread on the forum

**Comment by rogerclarkmelbourne** [comment]
I posted to the forum, 

https://www.opengd77.com/viewtopic.php?f=7&t=346

But so far only Angelo replied and he was one of the people who requested number keys to access the menus

I don't think it will be difficult to implement this in the CPS.

So perhaps its best to code it like you have described, but initially I will just implement the CPS so that it only supports access to the menus

I think it may be complicated to implement the option to have each button either as a Menu or as a TG, as it would require another column in the DataGridView to store the key function type e.g. Menu or Contact 

I don't think we need single key access to specific channels in the zone as this is already implemented using the Goto feature, where the number + green is entered.

I think it may start to get confusing for a lot of operators, if we make this too complicated.

**Comment by alexernst** [comment]
At least the function to read the values from codeplug is usable.
I will change this PR to use Function+Number to access menus.

**Comment by rogerclarkmelbourne** [comment]
Yes.

The codeplug API is great.

I will need to update the CPS to support the firmware functionality.
But you could test by just assigning some contacts to some numbers

Perhaps offset the number so that Contact index 1 = MENU_CONTACTS_MENU
then 2 = MENU_ZONE_LIST 3= MENU_BATTERY etc

We may need to re-organise the menus because of Hotspot mode and CPS, but this would also require changes to the localisation files.

Perhaps we should wait for more feedback from the forum.

**Comment by alexernst** [comment]
The meaning of <code>menuId</code> depends on the CPS I think. 
But there are some menus that require special handling like MENU_CONTACT_DETAILS, as the actual contact needs to be loaded. 

So, leave this PR open or merge it and comment out handleQuickKey() until we need it.

**Comment by rogerclarkmelbourne** [comment]
Ok.

I think perhaps we need something more complicated than just accessing the menus. E.g. Probably the ability to start scanning, or enable and disable the TS filter etc.

But this is much more complicated to implement

**Comment by alexernst** [comment]
Perhaps we should add something like a 'function event' comparable to the key and button events.
That would allow to map the keys to the functions and handle it in the handleEvent() functions.

**Comment by rogerclarkmelbourne** [comment]
Function Even is a good idea.

The official firmware has a system as something similar,where combinations of key presses are converted into a single key code.
But they only use this for the multi key input like Blue + Green + Star etc

**Comment by alexernst** [comment]
I will add an extra event to the uiEvent_t for this and prepare the code to handle this.

**Comment by rogerclarkmelbourne** [comment]
Alex.

I'll close this as it now has merge conflicts with your other PR to fix the TG 0 issue.

**Pull request closed without merging**
