### PR TITLE
Update from DG3GSP.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by f1rmb** [comment]
I told him that could still change.

**Comment by rogerclarkmelbourne** [comment]
OK

Its surprisingly complicated, and we are not tested in real world situations.. (I'm not...)

I suppose people would normally use this when operating mobile or portable or perhaps on their bicycle. All of which could have high background / wind noise etc

**Comment by f1rmb** [comment]
I never used vox, before writing this piece of code. I always found this not that great, as you can start xmitting just because you talk to other people next to you (errr, like yelling at the kids sat on the backseat, etc ;-) ).

**Comment by f1rmb** [comment]
I think the PTT latch is way better.

**Comment by f1rmb** [comment]
BTW, I tried the vox on the DM-1801: its noise background is quite high. But I wasn't able to really test it this morning, as one of my kids was sleeping in the next room.

**Comment by rogerclarkmelbourne** [comment]
Yep. Its not that useful, but as there is dedicated hardware for it, it seems logical to attempt to support it

**Comment by f1rmb** [comment]
Yes, sure.

**Pull request merged**
