### PR TITLE
Update spanish.h

### PR DESCRIPTION
**Pull request by EA5SW**
New PR with the text file

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK

It looks OK now.

I will double check and then merge

**Comment by rogerclarkmelbourne** [comment]
Umm

Encoding is UTF8

Does Spanish use any accented characters?

The file needs to be set to ANSI aka windows-1252-unix encoding

**Comment by EA5SW** [comment]
All files are saved as ANSI, appears that Github change to UTF8

**Comment by EA5SW** [comment]
I rewrite all with notepad++ to see what appears..

**Comment by rogerclarkmelbourne** [comment]
OK

Thanks

**Comment by EA5SW** [comment]
The catalan.h and spanish.h are now saved and verified with notepad++ that are ANSi, I hope that works now.

**Comment by rogerclarkmelbourne** [comment]
OK.

I will check..

Thanks

**Comment by rogerclarkmelbourne** [comment]
Sorry.  For me Catalan is ANSI in NotePad++ but Spanish is UTF8.

I'll convert in NotePad++ then merge but you will need to check its then OK

**Comment by rogerclarkmelbourne** [comment]
umm

Actually I think its some problem of the files not being detected correctly

I'll merge. now

**Comment by rogerclarkmelbourne** [comment]
Some texts are actually too long, but the firmware should just cut off any texts that won't fit.

e.g. Volumen BEEP:  will not fit if the number is negative e.g. -12dB and just shows -12, but I guess this is OK.

**Comment by EA5SW** [comment]
Now that works, I add accents and revise all again.
Thanks.

**Pull request merged**
