### PR TITLE
GD77S: Invert SK1/SK2 long/short press events.

### PR DESCRIPTION
**Pull request by f1rmb**
Adds DMR TS_TG and TS DMR filters support (LEVEL MODE {ON,OFF}).
Adds scan mode (SK1: start/stop, SK2: nuisance/reverse scan direction).

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks Daniel

It works well..

I wonder if we should change the settings magic number to force the new DMR filter default.

But I guess virtually no one has installed this on the GD-77S at the moment, and those people could increase their filter level.

**Comment by f1rmb** [comment]
Hi Roger,
  Yes, of course. I didn't changed it because I tought it my change for another new setting in the next days, but if there is a release plan, of course it needs to be increased.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK. 

I will increase the value, and then post to the web and ask for testers of this version.

But I think very few people use the GD-77S

**Comment by f1rmb** [comment]
Okay.
Yeah, most probably few people are using it, yet 😉

**Pull request merged**
