### PR TITLE
User Guide Chinese translation

### PR DESCRIPTION
**Pull request by michae1eo**
This is michael callsign BH4ESK. The OpenGD77 is really good. I used it a lot, and my friends also love the opengd77 firmware after I introduced to them. But some is confused by the manu system (which is a pretty big problem considering most of them dosen't read english) and couldn't utilize all the features. So I took some time to translate the User Guide. And also redo the quick start diagram so it's much easier for chinese users to understand.
One of my friend BG5IPF taught me how to use github and also proofreads the guide. I hope i can contribute to this project. 

btw. is it possible to also add a chinese manu system? i guess the font is a problem?

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

There are a few problems.

You seem to have added a blank line to the English readme.md file

Also, ideally this PR would not be 19 separate commits.
I think there is a "squash" merge method, to make this into 1 commit, but I would need to research how to do this.

Is it possible for you to replace the Readme.md with a version which has no changes and also make this PR just a single commit.

If you can't do that, I may have to manually commit this directly to the development branch, as if I made the changes.

Re: Chinese language version

Yes. The font is the problem. Its European languages only, and is a custom font.
There would not be space in the MCU ROM for both European and Chinese language font characters, so you would need to make a font, and also have a completely separate build of the firmware.

**Comment by f1rmb** [comment]
git rebase -i <sha1>

**Comment by f1rmb** [comment]
And for you Roger:

git merge --squash

*Untested.

**Comment by michae1eo** [comment]
Should I just fork a new one and commit all of the docs, then open a PR again? I'm not familiar with coding or something, i can consult my friend about this, it may take some time.

**Comment by f1rmb** [comment]
If you're not comfortable with git/github, yeah, that would be easier for you. Also, in this case, create a branch based on development one, it will keep your repository clean.

**Pull request closed without merging**
