### PR TITLE
speak Squelch changes

### PR DESCRIPTION
**Pull request by vk7js**
SIn Channel and VFO mode, left and right arrow will announce squelch changes at voice prompt level 3 in FM mode.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I just tried this, but it only announces the percentage and not what the percentage is of.
Then later if you press the Black button, it just re-announces the percentage.

The word "squelch" should be in the available vocabulary, so wouldn't it be better to announce that e.g. "Squelch 55%"

With power, it does not announce that the value is the power, but it announces the unit as "Watts" hence its obvious its power.

I guess perhaps it can be inferred, from the fact that "percent" is announced after the value, but there are the Watts values are unique to power whereas percentage is used on display brightness as well as squelch.

**Comment by cjeffcoat2** [comment]
Perhaps it should say squelch on the first press and then if it is interrupted by a second press it should just announce percentages like the other functions do. Thank you All for your development on this project.

**Comment by vk7js** [comment]
Hi Roger,

 

I looked through the voice prompts and while there is a language string for squelch, it is not an actual spoken word which means it would be spelled out, very very verbose and unnecessary. Since you know that left and right arrow change the squelch, the percentage is sufficient unless someone can add the word squelch to the voice prompts, probably not really worth it. Then, you’d only want to hear it after the percentage and since the percentage infers that anyway, there’s no need. You’d not want to hear squelch on every arrow prior to the number, it would be hugely annoying. Most blind people who read the manual would know what the function did, they’d just want to hear the changed value.

Joe

**Comment by rogerclarkmelbourne** [comment]
Joe

Why did you conclude that the word "squelch" was on in the voice prompts

The function which handles this is

`void voicePromptsAppendLanguageString(const char * const *languageStringAdd)`

and its used in many places throughout the code.

e.g.


`voicePromptsAppendLanguageString(&currentLanguage->battery);`

Any language string defined here

https://github.com/rogerclarkmelbourne/OpenGD77/blob/development/firmware/include/user_interface/uiLocalisation.h

Can be used.


This github repo contains all the wordlists, for all supported languages, and the scripts etc to generate the voice prompt file

https://github.com/LibreDMR/voice-prompts

However, you should use the 

https://github.com/rogerclarkmelbourne/OpenGD77/blob/development/firmware/include/user_interface/uiLocalisation.h

header as your reference for which words are available.

**Comment by vk7js** [comment]
Roger,

 

If you look through the actual voice prompt constants, there is no prompt for squelch, only a language string in the regular language string table. If I add that it would be spelled out, which I suppose is better than nothing, but, very verbose.

Joe

**Comment by f1rmb** [comment]
Joe,

   No, the word "squelch" is available in the voice prompts.


Cheers
...
Daniel

**Comment by vk7js** [comment]
Where is it in voicePrompts.h?

Joe

**Comment by f1rmb** [comment]
See voicePromptsAppendLanguageString()

**Comment by vk7js** [comment]
Daniel, append language string does not speak the whole word, it spells out the string from the resource table. That is what I am trying to tell Roger.

There is no voice prompt for squelch. There is only a localized string. If you use appendLanguageString, the string merely gets spelled out, not spoken as a whole word. That is too verbose to hear s q u e l c h 45%, s q u e l c h 50 % etc.

Whereas voice prompts for which there are actual constants in the voicePrompts.h file are actual words in the voice prompt file spoken as entire words. There is no squelch in that table.

Joe

**Comment by f1rmb** [comment]
That starts to be ... boring, Joe.

Do you want a proof? Go in display options, then select "Mode" entry. (LEFT/RIGHT arrows): between "Auto"  and "Manual" you *have* the "squelch" word.

Using the function I gave you (voicePromptsAppendLanguageString), and passing currentLanguage->squelch pointer will announce "squelch".
As the function name explicitly says, it Append,.
So you can Append whatever (string, number, spelled char, etc) before or after, and trigger voicePromptsPlay() at the end.

**Comment by vk7js** [comment]
Dear Daniel,

 

Thanks for this, so what you are saying is that the prompt constants in voicePrompts.h are not what are used. Rather, you are using the language string table as some kind of lookup. It is not in voicePrompts.h. Is that file not used? Or is it one of the tbd constants?

If you do something like appendstring(currentLanguage->none) it spells out the word none. So, that is what I thought you meant to do.

I’ll go do further research on your suggestion.

The confusion came from both the appendString(str) spelling out the language string, and the fact that the voicePrompts.h file seems to be out of date.

Joe

**Comment by vk7js** [comment]
Dear Daniel and Roger,

 

Thanks for your patience with this. I think I have it working as desired now.

I prepend the word squelch if a voice prompt is not already playing, otherwise I just say the percentage. This allows the word squelch to be spoken on first press, then multiple quick presses will just announce the percentage. 

Thanks again.

The voicePrompts.h file really confused me when I couldn’t find the entry for squelch, and then the appendString vs ApendLanguageString, were also confusing because one spells a resource string and the other uses a resource string as an index into a voice prompt table.

Joe

**Comment by vk7js** [comment]
Dear Daniel and Roger,

Thanks for your patience with this. I think I have it working as desired now.
I prepend the word squelch if a voice prompt is not already playing, otherwise I just say the percentage. This allows the word squelch to be spoken on first press, then multiple quick presses will just announce the percentage. 
Thanks again.
The voicePrompts.h file really confused me when I couldn’t find the entry for squelch, and then the appendString vs ApendLanguageString, were also confusing because one spells a resource string and the other uses a resource string as an index into a voice prompt table.
Joe

**Comment by rogerclarkmelbourne** [comment]
This PR has now been superseded by other changes and is no longer needed

**Pull request closed without merging**
