### PR TITLE
Set BW to 25kHz for CWID.

### PR DESCRIPTION
**Pull request by f1rmb**
Seems to be necessary for the DM-1801, as KD2LH reported.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Ok...

It’s strange that the modulation is lower on the DM1801, as they hardware is identical.

**Comment by f1rmb** [comment]
I need to check this, maybe it was listening with FM @ 25kHz.
Don't merge it yet

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
Ok.

Yes. I think listening should be narrow FM.

I presume that bandwidth is set to narrow to improve noise immunity, but it may not make much difference except on marginal signals

**Comment by rogerclarkmelbourne** [comment]
I think perhaps the bug report was erroneous, and that we dont need to change the deviation to 25kHz

**Comment by f1rmb** [comment]
Lets close it.

**Pull request closed without merging**
