### PR TITLE
Re-introduce new HS ID.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'm still waiting for Andy (PiStar) to accept the PR to add the new search string.

There is no point merging this PR until PiStar can be updated

**Comment by f1rmb** [comment]
Yes, I know this. I'm just maintaining it to make it merge without conflicts ;-)

**Comment by rogerclarkmelbourne** [comment]
I just checked and the PR for PiStar still has not been merged :-(

https://github.com/AndyTaylorTweet/Pi-Star_DV_Dash/pull/94

**Comment by f1rmb** [comment]
Yeah, I check everyday and no sign of life...

**Comment by rogerclarkmelbourne** [comment]
Umm.

Thats no good :-(

I wonder if Andy no longer has time to maintain the repo, in which case he should assign some collaborators

**Comment by f1rmb** [comment]
Yeah, even the TG4000 bug isn't fixed there. A guy reported he found my repo with the bugfix, but he get no reaction at all. Weird...

**Comment by rogerclarkmelbourne** [comment]
I had to manually update uiHotspot.c because too much had change since the PR was submitted.

See https://github.com/rogerclarkmelbourne/OpenGD77/commit/0caae9d6d1f4fe0450054f864df0b7c80c1bf7ed

**Pull request closed without merging**
