### PR TITLE
Access contacts in DMR mode for PC or TG entry

### PR DESCRIPTION
**Pull request by alexernst**
In DMR mode added entry 'Contact' to key HASH.
Select one contact stored in codeplug with LEFT or RIGHT and use it as PC or TG override.

The TG contacts are included as not all TG's need to be in the RX-list used for the active channel.
 
Perhaps we should add an alias for TG override. So the name of the contact instead of the ID is shown in uiVFOMode and uiChannelMode.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I think up and down arrows are better to select the contact.

I will change this

**Comment by rogerclarkmelbourne** [comment]
I think we probably also need to rename this file as its function has changed.

Any ideas of what to name it ?

**Comment by alexernst** [comment]
I used left/right as it's the same switching TG's, but up/down is also ok. Then it's the same as switching zones.

Filename: 
uiTXContact, but does not really honor talkgroups.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I renamed the file with a slightly different name to try to describe what the file contains, I also changed Right/ Left for Up/Down and also added enums for the various functions this screen now performs.

I tested all functions and it still seems to be working OK

**Comment by rogerclarkmelbourne** [comment]
I had some more thoughts...

We probably need some indication of whether the Contact is a TG or PC
Or...

Perhaps use 
# =TG enter , ## = PC entry
Function + # = TG contacts , Function + ## = PC contacts

I'm not sure how we keep the DMR ID entry, perhaps at the end of either of these sequences.
Or move it to some other screen.

**Comment by rogerclarkmelbourne** [comment]
@alexernst 

FYI. 

I posted the updated version to the forum.

Hopefully I will get some feedback about perhaps changing the access of the Contacts to Function + \#

But I'm really tired now, as its taken ages to administer the forum, so I don't have the energy to try implementing those idea

**Pull request merged**
