### PR TITLE
Update with latest button map from F1CXG

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I will merge later

**Comment by rogerclarkmelbourne** [comment]
Thanks

BTW. I"ve also manually updated the master branch with those 2 files, because most people will be looking at the User guide in the master branch.

**Comment by f1rmb** [comment]
Okay. This might conflict on the next merge ;-)

**Comment by rogerclarkmelbourne** [comment]
Yes. I'll need to check next time to ensure there is not a merge conflict

**Pull request merged**
