### PR TITLE
Add hardcoded 'Order' into translation. Update some French translations.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks. We may need to so something for the order types, but that will be more difficult, unless perhaps we do something like treat a long string as 4 smaller, fixed length substrings.

**Comment by f1rmb** [comment]
Okay. What do you have in mind ?

**Comment by rogerclarkmelbourne** [comment]
The sort of thing I do on more powerful platforms, use a delimiter in the string and then split on the delimiter into an array  e.g. I commonly use  the "|" character as a delimiter, as it doesn't seem to be use in normal texts.

That may be one way of doing it.

Its not as fast as just perhaps doing a union, but is probably easier to read.

**Comment by f1rmb** [comment]
Hi Roger,

   Okay. But for what purpose, instead of using the array char char for "Ct/DB/TA" etc, and rather building the string on the fly ?

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Yes. 
Thats a good idea. And store each element as a separate language item, rather than combining them into a string

**Pull request merged**
