### PR TITLE
Avoid updateScreen()s when not needed.

### PR DESCRIPTION
**Pull request by f1rmb**
Triggering light at the beginning of the event handler is way better than in the end (sometimes not reached).
setting.h: surround macro with do {} while(0).
Give some fresh air to menuChannelDetails: spaceless code won't run faster, but make it hard to read sometimes ;-)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

What is the reason for 

`do { settingsSaveSettings(includeVFOs); } while(0)
`

**Comment by f1rmb** [comment]
Hi Roger,

It's to avoid problem, like such:

```
if (x)
{
    foo();
    bar();
}
else
    SETTINGS_PLATFORM_SPECIFIC_SAVE_SETTINGS(true)

```

I know it's not the rule to use braceless blocks, but it's always good to have single/multiline macros within do {} while(0) block, just to be on the safe side.

**Comment by f1rmb** [comment]
BTW, just noticed I forgot so save the file for the non RD-5R case. Next time...

**Comment by rogerclarkmelbourne** [comment]
OK.
Its a good idea about the braces, but I suspect you can just have 

{ }

As this is valid C code

**Comment by f1rmb** [comment]
In a syntax point of view, yeah, but there are case where it will fail:
[](https://stackoverflow.com/questions/1067226/c-multi-line-macro-do-while0-vs-scope-block/1067238#1067238)

**Comment by rogerclarkmelbourne** [comment]
OK.

Its not a big problem, but I'm happy include the fix.

**Comment by f1rmb** [comment]
Okay ;-)

As the post explains

```
  if(x)
     THE_MACRO();
  else
  {
      bar();
  }

```

 will fail to compile with '{ ... }' only, as the ';' at the end of the macro will terminate the if() block condition statement.

**Pull request merged**
