### PR TITLE
Create new channel from VFO

### PR DESCRIPTION
**Pull request by rogerclarkmelbourne**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
This will need to be added to the languages file because "NEW CHAN" is not a generic term like "VFO" or "Rx"

`strcpy(buf, "VFO --> NEW CHAN");`

**Comment by ea3ihi** [comment]
What about the name "New chan NN" assigned to newly created channel, do we also add a text entry for that?

**Comment by ea3ihi** [comment]
I have added two new labels:

const char new_channel[LANGUAGE_TEXTS_LENGTH];// 14
const char vfoToNewChannel[LANGUAGE_TEXTS_LENGTH];// "VFO --> New Chan",

**Comment by rogerclarkmelbourne** [comment]
Have you finished testing.

Is this ready to merge now ?

**Comment by ea3ihi** [comment]
It needs a little more testing as I only use one tg list in my current codeplug

**Comment by rogerclarkmelbourne** [comment]
OK.

No worries.

**Comment by ea3ihi** [comment]
I have been testing and it works pretty well. I am not checking if the selected mode is digital, and doing some actions as copying the contact index that might not have sense for analog, but won't do any harm. I needed we can check if we are in digital mode.

`//copy current channel from vfo to channel
					nonVolatileSettings.currentIndexInTRxGroupList[0] = nonVolatileSettings.currentIndexInTRxGroupList[SETTINGS_VFO_A_MODE + nonVolatileSettings.currentVFONumber];

					//copy current TS
					nonVolatileSettings.tsManualOverride &= 0xF0;// Clear lower nibble value
					nonVolatileSettings.tsManualOverride |= (trxGetDMRTimeSlot()+1);// Store manual TS override`

**Comment by ea3ihi** [comment]
I have pulled your master branch as 2020-02-09 and created a build that I will publish for people to test the new channel feature

**Pull request merged**
