### PR TITLE
Fix hundreds spelling.

### PR DESCRIPTION
**Pull request by f1rmb**
Hi Roger,

Okay, I fixed my mistake.

Also, maybe you didn't noticed but I shorted the corners about spelling things like this:
439.9875

It will be spelled:
four hundred thirty nine point nine hundred eighty seven FIVE

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

 

I think this may not be correct.

 

I’m not sure in French, but in English the digits to the right of the decimal point need to be announced as separate digits.

 

I know some people say it like you have programmed it, but I think for scientific speech it needs to be  “point nine eight seven five”

 

Anyway, let me try it, but I think it not correct for scientific numbers when written or spoken

 

 

How would you write this in French

 

Quatre cent trente-neuf virgule neuf mille huit cent soixante-quinze ?

 

 

Thanks

 

Roger

**Comment by f1rmb** [comment]
Hi Roger,

   Yes, in french it will spelled like this.
But the change is trivial in the code to spell each digits (there is a enumerate boolean argument to the functions.
I can change that quickly.

Cheers.

**Comment by f1rmb** [comment]
In fact, you could also spell it

nighty eight hundred seventy five (IIRC, english use that trick too).

**Comment by f1rmb** [comment]
Anyway, I will change the frequency spelling code to enumerate from hundreds of kHz. Are you okay ?

**Comment by rogerclarkmelbourne** [comment]
Let me test this code first

**Comment by rogerclarkmelbourne** [comment]
Daniel

I think if we just use your function but set the last argument to try. Probably for the digits to the left of the decimal point and also to the right

```

			// First part
			pBuf += speechSynthesisBuildFromNumberInString(pBuf, destSize, buffer, true);

			// Insert the point
			*pBuf++ = SPEECH_SYNTHESIS_POINT;

			// Second part
			pBuf += speechSynthesisBuildFromNumberInString(pBuf, (destSize - (pBuf - dest)), point, true);

```

**Comment by f1rmb** [comment]
You want frequency to be enumerated on both side of the decimal ?

**Comment by f1rmb** [comment]
Here it is ;-)

**Comment by rogerclarkmelbourne** [comment]
Personally I prefer

439.9875

Four Three Nine Point Nine Eight Seven Five

This is the same format as used in aviation, and marine (shipping) and military etc.

**Comment by f1rmb** [comment]
Okay. I have no preference, just to make people happy :-D

**Comment by f1rmb** [comment]
Anyway, it's easier for people having problem with english, at least they understand numbers from 0 to 9.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

**Comment by rogerclarkmelbourne** [comment]
I changed it to say each digit separately.

I think this is best.

Thankyou

**Pull request merged**
