### PR TITLE
Change output filenames. Add code to download sgl using libcurl.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I also changed the source file

Its now

https://github.com/rogerclarkmelbourne/Radioddity_GD-77/raw/master/Generic_devices/generic_dmr_codec.bin

**Comment by rogerclarkmelbourne** [comment]
We should probably moved the Linux director into the tools director, and also move the existing files into the tools directory into a windows subdirectory

**Comment by f1rmb** [comment]
Hi Roger,

   Updated.
About Windows subdir, why ?  If it's about firmware_loader, it works under Windows and Linux (requires projects compilation).

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
I also moved the font_tools into tools subdir.

**Comment by rogerclarkmelbourne** [comment]
OK.

Forget the windows folder. I though perhaps there was a Visual C# project in the tools folder.

**Comment by f1rmb** [comment]
There is, the FirmwareLoader, but it's not Windows specific anymore.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by f1rmb** [comment]
Hi Roger,

   Anything wrong with this PR ?

Cheers.

**Comment by rogerclarkmelbourne** [comment]
No

I just have not had time to process it yet.

**Comment by f1rmb** [comment]
Okay ;-)

**Pull request merged**
