### PR TITLE
Slowdown handle event calls

### PR DESCRIPTION
**Pull request by f1rmb**
This PR contains also the DTMF alpha remap. It you don't want it, I can push a revert.

Cheers.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hold on, that introduce a bug with ORANGE key.

**Comment by f1rmb** [comment]
That's working as expected now :-)

**Comment by rogerclarkmelbourne** [comment]
umm

I'm not sure why, but I'm getting a merge conflict with the Spanish,h from the PR I just merged

**Comment by f1rmb** [comment]
Hi Roger, humm probably because there is also a small change in this PR too. I'll fix it.

**Comment by f1rmb** [comment]
Fixed.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I just got home, So I will test the PR later

**Comment by f1rmb** [comment]
Humm, problem with key repeat. doh!

**Comment by f1rmb** [comment]
Fixed ;-)

**Comment by f1rmb** [comment]
Hummm, the orange key release workaround is bad, keeping pressing that button trigger a reboot.

**Comment by rogerclarkmelbourne** [comment]
OK

I will wait.

No hurry...

**Comment by f1rmb** [comment]
Voilà, finally ;-)

**Comment by rogerclarkmelbourne** [comment]
I made one change, and replaced your ##defines or the event types into a typedef'ed enum.

As far as I can tell, I didn't break anything

**Comment by f1rmb** [comment]
Okay, I'll see that in a moment.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
You don't need to change anything. I changed the defines to a typedef enum

You can pull and test if you like.  But it works OK for me

**Comment by f1rmb** [comment]
I didn't meant to change anything, just the changes you've made ;-)

**Comment by rogerclarkmelbourne** [comment]
OK. You can just pull the latest version

**Comment by f1rmb** [comment]
Okay, ok master ? (I don't see anything here yet, or maybe I'm missing something).

**Comment by rogerclarkmelbourne** [comment]
Thats strange

I have pushed twice

Let me double check

**Comment by rogerclarkmelbourne** [comment]
Ah OK
My bad.

I merged the user guide changes on github and I thought I had pulled that to my local, but I had not done that .

I didn't noticed the pushes were failing

**Comment by f1rmb** [comment]
Ah, I seen the merge notification. Thanks Roger

Le mar. 10 déc. 2019 à 22:23, Roger Clark <notifications@github.com> a
écrit :

**Pull request merged**
