### PR TITLE
update old images to new UI

### PR DESCRIPTION
**Pull request by Neon22**
Also add a "NOT" in opening md file to correct typo.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'll try to get around to pulling and merging this later today.

**Comment by rogerclarkmelbourne** [comment]
Better late than never.....

**Comment by rogerclarkmelbourne** [comment]
@Neon22 

Can you take a look at this PR for the CPS

https://github.com/rogerclarkmelbourne/OpenGD77CPS/pull/24

IMO we just need some graphics which shows the which buttons to push on each different type of radios, so that the radio enters bootloader / upload mode, rather than the whole animated gif that has been proposed, as it only shows the GD-77

**Comment by Neon22** [comment]
I see the problem.
I added the "Transferring data" section in installation to the docs in last PR. Because its not in Master I think most people don't see it when they look at the website.

That section might be a good place to put the image you're asking for if you don't think the current text is clear enough ?
The image would illustrate the text basically. Agree ?

**Comment by rogerclarkmelbourne** [comment]
I think what the CPS needs is just the graphics of the radios from the User Guide, but stripped of everything except some arrow pointing to the buttons.  

I'll take a look in the User Guide to see if there is any way I can hack those graphics to make some new graphics which show people which buttons to press.

I think the whole video to animated gif thing is overkill

**Comment by Neon22** [comment]
PTT etc layout-01
Backup-02
Backup-01
Firmware_loader-01
Firmware_loader-02
Firmware_loader-03

**Comment by Neon22** [comment]
The images are well named.
The radios image goes with maybe some modified text in Installation/Transferring data.

The others show  the sequence involved to backup or to replace firmware.
Do you want to take it from here ? or...

**Comment by Neon22** [comment]
OK. made a branch on dev. sent you a PR.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by Neon22** [comment]
dude - if you're willing to put so much time into this - I really appreciate it - and so if there's anything I can do to help - you just let me know and I'll put the time in.
Cheers...

**Pull request merged**
