### PR TITLE
Fix CSharp flasher: GD-77 have to be the default, in command line mode.

### PR DESCRIPTION
**Pull request by f1rmb**
Disable model probing in Python.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

Sorry. I didn't check the command line...

**Comment by rogerclarkmelbourne** [comment]
I think perhaps the user should be forced to specify the model of the radio if they have specified a file name

e.g.

Running FirmwareLoader.exe with no args or with GUI will run the GUI version.
However if they specify a filename but nothing else e.g.

FirmwareLoadeder.exe OpenGD77.sgl

The command line should print a message listing the radio types and saying that the user must the model of the radio

This would make the PC exe consistent with the Python version

BTW. 
I've changed the post build steps in the .cproject, because the application name was wrong (because I renamed it last week) and the post build step now passes the mode of the radio but doesn't pass the GUI argument.

**Comment by rogerclarkmelbourne** [comment]
FYI.
The firmware loader is not working when its called from the post build step my MCUExpresso.

I know this was working last year, when I first added this step, but its now giving a File.IO error in 

sendFileData()

But the line in the code which breaks is 

int cursorLPos = Console.CursorLeft;

Which does not help to debug this.

I tried changing to using the sgl file instead of the bin, but that was not the problem.
I tried enabling the GUI e.g.

FirmwareLoader GUI GD-77 OpenGD77.sgl

But I still get the same error.


If I run the identical command from the command line from inside the Debug_GD77 folder it works fine.

Perhaps something has changed with MCUExpresso in V11.

Anyway. I think if no one actually uses this post-build step, we should just remove it, rather than leave it commented out.

**Comment by f1rmb** [comment]
Hi Roger,

   Okay. I will check that. I'm flashing all the transceiver using the flasher in command line, using command line version. The cursor position was disabled for non "Linux" version. Maybe something got broken lately.
About the mandatory model argument, yeah, it's possible. I will have to modify the .cproject and the FirwmwareLoader shell script accordingly.

Cheers.

**Comment by f1rmb** [comment]
About the disabled post build strep, you mean the one that flash the firmware after each build ?

**Comment by rogerclarkmelbourne** [comment]
Yes. In the .cproject there are several post-build steps after the build is complete e.g. running bin2sgl to make the sgl file and also to copy the sgl file to the correct name for the target.
In those steps there is also a commented out call to run the firmware loader, but I doubt anyone uses it, because they probably don't want to upload every time the build succeeds, because mostly I build the code just to check there are no compile problems.

**Comment by f1rmb** [comment]
About the Cursor pos, I see, it might be surrounded witth #if (LINUX_BUILD) #endif. I forgot that when I noticed it doesn't work under Windows.

**Comment by f1rmb** [comment]
> Yes. In the .cproject there are several post-build steps after the build is complete e.g. running bin2sgl to make the sgl file and also to copy the sgl file to the correct name for the target.
> In those steps there is also a commented out call to run the firmware loader, but I doubt anyone uses it, because they probably don't want to upload every time the build succeeds, because mostly I build the code just to check there are no compile problems.

Yes, by example, myself ;-)
I prefer to use external tool feature for this (unfortunately, it seems not possible to have external tool configuration part of the project file).

**Comment by f1rmb** [comment]
About the failure of the flash from the post build step, I will also take a look.

**Comment by rogerclarkmelbourne** [comment]
OK.
I don't think its important.  Probably no one uses it. We should just remove it from the .cproject

**Pull request merged**
