### PR TITLE
Csharp loader model probing and firmware checking

### PR DESCRIPTION
**Pull request by f1rmb**
Add HT model detection (+ a button in the GUI to re-detect). Check if the SGL matches the HT model.
Some GUI fixes under linux (label update in the flash progress window).

Tested under Linux and Windows.

image

Now, we can rid of the DM-1801 flasher.

Cheers.

### CODE REVIEW

**Comment by f1rmb** [comment]
Now I need to port this to the CPS's flasher.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

Tested on Windows with both the GD-77 and DM-1801

BTW. I had a problem merging back into local master because the exe was still running.

But I think the merge is OK now.
However you better pull and retest the windows exe yourself.

**Comment by f1rmb** [comment]
Hi Roger,

   Okay. Just md5summed the bin, and it's fine.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
Thankyou.

**Pull request merged**
