### PR TITLE
Enable/fix frequency step 6.25kHz

### PR DESCRIPTION
**Pull request by alexernst**
Adds one digit to all frequency values and fixes step 6.5 to 6.25 kHz. #54

While loading the codeplug all frequencies had been divided by 10. This has been removed to enable a step value of 6.25 kHz.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks I will test and merge

**Comment by rogerclarkmelbourne** [comment]
FYI.
VFO freq does not render correctly.

The decimal point is in the wrong location.

I will fix this. 

Don't update the PR

**Comment by rogerclarkmelbourne** [comment]
Actually,

I don't think its the VFO display.

Perhaps the non-volatile settings need to be reset

**Comment by rogerclarkmelbourne** [comment]
Yes.

We'll need to force a reload of the VFO by changing the magic number in the settings.

I'll change it

**Comment by alexernst** [comment]
Interesting. Does always work here. Whatever.

**Comment by rogerclarkmelbourne** [comment]
There are also some other places the freq is displayed.

I'm updating them now.

**Comment by rogerclarkmelbourne** [comment]
OK.

All fixed now.. I hope ;-)

**Pull request merged**
