### PR TITLE
Add Comments for Calibration Values. 

### PR DESCRIPTION
**Pull request by g4eml**
No Code Changes, Just added comments.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks
On 13 Dec. 2019 08:26, g4eml <notifications@github.com> wrote:No Code Changes, Just added comments.



You can view, comment on, or merge this pull request online at:
  https://github.com/rogerclarkmelbourne/OpenGD77/pull/229

Commit Summary
Merge pull request #12 from rogerclarkmelbourne/masterMerge pull request #13 from rogerclarkmelbourne/masterAdd comments for calibration values.

File Changes

    M
    firmware/source/functions/fw_calibration.c
    (86)
  

Patch Links:
https://github.com/rogerclarkmelbourne/OpenGD77/pull/229.patchhttps://github.com/rogerclarkmelbourne/OpenGD77/pull/229.diff

**Comment by rogerclarkmelbourne** [comment]
Colin

I think with RSSI meter range , one byte is the low end of the scale, but the other byte is probably the range of values rather than being the upper end of the scale

Because the values I have in my radio are 32 and 39 on VHF and 28 and 32 on UHF

And the observed output from the AT1846 for RSSI is roughly 30 to 70 

Of course we don't know what the lower and upper end of the scales represent e.g. is the lower end the noise threshold when connected to a dummy load, and what does the upper end represent  e.g. S9 +60db  etc ?

**Comment by g4eml** [comment]
Roger, 

From memory the original S meter display on the stock firmware was either nothing or full scale. There was very little range between them. I seem to remember changing the values to get a better range. My radio is set for 1C to 60. So I think the values are really the low end and high end RSSI values. 

I don’t think you are actually using them anyway in your current code. I don’t think hey are used to set any chip registers, just for software scaling of the S meter display. 

If we had the original test specification for the radio it would probably have set two defined RF levels to calibrate the two points. But as it worked so badly I wonder if they skipped that part of the calibration. 

Colin. 





On 13 Dec 2019, at 02:41, Roger Clark <notifications@github.com> wrote:

Colin

I think with RSSI meter range , one byte is the low end of the scale, but the other byte is probably the range of values rather than being the upper end of the scale

Because the values I have in my radio are 32 and 39 on VHF and 28 and 32 on UHF

And the observed output from the AT1846 for RSSI is roughly 30 to 70

Of course we don't know what the lower and upper end of the scales represent e.g. is the lower end the noise threshold when connected to a dummy load, and what does the upper end represent e.g. S9 +60db etc ?

**Comment by rogerclarkmelbourne** [comment]
OK.
I was hoping at some time to be able to use the RSSI calibration data points, 

Assuming the probably all are set the same for everyone, (I can check this because I have a lot of calibration data from my radios and other people's radios), I could probably use the data, as long as I used one byte as the low end and the other as the range.

Or I guess i could check the high end value and if its completely wrong, then ignore it and use the hard coded value thats currently in the firmware

**Pull request merged**
