### PR TITLE
Document contact's TS override

### PR DESCRIPTION
**Pull request by f1rmb**
based on what I read in CPS code

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'll double check this.

I wrote the code that handles this, but I wrote it a long time ago (perhaps 6 months + ) and I can't remember the exact details

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I remember why I used those bit codes.

The value of this reserved field seemed to default to 0xFF, as it was not used.

So I used the LS bit, set to 0 to indicate that the byte contained some data, and the next bit to store the TS override value (1 or 2)

**Comment by f1rmb** [comment]
Hi Roger,

   Yeah, that's what I was thinking, and it's clean.
I've just added the comment in the source code because I had to check the CPS one to find the information.
I didn't had time to check and fix the TS override bug for ###, probably the code that check the contact's TS override is missing in the selection function.

**Comment by rogerclarkmelbourne** [comment]
Re: TS Override ###

Yes. Its just missing the code that checks the override.  However, I don't really like the way that the ### to select the Contact, does not set the CurrentContact on the Channel or the VFO.
Instead when you select a Contact, it just uses the TG or PC value and puts it into the Override variable (setting) as if it was a numerical entry.
This results in the need for the display functions to lookup the contact of the TG / PC override, which isn't ideal -  however cleaning that code was not a priority for me, as I was investigating other problems and modifying the CPS for compatibility with the blind operators

**Comment by f1rmb** [comment]
Hi Roger,

   Yeah, I say it just override the TG, and force the displayed name.
I just raised a small PR to fix the contact TS override, and I will change the code to set the current contact instead, but next time I will have time ;-)

Cheers.

**Comment by f1rmb** [comment]
Humm, I checked the code, but since we use TGLists, it's not really possible to set the currentContact when selecting a contact from the global Contacts list, as not all contacts are part of the current TGList. But maybe I missed something here.

**Comment by rogerclarkmelbourne** [comment]
I'll need to have a detailed look at the code, but 

struct_codeplugContact_t currentContactData;

Is a global, in uiUtilities, so when the Contact is selected using ###, I thought that currentContactData could be updated with the data of the contact that is selected.

**Comment by rogerclarkmelbourne** [comment]
Umm. 

The problem is that the Channel and the VFO always load the contact from the list.

If we add a flag, we could prevent this.

I'll do some experiments and see if I can find a clean / KISS solution..

**Comment by f1rmb** [comment]
Hi Roger,

   Yeah true.
Also, manual TS override has a higher priority of the contact one, so manual TS override needs to be cleared when currentContact is set (see trxUpdateTsForCurrentChannelWithSpecifiedContact()).
Contact can be selected from menuContactList.c(menu->contact->etc and SK2+#) and uiTxTgPcContact.c (the ### Ct list).

**Comment by rogerclarkmelbourne** [comment]
There is another complication.

The override contact index would need to be saved in the nonVolatileSettings, 

So as we need to store the override flag somewhere, we probably need to add a int16_t overrideContactIndex to the settings struct and then use that as the flag, and perhaps use -1 to indicate no override, because I'm not sure if the valid contact indexes start from 0 or 1 in the TG list.
If 0 is a valid index, then we would need to use -1, the max number of contacts is 1024, so will easily fit in int16_t

**Pull request merged**
