### PR TITLE
More enhancements for Contact Screen

### PR DESCRIPTION
**Pull request by alexernst**
- Allow to delete TGs not in any RX Group
- Add confirmation before deleting
- Do not save new contact if contact with same TG/ID and calltype exists
- Remove previous used 'Saved' and 'Deleted' screens 

I wonder if it would be better to use a Quickmenu with ORANGE in the Contact List instead of long press GREEN to edit and blue+RED to delete?

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex
Thanks.

I'll take a look.

Re: Orange button.
I'm not sure which function you mean. Perhaps you mean select using up/down then press orange to choose the function to perform.

PS. I'm not sure if you "watch" the repo, but I pushed an experimental version with support to not filter by TS or even CC

This is enabled via the Quick menu on the Channel screen (I did not update the VFO yet)

**Comment by alexernst** [comment]
In the Contact List you can select a contact by UP/DOWN and then to delete a contact use SK2+RED keys. And to edit a contact Long Press Green.

Perhaps it would be better select a Contact with UP/DOWN, press ORANGE and get a menu with 'Edit' and 'Delete'.
I didn't want to simply use the GREEN key to open an extra menu as that selects the contact as the TX contact.

To be honest, I couldn't edit a contact and thought it was a bug, but I simply forgot that's Long press GREEN. So it's somehow not logical.

I saw the dmr-filtering branch but only skimmed over the commits.

**Comment by rogerclarkmelbourne** [comment]
Hi Alex

Yes. I agree the long press would be too complicated

It could be a sub menu using the Green key to select the item, but it would mean to use the contact would require an additional keypress, which is not so good.

**Comment by alexernst** [comment]
That's exactly my problem. 
One solution could be to use a sub menu with GREEN if opened from the menu and to direct select the contact if accessed with Blue+HASH from uiChannelMode or ui VFOMode. 

PS: Ordered a J-Link Mini, hope that makes debugging easier.

**Comment by rogerclarkmelbourne** [comment]
Hi Alex

Jlink will make things sooooo much easier

But please let me know before you try to install it, as you must backup some other parts of the ROM first

I probably need to add a function to backup the ROM into the CPS, to recover the bootloader and also the Hardware Lock bytes in the top of the MCU ROM

**Comment by rogerclarkmelbourne** [comment]
I've tested and it all seems OK.

**Comment by alexernst** [comment]
Hi Roger,

attached my JLink. You're right it is real much much easier. 
Now I have to find my way through the Eclipse debugger.

Alex

**Pull request merged**
