### PR TITLE
Add Newlib support

### LINKED ISSUE #622: Switch to newlib nano instead of redlib as C library
Currently, redlib is used as the libc in this project. The disadvantage of this is that redlib is proprietary, and no source code is available. This makes the project hard to build without the mcuxpresso IDE (my end goal is to be able to build the entire project without having to install proprietary tools and to document how to do this). Mcuxpresso also offers two other libc's: newlib and newlib nano. I tried to switch the project to use newlib nano, but found out there's just barely not enough space in SRAM_LOWER_BOTTOM (we need another 72 bytes at least).

Redlib:
```
    PROGRAM_FLASH:        476 KB       494 KB     96.36%
       SRAM_UPPER:       27600 B        64 KB     42.11%
SRAM_LOWER_BOTTOM:       27444 B      27488 B     99.84%
  SRAM_LOWER_AMBE:          0 GB       8744 B      0.00%
   SRAM_LOWER_TOP:          8 KB      29304 B     27.96%
```

Newlib nano:

```
Memory region         Used Size  Region Size  %age Used
/usr/local/mcuxpresso-ide/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.1.0.202001081728/tools/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld: /usr/local/mcuxpresso-ide/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.1.0.202001081728/tools/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libcr_newlib_semihost.a(syscalls.o): in function `_write':
   PROGRAM_FLASH:        476 KB       494 KB     96.36%
      SRAM_UPPER:       27476 B        64 KB     41.93%
SRAM_LOWER_BOTTOM:       27560 B      27488 B    100.26%
 SRAM_LOWER_AMBE:          0 GB       8744 B      0.00%
syscalls.c:(.text._write+0x0): multiple definition of `_write'; ./source/SeggerRTT/Syscalls/SEGGER_RTT_Syscalls_GCC.o:/home/jdv/Projects/OpenGD77-codec2/firmware/Debug_GD-77/../source/SeggerRTT/Syscalls/SEGGER_RTT_Syscalls_GCC.c:110: first defined here
  SRAM_LOWER_TOP:          8 KB      29304 B     27.96%
/usr/local/mcuxpresso-ide/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.1.0.202001081728/tools/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld: firmware.axf section `.data' will not fit in region `SRAM_LOWER_BOTTOM'
/usr/local/mcuxpresso-ide/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.1.0.202001081728/tools/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld: region `SRAM_LOWER_BOTTOM' overflowed by 72 bytes
collect2: error: ld returned 1 exit status
make: *** [makefile:55: firmware.axf] Error 1
```

I pushed my changes on https://github.com/redfast00/OpenGD77/tree/newlib-instead-of-redlib, so you can check it out if you want to.

### PR DESCRIPTION
**Pull request by cifred98**
Added the support to build with newlib instead of redlib.
I also added a makefile to build the project from Linux without the NXP IDE which supports both newlib and redlib
This should not break the redlib build from MCUXpresso however it is still not possible to compile with the newlib from the IDE
Closes #622

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Why does this PR include changes to the SPI Flash code ?

**Comment by n1zzo** [comment]
Compiling the code using the gnu toolchain and the newlib let the radio in a malfunctioning state,
where it was showing the message "CAL DATA ERROR".
After further investigation we dumped the flash content from the radio, and saw that the data
in it was messed up, but flashing the original fw made everything look normal again.
So it was a flash read issue, we noticed that all the flash block were missing the first bit,
this led us think that it was a timing issue.
By inspecting the flash code we saw the commented `nop` instructions and tried to uncomment those.
The result is that now the flash has enough time to emit the first bit and therefore the flash
data is read correctly. We tested the code on both Mcuexpresso and gcc, and both redlib and newlib
and for now it seem to read flash data correctly.
Nonetheless the nop should be replaced with a time delay of the time needed by the flash
to produce data, to be more resilient in the future.

**Comment by rogerclarkmelbourne** [comment]
Adding nops for both the MCU Expresso build and the Make build in the same commit is not good, because the MCU Expresso build does not need the nops, and this could potentially slow down the Flash transfers a lot on the MCU Expresso build.

I'm happy to add the make file for non-MCUExpresso builds, but I can't accept other changes in the same commit.

**Comment by rogerclarkmelbourne** [comment]
I had a look at your makefile and I can't see where it specifies what level of compiler optimisation is used.

If you look in the MCUExpresso project file, you'll see that some files do not have optimisation enabled.

You explicitly can't used compiler optimisation on any of the code which implements the software SPI functions e.g. for the SPI Flash and also for the UC1701 display and probably for the EPL003 speech synth chip.
If you enable compiler optimisation on any of those files the compiler generated code, creates non-symmetrical clock pulses and also has invalid timings between clock edges and the data.


There are also other files where optimisation can't be enabled in the MCU Expresso project, including the codec binary blob interface and for some reason the SAI (I2S) system does not function at all if optimisation is enabled (and I don't know why)

You'll probably find if you follow the same optimisation settings as the MCU Expresso project that you don't need NOPs in the SPI Flash, as even with NOPs you'll find that it may not work on some radios.

**Comment by cifred98** [comment]
The optimization level I used is Os, it's defined at line 118 of the Makefile.
I tried removing again the NOPs ad adding  ```#pragma GCC optimize ("O0")``` to SPI_Flash.c and it actually worked.
We should add it to all the files where optimization can't be enabled so we can build the project with Os without having to explicitly exclude those files from MCUXpresso and from the Makefile

**Comment by rogerclarkmelbourne** [comment]
SPI_Flash and the UC1701 definitely can't be optimised as it screws up the waveforms.
With the Flash its it breaks straight away, but with the display the problem causes intermittent corruption of the display.


Does the rest of the firmware work for you with all the other files set to -Os ??

i.e have you tested that DMR encoding and decoding and the I2S interface (audio streaming from the MCU to the DAC in the C6000)  works OK?


I'd love to be able to enable optimisation on all other files, but I simply could not get everything else to work.

Most puzzling was why the I2S (SAI) didnt work when optimisation was enabled. It seemed to stop the SAI end of  DMR transfer interrupt callback to not happen.

**Comment by n1zzo** [comment]
I've been testing the firmware with the optimizations disabled for some files,
the DMR RX works perfectly, the DMR TX is broken, only a low amplitude static is transmitted.
NFM RX and TX work, and all the other features of the radio seems ok, including CPS support etc.

**Comment by rogerclarkmelbourne** [comment]
@n1zzo 

Look in the MCUExpresso project and search for files which have -O0 optimisation, then modify the makefile so its the same

There are probably some files set to -O0 which perhaps could be -Os, but you will need to enable optimisation on each file, one by one and then retest both DMR Rx and DMR Tx.

I have not had time to understand why some files must use -O0. There are probably some bugs in the code, but I think they will take a long time to find them, and its not that productive, because the reduction in code size etc will not be much and the firmware works with those files set to -O0 so no one will notice any difference.

**Comment by n1zzo** [comment]
Hi Roger,
IU2NRO extracted a complete list of all the source files which are currently compiled with `-O0`,
they are the following:
```
amazon-freertos/FreeRTOS/event_groups.c
amazon-freertos/FreeRTOS/list.c
amazon-freertos/FreeRTOS/portable/fsl_tickless_systick.c
amazon-freertos/FreeRTOS/portable/heap_1.c
amazon-freertos/FreeRTOS/portable/heap_2.c
amazon-freertos/FreeRTOS/portable/heap_3.c
amazon-freertos/FreeRTOS/portable/heap_4.c
amazon-freertos/FreeRTOS/portable/heap_5.c
amazon-freertos/FreeRTOS/portable/port.c
amazon-freertos/FreeRTOS/queue.c
amazon-freertos/FreeRTOS/stream_buffer.c
amazon-freertos/FreeRTOS/tasks.c
amazon-freertos/FreeRTOS/timers.c
board/board.c
board/clock_config.c
board/peripherals.c
board/pin_mux.c
device/system_MK22F51212.c
drivers/fsl_dspi.c
osa/usb_osa_freertos.c
source/SeggerRTT/RTT/SEGGER_RTT.c
source/SeggerRTT/RTT/SEGGER_RTT_printf.c
source/SeggerRTT/Syscalls/SEGGER_RTT_Syscalls_GCC.c
source/dmr_codec/codec.c
source/firmware.c
source/functions/sound.c
source/functions/voicePrompts.c
source/functions/vox.c
source/hardware/EPL003.c
source/hardware/SPI_Flash.c
source/hardware/UC1701_transfer.c
source/hotspot/BPTC19696.c
source/interfaces/i2s.c
source/main.c
source/semihost_hardfault.c
source/usb/usb_com.c
source/usb/usb_device_descriptor.c
source/usb/virtual_com.c
source/user_interface/menuSoundOptions.c
startup/startup_mk22f51212.c
usb/device/class/usb_device_audio.c
usb/device/class/usb_device_ccid.c
usb/device/class/usb_device_cdc_acm.c
usb/device/class/usb_device_cdc_rndis.c
usb/device/class/usb_device_class.c
usb/device/class/usb_device_hid.c
usb/device/class/usb_device_msc.c
usb/device/class/usb_device_msc_ufi.c
usb/device/class/usb_device_phdc.c
usb/device/class/usb_device_printer.c
usb/device/class/usb_device_video.c
usb/device/source/ehci/usb_device_ehci.c
usb/device/source/khci/usb_device_khci.c
usb/device/source/lpcip3511/usb_device_lpcip3511.c
usb/device/source/usb_device_ch9.c
usb/device/source/usb_device_dci.c
usb/phy/usb_phy.c
```
We marked those files to be compiled with `-O0` also with our Makefile and now the radio
is fully working, I tested DMR, FM, private calls, everything seems fine.
We'll update the pull request soon, and we'll be awaiting for your green light.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I think a few of those files can be optimised, including Vox.c and voicePrompts.c
It looks like any new files may be set it to -O0 by default by MCUExpresso.

I don’t know why the RTOS is not optimised.. you could try enabling optimisation on those files.

But it takes a long time to retest everything, for each file where you enable optimisation

**Comment by rogerclarkmelbourne** [comment]
I've done some more work to try to identify which files definitely can't be optimised.

As far as I can tell, the RTOS can be optimised, as can the usb subsystem.

BTW.  You should not make changes to files outside of the source folder e.g. to add the HASH PRAGMA, because these files are from external sources and are likely to change.
e.g. The RTOS files are now out of date, (v10.0.1 instead of v10.3.0) and I will need to update them, when I get time.

If external library files need separate optimisation you should handle this in the Make system by having sub makefiles for those sub projects, rather than changing the files in those libraries

One file I'm not sure about is BTC19696.c  , the compiler level for this is set to -O2 but its possible that this can also be changed to -Os.  However I don't have time to investigate this at the moment, as its not high priority for me.

**Comment by cifred98** [comment]
Thanks for checking.

I've done some more testing with @n1zzo and these are the files that should not be optimized:
```
drivers/fsl_dspi.c
source/SeggerRTT/RTT/SEGGER_RTT.c
source/SeggerRTT/RTT/SEGGER_RTT_printf.c
source/SeggerRTT/Syscalls/SEGGER_RTT_Syscalls_GCC.c
source/dmr_codec/codec.c
source/firmware.c
source/functions/sound.c
source/hardware/EPL003.c
source/hardware/SPI_Flash.c
source/hardware/UC1701_transfer.c
source/interfaces/i2s.c
source/main.c
source/semihost_hardfault.c
source/user_interface/menuSoundOptions.c
```
maybe there are other files that can be compiled with Os inside the source folder but we haven't checked them yet.

As you can see there is still one file outside the source folder that needs the `#pragma`. Do you think it will be updated at some point or can we do this "dirty" fix for now?

About the MCUExpresso default optimization I think that after this PR it can be set to Os since it will be overridden by the pragma directive when needed

**Comment by f1rmb** [comment]
Hi,

  Just my 2 cents: pragma is evil.

I don't see why using it here, as the optimization level can be defined:
1) by the XPresso
2) by the Makefiles.

So, yeah, it is more work to handle file grouped by -O levels, but both build systems need to be separated. Imagine another platform, for whatever reason, will need a different level, shall we break everything again ?


Cheers.
---
Daniel

**Comment by f1rmb** [comment]
Just a question, why menuSoundOptions.c needs zero optimization ?

Cheers.
...
Daniel

**Comment by Nimayer** [comment]
> So, yeah, it is more work to handle file grouped by -O levels, but both build systems need to be separated. Imagine another platform, for whatever reason, will need a different level, shall we break everything again ?

Hi Daniel,
I think that for the files that currently break the build if optimized, the safest option is to write inside the file itself the optimization level supported.

If we instead set the optimization level from MCU expresso and the Makefile, we would have two separate lists of unoptimized files to be kept synchronized, if these lists were to differ, they could generate different behaviours depending on the build system used, we do not want this :)

Also I think it's unlikely that there will be some platform for which the files as they are now could be optimized.
The proper long-term solution could be to write code that can be optimized together with the rest of the project without breaking

**Comment by rogerclarkmelbourne** [comment]
I can't see why soundoptions.c should need to be non-optimised, its just another menu screen.

What happens if you optimise it ?

If the code breaks, I think the problem is more likely to be memory buffer overrun etc bug, than a being related to optimisation.

Re: PRAGMA
I don't like these either.  I generally find the compiler pragmas problematic because the don't always seem to be handled correctly  by the compiler.


Re: source/semihost_hardfault.c

I noticed it was not optimised, so I looked and its a function that contains assembler.

I wonder if files that contain assembler can't have optimistion enabled (which would explain why codec.c can't be optimised)

**Comment by cifred98** [comment]
The reason menuSoundOptions.c was in the list is that I wrote a python script to parse the `.cproject` file to find all the optimized files but it was ignoring the optimization at a folder level. It looks like that for some reason the optimization is defined for user_interface and then again for all the files inside it except SoundOptions.

About the pragma I agree with @Nimayer, the final goal is to be able to optimize everything without breaking stuff but until then I think that this is a good enough solution. 
To address the concerns of f1rmb of breaking everything again with a new platform we can put the pragma inside a conditional block

**Comment by rogerclarkmelbourne** [comment]
I've cleaned the project file a little 

menuOptions.c is now optimised

You won't be able to use any of the files in the interfaces folder, because they are all MK22 specific

To be able to build on multiple platforms, the structure of the project needs to change to move all the platform specific files into a separate sub-folder e.g. called MK22

But on the MD380 there are other problems with trying this approach, because the baseband RF chip is different and as is the DMR chip.

Currently the code structure, isn't clean enough to handle this, because trx.c code directly calls functions that are AT1846S specific.

I'd recommend that currently you just write a script to copy the GUI and other non-platform specific files and copy them into your project, and when you have got more of the functionality working, this will allow us to understand what structure if needed to support cross platform development

**Comment by n1zzo** [comment]
> I've cleaned the project file a little
> 
> menuOptions.c is now optimise

Can you confirm that an implementation which selects the optimization level only on the Makefile would be mergeable right now?
If so we can work on that.
 
> You won't be able to use any of the files in the interfaces folder, because they are all MK22 specific, so changing source/interfaces/i2s.c is pointless.
> 
> To be able to build on multiple platforms, the structure of the project needs to change to move all the platform specific files into a separate sub-folder e.g. called MK22

We started doing this job in our MD380 repo, where the drivers are separated by platform and
the [Makefile](https://github.com/n1zzo/OpenDMR/blob/7853135c9bb697ad21ca858b3c63b4bfd0b2765e/Makefile#L19) includes only the source folders with contains the drivers of a specific radio.
We need to port such logic in this OpenGD77 Makefile to be able to support more diversified radios in the near future.

> But on the MD380 there are other problems with trying this approach, because the baseband RF chip is different and as is the DMR chip.

That's another deal, and will require probably separate code, still haven't looked into that though

> Currently the code structure, isn't clean enough to handle this, because trx.c code directly calls functions that are AT1846S specific.
> 
> I'd recommend that currently you just write a script to copy the GUI and other non-platform specific files and copy them into your project, and when you have got more of the functionality working, this will allow us to understand what structure if needed to support cross platform development

This is something very feasible, right now on the MD380 we are copying source files by hand thus
we are out-of-tree. After this Makefile has been merged I will begin to work on a PR to merge all the necessary changes, e.g. include the [new generic graphics library](https://github.com/n1zzo/OpenDMR/blob/master/include/interfaces/graphics.h).

**Comment by n1zzo** [comment]
Hi Roger,
can you provide some feedback on which changes do you need to merge this?

**Comment by rogerclarkmelbourne** [comment]
Daniel has explained that 

#pragma GCC optimize ("O0")  

Should not be used.

Compiler optimisation level should be controlled by the Makefile

I can extract your Makefile and linker file, and manually merge those, but I can't merge the source file changes

**Comment by cifred98** [comment]
I modified the Makefile to allow optimizing everything except a list of files.
Now it should be ready for merging

**Pull request merged**
