### PR TITLE
Use ham band limits as default VFO A/B scan limits

### PR DESCRIPTION
**Pull request by ajorg**
The low / high VFO scan limits were hard-coded to 144-146 and 430-440. It seemed that it might make more sense to use the band limits already hard-coded elsewhere as the defaults.

Those ranges are narrower than the Tx band limits used in this patch (144-148 and 420-450) but if anything the Tx ranges should be the narrower limits and the default scan limits should be the broader ones. I think they should be the same by default.

I couldn't find any use of the `RADIO_VHF_MIN` variables and guessed that probably they were supposed to be what the `BAND_VHF_MIN` variables are now.

I did not actually test this on a radio because I made the edits on a Linux machine but it built okay and *looks* correct to me.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

I don't know why the scan values are even defaulted at all. 

Because VFO A is not necessarily used just for VHF (etc with VFO B)

I think these may as well, both be set to zero, and the operator would then have to set their own values.

I'm currently re-working a lot of code in the VFO, so I will change this in my local build.

I was also going to change this into a the low and high values into a struct, as using 4 variables in the settings for this seems messy.

**Comment by ajorg** [comment]
That's fine. I knew you had other ideas about how this all should work, but it sounded like those ideas were not something you planned on doing yet. I thought this might be better in the meantime.

If you do have clear ideas about how it should really work maybe you could describe those on the forum or a GitHub issue and one of us could work on making the changes.

**Comment by rogerclarkmelbourne** [comment]
@ajorg 

I don't use the VFO scan very much, hence didn't notice the various bugs until I started to implement the code to reverse the scan direction.


The problem with the VFO scan seems to be that the screen simply isn't big enough to display all the data that's needed.
The operator should be able to see and change the lower and upper scan frequencies and also be able to see the current frequency.

This sort of thing needs to be carefully designed, by mocking up the screen, and a decision needs to be made about whether the VFO scan is a completely different screen e.g. accessed via a menu, or whether the VFO screen has a Scan mode, where it looks and behaves differently, and possibly you access this mode via the Orange button menu system. There would need to be some indication that the VFO screen is in its Scan mode.

I'll open a thread on the forum in the developers section and perhaps a few members of the community can design the UI and functionality

**Comment by rogerclarkmelbourne** [comment]
I'll close this, because I'm going to default these to zero, and probably get the VFO scan to automatically do +/- 1MHz from the Rx freq if they are set to zero

**Comment by ajorg** [comment]
Sounds good.

I wondered if it could make sense to prompt to set the limits it they aren't set. Just failing will be confusing while it's not obvious how to fix it. ±1MHz seems reasonable as a guess but on a ham firmware it doesn't make a lot of sense to default to scanning non-ham frequencies. In my case that's likely to get stuck on some noisy radar and business channels.

Still mulling this over.

**Pull request closed without merging**
