### PR TITLE
Fix entry of TG or ID in contact details

### PR DESCRIPTION
**Pull request by alexernst**
I broke that in one of my earlier PRs.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex

I noticed 3 more bugs.

1. The Last Heard view on the Tx screen is removed after about 1 second. 
This bug seems to have started with the changes to the Function + number key

2. On the PC screen, if I press NO, then the text time there is a PC I do not get a notification. I'm not sure if this applies to just another PC from the same ID , or all other PC's

3. The morse beeps of "PC" only play while the radio is receiving the PC signal, so sometimes only part of the "PC" morse beeps are played

**Comment by alexernst** [comment]
If you decline a PC the next PC from the same ID is ignored until other TG or PC is received.
Maybe it's better to use a timer to mute this ID for 5 mins or so.

I will investigate the other bugs.

**Comment by rogerclarkmelbourne** [comment]
For bug 1.

I think  the problem is that in uiTxScreen.c that the KEYCHECK_DOWN is returning false even though SK1 remains pressed

```
	if (trxGetMode() == RADIO_MODE_DIGITAL && (KEYCHECK_DOWN(ev->keys, KEY_SK1)) && isShowingLastHeard==false && trxIsTransmitting==true)
	{
		isShowingLastHeard=true;
		menuLastHeardupdateScreen(false);
	}
	else
	{
		if (isShowingLastHeard)
		{
			isShowingLastHeard=false;
			updateScreen();
		}
	}
```

**Comment by rogerclarkmelbourne** [comment]
OK. I understand the logic for when the PC is rejected, but I agree perhaps there needs to be some timeout for this.

**Comment by alexernst** [comment]
I will add the timeout for the PC mute. 
Last heard fixed in PR. The else-branch must check for KEYCHECK_UP() to remove the last heard screen.

**Comment by rogerclarkmelbourne** [comment]
OK
I will check the else-branch

**Comment by rogerclarkmelbourne** [comment]
OK.

I fix the Last Heard / Tx Screen problem.

Thanks

**Pull request merged**
