### PR TITLE
Reintroduce tone scan in VFO quick menu.

### PR DESCRIPTION
**Pull request by f1rmb**
Reorder switch/case to follow the menu enum.
Change sprintf format to align freq, avoiding CTCSS word moves while scanning.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'll pull and test it.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I remember now the "Tone Scan N/A" text ;-)

**Comment by f1rmb** [comment]
I was hesitating to put a ':' in the middle.

**Comment by f1rmb** [comment]
But no, it's fine as it is.
BTW, I didn't even noticed tone scan was missing... ;-)

**Comment by rogerclarkmelbourne** [comment]
I only noticed when I was looking at the DM-5R, I never use it

BTW. Did you see the bug report on the forum about CTCSS not working.

I think it needs some more information, because no one else reported CTCSS not working.

**Comment by f1rmb** [comment]
Yes, I saw the post, but maybe I need to read it again because it wasn't really clear what is going on (or maybe I was still in the mist, missing some caffeine ;-) ).

**Pull request merged**
