### PR TITLE
TS disable override with long press STAR

### LINKED ISSUE #183: Method needed to disable the TS override
Possibly use Long Press on STAR key to remove the TS override ??

### PR DESCRIPTION
**Pull request by alexernst**
Just a small one for today.

Also adds:
- inverse TS '#' if manual override.
- underline 'TS#' if timeslot is taken from contact and differs to channel timeslot.

Inverse 'TS#' is still for Filter:none

Fixes #183

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I will test

**Comment by rogerclarkmelbourne** [comment]
I think although this now shows why the TS is a specific value, I'm not sure its useful to do so.

I think I will post some screengrabs to the forum and get some feedback about how this should be dispayed

**Comment by alexernst** [comment]
I implemented to display different TS reasons, to know when a manual TS override is active that could be disabled. 
I had the unintended contact TS override from my codeplug with other default values in the reserved bytes. And it took some time to figure that the contact settings are wrong.
So I added that info, but it might be too much.

**Comment by alexernst** [comment]
There is another problem with TS override when switching between VFO and Channel Mode. 
So I removed the visual things.

**Comment by rogerclarkmelbourne** [comment]
OK. I will pull again.

**Comment by rogerclarkmelbourne** [comment]
Sorry.

I've not had time to evaluate this again today.

I may have time later, but I'm not sure.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

The functionality to remove the TG override is good.

I think we would need to ask the forum whether any visual indication is needed that the TG is overridden for a specific reason. e.g. Contact TS override.

Or whether this is not necessary because it causes unnecessary visual complication to the UI

**Comment by alexernst** [comment]
Initially I added the visual indication to verify my function is working. 
After all I think it is not needed as it's important to see on which timeslot to transmit not why.
But asking the forum might be an idea.

**Pull request merged**
