### PR TITLE
Implement settings dirty flag and async settingsSave() for RD-5R like platforms.

### PR DESCRIPTION
**Pull request by f1rmb**
Get rid of SETTINGS_PLATFORM_SPECIFIC_SAVE_SETTINGS() macro.
Adds settingsSet() and settingsIncrement()/settingsDecrement() setters.
On RD-5R platform, it set a dirty flag (+ a time counter), so settings are saved async, if needed, after one minute (tunable), except for options and details menus.

The point of this PR is to avoid 1) the SETTINGS.... macro usage, 2) save some eeprom writes.
The cost is 8 bytes on RD-5R platform, 0 bytes for the others. 

**NOTE**: the problem with VFO TS override is still there.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I think 1 minute is far too long for the RD-5R, e.g. if someone changes channel, they may turn off after a few seconds.

Perhaps 5 seconds, but I'm sure even if the dirty time was 5 seconds, I'm sure people will log a bug and tell me that the channel data etc isn't getting saved.

I understand that the macro is not good, but I don't think where is any speed increase on the other platforms, because the EEPROM is only written when the radio is turned off.

On the RD-5R, we could implement something which checks whether its actually necessary to save to EEPROM, but I'm not sure how much time this would save.

Writing the whole of the settings to EEPROM is slow (and happens a lot on the RD-5R), so another option is to pass a pointer to the setting, (which you kinda do in this PR, although its hidden by the compiler), and then calculate the pointer offset from the base of the settings, the only write the individual bytes which need to be written.

However, this is a lot of extra code just for the RD-5R, when I don't think there is a problem.


I know macro's are not ideal, but your PR also adds 2 new macros for Increment and Decrement.

If the code was cpp, of course we could have the multiple functions with different signatures, but its not possible in C :-(


Unfortunately I don't think there is a perfect solution to the problem cause by the RD-5R hardware being cheap and not having some battery power control IC's

**Comment by f1rmb** [comment]
Yeah. As I wrote, the timeout is tunable (in settingsSaveIfNeeded()). I know this is not also ideal, but writting the whole settings (+ VFO codeplug) each time something changes is also far from good, as changing anything in the contact/channel selection triggers a full write. Even if the max EEPROM cycles is huge, it's drastically decreased in the time span, IMHO.

Using the settings entry offset address could also be problematic, as the struct may have some padding.

There are still some instant saving, like channel edition, menu on GREEN hit, etc. Only the changes in Channel and VFO screen are postponed.
What kind of timing do you think is better between EEPROM safety vs annoyance ? 1/2/3 secs ?

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Perhaps 5 seconds would be OK.

If the value is set to 1 second, does that make things much worse than 5 seconds ?

**Comment by f1rmb** [comment]
I don't know, as each time a setting changes, the timer postpone it's timeout, so if the user quickly change channel/contact/ts/etc before the timer expires, another _NOW_ + _X_ second is set.

**Comment by f1rmb** [comment]
About the remaining macro (settingsIncrement/Decrement), it's also possible I change the code the same way as SettingsSet() (aka _Generic()), I don't know the impact on the memory yet, but it's an easy change, as I don't have to change anything in the UI.

**Comment by f1rmb** [comment]
Okay, with Increment/Decrement not as macro, the cost is the same (8 bytes for the RD-5R, nothing for the others).

**Comment by f1rmb** [comment]
I also changed the timeout to 5 secs, maybe we can set it to 3.

**Comment by rogerclarkmelbourne** [comment]
I made a const for the DIRTY_DURATION and I had to set it to 500mS

Even 3 seconds is quite a long time when operating the radio, 500mS seems OK as it would be difficult to change channel and turn off the radio in less than 500mS

**Comment by f1rmb** [comment]
Okay ;-)

**Pull request merged**
