### PR TITLE
Battery graph

### PR DESCRIPTION
**Pull request by f1rmb**
Here is the battery graph, a menuBattery extension.
Use UP/DOWN to navigate the battery menu (a reminder is a the bottom of the screen).
Default graph style is filled graph, but you can use LEFT/RIGHT to change between line and filled styles.

The horizon scale represent ~70 minutes, a tick is drawn each ~15 minutes.

I've also optimized the code to minimalize redrawned areas, in the battery level window, as well.

GD-77_screengrab-2019-12-16_20_29_58
GD-77_screengrab-2019-12-16_20_30_10

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've merged and tested and it will be in today's "Latest" version

**Comment by f1rmb** [comment]
Thanks Roger,

   I don't know if 70 minutes is long enough, but it can be increase quite easily.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel.

I think its OK.

I'm doing a post on the forum now, to ask whether an hour is enough (I will say its an hour even though its 70 minutes)

**Comment by f1rmb** [comment]
Okay Roger.

**Pull request merged**
