### PR TITLE
Translation fixes

### PR DESCRIPTION
**Pull request by riku2015**

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi,

   You shouldn't change fhe file header/footer,  just the translated strings.

Cheers.

**Comment by riku2015** [comment]
Heya, thanks for notice. added them now :)

**Comment by f1rmb** [comment]
You're welcome.
You'd also changed the license, and removed the top comment line (...windows-1252----)

**Comment by riku2015** [comment]
Okey im very sorry about this messup, it seems licence was totally different than on older version of files. now i cut&pasted everything from english file. hope this is ok.

**Comment by f1rmb** [comment]
That's fine now, your revision line is fine too since it doesn't add a line count.

**Comment by rogerclarkmelbourne** [comment]
@f1rmb thanks.  You are correct, that it’s best to keep all files the same length. I am happy for people to be credited. So we probably need a empty credit block in all files so that the have the same structure for easy comparison

**Comment by f1rmb** [comment]
@rogerclarkmelbourne  yes, I'm used to use 'wc -l' to check the files too, and deeper comparison if necessary.

**Comment by rogerclarkmelbourne** [comment]
f1rmb.

Thats a good idea, but as I'm on Windows I have to scroll to the bottom of each file  to see the number of lines. ;-(

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
