### PR TITLE
Enable access to lower SRAM for data, heap and stack

### PR DESCRIPTION
**Pull request by alexernst**
The AMBE coder uses a block of ~8.5K In the middle of the lower 64K-SRAM for decoding and encoding. The space before and after is currently not used.

The .data section is now moved into the space before the AMBE RAM.
Heap (4KB) and stack (4KB) are moved to the space after the AMBE RAM.
This frees around 8.5K bytes in the upper 64K-SRAM.

This results in a memory usage of:
- upper SRAM: 64KB used ~41KB
- lower SRAM before AMBE: ~26.8KB used: 604B
- lower SRAM after AMBE: ~28.6KB used: 8KB
 
The compiler/linker positions all uninitialized variables into the .bss section in the upper SRAM and all initialized variables will get into the lower SRAM.

Moving a variable to a specific section is possible like this:
`BSS_LOWER_BOTTOM int var_in_lower_before_ambe_bss;`
`BSS_LOWER_TOP int var_in_lower_after_ambe_bss;`
`DATA_LOWER_TOP int var_in_lower_after_ambe_data;`

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex

Does the lower bank of memory get used for data, heap and stack ?

I have not looked at the SDK examples, but I presumed that perhaps the stack was only allocated from the upper bank

**Comment by alexernst** [comment]
With this modification the lower memory bank is used for stack and heap.
In MCUExpresso there is a view 'Image info' where you can examine which part of RAM and Flash is used and what for.

**Comment by rogerclarkmelbourne** [comment]
Ok.

I will compare this with the SDK examples which also use both memory banks

**Comment by alexernst** [comment]
I didn't find any examples other than explicit set a RAM section in the source code by __attribute__(...).

**Comment by rogerclarkmelbourne** [comment]
I did some tests and everything seems to be working OK.

BTW. Where is the View Image Info menu. I can't find it.

**Comment by alexernst** [comment]
thanks.

You can find the view under 
'Window' -> 'Show view' -> 'Other' and then select 'MCUXpresso IDE' -> 'Image Info'

In the Image Info view you have to load the last build artifact (Click the first Icon).

**Pull request merged**
