### PR TITLE
Adjust :, ;, and | in 8x16 font

### PR DESCRIPTION
**Pull request by ajorg**
This commit moves the colon and semicolon one pixel to the left (I was inclined to move them two pixels but thought that was likely to get shot down compared to this. The chance corrects the font looking like the colon is glued to the next character when more commonly it would be glued to the previous character. It puts them effectively in the center.

The commit also makes the pipe character solid instead of broken. Broken pipes are jarringly unfamiliar and are a different character anyway: ¦ vs |
To avoid looking too blocky the pipe is trimmed to a very slight slant that matches the slant of other characters in the 8x16 font.

Before (notice the colons are slightly too far to the right):
broken-pipe

After (# character to show slant for comparison):
solid-pipe

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
This would need to be updated in Daniel's master reference image for the font

**Comment by ajorg** [comment]
Oh! I didn’t realize there was a reference image. I thought the conversion tool was required. I’ll take a look and update that too.

**Comment by rogerclarkmelbourne** [comment]
This is Daniels domain.  I'm not sure if he uploaded the images.

**Comment by ajorg** [comment]
I can't find any reference image. Maybe you can just assign this PR to @f1rmb to review?

**Comment by rogerclarkmelbourne** [comment]
Yep Will do..

**Comment by f1rmb** [comment]
Hi,

    Just woke up :-)
Okay, the reference images are the font data, make from/to using UC1701_font_tool.c and its shell script compagnon.
I will just have a quick look at the diff, but it looks fine at the first sight.

Cheers.

**Comment by f1rmb** [comment]
I'm not sure slanted pipe, as pipe is pipe, and the font is slighlty bold (for readability).
So it's up to you Roger, the data for non slanted monoblock pipe (two pixel width):

0x00, 0x00, 0x00, 0xFE, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7F, 0x7F, 0x00, 0x00, 0x00,

Cheers.

**Comment by ajorg** [comment]
I obviously can’t quibble over two pixels. Whatever either or both of you decides is fine. I’m headed to bed now so if you want me to change something I’ll have a look tomorrow.

**Comment by f1rmb** [comment]
Okay Andrew, have a good night.

**Comment by rogerclarkmelbourne** [comment]
Wow. I thought you would be getting up soon ;-)

**Comment by rogerclarkmelbourne** [comment]
Is the semi colon, pipe and the # used anywhere in the UI,

**Comment by f1rmb** [comment]
In the UI, no, in the TA and/or CPS names, could be.

**Comment by rogerclarkmelbourne** [comment]
I'm struggling to see any difference with the colon  : 

My codeplug doesn't contain any of the other characters, and I've not noticed them being used in the UI.

**Comment by f1rmb** [comment]
the colum is one pixel off in the left direction, according to the pictures.

**Comment by f1rmb** [comment]
Err, not here, the pictures... Where did I saw that ?...

**Comment by rogerclarkmelbourne** [comment]
The : may have moved, but I could not really see any difference, between before and after I uploaded this version.

1 pixel movement wasn't really noticeable

**Comment by f1rmb** [comment]
I didn't try yet, maybe it make it clearer in the options, as name and option value looks separated;
image

typographically:
Main option:value    << is bad
vs
Main option: value   << is good

... compiling....
Looks less right aligned, which is better, IMHO

image

image

**Comment by rogerclarkmelbourne** [comment]
I have no preference

So use whichever you think is better.

**Comment by f1rmb** [comment]
;-)

Except the slant of the pipe, I think it's fine.

**Comment by ajorg** [comment]
Adopted the less slanty solid pipe.
solid-pipe

**Comment by rogerclarkmelbourne** [comment]
Whats the status of this PR ?

**Comment by f1rmb** [comment]
From my point of view, it's ready.

**Comment by rogerclarkmelbourne** [comment]
I've merged this with the development branch

**Pull request closed without merging**
