### PR TITLE
Update OpenGD77_User_Guide.md

### PR DESCRIPTION
**Pull request by deviousway**
Description howto wirte code plug on ArchLinx Distro

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
This isn't the description of how to load the codeplug, its how to load the firmware.

I can't accept this PR until its corrected.

**Comment by deviousway** [comment]
> This isn't the description of how to load the codeplug, its how to load the firmware.
> 
> I can't accept this PR until its corrected.

renamed  section to the  
#### Update firmware on Archlinux

**Comment by rogerclarkmelbourne** [comment]
Sorry. But you must be using an old version of the loader, because its no longer necessary to download the SGL.

The normal method is now to select your radio from the list and then press the "Download & Update button"

Users can download the sgl file if you want, but its no longer the preferred method, because the "Download & Update" button will download the latest stable version each time.

image

**Comment by rogerclarkmelbourne** [comment]
Actually, There is a PR to change this further, by adding the option to download the latest Stable or Development version.

So there is no point in updating the User Guide at the moment it will need to be updated in a few days when I merge Daniels pending PR

**Pull request closed without merging**
