### PR TITLE
Update spanish.h

### PR DESCRIPTION
**Pull request by EA5SW**
Update TA first to Spanish

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

Daniel has proposed some changes to this function, and has changed the name for this, so I think it will need a new translation after I have confirmed his PR works OK

**Comment by EA5SW** [comment]
Ok, when confirmed i changed it.

**Comment by rogerclarkmelbourne** [comment]
I've merged 2 PR's from Daniel, but you may like to wait as there is likely to be another addition because of the new text in the PR https://github.com/rogerclarkmelbourne/OpenGD77/pull/418
from EA3IHI

**Comment by EA5SW** [comment]
Yes, I made a new PR when available..

**Pull request closed without merging**
