### PR TITLE
Power & Freq changes

### PR DESCRIPTION
**Pull request by EA5SW**
Changes  to freq steps ,10 Hz,100hz and 1 Khz.

Power levels 50mw, 250mw and 500mw

What do you think Roger ???

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
AFIK the VFO freq steps are defined in the CPS, hence you can’t just change them in the firmware.
Also you removed VFO steps that would allow people to change channel using the VFO.
I don’t think people will like it.

I don’t know whether it would be possible to have additional step sizes, but the CPS defined steps can’t be changed. It may be possible t define additional steps, but I don’t know how many binary bts the codeplug allocates for the VFO step parameter 

Also the CPS would eventually need to be updated 

Re:Power levels

You can’t just change the meaning of the power step without resetting the nonVolatile settings, otherwise people that are currently using less than 1W would have a change to their radio without being alerted.

I also don’t know if many people are using 750mW, it may be a very popular setting, but probably not.

The hotspot mode calculation of power level would also need r be changed.


Overall, when you make a PR you have to consider the thousands of other people who use the firmware, and whether they would also want these features, especially because you removed some things m e.g. VFO steps.

**Comment by EA5SW** [comment]
Sorry Roger... I see also some mistakes..
I deleted it

**Comment by rogerclarkmelbourne** [comment]
OK

I'll leave this open as its easier to see it. But I won't merge it.

I will ask the forum about removal of the 750mW setting to see if its used

I may just add a 50mW setting and then there is no change for existing users.

**Comment by EA5SW** [comment]
The step of 10hz 100hz and 1khz are very good in vfo mode to adjust small steps for hotspots, or using the GD77 to listening satelite doppler..

Also for explample if leave:

const int VFO_FREQ_STEP_TABLE[8] = {1,10,100,250,500,625,1250,2500};

Retains the compatility with the CPS and are more real frequency steps under my point of view..


Also in the power settings if are a 50mw mode for hotspots you retain 250mw & 500mw for low power and have 1,2,3,4, and 5 W for Hi power.

Those are the idea of the PR...

**Comment by rogerclarkmelbourne** [comment]
See

https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/firmware/include/functions/fw_codeplug.h#L72

Those step values are define in the CPS.

https://github.com/rogerclarkmelbourne/OpenGD77CPS/blob/master/DMR/VfoForm.cs#L1312-L1329

https://github.com/rogerclarkmelbourne/OpenGD77CPS/blob/master/DMR/VfoForm.cs#L3980-L3990

Possibly the new step sizes can be put at the end of the list, but you can't change the meaning of the existing step sizes defied in the codeplug

**Comment by rogerclarkmelbourne** [comment]
FYI.

I've added the 50mW setting, and also a "5W++" setting, however the 50mW setting does not output the same power on all radios

On one of my radios it outputs around 60mW, and on another radio my power meter shows 0.00W.
My power meter does not seem to work well below 40mW, so its possible the power being produced is not 0.00W but could be 39mW etc, but its not possible of me to know,

I will need to investigate if another strategy for calculating the PA drive level is better than using an offset from the 1W drive level. e.g. possibly use a faction of the drive level for 1W, as this may be more portable across multiple radios.

**Comment by EA5SW** [comment]
I see all the test in the forum, but my meter don't allow me those low powers.
Thanks for the effort.

I modify also the frequency steps  to include all in MCU IDE and mod the CPS in Visual studio, I compile a test version, read and write the codeplug with the new values appears to work...

**Comment by rogerclarkmelbourne** [comment]
I'm going to close this, because the new power levels for 50mW and 5W++ have been added

**Pull request closed without merging**
