### PR TITLE
Remove unneeded chars, added in last commit.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thankyou

**Comment by rogerclarkmelbourne** [comment]
PS. I am busy with my 'day job' at the moment, so have not had any time to update the buffer size back to 17 instead of 33.

But its a fairly quick change as Notepad++ on Windows can do a multi-file search and replace, and most places that are set to 33 can now be 17.

BTW. I'm not sure if this needs to be a size_t variable. I think hard codeing it should be OK as the screen size does not change (at least for this radio), and if other radios are ever supported, I think a the whole UI would need to be different e,g. for the MD-380 etc

**Comment by f1rmb** [comment]
Okay Roger, no problem.

I'll do that (back to 17 when possible).
About size_t, yeah, my fault (I always put size_t for array index). I just check, it's typedef to
typedef unsigned int size_t;
And since it's a 32bits MCU, I guess it won't be smaller, no ?
About hardcoding a value, I thing it's nicer and clear to use a variable, since it's used in the snprintf() and friends in the functions, and I think (bet) gcc is smart enought to optimize that, even in debug build, don't you think ?

ATM i'm finishing translations stuff in ContactList, yead @ 4AM :-D

**Comment by rogerclarkmelbourne** [comment]
You could make it a static const int   , but just an unsigned int   may cause the compiler to make it into a local variable (depending on how clever the compiler is)

Using const int or const unsigned int, should be almost the same as a ##define but is preferable because its strongly typed.

I'm actually surprised that the compiler allowed a size_t variable to specify a array size, as it doesn't seem to allow that for some arrays.

The difference may be that this is a local var on the stack and not a global var.

**Pull request merged**
