### PR TITLE
In ChannelMode, display TG line when pressing SK1 (in RX).

### PR DESCRIPTION
**Pull request by f1rmb**
Add SK1 support in VFOMode, it displays CTCSS and squelch in analog.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I will pull and test.

**Comment by f1rmb** [comment]
Okay.

Funny to press SK1 while scanning ;-)

**Comment by rogerclarkmelbourne** [comment]
I made one change

The squelch value is displayed as a percentage in the CPS, where 1 = 0 % and 21 = 100% ( 0 = No custom squelch for this)


Umm

Actually I need to do this on the Channel screen as well as the VFO.

I'll change it now.

**Comment by rogerclarkmelbourne** [comment]
OK. I fixed that omission.

**Comment by f1rmb** [comment]
Yeah, I noticed that too, it was the plan to change this right after, but you've been faster ;-)

**Comment by rogerclarkmelbourne** [comment]
(LOL)

No worries.

**Pull request merged**
