### PR TITLE
[Hotspot] Cleanup in Serial comm (some commands should be ignored, some others …

### PR DESCRIPTION
**Pull request by f1rmb**
…are only used in answer frames).

### CODE REVIEW

**Comment by f1rmb** [comment]
the beginning was here #322

**Comment by f1rmb** [comment]
It's still not ready, BTW ;-)

**Comment by f1rmb** [comment]
Hi Roger,

    It looks working and stable now.

A new Option has been added (that will conflict with your TA branch, BTW), that let you choose the Hotspot mode: MMDVM(default) / BlueDV, as BlueDV doesn't really work as MMDVMHost does.

In MMDVM mode, when MMDVMHost is shutting down, the GD will go back to default root menu after a small amount of time, unlike in BlueDV mode, where you need to press RED key.
If MMDVMHost is shutting down while XMitting, it will turn back to RX mode. It's not possible to do this with BlueDV, AFAIK under Windows with latest preBeta version, as it leave the modemState to where it was (to circumvent this, user need to disable DMR mode first, then leave BlueDV). 

I left the possibility to enable debug screen, I will remove all of this if we don't get too much bug reports ;-)

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

OK.

No worries about the conflict with the TA Tx option etc.  That will not be difficult to fix.

I will merge later

**Comment by f1rmb** [comment]
I'm building a MMDVMHost modded version to display OpenGD77_HS in dashboards (I willl submit the patch to G4KLX).

Cheers.

**Comment by rogerclarkmelbourne** [comment]
> I'm building a MMDVMHost modded version to display OpenGD77_HS in dashboards (I willl submit the patch to G4KLX).

OK. You can try, but Jonathan seemed reluctant to support any non MMDVM hardware, when I originally discussed how to use MMDVMHost with the OpenGD77 HS

**Comment by f1rmb** [comment]
Okay, I'll try. Anyway, it's in my MMDVMHost fork ;-)

**Comment by f1rmb** [comment]
The patch is just to send correct software info in the network, instead of "Unknown".

**Comment by rogerclarkmelbourne** [comment]
BTW. I just had a bit of a problem with the PR from W0RMT, because he accidentally added a file with a forward slash in the filename, which trashed my local copy of the repo on Windows :-(

I've had to clone it onto my linux machine, and remove the file the recommit 

AArrggghhhhhhhh

**Comment by f1rmb** [comment]
Wow, a slash in the filename, never saw that ;-)

Hopefuly you fixed it.

**Comment by f1rmb** [comment]
I'm updating my Pi-Star forks with OpenGD77_HS support (V4 is ready, V3 in progress).

**Comment by rogerclarkmelbourne** [comment]
Yep. Its fixed now, but if anyone changes to that specific branch on Windows it will screw up their local repo and they will need to re-clone it.

**Comment by f1rmb** [comment]
Ah, that's not cool !

**Comment by rogerclarkmelbourne** [comment]
I pulled and started to test, but its too late for me to do enough testing today. 

I will test tomorrow and merge if no serious problems

**Comment by f1rmb** [comment]
Okay Roger, no problem.

**Comment by f1rmb** [comment]
Hi Roger, 

   I think you need to re-pull as I've added few things (like RSSI into frames).

Cheers.
---
Daniel

**Pull request merged**
