### PR TITLE
New memory scan strategy

### PR DESCRIPTION
**Pull request by ea3ihi**
This PR contains changes to the memory scan code. Channels are not directly loaded but instead checked and if channel is not in the nuisance list or has the skip flags, a nextChannel flag is set. This prevents stopping in a "skip" channel. A scanning symbol (using the letter Z) is shown in the screen header while scanning.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
@ea3ihi 

You have committed your .cproject in this PR

You need to replace the .cproject with the version from the master branch and then commit the change,

**Comment by ea3ihi** [comment]
The commited .cproject file is identical to your current one.

**Comment by f1rmb** [comment]
Nope, check the "Files Changes" in this PR.

**Comment by f1rmb** [comment]
As you already wrote, it's a bad idea to execute "git commit -a", just get the status with "git status" and add relevant files to "git commit" command.
.cproject shouln't be updated updated here, never. It's up to Roger to modify it (I don't have the same .cproject, as I use newer SDK version).

Cheers.

**Comment by f1rmb** [comment]
You can reset the cproject with:

git checkout upstream/master firmware/.cproject

if your local remove of this repository is named "upstream", otherwise use the name you choosed.

Cheers.

**Comment by ea3ihi** [comment]
I think it is highlightting the changes in respect to my previous versions of the .cproject file (?). I just copied your file again to my workspace and compared with the old version using notepad++ and they match, and also gitstatus states:

$ git status
On branch channelscan1                                                                                                                nothing to commit, working tree clean
--

**Comment by f1rmb** [comment]
Of course there is nothing, now, as you commited and pushed the modified .cproject file.

So, execute (in your branch)

git checkout upstream/master firmware/.cproject

(to have the full list or remotes: git remote -v)

then commit and push the .cproject, it will disappear from this PR.

Cheers.

**Comment by f1rmb** [comment]
it's worse ! :-D

Is your master branch synced with upstream ?

**Comment by f1rmb** [comment]
I think you should revert this latest commit.

**Comment by ea3ihi** [comment]
It was... a couple of days ago, will pull your master again

**Comment by f1rmb** [comment]
before, revert you last commit and push using "git reset --hard HEAD~1", then you need to push --force I think.

**Comment by f1rmb** [comment]
It was, but Roger fixed fw_sound.c optimization.

It's always better merge master changes to your dev branch (git checkout master; git fetch upstream; git merge upstream/master; git check <mybranch>; git merge upstream/master)
At least, you will experience merge conflict locally, that gives you a way to fix it before pushing the branch (or commits).

Cheers.

**Comment by ea3ihi** [comment]
Thanks for the support, pushing using --force did the trick, otherwise I was receiving "Everything up-to-date" all the time and the conflict won't go away

**Comment by ea3ihi** [comment]
But still lists some changes to the .cproject file

**Comment by f1rmb** [comment]
Okay. now .cproject is still in the state you pushed it at the beginning.
Now you need to revert these changes on on you dev branch.
Yeah, you can copy or checkout master's .cproject. then commit and push it.

**Comment by f1rmb** [comment]
Once you reverted locally, you can do "git diff firmware/.cproject" and see the exact opposite of what this PR does to the file (check "Files Changed" tab).

**Comment by ea3ihi** [comment]
Please close this PR, i will create a new one

**Comment by rogerclarkmelbourne** [comment]
Daniel

Btw.

I have updated to the latest version of the IDE already.

I think some of the differences in the .cproject now come from Alex, because he made changes to allow access to the lower 64k bank of RAM

Sometimes the IDE seems to change the .cproject for no reason, so I just checkout the local master again, and after that it does not seem to change even if build or clean the project.

It’s a common problem with all IDEs , they often do small updates to their project file e.g. change the “accessed date” 

But this is a pain when using Git, because it commits unrelated and useless changes.

I use    git status   a lot to see which files have been changed, so that I only commit the files which have changed as part of any modifications I make

**Comment by f1rmb** [comment]
Hi Roger,

 Okay about the .cproject. In fact, Xpresso update it when you leave it. And the major difference with mine is the SDK version. And that now:

> -                                       <fileInfo id="com.crt.advproject.config.exe.debug.1021312312.776969913" name="fw_sound.c" rcbsApplicability="disable" resourcePath="source/functions/fw_sound.c" toolsToInvoke="com.crt.advproject.gcc.exe.debug.475830819.1294673778">
> -                                               <tool id="com.crt.advproject.gcc.exe.debug.475830819.1294673778" name="MCU C Compiler" superClass="com.crt.advproject.gcc.exe.debug.475830819">
> -                                                       <option id="com.crt.advproject.gcc.exe.debug.option.optimization.level.1005845558" name="Optimization Level" superClass="com.crt.advproject.gcc.exe.debug.option.optimization.level" useByScannerDiscovery="false" value="gnu.c.optimization.level.none" valueType="enumerated"/>
> -                                                       <inputType id="com.crt.advproject.compiler.input.81270109" superClass="com.crt.advproject.compiler.input"/>
> -                                               </tool>
> -                                       </fileInfo>

Hmmm, why oh why. I need to check this.
Yeah, and Eclipse like to make changes in cproject file, and it couldn't be added to gitignore neither...

**Comment by rogerclarkmelbourne** [comment]
Yes.. it’s a pain...

**Comment by f1rmb** [comment]
About fw_sound.c, you apply -O0, right ?

**Comment by f1rmb** [comment]
If it's the case, it normal XPresso removes the line, as this file optimization is equal to default Debug project value.

**Comment by f1rmb** [comment]
Confirmed:

> arm-none-eabi-gcc -DSDK_DEBUGCONSOLE=0 -DGITVERSION=\"`git rev-parse --short HEAD`\" -DUSE_SEGGER_RTT -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -DFSL_RTOS_FREE_RTOS -DSDK_OS_FREE_RTOS -DCPU_MK22FN512VLL12 -DCPU_MK22FN512VLL12_cm4 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -D__REDLIB__ -I../board -I../include -I../include/hardware -I../include/codec -I../include/functions -I../include/interfaces -I../include/io -I../include/usb -I../source -I../ -I../amazon-freertos/include -I../amazon-freertos/FreeRTOS/portable -I../drivers -I../device -I../CMSIS -I../usb/device/class -I../usb/device/source -I../usb/device/include -I../usb/device/source/ehci -I../usb/device/source/khci -I../usb/device/source/lpcip3511 -I../usb/include -I../usb/phy -I../osa -O0 -fno-common -g3 -Wall -c -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -fmerge-constants -fmacro-prefix-map="../source/functions/"=. -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"source/functions/fw_sound.d" -MT"source/functions/fw_sound.o" -MT"source/functions/fw_sound.d" -o "source/functions/fw_sound.o" "../source/functions/fw_sound.c"

**Comment by rogerclarkmelbourne** [comment]
Ok.

I can manually remove that line from the xml of the .cproject

**Comment by f1rmb** [comment]
Just leaving XPresso, and it will be removed.

**Pull request closed without merging**
