### PR TITLE
Cleanup TA to display, removing space at the beginning and end of the 'string', otherwise text if badly centered.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

The TA needs to be cleaned up a lot.

Initially I had it just wrapping over both lines, buy splitting the total TA string after 16 characters, but I found mostly the callsign is sent in the first 6 characters, so I changed to put the first TA block (6 chars ) on the middle line and the rest of the TA on the lower line
But this is not ideal either, as i noticed sometimes people had a short callsign e.g. 4 chars and part of their name from the APRS data section on the BM self care is also part of those 6 charars

e.g. 
"N1ID J"
"ohn"

I thought of perhaps some intelligent split of the TA data when there is a space

But now I think that it would be better to animate the TA text as a "ticker tape" and only use the middle of the screen for the TA or ID data
This would also allow extended DMR ID database text of more than 16 chars etc

**Comment by f1rmb** [comment]
Don't merge that yet, I found a problem.

**Comment by f1rmb** [comment]
And yes, we need rolling texts ;-)

**Comment by f1rmb** [comment]
I stumble on a funny thing while testing this small tweak:
I got the first TA with non ASCII char.
It was displayed as "-?D?P"
MMDVMHost log relevant part:
M: 2019-11-19 20:46:53.417 0000:  04 00 0D 2D 04 44 0D 50 00                         *...-.D.P.*
M: 2019-11-19 20:47:23.760 DMR Slot 1, received network end of voice transmission from KD5ILG to TG 3100, 31.1 seconds, 0% packet loss, BER: 0.0%

At least our new ? char was a good marker.

Now this PR is working.

**Comment by f1rmb** [comment]
Temporary, I can add something smarter for TA splitting.

**Comment by rogerclarkmelbourne** [comment]
I think the last block of the TA contains GPS data (I can't remember the block code. Perhaps block 7)
But I can't remember if I process the last possible TA block

Or was this character in the first 2 or 3 blocks of data?

**Comment by f1rmb** [comment]
I don't know the TA structure, but in MMDVMHost's log, I don't see any GPS coords, Only TA, splited in sequences.

**Comment by f1rmb** [comment]
Like this one:
M: 2019-11-19 20:56:59.197 DMR Talker Alias (Data Format 1, Received 6/22 char): 'KA1BKR'
M: 2019-11-19 20:56:59.197 DMR Slot 1, Embedded Talker Alias Header
M: 2019-11-19 20:56:59.197 0000:  04 00 6C 4B 41 31 42 4B 52                         *..lKA1BKR*
M: 2019-11-19 20:56:59.905 DMR Talker Alias (Data Format 1, Received 13/22 char): 'KA1BKR DMR ID'
M: 2019-11-19 20:56:59.905 DMR Slot 1, Embedded Talker Alias Block 1
M: 2019-11-19 20:56:59.905 0000:  05 00 20 44 4D 52 20 49 44                         *.. DMR ID*
M: 2019-11-19 20:57:00.613 DMR Talker Alias (Data Format 1, Received 20/22 char): 'KA1BKR DMR ID: 31519'
M: 2019-11-19 20:57:00.613 DMR Slot 1, Embedded Talker Alias Block 2
M: 2019-11-19 20:57:00.613 0000:  06 00 3A 20 33 31 35 31 39                         *..: 31519*
M: 2019-11-19 20:57:01.351 DMR Talker Alias (Data Format 1, Received 22/22 char): 'KA1BKR DMR ID: 3151999'
M: 2019-11-19 20:57:01.351 DMR Slot 1, Embedded Talker Alias Block 3
M: 2019-11-19 20:57:01.351 0000:  07 00 39 39 00 00 00 00 00                         *..99.....*
M: 2019-11-19 20:57:02.561 DMR Slot 1, received network end of voice transmission from KA1BKR to TG 91, 8.0 seconds, 15% packet loss, BER: 0.0%

**Comment by rogerclarkmelbourne** [comment]
OK. 

Thats a standard one. Generated by BM.
I don't think that station has changed their data in the Self Care page on the BM site.

Perhaps a bug in BM? 
or bad data from the www.radioid.net DB

**Pull request merged**
