### PR TITLE
Update main.c

### PR DESCRIPTION
**Pull request by vk7js**
Hold down hash while powering on to enable Voice Prompts if they are disabled. This is like the Kenwood TH-D74A and many blind people would be used to this power-on sequence to get voice prompts up and running.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'm not sure if # on boot is a standard, or whether it is just on one Kenwood radio.

I'll refer this to DJ0HF for review

**Comment by vk7js** [comment]
Hi Roger,

 

Its not a standard, but since it is done on the only other mainstream accessible handheld radio, the Kenwood TH-D74A, we are being consistent with that and I guess creating a de-facto standard.

My beta testers love it.

Joe

**Comment by vk7js** [comment]
Dear Roger,

 

I do plead with you to include hash on power-on to turn on voice prompts. What perhaps you don’t know is that I am on a blind hams list with over 160 blind hams and the number of requests I get to help because people can’t follow Ian’s simple instructions are numerous. His instructions are great, don’t get me wrong, but inevitably blind folk who aren’t as savvy press the wrong keys and when they have no voice feedback get messed up pretty quickly. I challenge you to take a radio without voice prompts and get voice prompts going. It isn’t as straight forward as you think.

It is far easier in an instruction set to say “hold down hash and turn on the radio.” Rather than turn on the radio, press the green key, arrow up four times, press the green key again, arrow up once, then arrow right 4 times. It is so fraught with the possibility of making error, not to mention the fact that Ian may not always be around to update his instructions if the menu system changes and those instructions are no longer relevant. If you don’t have a simple mechanism, you can’t simply update the Sound menu without the possibility of breaking these already long instructions.

 

When I add a feature or fix something, it is not merely because I have a whim to do so. I am already an incredibly busy person as you are. I add things on request and because as a blind person myself, know what blind people need, having worked in the accessible technology industry for more than 30 years, in my current job for more than 25 and a programmer for several years even before that. My life has been about making computers, gadgets and software accessible.

Kenwood added this feature to their very accessible ht because it is so difficult for a blind person to turn the voice prompts on for the first time, especially if they do not live with a sighted person. If they do, and share a radio, the blind person may be left with  a radio with voice prompts off. No, just because one lives with a sighted person does not mean they always remember to do the right thing, in fact, they rarely remember. On a daily basis I’m having to tell my children to put things away so I don’t trip over them, etc etc.

Thanks for your consideration.

 

Joseph

**Comment by vk7js** [comment]
The arguments from the blind hams community are as follows, even if DJ0HF doesn't think it a good thing. I post on behalf of about 384 users:
1.	The multiple steps are dependent upon a static menu structure or someone updating documentation if they change. Ian may not be around to change them.
2.	The multiple steps are prone to error and could result in a user accidentally changing another setting unintentionally and not even knowing it because voice prompts are not yet enabled. 
3.	Even though someone who had the skill of uploading the firmware, installing the voice prompts and following Ian's instructions, could still get that last key sequence wrong since the other steps of uploading are basic computer skills which we agree most people even attempting this would already have. However, the key sequence could be the final straw for someone not doing it. We think it is a no brainer to add the shortcut.
4.	Kenwood obviously thought it also helpful and. For us to choose the same keystroke just makes sense and creates a de-facto standard. If we keep pushing for this in other radios, eventually it will just be a known fact amongst blind hams that that is the way you turn on voice prompts, or something to try. 
5.	Even though the Kenwood d74a radio is the only radio which does this, it happens to be the only other serious contender for accessibility and is the radio which blind hams buy if they can afford it. Many already have one.
6.	If the radio is shared between a blind and sighted ham as it might be in a family, the sighted ham may leave the radio with voice prompts off and may not be around to turn them on. It is far more likely that someone is able to remember this shortcut than the complicated key sequence that exists now.
7. The change would not affect a sighted ham one bit, and may be just as helpful to them.

**Pull request closed without merging**
