### PR TITLE
Update uiUtilities.c

### PR DESCRIPTION
**Pull request by vk7js**
Only speak characters during text input at voice prompt levels 2 and higher. If users have beeps enabled they don't want to hear the characters being entered.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Please read my previous responses.

Changes like this need to be done via consensus, usually via the forum, or some other online method where many users can respond.

Its not just blind users who use the voice prompts

**Comment by vk7js** [comment]
Roger, Since this has not been pushed to release yet, no-one has seen the original change so you should be able to pull it fine. The original change spoke char input at prompt level 1 and above which meant that if users who only turned beeps on and did not want voicing used character input they'd hear the characters and probably complain. As I said, the original change of speaking chars on input has only gotten into dev, not release so has limited trial except for the beta testers I use for my change who agree with it.

**Comment by vk7js** [comment]
Hi Roger,

 

The original change of speaking chars on input is not in release yet, only development so the only users who have seen this are my beta testers.

People who enable beeps but not voicing might get annoyed if you don’t pull this since at level 1 they’ll start hearing chars. As I said, this is not in release so very limited users  would have seen the original change.

Joe

**Comment by vk7js** [comment]
Hi Roger,

 

I’m really not fussed if you don’t pull this one, for all blind folk they’d prefer speaking at all voice prompt levels for character editing but for sighted folks they probably want to hear just beeps at level 1. It is a bit confusing because there are 6 levels of voice prompt. Silent, normal, beep, level1, 2 and 3, however in the menus at least it seems like there are only 4, it’s a bit hard to tell since once you arrow left past level 1, things no longer speak.  My intention is simply to honour the voice prompt properly at the beep level. If this is already correct that is fine. Remember, I added the char input speaking and it hasn’t been released except to the dev branch so whatever change is made here hasn’t been seen by those who only use the stable release.

Joe

**Pull request closed without merging**
