### PR TITLE
Apply contact TS override

### PR DESCRIPTION
**Pull request by f1rmb**
From various contact picking lists (###, menu contact->list->select TX, SK2+#)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Would this be superseded if the CurrentContact can be set ?

**Comment by f1rmb** [comment]
See the other reply I've made on the other merged PR.
Of course yes, but as you can see, currentContact is linked to TGList ATM (e.g. loadChannelData() in channel mode).

**Comment by rogerclarkmelbourne** [comment]
Should I merge this even though we may develop another way to solve the problem ?

**Comment by f1rmb** [comment]
It's up to you, but for sure that fix the problem until something cleaner is implemented.

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll merge it, and we do a better fix later.

**Comment by rogerclarkmelbourne** [comment]
Thanks

BTW. I'll update the development Release with these changes (and my changes to the DTMF and 1750Hz deviation)

**Comment by f1rmb** [comment]
Okay. Yeah, I saw the log about the deviation fix.

**Pull request merged**
