### PR TITLE
New contact list

### PR DESCRIPTION
**Pull request by alexernst**
This is not ready to merge, but I need some feedback.

Features: 
- Use contact data instead of overrideTG
- Select highlighted contact with PTT
- PC and TG in one list (could be a setting, as it's nearly no overhead)
- Sort contacts by name (could also be a setting)
- Search in contact list (use number keys, requires sorted contacts)
- Hold SK2 in contact list to display contact details

Todo:
- some more refactoring
- more error checking
- voice prompts
- make sort and search case insensitive

To enable sorting I added the contact names to the contactCache. This requires 16KB more RAM. There is still  ~13KB free in  upper ram.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Why are you always checking 1024 contacts 

```
-- for (i = 0; i < numContacts; i++)
//	int lastIndex = 0;
++	for (i = 0; i < 1024; i++)
```

When searching for contacts, this could be very ineffecient for most people who only have a few contacts (I only have 16 contacts)

Why can't you use numContacts ??

**Comment by alexernst** [comment]
Changed that already local, but didn't update the branch. I will update the PR later, including voice prompts for 'Edit contact' screen, case-insensitive sort and search and some more fixes.

I loaded 1024 contacts and sort and search did perform well. But as it's a sorted list I will change the search algorithm to be the same as used for the DMR Ids.

But which one is better: seperated lists for TG and PC or one list for all?

**Comment by rogerclarkmelbourne** [comment]
>But which one is better: seperated lists for TG and PC or one list for all?

I don't know. 

I probably depends on the mix of TG and PC in the individual operator' codeplug

**Comment by alexernst** [comment]
I will make it a setting under 'Display options'. 

Adding a new option to 'Display options' requires changes to the voice prompt files?

**Comment by rogerclarkmelbourne** [comment]
I think that may make things too difficult for many of the users

**Comment by zzigi4859** [comment]
Hello, thank you in advance for the AWESOME work regarding the firmware and CPS.

My name is Ivan and I'm from the Czech Republic and my English is not good, I'm sorry.

I would have a few suggestions for improving the firmware or CPS:

- in the item contact sheet to make a division into:
TG list DMR
private list DMR
contact list DTMF
new DMR contact
favorite DMR contact
enter number - enter the radio station number - enter the DTMF number

For a private contact - if I want to dial it, the function is missing
- alert call
- station verification
- eavesdropping
- unlock the station
- block the station

Add the item DTMF list to the menu - it will be used for the possibility of dialing the DTMF number for access to the Echolink network - many converters are - it has the possibility of connection to the Echolink network not only in analog, but also in digital DMR.

Possibility to assign functions via a radio menu or CPS to a long press of the buttons - blue, black and orange. It is a pity to leave it unused.

Solve S-METER better graphically than just a line - on the basic screen not for example:

S1 .......... S3 .......... S5 ......... S7 ......... S9 / -128dBm /

the dbm value will then be shown at the end of the S-meter
- it is not necessary to switch to the signal strength item in the menu
The item in the signal strength menu will be retained, for example even expanded frankly?

I would separate the upper segment of the display, where the icons are, with a line

SCAN CTCSS AND DCS would be divided into separate items:
SCAN CTCSS
SCAN DCS

Resolve the following issue:

If a radio converter is not available and I turn on the function without a talker on another radio station - I talk in DMR, then the TYT-MD760 radio station, if it has different frequencies on the programmed channel or VFO, hears this operation, shows TG and ID radio stations there is no sound from the speaker.

The frequencies must be set the same, then the sound goes to the speaker.

Please fix this matter.

Thank you very much and I wish you many more successes in programming firmware and CPS.

**Comment by zzigi4859** [comment]
Resolve the following issue:

//Talk Around FUNKC//

If a radio converter is not available and I turn on the function without a talker on another radio station - I talk in DMR, then the TYT-MD760 radio station, if it has different frequencies on the programmed channel or VFO, hears this operation, shows TG and ID radio stations there is no sound from the speaker.
the frequencies must be set the same, then the sound goes to the speaker.

Please fix this matter.

**Comment by rogerclarkmelbourne** [comment]
@ zzigi4859 

This is a PR you have posted to not an issue.

**Comment by alexernst** [comment]
I think you can close this PR as it is no longer mergable.

**Comment by rogerclarkmelbourne** [comment]
OK. I'll close it

**Pull request closed without merging**
