### PR TITLE
Move Scan Mode setting to Options Menu. 

### PR DESCRIPTION
**Pull request by g4eml**
New Non Volatile setting for scan mode in options menu.
Revert Scan activation back to single selection in Quick Menu
Add three new strings in language files. (these will need to be translated)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin

BTW. I think something has gone wrong when you edited the language files.

You can't edit them using an editor set to UTF8 as the accented characters are ANSI codepage.

Daniel said he was now using Emacs on linux and I'm using Notepad++

See https://github.com/rogerclarkmelbourne/OpenGD77/wiki/Language-translations

I think I'll need to do a manual merge and update the language files myself to retain the accent characters

**Comment by rogerclarkmelbourne** [comment]
Thanks

I fixed the language file problems and also put in some additional comments into the language files

**Comment by g4eml** [comment]
Hi Roger, 

Sorry, I am just using MCUXpresso for the editing. I didn’t realise that wouldn’t work. 

Language files might be a good idea but they are a bit of a pain to work with, especially with a lot of updates going on. 

73 
Colin.

**Comment by rogerclarkmelbourne** [comment]
Colin

This is my fault.

I should have documented that its not possible to edit this in MCUExpresso

It only came to light yesterday, and I did update the Wiki but didnt alert everyone.

**Pull request merged**
