### PR TITLE
Typedef and uc1701 rename

### PR DESCRIPTION
**Pull request by f1rmb**
Rename uiEvent*_t, UC1701_ functions and font/alignments/choices.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Wow.

I think I will need to test this a lot

**Comment by f1rmb** [comment]
Hi Roger,

😉 I tested a lot already, but error is possible (but I doubt, I use find
and sed for many of them, only the UC1701 related stuff has been done by
end, but ton of compilation failures, on purpose) 😁

Cheers.

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
Tested on most screens and it seems OK. So I have merged.

**Comment by f1rmb** [comment]
Nice ! Thank you Roger.

**Pull request merged**
