### PR TITLE
Fix RED and GREEN in FWinfo and Battery menus.

### PR DESCRIPTION
**Pull request by f1rmb**
Change KEYCHECK_PRESS to KEYCHECK_SHORTUP for GREEN in RED in battery and FWinfo menus.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I didn't notice the problem on those menus.

**Comment by f1rmb** [comment]
Me neither, it's just by accident, playing with the menus ;-)

**Comment by rogerclarkmelbourne** [comment]
LOL

OK.

I'll try merging the audio-assist branch

**Comment by f1rmb** [comment]
Okay.
Yeah, most of the time I use long RED to exit.

**Pull request merged**
