### PR TITLE
Implement DMRIDs pseudo cache.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Does this PR supersede the other PR (are they combined) or does the other PR need to be be pulled first ?

**Comment by f1rmb** [comment]
Hi Roger,

   Unlike what github displays here (the commits in contact_display_priority_merged branch), the two PRs are independants.

BTW, how could I know when DMRIDs flashing is done, I looked at fw_usb_com.c, but it's not clear to me.

Cheers.

**Comment by f1rmb** [comment]
About is it necessary to pull the other first, I don't know if it will produce some merge conflicts. Lemme check.

**Comment by f1rmb** [comment]
Hold on a sec. What is this...

**Comment by rogerclarkmelbourne** [comment]
DMR ID flashing is not a special function, its just CPS Write to Flash, at the address of the DMR ID

**Comment by f1rmb** [comment]
Yes, I see (Write command == 3, with some address offset), but is there a way to know when it's done.

**Comment by rogerclarkmelbourne** [comment]
This is not specific to the DMR ID, but I send Command 5 when the DMR ID upload is complete.

**Comment by f1rmb** [comment]
Okay. Thanks.

**Comment by f1rmb** [comment]
Okay, commit history looks fixed now.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by f1rmb** [comment]
Just pushed the merge conflict fix.

**Comment by rogerclarkmelbourne** [comment]
Umm

I've also fixed the merge conflict

Can you check my Master, I it compiles OK, so I think its OK.

**Comment by f1rmb** [comment]
Looks fine and it compiles.

**Comment by f1rmb** [comment]
Closing as it's merged now. Thanks Roger.

**Comment by rogerclarkmelbourne** [comment]
OK

I will test it for a while and also possibly send to some of the beta testers, before I make a new 'latest' version

**Comment by f1rmb** [comment]
Okay.

**Pull request closed without merging**
