### PR TITLE
rename uiEvent_t to ui_event_input_t enum.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
From a style point of view I'd prefer

`uiEventInput_t`

or perhaps 

`uiInputEvent_t`

I'm not sure if it would be possible to have a UI output event so the "input" part seems redundant 

AFIK this can be generated by both buttons and keys, hence why I didn't call it uiKeyEvent or uiButtonEvent

I guess it could be called uiButtonAndKeyEvent_t 

What did you not like about uiEvent_t ?

**Comment by f1rmb** [comment]
Héhé,

   Well, It's not that I don't like it, it's mostly there is no real rules about type naming shame.
We have some struct_x_t, myType_t, my_type_t. I would vote to have  one style only, whatever it is ;-)

Tell me what you prefer, and I can change that for the whole UI related parts (I won't touch with a ten-foot pole low level API).

Cheers.

**Comment by rogerclarkmelbourne** [comment]
My personal preference is for camel case.

However I think Kai must have preferred underlines as we still have some function names which have underscores in them and also some variable names.

Ask Alex, but looking at his code e.g. for the menuContactsList, I think perhaps either he normally uses Camel Case or possibly he is just following what I was using.

Also, because the project is in C and not C++, and we don't have classes to name the functionality, I started to name the functions for specific sections of the code with the section name .

e.g. codeplugZonesGetCount()

But there is still a large amount of unconsistency of the naming, which should be corrected, as long as it does not break the firmware ;-)

I don't see any point in the filenames prepended with fw_   as its all firmware, so that part of the name is redundant.

Also, there are some parts of the code which are not not really in the correct file.

e.g. fw_i2c.c has some functions in it which are specific to the AT1846S and are not used by the EEPROM even though it is on the same I2C bus.

This is a legacy from when Kai originally wrote the code and was not using the EEPROM

So the functions like

write_I2C_reg_2byte() which are only use by the AT1846, should be moved into the AT1846 C file and renamed accordingly and also made static.


Likewise some of the functions in fw_spi.c are actually only used by the HR-C6000 and should probably be moved into that file and renamed


BTW. I probably made a mistake by putting the language header files not in the include tree.

I'm also not sure of the benefit of adding include paths to the overall project, as that can cause problems, hence for the menu includes more of the path needs to be specified.

Though there may or may not be a perfect solution to the includes, so perhaps its better not to mess things up too much at the moment ;-)


Also. In terms of code cleaning, the way the C6000 registers are individually setup in HR-C6000 is inefficient, because most of the register initialisation, could be put into arrays.

Some of it is already in arrays, but a lot of it is not.

I'm sure you have also seen some things which are not perfect..

I hope that all makes sense and is logical

**Comment by alexernst** [comment]
Indeed I prefer CamelCase. 
I don't think we should refactor too much just to refactor. But if something is changed because of bug fixing or new features, and has 'wrong' naming scheme, that's the opportunity to also fix the names.

It's the same with files or functions that are at the wrong folder. Move it when the file is touched.

**Comment by f1rmb** [comment]
Okay, I agree.
   About the function naming, I think it should be done before the code become too large, even if that introduce large PRs.

   I also prefer CamelCase, so, I'll make few changes in typedefed structs/enums.


Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll close this PR.

**Pull request closed without merging**
