### PR TITLE
Contact screen added

### PR DESCRIPTION
**Pull request by alexernst**
This adds a submenu 'Contacts' in the main menu.

Contact List:
- SK2 + HASH shows Contact List in Channel and VFO mode
- switch between TG and PC with HASH

Manual Dial opens uiTxTgPcContactOwnId.
- still available with HASH in Channel and VFO mode

New Contact is without function at the moment.

If this works next is to remove Contacts from uiTxTgPcContactOwnId.c and implement 'New Contact'

Maybe 'Contacts' and 'Last Heard' should be moved above 'Zone' so it's easy selectable.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'll look at this in the next hour

**Comment by rogerclarkmelbourne** [comment]
Alex
Was there a reason to have separate defines for 

`CONTACT_CALLTYPE_TG`;
and
`CODEPLUG_CALLTYPE_TG`

I think I can just add CONTACT_CALLTYPE_ALL  to make

`enum CONTACT_CALLTYPE_SELECT { CONTACT_CALLTYPE_TG=0, CONTACT_CALLTYPE_PC, CONTACT_CALLTYPE_ALL }`;

Then I can remove

```
#define CODEPLUG_CALLTYPE_TG  0
#define CODEPLUG_CALLTYPE_PC  1
#define CODEPLUG_CALLTYPE_ALL 
```

??

**Comment by rogerclarkmelbourne** [comment]
I think probably "Manual Dial" is not needed, and the name may be confusing, because Manual DIal on the official firmware is only for PC.

**Comment by alexernst** [comment]
Yes, the defines are duplicates. I started with them, added the enum later and didn't delete them.

I used the entry from menuStringtable[] which already contains 'Manual Dial'. It's a link to uiTxTgPcContactOwnId so not absolutely needed. I would suggest rename to 'Manual Entry'  and keep as an extra way.

BTW: I want to extend the Contact List to allow editing. But pressing GREEN on a contact is used to set the override TG/PC. I'm thinking about using RIGHT to select contact details. But I'm not sure about this.

**Comment by rogerclarkmelbourne** [comment]
Ok

The define for TG was used in one place but I removed it

I also noticed the new function and assumed it was for future use.

Re: Manual dial menu

I added those items when I initially created the menu system, but the have now been superseded by the newer functionality 

I will remove them and then merge you PR.

But it’s too late for me to do this tonight. I will do it tomorrow morning

**Comment by rogerclarkmelbourne** [comment]
I made some temporary changes

I hid removed the New Contact and Manual Dial and replaced with empty text.
But as my menu system can't handle less than 3 items per menu, I had to assign those 2 empty entries to the Contacts screen.

In the future we may need to modify the menu system to handle when there less than 3 items in the menu. 
But I don't have time to do that now, as I have other PR's to merge, which are higher priority for the project

Everything else is OK ;-)

**Comment by rogerclarkmelbourne** [comment]
@alexernst 

FYI

Someone noticed that the Channel Details menu item was missing

I found and fixed the bug. 

Its because you added a new menu item, but didnt increase the number of menu items

https://github.com/rogerclarkmelbourne/OpenGD77/pull/96/files#diff-54f69ff5dc65f2af867019d03f049fa0

Number of menu items is the first item in the list

I just did a fix to increase the number from 9 to 10.

https://github.com/rogerclarkmelbourne/OpenGD77/commit/7b0a786495bfe59395d4f6820b8cd16dda165c9a

There may be a better way to handle this, so that the number does not need to be defined, perhaps a sizeof() in the code somewhere

**Comment by f1rmb** [comment]
I didn't check, but i've made some changes that permits less than 3 entries.

Cheers

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
Daniel

Thanks...

**Pull request merged**
