### PR TITLE
Add emacs header to keep right encoding (edition is utf-8, but file is saved with right coding)

### PR DESCRIPTION
**Pull request by f1rmb**
Quite useful to not care anymore while editing these files (at least with emacs).

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel 
Is this an automatic thing which fixes the problem or just a comment ?

When I was merging Colins Scan PR, I had to fix the problems cause by editing to add the new texts so I took the opportunity to add comments warning that the text must not be edited in MCUExpresso

**Comment by f1rmb** [comment]
Roger,
   Yeah, I saw the PR, and the accents problem.
Yes, this is a fix, which works for emacs (you can configure a lot of things with such comments, that are parsed by it).

**Comment by rogerclarkmelbourne** [comment]
OK

I'm getting a merge conflict now for german.

But I can manually merge

**Comment by rogerclarkmelbourne** [comment]
BTW.
I'm trying to keep the formatting of these files identical, so I can check for differences just be checking the number of lines in the file.

i.e So I can see if a file is missing some new texts

**Comment by alexernst** [comment]
BTW:

In MCUXpresso you can set the text encoding for the folder <code>language</code> to ISO-8859-1. 
<code>languages -> right click: Properties -> Ressource </code>
Set text file encoding from 'Inherited from...' to 'Other ISO-8859-1'.
The setting is saved under <code>firmware/.settings/org.eclipse.core.resources.prefs</code> but the <code>.settings</code> folder is in <code>.gitignore</code>, which seems to be best practice.

I think that should enable editing the language files in MCUXpresso.

**Comment by rogerclarkmelbourne** [comment]
I think Alex's suggestion supersedes as MCUExpresso seems to edit it OK if the encoding is set via the "Resource" property in MCUExpresso

**Comment by alexernst** [comment]
Somehow me comment is gone ??

So in MCUXpresso it is possible to set the text file encoding for folder <code>languages</code> to <code>ISO-8859-1</code> with Right-click on <code>languages</code> -> Properties.

But ISO-8859-1 is not exactly windows-1252. The characters 128-159 are not used in ISO-8859-1 but in windows-1252.

**Comment by rogerclarkmelbourne** [comment]
Ah.

Also,  the .cproject file does not seem to change when I modify this setting

**Comment by alexernst** [comment]
No, it's a file in .settings, org. eclipse.resources.prefs I think.
But .settings is in .gitignore and that seems to be best practice. Perhaps we should include that single file in git.

**Comment by rogerclarkmelbourne** [comment]
I've manually added the header.

**Pull request closed without merging**
