### PR TITLE
PTT toggle label translated

### PR DESCRIPTION
**Pull request by EA3BIL**
PTT toggle label translated.
No further modifications as far as I see right now.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
There is something wrong with this file, perhaps the encoding or the line end types, but Github won't auto merge this file

**Comment by EA3BIL** [comment]
Oky...

Will check the file and PR again.

Thanks for the advice !

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by EA3BIL** [comment]
I hope it works now.

**Comment by rogerclarkmelbourne** [comment]
Its still showing a conflict on every line.

I'll try pulling and manually editing the file to just use the new data

**Comment by EA3BIL** [comment]
Oky…

 

De: Roger Clark <notifications@github.com> 
Enviado el: viernes, 3 de enero de 2020 0:43
Para: rogerclarkmelbourne/OpenGD77 <OpenGD77@noreply.github.com>
CC: EA3BIL <ea3bil@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [rogerclarkmelbourne/OpenGD77] PTT toggle label translated (#316)

 

Its still showing a conflict on every line.

I'll try pulling and manually editing the file to just use the new data

**Comment by rogerclarkmelbourne** [comment]
I've manually copied the 3 lines which were changed in your catalan file into my local copy.

See.
https://github.com/rogerclarkmelbourne/OpenGD77/commit/eaa352ffbdbaad03a5c2cf6bed785b579ef70fb0

It looks like the only text which was actually different is the line for .ptt_toggle

**Comment by EA3BIL** [comment]
Yes, that was the only change.
I really don't know what what was wrong on #316 and why it shown those
problem.

Anyway,
Thanks for help !!.

**Comment by rogerclarkmelbourne** [comment]
No worries...

**Comment by EA3BIL** [comment]
BTW...

I'm currently working in a OpenGD77 Simulator to be used at colleagues
explanation about the FW.

This will allow to have the "walkie on a big sreen" to see what does it do
every single keystroke and the information should be showing on GD77's lcd.


(As soon as I have the laptop back to live after reinstalling Ubuntu &
Potatoe 10 Pro 64b).



Cheers,
Rafa.

**Pull request closed without merging**
