### PR TITLE
RX Frequency and Offset footer

### PR DESCRIPTION
**Pull request by ajorg**
When using channels I often want to know what frequency and offset are in use. This is especially important when multiple channels have the same name (there are maybe 7 repeaters in the Seatle area with the callsign "WW7SEA").

This shifts the channel number / zone name field up two pixels and adds a footer displaying the RX frequency and the positive or negative offset (if there is one). The result is a little information dense, but I don't think it's overwhelming. I trim the numbers so that unnecessary zeros on the ends of things aren't there. For example it would display `146.96 -0.6` or `440.625 +5.0`.

rxfreq

It displays correctly when the offset is less than 0.1, when it's positive and when it's negative, etc.. I also put the frequency and offset formatting in a utility function so that it could be used elsewhere if desired and changed in only one place if needed.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'll take a look

**Comment by rogerclarkmelbourne** [comment]
How did you manage to have multiple channels with the same name.

As far as I can tell the CPS does not allow channels to have the same name

**Comment by ajorg** [comment]
> How did you manage to have multiple channels with the same name.

I use [Colin's CSV tool](http://www.gb3gf.co.uk/Files/GD77-CSV.zip) to shove the entire regional coordination database into my codeplug.

I've actually got many channels that have exactly the same names, even though I also add the location name to the channel name. So I've got 3 that have "WW7SEA Seattle" and 4 that say "W7ACS Seattle", among many others.

**Comment by rogerclarkmelbourne** [comment]
Umm.

This change is very specific to you, as the CPS does not really support it.

**Comment by rogerclarkmelbourne** [comment]
I'll mention to Colin that his tool allows this, as it may be an unintentional bug

**Comment by ajorg** [comment]
It doesn't seem to me to be a bug. The radio firmware doesn't care if multiple channels have the same name, does it? I imagine the only reason the CPS cares is that it becomes hard (same as here) to tell which is which when setting up zones. I'd much rather change the CPS so that it shows the channel details when you hover over a name or something like that than have to create custom names for all of these channels that have the same name.

**Comment by ajorg** [comment]
> This change is very specific to you, as the CPS does not really support it.

As to that, it's very useful information, even when your names are unique (I still would have written it).

If you have a lot of channels (I have 300+) it's _very_ helpful to be able to see what frequency you're on at a glance. For example some repeaters are known more commonly by their frequency than by their callsign. If I'm browsing through my channels for the `.96` repeater that I recall has a frequency of `146.96` and my channels are ordered by frequency, then I know I'm getting closer to the right channel when the frequency is getting closer.

It's unused space at the bottom of the display. Were there other plans for what might go there? I'm happy to put it behind some option if it's something you think you'd rather not have on your radio.

**Comment by rogerclarkmelbourne** [comment]
image

image


Although this text does fit on the screen, I don't think what its displaying is clear

e.g. mine is displaying "439.5-5.0"

I'd need to get some feedback from the forum about whether people want this extra information on the screen and if so , in what format and what location.

e.g. the text could be centered and also include the Mhz and put brackets around the offset 

However, it would still need positive feedback.  As this could end

**Comment by ajorg** [comment]
I agree some feedback is merited. I'm assuming you were about to write that it could end in confusion for some users. I've posted [a feedback thread](http://opengd77.com/viewtopic.php?f=7&t=215&sid=105c7cce83a110d941a11b40c9f79af8).

**Comment by f1rmb** [comment]
What about that: use a key (e.g. Black button) to temporary display RX/TX grep and memory #. When the key is released, return to "normal" channel display.
Or, define a key to toggle display mode while in channel mode.

Some Ham HT use that kind of feature.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
@f1rmb 

Yes. Thats possible.

I was hoping that the Black button could ultimately be user definable, but I will need to modify the CPS so that it lists the possible uses for the Black button.
Which could include it being context sensitive , i.e on the Channel screen it does something different to on other screens.

With the changes to 80 channels per zone it looks like I will need a separate version of the CPS for the OpenGD77, which will make the assignment of the Black button functionality possible.

**Comment by f1rmb** [comment]
> @f1rmb
> 
> Yes. Thats possible.
> 
> I was hoping that the Black button could ultimately be user definable, but I will need to modify the CPS so that it lists the possible uses for the Black button.
> Which could include it being context sensitive , i.e on the Channel screen it does something different to on other screens.

Yeah, whatever. I just tell about the Black button as an example, but that could be another one of the keypad. If it's temporary, that's fine IMHO, if it's a toggle, a key combination or a long press is fine.


> 
> With the changes to 80 channels per zone it looks like I will need a separate version of the CPS for the OpenGD77, which will make the assignment of the Black button functionality possible.

Okay. But as I told above, that was just for the idea of the temporary display mode. And I totally understand the idea to keep the Black button for other (undefined yet) purpose.

Cheers.
---
Daniel

**Comment by ajorg** [comment]
I rebased and made some minor cosmetic changes: added a space before the offset and shifted right by 6 pixels. I considered centering, but I want to leave space on the right for something else, like the TX CTCSS tone.

**Comment by rogerclarkmelbourne** [comment]
I'm going to close this at the moment, as there seems to be very little interest from forum members about it.
Only one or two responses.

**Comment by ajorg** [comment]
I can keep my local branch meanwhile I guess. Thanks anyway.

**Pull request closed without merging**
