### PR TITLE
Add quick functions on Blue+<NUMBER>

### PR DESCRIPTION
**Pull request by alexernst**
Each function is represented as an uint16_t. If bits 15:8 contain a menu number >0 from MENU_SCREENS this menu screen is opened. 

The lower 8 bits code the function. This value is added to uiEvent_t as .function and FUNCTION_EVENT is set in .event.
These functions need to be implemented in handleEvent() functions.

To implement user changeable functions some changes to the CPS are required.

Following functions are hardcoded in the source for now, so they are more samples for testing. 

Blue+1: Start scanning - only in channel mode
Blue+2: Jump to Battery screen
Blue+3: Jump to Last Heard screen
Blue+4: Jump to Channel Details screen, CC setting
Blue+7: decrease brightness
Blue+8: increase brightness

Also added is support for short and long pressing buttons ORANGE and SK1.
This is done by adding ORANGE and SK1 as extra keys (KEY_ORANGE, KEY_SK1) to the keypad functions. 

As a sample/testing:
long press ORANGE: start scanning   (this should also be user definable in the CPS)

### CODE REVIEW

**Comment by na7q** [comment]
How about Blue + 0 for scanning? I know some folks with broken Orange buttons. Would make a good alternative if 0 is not currently being used.

**Comment by alexernst** [comment]
These functions are only for testing. 
After the CPS is modified the functions and keys will be changeable.

Look at Blue+1 above :-)

**Comment by na7q** [comment]
Apparently I can't read in the early mornings! Ha. Thanks. You are doing great work here.

**Comment by rogerclarkmelbourne** [comment]
Function + Green already goes to Channel Details screen, but we could now remove that function

**Comment by alexernst** [comment]
Blue+4 jumps not only to the channel details, but also to the entry for CC. 
I don't know how complicated it is to change the lists in the CPS, as these functions should be read from codeplug.

BTW: 
This will conflict with Daniels Last Heard PR as he also changed the uiEvent_t. I will fix that after you merged #341.

**Comment by rogerclarkmelbourne** [comment]
I will merge this before Daniel's Last Heard, because I think the Last Heard requires some changes.

**Comment by rogerclarkmelbourne** [comment]
Thanks.  I think perhaps the key association may need to be changed in the future, but I think the feature to directly change things like the brightness is excellent

**Comment by f1rmb** [comment]
This works nicely.
One suggestion would be about default (current) shortcut assign. I think it would more human friendly to use one of the letter as a reminder, like <BLUE>+L (5)for Last head, <BLUE>+B (2) for Battery, <BLUE>+S (7) for Scan, etc.

**Comment by alexernst** [comment]
The association between key and function was more for testing.

**Comment by f1rmb** [comment]
Yes No problem. It was just a suggestion for the default mapping and to get your feedback.

**Pull request merged**
