### PR TITLE
Hotspot fine tunning

### PR DESCRIPTION
**Pull request by f1rmb**
There is small changes, MMDVMHost related + HS FW display on SK1.
I'm waiting for the reports about BlueDV problems.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Do you want me to merge this now or wait for BlueDV bug reports ?

**Comment by f1rmb** [comment]
Hi Roger,

   Well, I think I will make another PR for BlueDV.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
Tested and seems to be OK...

**Comment by f1rmb** [comment]
Thanks Roger

**Pull request merged**
