### PR TITLE
firmware and backup docs

### PR DESCRIPTION
**Pull request by Neon22**
images and minor text change

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'm not sure the text change is correct.

Is it referring to updating the firmware ?

**Comment by Neon22** [comment]
Specifically the text says:

> 1. A Firmware upgrade. Get the radio into dfu mode by:
> 
>-  Holding down the two buttons indicated below and turning the radio on.
>-  The LCD screen will be blank.
> - Connection will use the HID codes and a driver is not required to be installed.
>   -  Radioddity GD-77 or 77s or the TYT MD-760 or 730:
>      - Hold down the two small Blue and Black buttons under the PTT button.
>      - Some variants have no Blue button. It will also be Black.
>  -  Baofeng DM-1801 or DM-860:
>     -  Hold down the two small Black buttons under the PTT button.
>  - Baofeng RD-5R or RD-5R Tier2:
>     - The Orange Call and Black PTT buttons.

Followed by the image of the three radios side by side

**Comment by f1rmb** [comment]
BTW, I just noticed a typo about the RD-5R, as it's not the Black PTT button, but the Black MONI button ;-)

**Comment by Neon22** [comment]
Oh is it ?
So the MONI or Monitor button - is that the one  marked S1 ?
Because we call it S1 or SK1 in the rest of the manual - presumably to avoid having to repeat the special RD-5R naming everywhere...

**Comment by f1rmb** [comment]
No,

   SK1 is the button above the PTT, and SK2 is below PTT. I didn't checked the pictures yet.

**Comment by f1rmb** [comment]
So, on the picture, S1 is SK1, and Fn is SK2

**Comment by f1rmb** [comment]
On my RD-5R the SK1 button has "CALL" engraved.

**Comment by Neon22** [comment]
@f1rmb Thanks for the clarity.
@rogerclarkmelbourne I will add firmware text to the image of the radios. Hopefully this, and the existing text near the image will do the job.
Else please let me know :)

This will require me cleaning up the files and closing this PR and submitting a new one. I will encapsulate the discussion in eth submission notes of the new PR.

**Comment by rogerclarkmelbourne** [comment]
OK.

No rush, I am very busy at the moment, so don't have much time to update things.

I'll close this PR.

Resubmit when  the update is ready

Thanks

**Pull request closed without merging**
