### PR TITLE
GD77S fixes

### PR DESCRIPTION
**Pull request by f1rmb**
Hi,

  It's the PR of the day, but unfinished yet ;-)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Why did you set the Tx beeps to Start and Stop on the GD77S ?

**Comment by rogerclarkmelbourne** [comment]
Also.

What was the problem with the sgl file length ?

**Comment by f1rmb** [comment]
> Why did you set the Tx beeps to Start and Stop on the GD77S ?

Hi Roger,

    Well, just to have a small feedback, as I think users will want to have tthat because of external mic usage. I can remove this if you want.

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
> Also.
> 
> What was the problem with the sgl file length ?

My bet is, the firmware binary was cropped on bin2sgl stage (up to 327681 bytes for the firmware), as the .bin was large as the one created when compiling for GD-77 (487424 bytes), probably because of the linker script memory mapping.

**Comment by rogerclarkmelbourne** [comment]
OK.

Neither of these is a problem.

No need to create another PR.

**Pull request merged**
