### PR TITLE
While CC scan is running, "Color Code #" is displayed at Contact location, 

### PR DESCRIPTION
**Pull request by f1rmb**
and all infos are moved down by one row. Tx info is hidden.
Any user key event stops the scan (as before), and screen redrawn with default layout.

GD-77_screengrab-2019-12-23_04_47_36
The scrambled header line is due to scanning while screen grabbing.

This PR may conflit with the one related to VFO A/B changes.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
There do not seem to be any merge conflicts

**Comment by rogerclarkmelbourne** [comment]
I need to push some local changes, and then I'll try merging locally

**Comment by f1rmb** [comment]
Yes, it seems not, but since same code are changed, I was afraid that did happen.

**Comment by rogerclarkmelbourne** [comment]
Ah

This now has a merge conflict :-(

**Comment by f1rmb** [comment]
Okay, lemme fix this, and move the vfo markers + offset the freq by 4 pixels.

**Comment by rogerclarkmelbourne** [comment]
OK.

BTW. Did you get my email ?

**Comment by f1rmb** [comment]
Okay, merge conflict fixed, and all stuff has been moved.
GD-77_screengrab-2019-12-23_06_03_38

Yes, but I just had time to read it ;-)

**Comment by f1rmb** [comment]
Hold on a second, I will factorize that a little bit...

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by f1rmb** [comment]
Okay, slightly better ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks

BTW. There is one pre-existing bug with the CC and Tone scan.

If the Red button is pressed to terminate the scan it also changes from VFO mode to Channel mode.

**Comment by f1rmb** [comment]
Yes, I noticed that too.
Humm, could be easy to fix, give me a second ;-)

**Comment by f1rmb** [comment]
LOL, it will take more time, there is something odd with this.

**Pull request merged**
