### PR TITLE
update language finnish and rx ctcss issue resolve

### PR DESCRIPTION
**Pull request by riku2015**
this will fix rx ctcss issue mentioned on https://www.opengd77.com/viewtopic.php?f=11&t=794&start=40
Its a small change to code, been testing it now couple months. code lines is well documentaded to understand what they do.
also updated finnish language fix

### CODE REVIEW

**Comment by f1rmb** [comment]
Your translation file is bad (see the <<<<<<< HEAD / ====== / >>>>>> lines).

**Comment by rogerclarkmelbourne** [comment]
Also. I think people already tried your CTCSS changes and they break other things.

**Comment by rogerclarkmelbourne** [comment]
Please describe what bug the changes to CTCSS are to fix and how to replicate the bug and also how to confirm that these changes cause no other problems.

**Comment by rogerclarkmelbourne** [comment]
closing as no reply from the OP to both questions.

Please re-open when issues with this PR have been resolved

**Comment by riku2015** [comment]
Hi, Roger. nice to have your attention on this issue. there is others also having this one, it has been there long time now, would be nice to have finally this resolved.

here is a short video describing how to replicate the bug with 2x gd77 radios. you need to talk VERY LOUD(very important, put your mouth on the radio very close until you really touch it with your lips, and talk very very loud) to have this happening and use ctcss on both radios. https://youtu.be/VEudaakpI08 There is other people also managed to replicate this, our ham club members has more than 10x gd77 radios from different eras, all of them doing this problem. 

**The "bugfix" described, this is only change on code. this should not break anything in theory, have been using it now a couple months without issues. maybe add it on testing version and see if someone has problems with it?:**
				trx_ctcc_measure_count++;
				if (trx_ctcc_measure_count==100){	// **add squelch close delay when using ctcss to avoid breaking ups on high deviation**
					disableAudioAmp(AUDIO_AMP_MODE_RF);
					trx_ctcc_measure_count=0;
				}
				if (!rxCSSactive){			// **when not using rx ctcss will close faster squelch**
					disableAudioAmp(AUDIO_AMP_MODE_RF);
					trx_ctcc_measure_count=0;
				}
				if(trxRxNoise > squelch){		// **last resort squelch closing, when there no signal. this fixes above squelch tail when use ctcss**
					disableAudioAmp(AUDIO_AMP_MODE_RF);
					trx_ctcc_measure_count=0;
				}

that last resort line will avoid create another bugs. 
This code will add a small delay when receiving ctcss, in theory you can still get the bug when high modulate over that delay, but for normal talking it is sufficient.

**Comment by jfml2020** [comment]
I leave a video with my problem too, the radio was one of the first they made: https://youtu.be/uhMo_mXPdgA

**Comment by rayslinky** [comment]
I'm also seeing this issue, can you resubmit the patch? Both videos match up with my experience.

**Comment by rogerclarkmelbourne** [comment]
@rayslinky 

Ideally you should verify whether this patch actually fixes your bug.

I don't add speculative patches that could potentially fix problems as potentially they could break things for other people

I also can't accept patches for problems which I can't replicate, (for the same reason).

**Comment by rayslinky** [comment]
I have applied this patch and can confirm it resolves my issue.

**Comment by jfml2020** [comment]
> I have applied this patch and can confirm it resolves my issue.
> 
> I'm happy to resubmit it as a stand alone PR.

could you send me ? is it complicated to add? Thank you

**Comment by f1rmb** [comment]
From what I could hear in this (too) short video looks more like an over-deviation than anything else.
You have also to bear in mind that a patch that try to circumvent a specific external problem won't be applied.

**Comment by rogerclarkmelbourne** [comment]
The patch also seems to remove some voice prompt functionality

The patch seems to always add a 100mS of unsquelched hiss at the end of every transmission when CTCSS or DCS is enabled, regardless of whether the signal is overdeviated or not.

The patch code is inefficient, the first check should probably be for (!rxCSSactive || trxRxNoise > squelch)  and the other code should be in an else statement.

Overall the patch appears to be at best work-around and not really a solution.

**Comment by rayslinky** [comment]
I applied this patch and while it does work around the issue, I did notice some clicking/popping that I hadn't noticed before. I flashed back to the stable 08.01 and unstable 08.04 versions and I hear it there too, but it is less pronounced. When I remove DCS from the channel, I still notice it (again less pronounced than with the patch), so I suspect something somewhere else in the stack for my case.

**Pull request closed without merging**
