### PR TITLE
Don't mess with talkerAlias buffer directly.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
Don't merge it yet, I stumbled on something...

**Comment by rogerclarkmelbourne** [comment]
Its OK.

I'm still trying to fix the scanning crash bug ..

**Comment by f1rmb** [comment]
Okay.

**Comment by f1rmb** [comment]
I'm tracing the TA from BM, and sometimes there is crap inside...

**Comment by rogerclarkmelbourne** [comment]
aarrgghh

BTW. I've committed some changes to the I2C code with debugging in it, so that if it goes wrong I may be able to see if its a bus clash even if I don't have any breakpoints enabled.

Currently the scanning is not crashing for me, but I don't know why its not crashing, as I didn't add any code to fix it !

**Comment by rogerclarkmelbourne** [comment]
But its time for me to stop now as its 10pm

**Comment by f1rmb** [comment]
Okay, good night Roger (i'm still tracing TA).

**Comment by f1rmb** [comment]
It seems, sometimes, TA BLOCK2(0x06) and BLOCK3(0x07) are dropped. BLOCK3(0x07) everytime...

HEADER(0x04) and BLOCK1(0x05) are always part of the TalkerAlias.

**Comment by rogerclarkmelbourne** [comment]
Ok.
Is it ok to pull and merge this ?

**Comment by f1rmb** [comment]
Hi Roger,

Yes.

**Comment by rogerclarkmelbourne** [comment]
Thanks
I've now tested and merged

**Pull request merged**
