### PR TITLE
CWID: set 360ms of silence at the begenning of CW sequence (instead o…

### PR DESCRIPTION
**Pull request by f1rmb**
…f 180ms). Use Tx delay value from MMDVMHost (default in Pi-Star is 100ms), and this before keying CW sequence.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
Daniel

I have merged this, but I noticed a bug which I think was in the CW ID before this change

Sometimes. The first time the CW ID is keyed, there is a beep of a different frequency before the CW ID starts.

The next CW ID etc plays OK.

**Comment by f1rmb** [comment]
Ah ah. I was wondering it it could be possible. So yes. Hold on a sec ;-)

**Comment by rogerclarkmelbourne** [comment]
ok

**Pull request merged**
