### PR TITLE
Edit contact and channel names

### PR DESCRIPTION
**Pull request by alexernst**
In the contactDetails and channelDetails screens the names can be changed.
- Keys 0 to 9 are used for characters. I took the key-binding from the GD-77 manual.
- Left and Right to move cursor
- Blue+Left deletes character
- Blue+Right inserts space

I added three functions to <code>menuSystem.c</code> that might be better placed in an extra file like <code>uiUtilityInput.c</code> or <code>uiUtilityForms.c</code>.

Also I changed the type for the keycode from <code>uint32_t</code> to a new <code>struct keyboardCode_t</code>.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex

This has a merge conflict with fw_main.c

I will try to resolve them.

**Comment by alexernst** [comment]
Yupp, take the master version and set .keys=NO_KEYCODE in line 66

**Comment by rogerclarkmelbourne** [comment]
OK

I think its safer if you update, as I may make a mistake

**Comment by rogerclarkmelbourne** [comment]
There is some other change that Daniel has made with oldKeys

**Comment by alexernst** [comment]
Please try again.

**Comment by rogerclarkmelbourne** [comment]
OK.

No merge conflicts now.

I will pull and test.

Thanks

**Comment by alexernst** [comment]
Yes, there are some deeper changes. So can't be tested enough.

**Comment by rogerclarkmelbourne** [comment]
OK.

I want to do a release today, so I may not include this in the release

**Comment by alexernst** [comment]
Perhaps make it an extra version to get some feedback from the forum.

**Comment by rogerclarkmelbourne** [comment]
Yes.

I also had that idea

Thanks.

**Comment by rogerclarkmelbourne** [comment]
I will post to the forum later. After I released the version with the other changes

**Comment by rogerclarkmelbourne** [comment]
Several other people have tested and have not reported any errors, so I have merged.

**Pull request merged**
