### PR TITLE
[UPDATED] Fix timing (based on ticks) problems, fw_millis() returns ms. uiEvent ticks member renamed to time.

### PR DESCRIPTION
**Pull request by f1rmb**
If SK1 is pressed, extra infos + elapsed time are displayed, using 6x8* fonts.
TxScreen displays LH on SK1, but only centered callsign (just like normal LH screen).
Fix the damn fw_millis(): now it returns milliseconds. Rename uiEvent_t 'ticks' member to 'time'. Review all timediff checks (I hope I didn't missed one).

About LH (don't take care of elapsed time values)
GD-77_screengrab-2020-01-10_09_57_50
GD-77_screengrab-2020-01-10_09_57_59

### CODE REVIEW

**Comment by na7q** [comment]
Adding the TG number or name would be incredibly helpful. Especially for full time TGs on hotspots and repeaters.

**Comment by f1rmb** [comment]
The problem is screen width. I don't know how to add TG number.

**Comment by f1rmb** [comment]
I think I've found a way.

**Comment by f1rmb** [comment]
This screengrab is corrupted, but it gives an idea.

GD-77_screengrab-2020-01-10_16_54_29

**Comment by rogerclarkmelbourne** [comment]
This is a useful feature, but It makes the Last Heard screen much more difficult to read because of the small text for everything.

I had investigated a way to select a line in the listing to get more details, but it was not easy.

However another option is to use the Function key , or perhaps SK1 to change what is displayed.
I think this may be more user friendly than the small text.

**Comment by f1rmb** [comment]
It uses small font, yes, but only when SK1 is pressed.

**Comment by rogerclarkmelbourne** [comment]
Ah..  ok.

**Comment by rogerclarkmelbourne** [comment]
I think displaying all those extra details in small text is too confusing

I think its probably something we will need to ask the forum, but personally, I only need to know the TG and roughy how long ago, i.e in minutes

I don't think DMR ID is needed, nor is the time to nearest second. 

I hacked you code to produce this display

lastheard_details

**Comment by rogerclarkmelbourne** [comment]
I just noticed that you have also removed the name in the normal display of the Last Heard screen.  
I don't see a reason for the name to be removed, as it worked well before the change

**Comment by f1rmb** [comment]
Hi Roger,
   Okay for the above. But what name, I'm probably missing something here.

Cheers.


Le sam. 11 janv. 2020 06:44, Roger Clark <notifications@github.com> a
écrit :

**Comment by rogerclarkmelbourne** [comment]
lastheard_name

This was the display before your change.  It has the callsign and the name, but I think in your version its only displaying the callsign  (when SK1 is not pressed)

**Comment by f1rmb** [comment]
Ahhh, well, the current code just crop a 16 chars, unlike here where it tries to find callsign and display the rest of the TA at the bottom like

**Comment by f1rmb** [comment]
And here, the last herad list looks really "ugly", sometimes, The shortest the callsign is, the ugliest it's rendered, as it crop at 16, always, so it fill the whole line.
I don't know which is the better, displaying callsign only, when it's possible, or happen chunk of cropped words to fillup remaining spaces.

**Comment by f1rmb** [comment]
Just tell me, and I will change the code in the PR.

**Comment by f1rmb** [comment]
Hi Roger,

   Last heard stuff will be part of another PR, it's removed from this PR now.

**Comment by rogerclarkmelbourne** [comment]
OK.

I posted a question to the forum with some mockups and also the old build with small text;  which I don't like ;-)

**Comment by f1rmb** [comment]
Okay,

   Anyway, the next PR about LH won't use small fonts, but stuff you asked for :-D

**Comment by rogerclarkmelbourne** [comment]
(LOL)

OK.  I did ask some other people and they preferred the larger font, but I will also see what the comments are on the forum

**Comment by f1rmb** [comment]
I also posted on the forum's thread about this.

**Pull request merged**
