### PR TITLE
Handle Stable 'R' and Unstable 'D' firmware downloads.

### PR DESCRIPTION
**Pull request by f1rmb**
Fix typo in OutputType_UNKNOWN.
Rebuild binaries.

I will modify the Python version later.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I tested it, and its working for the stable Release, but I will wait to merge this until we are able to test all the functionality.

**Comment by f1rmb** [comment]
Okay.

**Comment by f1rmb** [comment]
Just pushed the updated Python version (-U --unstable -S --stable optargs, stable is default).

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

**Comment by jfml2020** [comment]
Hello.first of all thank you for this project .... incredible . My question that I have been looking for the holy grail for a long time;) Is it possible in promiscuous mode to listen RAS? currently listen randomly .. thanks

**Comment by f1rmb** [comment]
Fixed issue #595

**Pull request merged**
