### PR TITLE
HR_C7000 Datasheets

### PR DESCRIPTION
**Pull request by djshadowxm82**
Documentation for the HR_C7000 DSP chip v1 and v2

### CODE REVIEW

**Comment by djshadowxm82** [comment]
If you fancy venturing into GD73 or other radios with this chipset. Here ya go. Enjoy

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks

I did some research into the C7000 and it also contains the MCU, and from what I can remember its not got an ARM core :-(

**Comment by rogerclarkmelbourne** [comment]
BTW.

Can you get hold of a full data sheet for the AT1846S ? 

The docs which we have, do not contain information on all the registers which are used by the code.

We only know we have to set those registers because of reverse engineering the official firmware and by doing data captures on the I2C bus

**Comment by djshadowxm82** [comment]
That one I may not be able to get ahold of.

**Comment by maozhenyu123** [comment]
I briefly read those two documents, but I am still not figuring out the structure of the firmware.(i.e. for GD-73/MD-430, what kind of binaries it is)

I guess the firmware will only be loaded to CPU CK803s and not for the HR_C7000 as a whole part? If so, I've got some reference: 

1. **Usage of CK803:** including headers and kernel files: https://github.com/alibaba/AliOS-Things/tree/master/platform/mcu/csky/csi
2. CK803s building tools: https://github.com/c-sky/tools/
3. BTW, C-SKY has been acquired by Alibaba, which gives me access to talk with their engineers.

Maybe I could do some reverse eng. on GD-73's firmware to see if there is a match.

**Comment by rogerclarkmelbourne** [comment]
Very interesting..

I noticed that the manufacturer name had changed and was not Hongrui.
I presumed that Hongrui was acquired by Dahua.

Decompilation of the official firmware may be difficult, because tools like IDA Pro and Ghidra do not support this processor.

I don’t think the official binary is encrypted, so at least that is one big problem which does not need to be solved.

One other problem writing firmware for this chip, is that I think the RAM memory is very small. Perhaps only 24k, which will make things more difficult.

The NXP MK22 in the GD-77 etc and the TYT radios like the MD-380 have much more memory e.g 128k in the MK22. I think this may limit the functionality.

**Comment by maozhenyu123** [comment]
You mean this RAM? it's 288K
image

But according to the manual, the program should be loaded into the flash memory, which could big as 16MB.
image

**Comment by maozhenyu123** [comment]
> You mean this RAM? it's 288K
> image
> 
> But according to the manual, the program should be loaded into the flash memory, which could big as 16MB.
> image
And the startup workflow:
image

**Comment by rogerclarkmelbourne** [comment]
Thanks

Someone posted some old data, a few weeks ago, based on a FCC submission, and the data seemed to show the IC only had 24k.

But I see now it has lots of RAM.

Definitely and interesting IC.  Perhaps the new owners may be more willing to share the data sheets and application notes and the programming SDK etc, as it would result in more sales.

I also wonder if this IC has access directly to the 4FSK decoder and encoder, because this would allow other modes like D-Star, YSF, P25, NXDN etc to be supported.

I wonder if TYT will bring out better radios (than the GD-73), which use this chip

**Comment by maozhenyu123** [comment]
If you select "DMR Layer 1: Physical Layer Mode", you will be able to send and receive 36 bytes(288 bits) per time and get them demodulated/modulated by 4FSK, I am not sure if that would help to do other protocols like D-star and etc.

**Comment by rogerclarkmelbourne** [comment]
OK.

I don't know anything about D-Star or YSF etc, but I doubt its the same packet size.

I wonder what happens if the data burst is longer or shorter. 

I don't think YSF or D-Star uses TDM, so the 4FSK is probably continuous

The other way to decode other protocols would be to directly access the ADC value as an audio stream.
i.e Perhaps in FM mode, but all the filters like de-emphasis etc would need to be disabled, and its unclear how to use the C6000 in FM mode.

**Comment by maozhenyu123** [comment]
> I don't think YSF or D-Star uses TDM, so the 4FSK is probably continuous

4FSK TDMA could be disabled by setting i_s_continuemode_ to Continuous mode. Maybe we could re-assemble messages. 

> The other way to decode other protocols would be to directly access the ADC value as an audio stream.

By setting ADC_P2S_EN to 0x1, we could get ADC data directly to the serial. I am not sure with the DAC part.

> i.e Perhaps in FM mode, but all the filters like de-emphasis etc would need to be disabled, and its unclear how to use the C6000 in FM mode.

The C7000 allows us to use TX_RAM/RX_RAM as the source/sink, this will bypass CODEC module, and all its related filters. Then we can directly operate those RAMs. Will that be enough?

One more interesting thing, in the document, the IC was also called DH4570 for several times. In this case, I assume C7000 is just DH4570 or may be the successor of DH4570.

**Comment by rogerclarkmelbourne** [comment]
Do you think these are new features in the C7000 or do they perhaps exist in the C6000?

I've not had time to pass the document though a translator into English

**Comment by rogerclarkmelbourne** [comment]
BTW. I do have a GD-73. Radioddity sent one to me as a sample.

**Comment by maozhenyu123** [comment]
> Do you think these are new features in the C7000 or do they perhaps exist in the C6000?

I don't think so. (But C6000 supports Layer 1/Physical DMR access for sure).

The major problem is that the addressing map and size of registers is totally different between C7000 and C6000 (i.e. The C7000 has 32 bits registers while C6000 has 8 bits?). This means even if the C6000 comes with those functionalities, we are still lacking register configurations to use them.

**Comment by rogerclarkmelbourne** [comment]
OK.

I did try reading beyond the end of the DMR data buffers in the C6000 and I can see more data, and the data changed during DMR reception, but I don't know what the data contains.

I think the problem with writing code for the GD-73 is that the display is small and it only has a few buttons, and also its only 2W and does not have an external antenna.

So its use would be limited.

Perhaps TYT or Baofeng may make some better radios using the C7000, but at the moment, all my effort is taken on the GD-77 / DM-1801 / RD-5R and the CPS, and perhaps in the future on the MD-380 and the UV-380

**Comment by maozhenyu123** [comment]
There is a radio using the HR-C7000 chip, but not that famous:

The Connect System **CS-120D**(or Covalue **GDR-5800** series, same model):
Product Info: http://www.connectsystems.com/products/top/radios/CS120D.htm
Service Manual(including PCB, ICs and diagrams): http://www.connectsystems.com/products/top/radios/CS120D/DR5800-2%20ServiceManua01.pdf

Other interesting facts: 
The GDR-5800 series using a CPS software called CSI, and I believe this is the same(predecessor) software of Hytera devices(PD6xx/7xx/9xx/RDxxx). They all use RCDB/RDBX as their codeplug and have exactly same UIs. Based on those facts, I suspect the Hytera devices....

**Comment by maozhenyu123** [comment]
I also got some API documents/user manual for the CK803s CPU:

https://cop-image-prod.oss-cn-hangzhou.aliyuncs.com/resource/420257228264570880/1577092836812/CSI-RTOS_Smart_SDK%28v1.6%29_User_Guide.pdf

https://cop-image-prod.oss-cn-hangzhou.aliyuncs.com/resource/420257228264570880/1577092915253/CSI-API_v1.6.pdf

And the CSI build tool kits(CDK):
https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/420257228264570880/1587718143976/cdk-windows-V2.2.1-20200418-2230.zip

**Comment by maozhenyu123** [comment]
@djshadowxm82 just wondering if you have access to some sample codes or config of this chip

**Comment by djshadowxm82** [comment]
Unfortunately probably not. This is probably the limits of what I can
acquire.

**Comment by djshadowxm82** [comment]
> Do you think these are new features in the C7000 or do they perhaps exist in the C6000?
> 
> I've not had time to pass the document though a translator into English
The continue mode exists in the C6000
image

**Pull request merged**
