### PR TITLE
Added Swedish Language Support.

### PR DESCRIPTION
**Pull request by qabdbai**
Added Swedish language file by copying and changing the Danish language, and updated uilocalisation.c and .h to add one more language. Language added at end of list as requested.   Compiled with 0 errors, 0 warnings. Tested by loading OpenGD77 Firmware to Radioddity GD77.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Do all the accented characters display correctly ?

**Comment by f1rmb** [comment]
This language adding is incomplete and won't work, as the array isn't added to the list in uiLocalisation.c

**Comment by rogerclarkmelbourne** [comment]
Umm. 

Obviously @qabdbai  could not tested this.

I don't think its worth wasting time until @qabdbai  has confirmed it is actually working,

**Comment by qabdbai** [comment]
Thanks for the comments.
@Roger Yes, the accented characters ÅåÖöÄä did display correctly. 
@F1RMB I will check the commit to ensure all the changes are included, although obviously they are not. It worked fine on GD77 here and yes, I have been testing the change for most of the day here, so it is my use of Git and GitHub that is in error.

David VE2XPM

**Comment by qabdbai** [comment]
uilocalisation.c was missing from the PR. Apologies for wasting your time. Will correct and resubmit.

**Comment by rogerclarkmelbourne** [comment]
Do you speak Swedish ?

Normally languages are only added by people who speak that language as their first language, otherwise we have a lot of problems with translations

**Comment by f1rmb** [comment]
Maybe you just forgot to commit and/or push the last change.

**Comment by qabdbai** [comment]
@rogerclarkmelbourne Yes, I do speak Swedish, having spent a quarter of my life there. My day job is as a Product Manager with Ericsson so I use Swedish every day. reading writing and in meetings. My daughter lives just outside Gothenburg and her partner is SA6CCZ, so I can easily get the language validated if required.

**Comment by qabdbai** [comment]
> Maybe you just forgot to commit and/or push the last change.
Yes, I suspect that is the case, so I will follow up. Thanks for your help!

I will close the PR and resubmit when I have completed the language validation with SA6CCZ, a native Swedish speaker, and also ensure I include all of the relevant files.
Thanks

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

**Comment by qabdbai** [comment]
swedish.h sent to SA6CCZ for validation. Niklas is secretary of the Vårgårda Radio Club and is active in managing DMR repeaters in the Gothenburg area, as well as being an active DMR user, so he can confirm what Swedish language users would expect to see, and provide the validation you want.

I will update the file with any changes, and with his callsign to recognize his contribution, and then test before submitting a new PR. I have just checked and uilocalization.c would be included in the PR.

**Comment by f1rmb** [comment]
Hi,
  in fact, uiLocalisation.c is part of this PR, but the diff just add the header include line. What is missing is the line that adding the Swedish translations structure to the language array, just below.

Cheers.

**Comment by f1rmb** [comment]
@qabdbai I just checked your PR, and the language file isn't using the correct encoding (UTF-8 instead of windows-1252.

I will raise a PR on your repo.

**Comment by f1rmb** [comment]
@qabdbai There is definitely a problem with the encoding. It's reported as UTF-8, which is forbidden for the firmware, but it seems it's not, as all the accented characters are wrong. The file look borked.
Do you have another source for the file, with known encoding ?

**Comment by qabdbai** [comment]
Hi Daniel,

Strange. I was careful to read the instructions that Roger provided, and I
followed the advice to use ANSI coding and I also installed Notepad++ which
I think was recommended, probably by Roger. I deliberately checked that
Notepad++ was set to ANSI coding too, and just rechecked and it is.

I need to follow up here, and pay more attention to the encoding.

BTW I have just done a completely clean build today and reloaded onto the
GD77, and there are no errors, no warnings and the Swedish language works
fine on the GD77. I am using that as the default now.

**Comment by f1rmb** [comment]
Okay, but do you have another version of the translation file somewhere, as the one in this PR couldn't be edited (check in the "File Changed" tab, all accents are question mark over a black square.

Cheers.

**Comment by qabdbai** [comment]
@f1rmb, yes Daniel I do, so I will make a third commit on the same branch including the un-borked file and then see where we are.

I have just been comparing the file submitted against one that is deliberately UTF encoded, and the file contains the correct ANSI encoding (0xE5) compared to UTF8 (0xC3A5).

**Comment by f1rmb** [comment]
You can also send it to me, via email.

Cheers.

**Comment by f1rmb** [comment]
Okay, that one looks better. It's encoded to UTF-8, but it can be edited. I'm checking about reencode.

**Comment by f1rmb** [comment]
Few entries look weird, can you re-translate it here ?:
.band_limits			= "�ppna FRQ",
.brightness_off			= "Minst ljusniv�",
.colour_invert			= "F�rg:Omv�nt",
.colour_normal			= "F�rg:Normal",
 
There is also two missing entries (has been added earlier):
 .vox_threshold                          = "VOX Thres.", // MaxLen 16 (with ':' + .off or 1..30)
.vox_tail                               = "VOX Tail" // MaxLen 16 (with ':' + .n_a or '0.0s')


Thanks.

**Comment by qabdbai** [comment]
@f1rmb Hmm ... There is still something strange in my environment. According to Notepad++ it's in ANSI. Reading into Atom it is recognized as Windows-1252 aka ANSI. How are you seeing it as UTF-8? Interested ...

**Comment by f1rmb** [comment]
$ file -bi swedish.h
text/x-c; charset=utf-8

Emacs also open it as UTF-8, most of the accents are correct. just the listed above are wrong.
Looks like a mix of encoding, but it will be easy to fix now.

**Comment by qabdbai** [comment]
Öppna FRQ (0x00F6)
Minst Ljusnivå (0x00C5)
Färg: omvänt (0x00C4 twice)
Färg: Normal (0x00C4)

Thanks, Daniel!

**Comment by f1rmb** [comment]
Okay, now the two last missing about vox threshold and vox tail ?

After that, fetch and merge your fork, from the upstream (roger's) repos, to synchronize with latest version of the translations, and I will email you the fixed version that you can copy commit and push.

**Comment by f1rmb** [comment]
I will email you the fixed version, I've added the two missing entries (at the bottom).
Quickly checked the content, some translations are too long (like .scan_delay), once you have synchronized your fork, recompile with the new translation file, and check the things in the 3 options sub-menus, you may have reduce some translations.
Use notepad++, and never edit with Xpresso, as it will mess-up the encoding.

**Comment by f1rmb** [comment]
Email sent. Good night !

**Comment by qabdbai** [comment]
Thanks Daniel. I am getting some questions related to the translation now. Tomorrow I will follow your instructions. Point about editing in Xpresso noted, and I will only use Notepad++ in the future.

**Comment by f1rmb** [comment]
Hi David,

   Any new about the translations ?

Cheers.

**Comment by rogerclarkmelbourne** [comment]
It looks like this has been abandoned. I'm going to close it.

Please re-open when and if this PR is ready

**Pull request closed without merging**
