### PR TITLE
Contact lookup priority order between codeplug/DMRIDs and TA.

### PR DESCRIPTION
**Pull request by f1rmb**
This revert the latest changes about this topic.
ATM, I didn't set a translation for "Order" string. It's not the best choice anyway, but only 7 characters are free to define something.

Hope you will like it.

Cheers.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I have been out all day, so I will need to look at this tomorrow.

I think I have not been looking in detail at many PR's and should allocate more time to understanding how they work.

e.g. I should have noticed that Alex's PR to lookup the Contact would cause problems.

**Comment by f1rmb** [comment]
No problem.

I will look closer to optimize the DMRIDs lookup thing, as current code would iterate way too much if the number of entries is big, plus possible delta of 'region' IDs (e.g. few 100k + ton of 300k).

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
I think the DMR ID lookup should be OK, because its a binary search.
The CPS has to sort the ID's in ascending order, otherwise the DMR ID lookup does not work.

I think the only thing which could possibly be optimised is the software SPI for the access to the Flash memory, because I'm sure it will be much slower than the chip allows.

In the long term we could code it in assembler, as it would not be too difficult to write in assembler, but its low priority at the moment.

When I get some free time, I'll load the official firmware into my radio thats connected to the logic analyser dongle, and look at the SPI signals to see if the official firmware accesses the Flash memory better than the OpenGD77 firmware does, but I suspect they just coded it on C on which case it will be similar to what we are doing.

**Comment by f1rmb** [comment]
Hmmm, yes, but not ;-)

The current code doesn't check if the ID is between the min and max IDs. Then, it jumps midway in each iteration. In this end, it does a ton of iterations (in the case of a mid-huge DB).
I think about something like storing (at startup) min / max IDs, and also sub divise the whole IDs in maybe 10 subgroups, and jumping directly in the right sub-goup to look it up (if the search ID is part of the whole available IDs), doing the same thing as it does now (midway jumps).

Maybe I'm not clear here.

**Comment by f1rmb** [comment]
min                                                        max
+---------+--------+--------+---------+----------+
    sub1   sub2     sub3     sub4      sub5

Like this

**Comment by rogerclarkmelbourne** [comment]
Ah. OK

You could check its between the min and the max before attempting the search.

**Comment by f1rmb** [comment]
Yeah, that's the first thing to do, then optimize the region to search in.

**Comment by rogerclarkmelbourne** [comment]
I'm not sure how you can improve on the main binary search, apart from checking in ends of the range before starting the search

**Comment by f1rmb** [comment]
Okay, I've made some test here (running on Linux, not in a GD, but checking how many times is read the flash:

About ID outside the available IDs boundaries, it's iteration, of course

There is 13 regions, if DB number if entries is > 40.
1 iteration = 1 flash read for ID, only, so if found, there is one more read the the whole contact.

Current code in the firmware iterates 17 times, +1 if ID is found.


```
// Missing ID, but in boundaries
// french DB only (1967 entries)         : 7  iteration with regions, 11 without
// french half DB only (985 entries)     : 6  iteration with regions, 10 without
// full DB (152398 entries)                  : 14 iteration with regions, 17 without

// Findable entry
// french DB only (1967 entries)     : 7  iteration with regions, 10 without
// french half DB only (985 entries) : 6  iteration with regions, 7 without
// full DB (152398 entries)               : 11 iteration with regions, 16 without

```

I will send you my ugly test code.

Cheers.

**Comment by f1rmb** [comment]
I will make some test with a DB around 10k entries.

**Comment by f1rmb** [comment]
Oh, and BTW, I've found a condition when the GD may crash. I will raise a PR for this first.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
I checked the code and I understand how it works.

I'll need to test it on my radio for a while

**Comment by rogerclarkmelbourne** [comment]
I think we may need to start a forum thread for this, because for me I don't have any callsigns in the Contacts , so it does not need to be searched.

And some people may also ask why it cant do 

CC TA DB, or DB TA CC

or just TA  ?

I know we can easily have just TA or just CC/DB but I think also that perhaps we may be making things too complex already.

**Comment by f1rmb** [comment]
Hi Roger,

   Whatever.
TA in the middle is pointless, as all of this (since the beginning) is related to priority of lookups, TA isn't a lookup, it's an optional data, only available on BM (or using our hotspot on non TA featured networks).

Users have control of DB/CC, some of them fill their codeplug with a lot of contacts, some other prefer DB.

Cheers.

**Comment by f1rmb** [comment]
As a side note, my codeplug is minimalist, no personal contacts, and my DB is empty (I needed to fill it up to test all of this). I prefer using TA on BM, or use the GD as hotspot, and it fill the gap of missing TA for IPSC2 networks. But I'm just a single user among many others ;-)

**Comment by f1rmb** [comment]
About DMRIDs cache stuff, here is a live result:

with slices stuff (3 iterations (flash read of ID only) + 1 to read the contact's text:
[13:36:18:891] ITER: 3, FlashRead: 4 :: 'F5SHD PHIL'␊

Without (looking up in the entire 208k database):
[13:38:06:918] ITER: 11, FlashRead: 12 :: 'F5SHD PHIL'␊

3 instead of 11 iteration, I could say it's way better.

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK.

Sounds good.

PS. See my question in the other / newer PR

**Comment by rogerclarkmelbourne** [comment]
Does this PR need to be merged first?

**Comment by f1rmb** [comment]
Let me recheck if if doesn't conflicts with the other.

**Comment by f1rmb** [comment]
Hmmm, you will have a conflict merge in both way. An easy one to fix, on the same uiUtilities.h file.

**Comment by rogerclarkmelbourne** [comment]
OK

No worries. I'll take a look

**Pull request merged**
