### PR TITLE
Add option to turn HS always ON.

### PR DESCRIPTION
**Pull request by f1rmb**
As I read few times users asking for this, here is a small PR.

BTW, I will make another PR related to options, as all all changes are real-time applied, so non cancelable on RED, yet.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Rather than a separate option. Perhaps have this as part of the Hotspot host type.

BTW. The only reason I made it necessary to SK1 to be pressed for the hotspot mode to be enabled in the Tier2 version, was because I knew it was not 100% tested and stable and could hang etc.

However, if its now stable, then there is no need for SK1 to be pressed. However perhaps using the settings to allow the operation of the Hotspot is useful ?

PS. I still have no response from the author of BlueDV, and the PR for PiStar has not been approved yet

**Comment by f1rmb** [comment]
Like OFF/MMDVM/BlueDV/ ?

About David, ah, maybe he is busy...

**Comment by f1rmb** [comment]
Maybe I will close this one and the restore options on RED, and create a single one, to avoid merge conflicts.

**Comment by rogerclarkmelbourne** [comment]
ok

**Comment by rogerclarkmelbourne** [comment]
I won't merge any more today. As its getting late for me  (I didnt sleep well last night)

**Comment by f1rmb** [comment]
No problem, anyway I need to modify the code first. Good night Roger.

**Comment by f1rmb** [comment]
Closed as #361 as been raised

**Comment by f1rmb** [comment]
Closed as #361 as been raised

**Pull request closed without merging**
