### PR TITLE
Channelscan3

### PR DESCRIPTION
**Pull request by ea3ihi**
Here we go again, now it seems only one file is changed and the .cproject has not been touch?

### CODE REVIEW

**Comment by f1rmb** [comment]
Yes, but the previous one you just closed was fine too.

**Comment by ea3ihi** [comment]
Yes, probably it was afer all my pull, push, commit.... I had to go back to a known place and walk the path again. I am not very profficient with git when things get screwed

**Comment by f1rmb** [comment]
Okay.
To safely create a branch for your changes, start from a clean master (git checkout master; git fetch upstream; git merge upstream/master), then create a branch (git checkout -b my_branch).
If some commit has been pushed to the master (this repository), commit you changes to your local development branch, then go back to master branch, fetch and merge your local master, return to your dev branch, and merge upstream/master there:

git checkout master; git fetch upstream; git merge upstream/master; git checkout my_branch; git merge upstream/master

This way, if there a conflict, git will complain locally (at the git merge upstream/master step). Just fix the errors (all are surrounded with ==== HEAD ... ====. Once fixed, re-add the file(s) to your branch
git add \<file in conflict.x\> \<etc...\>.

Then push.

**Comment by rogerclarkmelbourne** [comment]
This PR now only seems to change one file.. which is good.

I will review it

**Comment by rogerclarkmelbourne** [comment]
I'm still comparing the source code, but one thing which makes things more difficult is if you change the formatting on any line that is not part of the actual code change.

e.g. I see you put spaces around some of the  =    characters

This causes this to be seen as a code, change and hence you have changed around 250 lines of code, whereas your functional changes were much smaller, probably 100 lines or less.

Can you resist changing formatting when you do a PR as it makes the changes difficult to track.

If formatting changes are needed, they would be better off in a separate PR.

**Comment by rogerclarkmelbourne** [comment]
There is not enough space for the Z symbol on the top line of the display

channel_scan

I don't think its necessary.

I will remove it.

**Comment by ea3ihi** [comment]
Thanks for the extra work merging my PR, I think issue #141 can be closed.

**Pull request merged**
