### PR TITLE
Allows sending 1750 Hz tone

### PR DESCRIPTION
**Pull request by alexernst**
This pull request enables sending a 1750 Hz tone using PTT + SK1 in analog mode. (Issue #13)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thankyou.

Several people have requested this feature recently.

I may change the button from SK1 to SK2.

I also considered modifying the CPS so that the tone could be controlled from the Channel data.
I think there are multiple redundant data fields in the codeplug channel data structure

In the Tx screen I could then check if there is an Rx signal, by reading the RSSI value, and if there is no signal, the tone could automatically be sent.

BTW.
I also had several requests for DTFM tones to be generated on FM, using the number keys.
It looks like your code may potentially also be used generate these tones

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I had to make a few changes, because there was 1 bug and a few other potential problems.

I changed the button to SK2.
I found when I pressed the button (SK2) in DMR mode that it terminated the transmission, and in FM mode I noticed the counter stopped working.
This was because of a problem in fw_main.c, where the TX Screen was being added again to the screens stack whenever any button was pressed during TX.

Also. I don't think task critical blocks are needed for the AT1846 commands, because in FM mode, no other activity will be happening on the I2C bus.

The task critical blocks are needed in some places because the EEPROM and the AT1846S share the same I2C bus on the MCU. So if different tasks try to use the I2C bus at the same time it causes big problems and normally a hardware power cycle is needed to recover from bus contention.

In DMR mode special care has to be taken with the I2C bus devices, because in AT1846S needs to be controlled by the DMR  ISRs.

Hence in DMR mode, the tasks should not access either the EEPROM or the AT1846S unless their access is synchronised with the DMR ISR's to ensure there will be no current access.

I also made a change in fw_trx.c in trx_activateTx(), so that 

`trxSelectVoiceChannel(AT1846_VOICE_CHANNEL_MIC);// For 1750 tone burst`

is only called in FM mode.  

I'm not sure whether that line is actually needed or not. Perhaps its a precaution in case the AT1846S has the wrong input selected.

**Comment by alexernst** [comment]
I have to take a deeper look in the differences between FM and DMR and how everything works together.

I wasn't sure whether the voice path is needed for the HR-C6000 or not. So I did the reset for both modes.

The trxSelectVoiceChannel() is a precaution. If SK2 is released before releasing PTT the voice path is reset in menuTXScreen's handleEvent(). But if PTT is released first this code might not be reached. 
I will add DTMF and see if I find a nicer solution.

**Comment by rogerclarkmelbourne** [comment]
@alexernst 

Voice path on the DMR is completely different to FM.

In DMR, the mic is routed into the RC-6000 DMR DSP chip, and the audio is digitised. The audio is then read via I2S into the MCU, and encoded to AMBE.
The code uses binary chunks of the official firmware to handle the AMBE encoding and decoding.

The encoded AMBE bytes (27 bytes per DMR frame), are sent to the HR-C6000 and it creates the 4FSK modulation.

The 4FSK is not sent back to the mic input of the AT1846, but instead the HR-C6000 directly modulates the main clock reference for the RF section, which is a 25Mhz Voltage Controlled TCXO (VCTCXO).

We think they don't use the audio input on the AT1846 for DMR because there must be problems with the mic audio path which apply signal conditioning, which can't be disabled in the AT1846, but we don't know for sure why it does this.

The same principal is used by most radios designed by TYT e.g. I think the MD-380 does the same thing.

The AT1846 is still used to generate the actual Tx freq, but during DMR Tx it must not have any modulation on the signal, as this would interfere with the modulation being generated on the main clock by the C6000.

I guess ideally the audio input on the AT1846 should be disabled completely during DMR Tx, but things seem to work OK as they are at the moment.

BTW. Several people have also requested Mic gain control on both DMR and FM.

On FM this will be a setting in the AT1846, but on DMR it will be a setting in the C6000, possibly this 

`	write_SPI_page_reg_byte_SPI0(0x04, 0xE4, 0x4B);  //CODEC   LineOut Gain 2dB, Mic Stage 1 Gain 0dB, Mic Stage 2 Gain 33dB`

and

`	write_SPI_page_reg_byte_SPI0(0x04, 0xC2, 0x00);   //Disable Mic Gain AGC`


I may have a play with those settings later.

Anyway. Thanks again....

**Comment by rogerclarkmelbourne** [comment]
@alexernst 

FYI.

VK3YNV said he would investigate implementing the DTMF. 

If you have not started writing DTMF, then please do not start, otherwise there will be duplication of effort

**Comment by alexernst** [comment]
Upps, I have it nearly working. Just some testing to be sure. I think gain and/or deviation has to be adjusted. But I'm not sure right now.
And I would like to get some audio feedback.
And sending DTMF contacts from codeplug.

**Comment by rogerclarkmelbourne** [comment]
OK

I didn't start writing the code yet.

Perhaps create a PR for the basic functionality and then do an update for the additional functions.

**Pull request merged**
