### PR TITLE
Take care of half the BW for band limit checking.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

I also thought about this a while ago.

I agree you are probably technically correct, however I will check what my Yaesu FT-991A does, because I think it probably allows me to transmit on 144.000000Mhz in FM and possibly in lower side band, where technically both would result in modulation outside the band.

**Comment by f1rmb** [comment]
Well, I can't test what commercial ham HT does, as all of my HTs are wide
open...

Also, I was thinking about band plan per region. Since we have
localisation, we could add different settings as well. Of course of a
German lives in USA, that won't work unless it turn off band limits.

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
I am not sure about band limits per country, or region, this could get very complicated, as I think there would be many anomalies

**Comment by f1rmb** [comment]
Hi Roger,

Yeah, true. Nevermind 😉

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
I checked my Yaesu, And it lets me transmit on 144.000 MHz on FM and also 148.000 MHz. I think people would find it strange if the firmware did something different to what the major amateur radio manufacturers do.

PS. I will ask about this, but its probably a "grey area".

**Comment by f1rmb** [comment]
Hi Roger,

    Okay. As i told you, you can close this PR, that was just an idea since technically it can be out of band. But hey, all manufacturer just take care of center frequency apparently ;-)

**Pull request closed without merging**
