### PR TITLE
Correct SPI Clock Configuration

### PR DESCRIPTION
**Pull request by g4eml**
From the recent Captures of the official firmware the SPI clock can be seen to be Active High triggering on the falling edge.
The OpenGD77 code was configured as active Low triggering on the leading edge.
This change corrects the setting.
Probably doesnt make any difference though as the actual clock edge is the same.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin

OK.

I think this will need a bit of testing on multiple radios, so I'm not going to merge it into the master straight way.

I'll post a test version, so that some of the members of the forum can try it first.

**Comment by g4eml** [comment]
I agree it needs testing. It works OK on my two radios. 

As I said I suspect it may not make any noticeable difference anyway. Even though I think the configuration was wrong it may not be critical. On the other hand it potentially could reduce any intermittent errors. 

Can you do an SPI capture while running it? Then we can confirm if it is the same as the official firmware. I think it will be. 

Colin. 



On 8 Jan 2020, at 23:15, Roger Clark <notifications@github.com> wrote:

Colin

OK.

I think this will need a bit of testing on multiple radios, so I'm not going to merge it into the master straight way.

I'll post a test version, so that some of the members of the forum can try it first.

**Comment by rogerclarkmelbourne** [comment]
Hi Colin

OK.

I'll pull your branch and load it onto my test radio (via USB), and confirm that it has changed the waveforms

**Comment by rogerclarkmelbourne** [comment]
I'm going to merge this, as otherwise there could be problems merging your VFO Scan PR

**Comment by rogerclarkmelbourne** [comment]
Colin

I think the clock speed is also too low.

I see that the code has the speed set to 500k in fw_spi.h and I checked the capture and thats approximately what I'm seeing

The official firmware seems to be running the SPI clock speed at 1.5Mhz

However when I tried changing the speed to 1.5Mhz I lost Tx audio, so perhaps the 2 buses need to operate at different speeds.

Strangely the Rx audio was working when I changed the master SPI speed to 1.5Mhz, which would apply to both buses.

**Pull request merged**
