### PR TITLE
Simple TalkGroup filtering

### PR DESCRIPTION
**Pull request by Teeed**
Enable in quick menu (orange button), set Filter to TS+TG. This will cause squelch to be opened only when there is a conversation on selected TalkGroup. This mode will be indicated in left upper corner as TSX**G**.

Needs further testing. Binary version (for testing) available at: https://github.com/Teeed/OpenGD77/releases/tag/TGfilter

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Why have you appended a 'G' to the 

					if (nonVolatileSettings.dmrFilterLevel >= DMR_FILTER_TS_TG)
					{
						strcat(buffer, "G");
					}

**Comment by rogerclarkmelbourne** [comment]
This new functionality doesn't work correctly.

All that you are doing is muting the audio if the TG doesn't match.
Its still displaying the TG and the Callsign / ID.

And it doesn't mute the audio on simplex it only mutes it on duplex.

**Comment by Teeed** [comment]
That works as indended. I still wanted to keep user notified about activity on TS, that is why it only mutes audio.

It appends G not to the group name but to the text displayed in the left upper corner of the screen - it has nothing to do with group name. Buffer is 17 bytes long (16 txt + nullbyte) as I recall, so it is plenty of space to fit "DMR TG1G" text.

**Comment by rogerclarkmelbourne** [comment]
OK.

I think most users would expect TG filtering to work in the same way as in the official firmware, so that only the Green led illuminates but nothing else on the radio changes if there is a signal not on the selected TG.

Re "G" on the display

The top row of the display becomes difficult to read when there is insufficient space between the elements, and when 250, 500 or 750mW power is selected, there is not much space between the power and TS2G display.

Hence I have modified other PR's which try to squeeze more items onto the top row of the display, to remove things which make the display difficult to read

**Comment by Teeed** [comment]
Well, about crowded top bar: I will rethink this a little ;) maybe changing TS1 to TG1 (when this mode is enabled) would give enough indication?

About difference between "original" behaviour: it currently only takes selected TG instead of whole RxGroup..

**Comment by Teeed** [comment]
About displaying information on a screen in TS+TG filter mode: if we choose to not display any "undergoing call information"  there will be no way of telling if current timeslot is occupied.

**Comment by rogerclarkmelbourne** [comment]
User feedback from the forum was that this functionality was not what users expected, as it does not replicated the TG filtering in the official firmware.

**Pull request closed without merging**
