### PR TITLE
Clean a bit the GD77S settings. Swap Power and Zone settings order.

### PR DESCRIPTION
**Pull request by f1rmb**
Okay. Fixed...

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

I think there is something missing from the announcements when changing Zone.

When I Long press Orange and hear 

"Set On Store N" where N is the store number, then Press Blue to decrease the Zone number, I just hear the word "Store" and not the number of the store.

Also if I press SK2 again, nothing happens.

I would expect when it "Set On" mode that it says in this mode until I take it out of the mode by either Long press on Orange or perhaps press the PTT.

Also, the radio suddenly then started to constantly make a strange sound

I recorded it.

(Ignore the echo, its because when I recorded it my PC speakers were tuned one and it produced an echo)

Even if I power cycle the radio or remove and reconnect the battery it kept constantly making this noise until I rebooted with SK2 pressed to reset the settings



[strange_noise.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/4609083/strange_noise.zip)

**Comment by f1rmb** [comment]
Hi Roger,

   Okay, I will take a look at this.
Is the channel that was selected when you turned ON the GD was an Analog or Digital ? 


Cheers
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
Hi Daniel

Sorry, I don't know which zone the radio was in when this happened. because I was trying to change zones and understand the the UI, and the Zone number is not annunciation when you change zones.

**Comment by f1rmb** [comment]
Hi Roger,

   Okay.

**Comment by f1rmb** [comment]
Hi Roger,

Okay, I fixed lot of issues (not pushed yet).

Now I will check the sound problem.

**Comment by f1rmb** [comment]
Okay, the "Strange Sound" is the error beep, as you select a channel which is not set on that zone ;-)


Cheers.
---
Daniel

**Comment by f1rmb** [comment]
Hi Roger,
   BTW, I changed the error sound to "CHANNEL ERROR...", that's better IMHO.

I won't push the changes and fixes tonight, as I still have a little bug, and it's a bit late.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

I'll wait until everything is pushed

**Comment by f1rmb** [comment]
Okay, I pushed:

* Fix Zone selection.
* Announce CHANNEL ERROR instead of beep error when an empty channel is selected.
* Leave settings on PTT too.
* Spell hotspot mode: MODE RED for MMDVM, MODE BLUE for BlueDV, on boot (when SK1 and/or PTT are pressed).

**Comment by rogerclarkmelbourne** [comment]
OK.
I'll pull now and test.

**Pull request merged**
