### PR TITLE
Map SK2+<number key> to menu entries or options

### PR DESCRIPTION
**Pull request by alexernst**
Now that in the OpenGD77 CPS the dialog for quickkey setting is disabled, this PR enables direct assigning quickkeys.

Most menu entries can be mapped to a number key for direct access. Simply select an entry and long-press a number key.

Assign 'channel details' on key '2':
GREEN -> DOWN to 'channel details' -> long-press '2'
Assign  'Sound options'->'Prompt' to '3':
GREEN -> DOWN to 'Sound options' -> GREEN -> UP to 'Prompt' -> long-press '3'

Afterwards pressing SK2+number on Channel or VFO screen jumps direct to that entry.

- This does for now not work for the Quickmenus.
- On the RD5R key '5' is still mapped to the torch and cannot be reassigned.
- The settings are saved in the codeplug. If the menu structure changes the saved values will link to the wrong entries and have to be reassigned. 
- Only tested on GD-77 so far.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Alex

I like this.

FYI. The number key assign screen (and the others) were removed because some users, especially the blind users were confused with screens being present but not functional.

I initially just displayed a popup message on the unsupported screens, but I still had complaints that people did not understand why a message was being displayed to say the feature was not supported yet.

So I had to completely remove them.


One thing however, is that this change removes the functions to increase and decrease the brightness.

Ideally we need some way to be able to assign keys to control individual options within the screens, not just open individual screens, otherwise we loose some functionality with this PR.

**Comment by rogerclarkmelbourne** [comment]
Looking at the code to handled the increase and decrease in brightness, in Display options, I think this should be removed if its no longer used.

Also, the method of handling individual options, by having separate functions, as was implemented for the increase and decrease in brightness, is not scalable across all possible functions, because it adds massively to the code size and even if the changes to individual settings were put into separate functions.

I think this will need to be handled in a different way, probably by being able to send simulated key sequences to the menus.
Perhaps not actual key presses, though this is possibly one method.

Also.
Because the quick keys are stored as a 16 bit value, I think there would be scope to control individual settings, as long as as we limit the number of sub-items in each menu.
The channel details is the screen with the most settings, which is currently 15, and it may be unavoidable to keep this number < 16.

Hence we would need to assign 5 bits to the  sub-option / setting, and either 4 or possibly 5 bits to the menu number (currently there are 12 top level menu's and I think its unlikely this would need to exceed 16.

Even with 5 bits assigned to menu number, and 5 bits assigned to setting / sub-option, this leaves 6 bits to control individual settings, which I think is definitely enough. 
e.g. Even if someone wanted to be able to change Zone, 6 bits is 64 zones, and if we can limit the top level menu to 4 bits, then that gives 7 bits for individual settings.


BTW. 
In terms of being able to have a UI in the CPS, it would be a huge amount of work, and also a lot of work to maintain, so I doubt anyone would ever have time to do this.

**Comment by rogerclarkmelbourne** [comment]
BTW. Just test it and it doesn't seem to work for me

I tried to assign '9' to the Zone menu, but it seems to open the menu, but it then immediately closes.

There is a problem on the Channel details screen, because the initial selection is the channel name, and pressing and holding a key enters a character into the name.

I think perhaps we would need to use some other key combination to prevent this happening, e.g. SK1 + KEY to assign a key shortcut.

Also. So assign shortcuts to sub items e.g. Increase brightness, I think we'd need to use something like SK1 + RIGHT + Number key

ie SK1 + Number key would possibly open the top level of a menu. SK1 + Arrow + Number would assign the key to the specific option  and right or left arrow 

Not sure how what UI would be best to select an individual zone.

**Comment by alexernst** [comment]
I like the idea of pressing SK2+Arrow+Number to assign the directly change an option. Will try this.

Selecting a zone is possible bei opening the zone menu go to the zone and instead of selecting with GREEN  use long-press number. I have an almost working modification of the contact list, which is using the contact data instead of overrideTG, that enables the same to assign a contact to a key.

I will fix the zone and channel details problem.

I'm using long-press and not SK2+key to save the shortcut, as I first didn't restrict the shortcuts to be available only on VFO and Channel screen. But with this restriction SK2+key would be possible now. Don't know which one is better.

**Comment by alexernst** [comment]
The structure of the 16bit value by now is:

bits 15,14: contact, menu entry or (menu independent) function
bits 13-8: menu id (this could be shorter)
bits 7-0: menu entry or menu specific (on the battery screen it is used to set which screen to display and how the graph is displayed)

if bits 15,14 = 0,0 bits 9-0 contain the contact index. Not used right now.

An independent function could be the torch on RD-5R.

2 bits for the type of shortcut
4 bits for the menu id
5 bits for the menu entry
5 bits for entry specific functions (e.g. for color code this could be 0 to 15 up and down. Don't know how the UI could be.)

One possibility was to start assigning with long-press key or SK2+key and then RIGHT, LEFT or GREEN to select between change option and select actual option.

**Comment by alexernst** [comment]
The last commit includes an option to set keys to increment and decrement brightness. Ser wirh SK1+key and then Green, Left or Right.

Maybe this is a useable UI. The code overhead is relative small, but it needs more work.

**Comment by rogerclarkmelbourne** [comment]
OK.

I've been busy all day.

I have a Private Call bug to fix, and then I'll take a look at this PR...

**Comment by alexernst** [comment]
I changed to SK1+number as there is no other easy way to fix the channel name problem. 
Entering alpha-numeric chars and detecting long-press conflicts and shouldn't be used together. Fixing this would require to change the keyboard code. 

The menuId is stored in 5 bits for now, as in fact it is the id of the screen and not the menu index.

But the main focus of the last commit is the UI implemented on the Display options screen.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'm freezing the code for a few days prior to releasing a stable version on 1st August, but I will pull your PR to a separate local branch to test it

**Comment by rogerclarkmelbourne** [comment]
FYI.

I think if the user updates their codeplug, all the key shortcuts will be deleted won't they ?

**Comment by rogerclarkmelbourne** [comment]
BTW.

I have to prioritise bug fixes above new features at the moment, and I have 2 bugs that need to be fixed in the CPS, so it may be some time before I'm able to look at this PR.

**Comment by alexernst** [comment]
The key bindings will be saved in the codeplug. So if you read from the radio, modify the codeplug and write back the bindings will be retained. If you write a saved codeplug to the radio, the bindings will change.

As an alternative It would be possible to add the key bindings to nonVolatileSettings.

**Comment by rogerclarkmelbourne** [comment]
The CPS currently has a bug where the codeplug can't be read back from the radio correctly

The CC on DMR channels and not updated from the value in the radio and I suspect there are likely to be other parameters which are not read back into the CPS correctly


Do not change you code to store this as an addition data to the nonVolatile settings, as there is limited space in that area, and it would probably result in some other part of the codeplug being overwritten.

**Comment by rogerclarkmelbourne** [comment]
I think I have now fixed the readback bug.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I have manually merged this into my local code, and have also made some changes

So I will close this PR

**Pull request closed without merging**
