### PR TITLE
add Dutch language

### PR DESCRIPTION
**Pull request by on7lds**

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi,

   please, remove firmware/.cproject that has been commited.

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
BTW, it seems you dev branch is a bit behind Roger's development one, so three translations are currently missing.

Cheers.
...
Daniel

**Comment by on7lds** [comment]
OK,
I'll start over from the current branch and submit a new PR.

**Comment by f1rmb** [comment]
No need, you can just fetch and merge to your current 'dev' branch.

**Pull request closed without merging**
