### PR TITLE
DM-1801: Handle VFO/MR and A/B keys.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
LOL
Hold on a second ;-)

**Comment by f1rmb** [comment]
Errr, there is still a problem...

**Comment by f1rmb** [comment]
Now it works as intended :-D

**Comment by rogerclarkmelbourne** [comment]
OK. 

LOL.

I'll try it.

**Comment by rogerclarkmelbourne** [comment]
BTW. I'm writing some code to copy the calibration to 0xF000, for both the GD-77 and DM-1801 so that the calibration table is in the same location for both, and I can then modify the CPS to use that address.

This also allows us much more space for the DMR ID's on both radios.

I also probably need to add some function to the USB to get the radio name e.g. just return a string of the name, and also perhaps get the build number.

As the DM-1801 has a larger Flash chip, so can store more DMR ID's

**Comment by f1rmb** [comment]
Okay Roger.
Unifying the cal addresses sounds nice.
About the USB, you mean grabbing the ID from the flash ?

**Comment by rogerclarkmelbourne** [comment]
We could get the device ID / module number from the Flash, but I was thinking also we could return a string that we hard code into the firmware, as the radio model name e.g. "GD-77" or "DM-1801" or "GD-77S" etc, and also perhaps get the build date and the git version.

**Comment by f1rmb** [comment]
Oh, okay, that's nice.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

On the DM-1801
We can probably remove the Red key operation to change from VFO < --  > Channel
And also remove the VFO A/B  change via the Orange key (but this may be more difficult as it changes the default operation)

BTW.

I may as well merge my calibration copying branch, as I think is OK. and does not really damage the calibration table in Flash, and people could go back to an old version and their radios would work just fine even if the copy didnt work.

**Comment by f1rmb** [comment]
Okay about the RED/ORANGE duplicate removal, I'll do that.

Calibration:
What about if some people fill original region with DMR IDs, and go back to original firmware (with a DM-1801, I mean)?

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Those people will have backup at 0xF000 but also I thought I would automatically backup their calibration using the CPS and save it.

However its not just the calibration data which is essential to the official firmware.

Jason VK7ZJA found many other addresses in the Flash which could not be set to zero.
He erased is Flash memory using a hardware programmer tool and found the GD-77 would not work, and he had to find which bytes were essential.

I can't remember which addresses were essential, but Jason will have the list.

Anyway, I posted to the forum about this and everyone who replied told me they would never go back to the official firmware ;-)

**Pull request merged**
