### PR TITLE
Add keylock with key star in main menu

### PR DESCRIPTION
**Pull request by alexernst**
In the main menu pressing star locks keypad.
Unlocking with green key followed by star. #43

 PTT will not be locked.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I'm testing this now.

I think the time the message is shown is too short. 

I will increase it, and to make sure that its not too easy for a child to unlock, I will change so that Function + Star is needed to unlock.

The operator who asked for this feature has a small child who he said plays with the radio.

I will check if a feature to lock the PTT is also needed, as an additional function on the lock screen

**Comment by rogerclarkmelbourne** [comment]
BTW.

Why do you get the bootscreen text

```
	char line1[16];
	char line2[16];

	codeplugGetBootItemTexts(line1,line2);
```

I think perhaps this code is redundant as those var's are not used

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've merged this, with a few changes.

Increased timeout to 2000 ms 

Changed exit sequence to Function + Star

Removed redundant code

**Comment by alexernst** [comment]
I copied the startup screen and didn't deleted those lines. 

Funny, I started with Function+Star and changed it later and also I shortend the time the lockscreen is displayed. Was too long for me.

Perhaps such values should be user changeable.

**Comment by rogerclarkmelbourne** [comment]
OK

I think 2 secs is a good compromise. 
1 sec was too short to allow time to read the screen and understand what needs to be done to unlock.

I think Function + Star is better, as I know someone who said his children constantly press the buttons, so pressing Green and then Star within 1 or 2 seconds would be possible
Its much more difficult for a child to hold the Blue button and press the Star

**Comment by rogerclarkmelbourne** [comment]
@alexernst 

Why did you delete your branch for this ?

It disappeared after I pulled a local copy of your branch for the PR, which confused me.

I hope the version I merged is OK, but I think it is

**Comment by alexernst** [comment]
It's merged, so no need to keep it.
I wouldn't delete it if I see any problems. 

Next time I wait longer ;-)

**Comment by rogerclarkmelbourne** [comment]
Hi Alex

No worries.

**Pull request merged**
