### PR TITLE
Update from OK2HAD.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
Hold on, he sent a complete update.

**Comment by f1rmb** [comment]
Okay, it's ready for merge now.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll merge later.

I'm trying to fix some problems in the CPS for blind operators as the Channel and Contacts forms are not tab'able because they don't have focus when they open :-(

**Comment by f1rmb** [comment]
Sure, no problem.
Yeah, I saw the posts on the forum about this.

**Pull request merged**
