### PR TITLE
Added Complete Chinese Datasheet on HR_C6000

### PR DESCRIPTION
**Pull request by djshadowxm82**
I was able to obtain an un-corrupted copy of the datasheet for the HR_C6000

### CODE REVIEW

**Comment by djshadowxm82** [comment]
@rogerclarkmelbourne I hope this is helpful to you. Albeit, its not translated, but hoping the diagrams and anything else you may be missing from the copy you had in the repo is helpful to development. - kc3awn

**Comment by rogerclarkmelbourne** [comment]
Thanks

Were there any other data sheets or application notes where you got this one from?

I presume not... 

As this one is not corrupt, I presume its the original, from which our other / corrupted versions were derived.

**Comment by djshadowxm82** [comment]
I reached out to someone that had access to this sort of stuff. What else might you be looking for? I just tried hailing you via private call aswell.

**Comment by rogerclarkmelbourne** [comment]
@djshadowxm82 

I'm not at home at the moment, so can't get on the radio.

This datasheet does not seem to contain data on all the registers that the official firmware uses.

For example. Reg 0x57 appears to be used by the official firmware, possibly to read the current TimeSlot, but there is no data on the registers after 0x55 but before 0x5F

0x57 does seem to contain data about the timeslot, but its different from the data in 0x52, which seems to be the register the data sheet says is used to read the timeslot (aka timecode)


I also wonder whether there are some features which are not described in the datasheet.

For example, it would be great if there was some way to access the raw 4FSK decoded data, because this may allow other modes (than DMR) to be decoded.

But the block diagram does not show a path to access the raw 4FSK data.

Also, its not clear whether perhaps the C6000 could operate as a SFR. i.e receive on 1 TS and then restransmit it on the other timeslot.

We've not tried to write code to do this, but there does not appear to be anything in the datasheet about SFR operation.

Thanks.

**Comment by djshadowxm82** [comment]
Unless I'm reading this incorrectly or looking at the wrong section, it would appear those registers you spoke of, are detailing the Base Station Data Sync handling.

image

I had some folks just the other day asking about SFR and DCDM (dual capacity direct mode) would be interesting. 
There were a few other things in this datasheet had mentioned but wasn't sure if they were exposed or not as I don't know what the 77's pinout to the MCU look like. Saw that the c6000 would do encoding/decoding of 2/5 tone. Would be very handy to be able to have this do 2 tone decoding for SelCall paging. (I'm a firefighter too so this would be nice feature). Also made note that your code has no handling for setting the LED yellow. When encryption was turned on on 77 offical firmware the led was strapped to yellow. Would be nice to have that come up as a flashing or solid alert for 2/5 tone decode or dtmf decode or even an incoming private call as a visual.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I've merged this.

Daniel sent me a machine translation of it via email, which I will also add to the repo

**Pull request merged**
