### PR TITLE
Instant display contact info when getting out of a menu while RXing.

### PR DESCRIPTION
**Pull request by f1rmb**
This fixes latency about contact informations rendering, when getting in and out of any menu when RXing (DIGITAL mode only).

### CODE REVIEW

**Comment by f1rmb** [comment]
LOL, hold on, it doesn't honor TG filtering :-D

**Comment by rogerclarkmelbourne** [comment]
OK.

I will test later.

I'm working on another filter, for Digital Contacts only. 
Its a bit like the TG filtering, except the acceptance criteria is whether the other station is in your Digital Contacts, (it does not matter what TG they are transmitting on)

**Comment by rogerclarkmelbourne** [comment]
(LOL)

OK

**Comment by f1rmb** [comment]
Okay Roger, that's a nice filter too.
I pushed the fix about TG filtering.

**Comment by rogerclarkmelbourne** [comment]
OK. I'm testing the Digital Contacts filter

The only problem is the name in the UI.

I put DC at the moment because to use "Cc" is perhaps confusing in this contacts, as it looks a lot like CC for Colour Code :-(
And I can't use "PC" because that implies only Personal Calls will be accepted.  But perhaps PC is better?



Even DC is not good, as it probably needs to be translated, as some language D is not for Digital and C is not for Contact.  (aaargghh)

**Comment by f1rmb** [comment]
Maybe we can use Ct or CT, and replace Cc by the same acronym ?

**Comment by rogerclarkmelbourne** [comment]
Thanks.

It seems to work.

**Pull request merged**
