### PR TITLE
Yes, there were missing accents.  Fully fixed now.

### PR DESCRIPTION
**Pull request by EA3BIL**
Yes, there were missing accents.  Fully fixed now.
Notepad++ ANSI.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK

I'll pull and merge again

**Comment by rogerclarkmelbourne** [comment]
Accents look OK now. 

So I have merged.

**Comment by EA3BIL** [comment]
Yes, it's ok now.  :)

Thank you very much !

**Comment by rogerclarkmelbourne** [comment]
OK. I checked it and the accents were being displayed.

Its part of this test release

https://www.opengd77.com/viewtopic.php?f=11&t=337&start=10#p2656

**Comment by EA3BIL** [comment]
Brilliant !

I'll load it in a few minutes and check.

Just getting back home after taxing wife to job.



BTW...

How are the fires doing?
I saw at the morning news you are dealing with really high temperatures and
several big fires burning. OMG!.

**Pull request merged**
