### PR TITLE
Add Chinese user guide and quick start diagram

### PR DESCRIPTION
**Pull request by michae1eo**
This is the finish chinese user guide. I make all the file into one commit.
VY 73

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thankyou.

It looks good now.

I will try to merge it later.

BTW. 

If you are a programmer and want to do a specific Chinese language version, it may be possibly. But it would not be practical for me to maintain both main version and the Chinese language version, so you would need to ask people to use the version from your own repo.

The system only handles single byte characters, so you would be limited to a maximum of 256 characters.

I am not an expert in the Chinese language, but I know that there are many more than 256 characters in the Chinese language, but perhaps you could review all the texts and convert them to chinese and only use a maximum of 256 characters.

Also, you would need to then build a the bitmap font for those 256 characters which you are using.

BTW. You may also want to consider building voice prompts for Chinese, this may be easier.

Voice Prompts are pre-processed using Amazon Polly, into AMBE files, which are then played by the radio.

e.g. Here is the english language word list

https://github.com/LibreDMR/voice-prompts/blob/master/languages/english_UK/wordlist_english_UK.csv

If you can translate the wordlist to Chinese, then that Voice Prompt data pack could be loaded into the radio and most things would speak in Chinese.

BTW. The scripts to make the voice packs are written in Python (by me) and the radio is used to encode the MP3 files into AMBE etc

**Comment by rogerclarkmelbourne** [comment]
Thanks

I have reviewed the User Guide using Google Chrome to translate the HTML and it looks good.

The changes have now been merged

**Comment by michae1eo** [comment]
Yes, thanks.
Sure I can make a chinese voice prompts, it seems raletive easy. But as for the font, I'll see what I can do.

**Comment by rogerclarkmelbourne** [comment]
[chinese_voice_prompts.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/5275045/chinese_voice_prompts.zip)

**Comment by rogerclarkmelbourne** [comment]
@michae1eo 

I tried to make some voice prompts for Chinese using Google Translate. 

Please unzip and try the file I just attached

Change the csv if the translation is incorrect.

BTW. MS Excel does not seem to edit the csv correctly for unicode characters. Please edit in some other editor e.g. Notepad++ etc

**Comment by michae1eo** [comment]
Have to say Google Translate is pretty impressive, most of them are fairly correct as for grammar, but not for expression. I corrected all of them. 

I also tested the already packed .vpr file, due to the difference between languages, some voice prompt is in wrong order which i can't correct just in .csv file.

For example:
1. When annocing percentage value like UHF Squelch, in English it's "Three Zero Percent", but in Mandarin we pronounce percentage first, then the value, like "Percent Three Zero" 
2. When dealing options with time like"Timeout: 15s", it should pronounce "Fifteen Seconds", instead it pronounce "One Five S". I do notice there's "PROMPT_SECONDS" in wordlist so maybe just not incorporated yet.
3. In Channel Details "Rx" should be pronounced "Receive Frequency", and frequency also should be "Mega Hertz" rather than "M H Z", this happens a lot, when Pronouncing some option it just "speaks out" one by one individually. I checked english usa and uk, this seems to be a common problem and maybe resolved later.

I attached the fixed wordlist, github doesn't support .csv directly so I just renamed to .txt file and recheck to make sure it's UTF-8 in npp.
[wordlist_chinese - 01.txt](https://github.com/rogerclarkmelbourne/OpenGD77/files/5276768/wordlist_chinese.-.01.txt)

**Comment by rogerclarkmelbourne** [comment]
I've copied the text from this thread to the repo for the voice prompts

https://github.com/LibreDMR/voice-prompts/issues/14

**Comment by rogerclarkmelbourne** [comment]
@michae1eo 


See

https://github.com/LibreDMR/voice-prompts/releases

Please try 
https://github.com/LibreDMR/voice-prompts/releases/download/R2020.09.26/chinese_zhiyu.vpr

And if there are any mistakes please submit a PR to 

https://github.com/LibreDMR/voice-prompts

**Pull request merged**
