### PR TITLE
Add delete contact to 'Contact List', use DMR ID as name in 'New Contact'

### PR DESCRIPTION
**Pull request by alexernst**
1. If a new private contact is created and the ID is found in the DMR ID database that info is used as the contact name instead of 'PC #######'. The text from the DMR ID is shorten to 16 letters.

2. Deleting a contact is added to the 'Contact List'
Deleting a private contact is done by pressing SK2+RED.
TG's can not be deleted right now. I will add this later for TG's not used in a RX Group.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'm just processing Colins' PR to add functionality to the Scan function.

PS. Did you see my email about how do I use the Long press ?

**Comment by alexernst** [comment]
I created this pull request to not forget it. So don't hurry.

PS: Answered your mail.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I got your email.

I'll  change Channel mode to use the new key handling

Thanks

**Comment by rogerclarkmelbourne** [comment]
Thanks

I tested and the functions seem to work OK.

**Pull request merged**
