### PR TITLE
Add online downloading feature.

### PR DESCRIPTION
**Pull request by f1rmb**
image

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

Thats cool.

Its too late for me to test it now.

I'll test it tomorrow morning

**Comment by f1rmb** [comment]
Okay Roger ;-)

**Comment by rogerclarkmelbourne** [comment]
is LibUsbDotNet.dll needed for Windows ?

I tried copying just the exe into a folder and it crashes, unless I also copy in the dll

This will be a problem for people, because I can't write an installer because antivirus programs seem to treat all unknown installer exe files as a virus

We need to try to just have this as a single file that can be downloaded for Windows.

**Comment by f1rmb** [comment]
Hi Roger,

   LibUsbDotNet.dll is only needed for Linux, as it's used for USB HID support.
So, which exe did you used in Windows ? Did I messed up builds ?

Just checked the Windows exe:
```
AssemblyRef Table
1: Version=4.0.0.0
        Name=mscorlib
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
2: Version=4.0.0.0
        Name=System.Windows.Forms
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
3: Version=4.0.0.0
        Name=System
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
4: Version=4.0.0.0
        Name=System.Core
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
5: Version=4.0.0.0
        Name=System.Drawing
        Flags=0x00000000
        Public Key:
0x00000000: B0 3F 5F 7F 11 D5 0A 3A 
        Zero sized hash value

```

And the Linux one:
```
AssemblyRef Table
1: Version=4.0.0.0
        Name=mscorlib
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
2: Version=2.2.8.104
        Name=LibUsbDotNet
        Flags=0x00000000
        Zero sized public key
        Zero sized hash value
3: Version=4.0.0.0
        Name=System.Windows.Forms
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
4: Version=4.0.0.0
        Name=System
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
5: Version=4.0.0.0
        Name=System.Core
        Flags=0x00000000
        Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
        Zero sized hash value
6: Version=4.0.0.0
        Name=System.Drawing
        Flags=0x00000000
        Public Key:
0x00000000: B0 3F 5F 7F 11 D5 0A 3A 
        Zero sized hash value
```

Windows build uses hid.dll, via PInvoke, but it's part of the OS:
```
                [DllImport("hid.dll", SetLastError = true)]
                protected static extern void HidD_GetHidGuid(out Guid gHid);
```

Cheers.

**Comment by rogerclarkmelbourne** [comment]
I just tried GD77_FirmwareLoader.exe  not the linux version

**Comment by f1rmb** [comment]
Wow. Let me check in my VM.

**Comment by f1rmb** [comment]
Humm, I don't have any problem to run the Windows exe without the  LibUsbDotNet.dll  here. Strange.

**Comment by f1rmb** [comment]
Okay, I get the same problem. I will check why now.

**Comment by rogerclarkmelbourne** [comment]
OK.

I can double check if you want.

**Comment by f1rmb** [comment]
Okay, fixed. I just had to clear everything by hand (cleaning the solution wasn't enough), and rebuild the binary.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
LOL

OK.  I'll pull again and retest

**Comment by f1rmb** [comment]
Humm, there is a problem with SSL/TLS under windows. I rebuilt a non https version, and it works. I will update right now.

**Comment by f1rmb** [comment]
With the current binary, do you have a problem when downloading ?

**Comment by rogerclarkmelbourne** [comment]
hang on I'll pull again and test it

I'm cooking the chicken for our evening meal at the same time as writing an email and looking on github ;-)

**Comment by f1rmb** [comment]
:-D

**Comment by f1rmb** [comment]
Okay, I found a fix for this.

**Comment by rogerclarkmelbourne** [comment]
Yes

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
BTW.

Probably change the text "Download and flash" to "Download and update"

People may not understand "flash" I think its too technical

**Comment by f1rmb** [comment]
Okay, wait 5 minutes then :-D

**Comment by f1rmb** [comment]
Done ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks

I tested dragging and dropping the GD77 SGL into the exe and I also tested the download option.

Both worked fine.

**Comment by f1rmb** [comment]
Okay.
I've added similar feature to the CPS (in the PR already raised).

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

I didn't noticed that. But I receive a lot of emails during the night.

I'll check soon.

I am working on a small bug fix for the VFO scan, because it does not restart if the current frequency has a signal

**Comment by f1rmb** [comment]
I have to confess I didn't even tried the new VFO feature... Well, fighting the CPS under Linux, not that funny ;-)

**Comment by rogerclarkmelbourne** [comment]
No worries. I sent it to a few people, and their tested it, but they did not see some of the bugs.

**Pull request merged**
