### PR TITLE
Bugfix chanmode switch

### PR DESCRIPTION
**Pull request by patrol-cz**
Fix of the incomplete channel setup after manual switch of the channel mode between analog and digital. Especially for the digital mode, a lot of properties (CC, TS, RxGroup..) were not set up and some subsequent manipulation (like a short PTT press) was neccessary to fix it.

### CODE REVIEW

**Comment by f1rmb** [comment]
I'm not sure the beepAssist will still work, and loadChannelData() will be called twice .

**Comment by f1rmb** [comment]
Also, TS/CC and so on aren't touched when switching from DIGITAL to ANALOG, so there is no need to set them again while toggling from ANALOG to DIGITAL.

**Comment by patrol-cz** [comment]
Hi Daniel!
  You probably didn't catch the problem. The following steps will
reproduce it.
  1) Be tuned on a digital channel, say CHAN_A.
  2) Move to a new chanel, say CHAN_B, which is in analog mode by
  default.
  3) Use Blue+Star.
  ... You'll get a digital mode of CHAN_B but with values from CHAN_A.
You will see them on the display and they will be transmitted on the
first PTT press.
  After de-keying, they will be corrected to proper values, but it's too
late.
  Pavel

**Comment by patrol-cz** [comment]
Hi Daniel,
  I'm not sure why loadChannelData() will be called twice - at least
with the invocation patch which I described in the previous mail I
believe that it's not true, because otherwise the channel would be set
up properly, and it isn't. Of course it would be possible to add
assignment commands for all the channel properties, but I believe that
loadChannelData() is there to do exactly this, so I believe it will work
as well, and the code will be shorter (but of course will take more CPU
cycles)...

  I can't judge the beepAssist issue, my understanding of the code is at
the very start (about 2 hours of study to find the place and propose
this very simple and straightforward solution, but of course as a newbie
I may be wrong).

  WIth regards,
    Pavel

**Comment by f1rmb** [comment]
Okay, I see.
The problem is because when you de-keying, the channel is fully (re)loaded, but since the channel configuration is ANALOG, all of the TS/CC/etc are "unset" (TS1/CC0).

So, IMHO calling loadChannelData() needs to be done when switching from DIGITAL to ANALOG, only.

About the beepAssist, the MENU_STATUS_FORCE_FIRST assignment needs to be done when switching from ANALOG to DIGITAL, as it means your in DIGITAL (that's for blind operators).

Cheers.

**Comment by f1rmb** [comment]
So, the following fixes the ANALOG->DIGITAL switching problem:

```
diff --git a/firmware/source/user_interface/uiChannelMode.c b/firmware/source/user_interface/uiChannelMode.c
index af275ca4..0812ab64 100644
--- a/firmware/source/user_interface/uiChannelMode.c
+++ b/firmware/source/user_interface/uiChannelMode.c
@@ -1075,8 +1075,7 @@ static void handleEvent(uiEvent_t *ev)
                                if (trxGetMode() == RADIO_MODE_ANALOG)
                                {
                                        channelScreenChannelData.chMode = RADIO_MODE_DIGITAL;
-                                       trxSetModeAndBandwidth(channelScreenChannelData.chMode, false);
-
+                                       loadChannelData(true, false);
                                        menuChannelExitStatus |= MENU_STATUS_FORCE_FIRST;
                                }
                                else

```

**Comment by patrol-cz** [comment]
Hi Daniel!
  
> So, the following fixes the ANALOG->DIGITAL switching problem:

It was my first version of the patch :-).
However I wanted to make it even more perfect and because I was not sure
whether it doesn't forget something also for the opposite transition
(the only thing it does now is setting the CTCSS/DTSS), I realized that
calling loadChannelData in both transitions will not make any harm and
that all the code can be simplified even more by eliminating 'if' and by
using a conditional operator instead. Thank you very much for your
revision and fixing my errors. 
  So, what now ? Will you apply your patch, or should I cancel the old
pull request, make a new patch and ask for a new pull request ?

With regards,
  Pavel

**Comment by f1rmb** [comment]
Hi Pavel,

No no, you can change your modifications in this PR, and if Roger is happy with it, he will merge it.


Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
