### PR TITLE
Update timeout screenshot of incoming dev release.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by f1rmb** [comment]
Outdated

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by f1rmb** [comment]
Errr, after double checking, no, it's not outdated. I got lost somewhere ;-)

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll merge

**Comment by f1rmb** [comment]
Thanks Roger.

**Pull request merged**
