### PR TITLE
New display setting to set minimum backlight value

### PR DESCRIPTION
**Pull request by ea3ihi**
New setting to set a minimum brightness for the screen, so instead to turn completely off, it can have some brightness.

There is a new label for the display meny, and an entry in the nonvolatile settings to keep the value.

I have not tested all the languages to see if the new label fits, and in some languages i have just added the string "min" to the standard brightness setting.

I have tested it in my gd77 and it works like a charm, but now it seems i can not write my codeplug to the talkie anymore, maybe some changes need to be done in the CPS software due to the new setting in the non volatile area?

### CODE REVIEW

**Comment by f1rmb** [comment]
You should also handle the BACKLIGHT_MODE_NONE, as it should never lit the backlight.

**Comment by rogerclarkmelbourne** [comment]
I don’t understand why this is needed.

Do you want settings from 1 to 9%  or resolution of less than 10% steps?

The display can already be put into None mode, where it has no backlight at all.

**Comment by rogerclarkmelbourne** [comment]
Or is this so that the Off setting still has some intensity.

**Comment by ea3ihi** [comment]
> You should also handle the BACKLIGHT_MODE_NONE, as it should never lit the backlight.

Can you add more information about handling BACKLIGHT_MODE_NONE?

I have tested this option and enabling it did not set the brightness to 0, but instead the screen kept my "min brightness" of 8. After switching off and on again the gd77 and having the "none" option active, the screen is not lit anymore.

Do you mean that we should set the value to 0 if the "none" option is selected, so the screen light is off without the need to reboot?

**Comment by f1rmb** [comment]
Yes, in BACKLIGHT_MODE_NONE, the backlight never light up.

**Comment by ea3ihi** [comment]
I have added changes to my repository to take into account that if the setting is BACKLIGHT_MODE_NONE the backlight should be set to 0 and not to the minimum value.

Should I add a new pull request?

**Comment by rogerclarkmelbourne** [comment]
There is a merge conflict in menuDisplayOptions.c

**Comment by ea3ihi** [comment]
Yes, the conflict is due to changes in the latest merges. I will fix it and create a new pull request

**Comment by rogerclarkmelbourne** [comment]
Btw

I think I will need to ask the forum if users will understand how to use this feature, because I can’t merge features that only a few few people will use, as there is only limited ROM space for features and there are still some essential functions which still need to be written, including the SMS and also the low power usage ( cpu sleep ) functionality

**Comment by ea3ihi** [comment]
Totally understandable. I like this feature, the screen readability at values as low as 5% is very high compared to having the light completely off.

The conflicts are fixed now.

**Comment by khaytsus** [comment]
@ea3ihi Curious, is the CPS still broken with this change or did that issue go away?

**Comment by ea3ihi** [comment]
> @ea3ihi Curious, is the CPS still broken with this change or did that issue go away?

The was no such issue, i just thought something was wrong but it was just a matter of selecting a zone. After the firmware upload no zone is selected and I was a bit lost trying to go from vfo to channel mode and my channels were not there....

**Comment by ea3ihi** [comment]
Ready to merge

**Comment by ea3ihi** [comment]
In terms of ROM space, this feature just adds a byte for the settings, a new label in all the labgages and a few lines of code. I will publish a release with this feature in the forum for people to try it and give feedback. After using it for a few days now that i am testing a version which does not have it I really miss it.

**Comment by rogerclarkmelbourne** [comment]
@ea3ihi 

I have merged, but I had to make some changes to the PR files

You changed the .cproject file, which was not part of any of the functionality changes.

Before you commit any changes its best to check which files have changed, and then revert any files which have changed unnecessarily.

I find that MCUExpresso often changes the .cproject file for no reason, and I have to use git checkout firmware/.cproject to restore it

There was also a problem when uploaded this version, as the display changed to inverse video.

I think this must be because the settings magic number needed to be increased, as somehow the PR became out of sync with the changes by other people.

I hope however that its now working OK

**Comment by ea3ihi** [comment]
Nice! When new settings are added the magick number should be updated to force reverting to proper defaults. I will be more carefull with what files are added to the commits, sometimes i abuse using git commit -a

**Pull request merged**
