### PR TITLE
No tx freq limited for gd77s

### PR DESCRIPTION
**Pull request by f1rmb**
As there is no option to turn this off on the 77S, and channels are defined in the CPS, let's turn it off by default.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

Too late for me to merge and test today.

I'll merge it tomorrow

**Comment by rogerclarkmelbourne** [comment]
Daniel

Thinking about this. I don't think we should default the band limits to being off on the GD-77, because its probably mostly used by blind users and they may accidentally setup a channel thats out of band.

We should probably implement some method to change this setting via some button press when starting the radio e.g. SK2 + ORANGE, or SK1 + Orange, or perhaps SK2+PTT

BTW. Also, we seem to have lost some of the other startup  things that I thought we had in previously versions for the GD-77/DM-1801/RD-5R.  Because I thought we had some way to reset the calibration to the manufacturers original calibration, and we no longer seem to have that function.

**Comment by f1rmb** [comment]
Okay, I will had that as startup option. I've already changed the code to use SK2 only as a hotspot mode toggle (as now it spells it correctly).
You mean the one that also reset the the picture/boot melody, yep, we had that.

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
It was the call to the calibrationCheckAndCopyToCommonLocation() function, to force reload.

Cheers.

**Comment by f1rmb** [comment]
Checking the git log, you changed that one the May 9th
commit 5403651b1c29bec1b5fd54f84df3ce49a4a4d748
Author: Roger Clark <roger@rogerclark.net>
Date:   Sat May 9 08:55:16 2020 +1000

    Automatically update calibration data based on correct initial bytes in the calibration data

diff --git a/firmware/source/main.c b/firmware/source/main.c
index 3903f21c..14314f4d 100644
--- a/firmware/source/main.c
+++ b/firmware/source/main.c
@@ -169,7 +169,7 @@ void fw_main_task(void *data)
        dac_init();
 
        // We shouldn't go further if calibration related initialization has failed
-       if ((SPI_Flash_init() == false) || (calibrationInit() == false) || (calibrationCheckAndCopyToCommonLocation(buttons & BUTTON_SK2) == false))
+       if ((SPI_Flash_init() == false) || (calibrationInit() == false) || (calibrationCheckAndCopyToCommonLocation(false) == false))
        {
                showErrorMessage("CAL DATA ERROR");
                while(1U)

**Comment by rogerclarkmelbourne** [comment]
Ah.

I remember.

This was the commit after I fixed the bug for the RD-5R using the incorrect copy of calibration data.

Initially I thought I needed to add that functionality, so that RD-5R users could force the factor / official calibration to be recopied, but I found that because the first 8 bytes were always different in the incorrect copy of the calibration. The correct data was automatically copied without needing that function.


However, recently I had to change the signature bytes pattern, because some RD-5R radios have different byes in the start of the calibration data, hence the correct data is now not always copied

I should have re-instated the function to allow the user to force reloading of the official calibration data when I changed the signature bytes.

But..

Perhaps we should use some other key sequence rather than SK2 on its own.

Probably SK2 + some number key.   I know this could not be used on the GD-77S, but I don't think there will be any calibration problems on either the GD-77 or GD-77S, and people can always do the same thing by backing up the Flash and erasing our cache of the calibration and then restore that modified Flash backup.

**Pull request closed without merging**
