### PR TITLE
hold down hash while powering on to enable voice prompts.

### PR DESCRIPTION
**Pull request by vk7js**
Hold down hash while booting to enable voice prompts if they are disabled.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi Joe,

   Wrong branch. Don't use master, create a new branch from development, and choose development as PR target, as I explained you previously.

Cheers.
...
Daniel

**Comment by vk7js** [comment]
This is so painful. I meant to do it into the dev branch.

Joe

**Comment by f1rmb** [comment]
I don't think so (I don't know what your using to deal with git repo).
Just create your own branch from the development branch, with command line it's easy:

git checkout development
git checkout -b my_shiny_feature

Do whatever, commit your changes to that *current* branch, push it to your repo

git push origin my_shiny_feature

Then raise a PR, chosing Roger's development branch as target.

As I told you, this way you don't messup your own fork, as a branch, with or without merge, won't be impacted (you can't imagine how messy it could become on your side).

Cheers
...
Daniel

**Comment by vk7js** [comment]
Ok, I’ll go search for the commandline utility instead of the desktop utility which seems to assume certain defaults.

If I want to create several pull requests, can I just do the git checkout -b featureName to create separate branches based on development with each separate feature and then create pull request for each branch? Will each feature name be a separate directory copied from development? The thing is, I want to put in all my changes and then move on, rather than waiting for each pull request to be handled and then submitting the next lot.

Joe

**Comment by f1rmb** [comment]
Yeah, thats the point of making branches.
If you commit one change to your development branch, you're stuck, you can't add a new change while bidding the previous one. It works like nodes, they are independent from each other, but share their parent.
So, doing a branch per change is the way to go, and you can, locally, create another branch from development, and merge in all the changes you've made, using:

git checkout -b my_full_featured_branch
git merge origin/feature_one
git merge origin/feature_two
etc...

This way, your development branch is pristine, every single branch remain clean (and you can still making changes before PR merge). And you can also delete/abandon any branch without messing anything.

Cheers.
...
Daniel

**Comment by vk7js** [comment]
Daniel,

 

I think I’ve done this correctly, could you please take a look? There should now be several pull requests for all of the individual changes which I could do separately which had no overlaps.

 

One of the refactoring changes where I pulled out tests for voice prompt level to call site I could not do until all of these get pulled, but given the fact that changing this makes it harder to maintain if the voice prompt level needs to be adjusted, I may not end up doing it unless roger asks.

Thanks

Joe

**Comment by vk7js** [comment]
What I found was that after I used GitHub Desktop to create a branch, even if on the local machine I chose development as the parent, when I went to create the pull request, on the server the base branch was set to master and I had to manually change it. I thought that if I had created the branch with the parent as development on my local repo that when creating the pull request, it would set the parent correctly. In any case, I think I’ve worked it all out now. I look forward to your comments to confirm or correct.

Thanks

Joe

**Comment by vk7js** [comment]
Hi Daniel/anyone else who cares,

 

This branch does not work yet but I wanted your comments on why you think it might not work? The idea is that in FM Analog mode, in channel or VFO screen, hash will unconditionally open the squelch until pressed again (or another key is pressed), i.e. even if css code is on. I often want to check the signal on a frequency on a channel which usually has an rx code on it. The code looks like it should work but doesn’t. I wonder if you can see what is wrong?

 

Thanks

Joe

**Comment by f1rmb** [comment]
Hi Joe,

   We're talking on an unrelated closed PR, I can't see any new modified code here.


Cheers.
---
Daniel

**Comment by vk7js** [comment]
Hey Daniel, its on the vk7js/OpenGD77 repo, TemporaryOpenSquelch branch. Not sure how to send you a message from that experimental branch.

Joe

**Comment by HegrJan** [comment]
Is this PR closed because the wrong branch or because your PR accepting policy? I'd strongly appreciate this feature.

**Comment by vk7js** [comment]
Dear Jan,

 

I have not been able to figure out how to build the DM1801 or RD5R configurations of the project. If you could kindly download the MCU XPresso IDE listed on the GitHub wiki, and try importing the project, I’d really appreciate it. I just don’t have the time to figure it out. Being totally blind, it might be something really simple.

 

Here’s what I tried.

1.	Downloaded the MCU XPresso IDE.
2.	Chose the correct older sdk, 2.7.0, not 2.8.2 as the latter SDK doesn’t work. Note the wiki says to get the latest which was probably true at the original time of writing. Note to get the older SDK you’ll need to Show older rather than just latest SDK options in the web interface in the getting started page of the IDE.
3.	Once the SDK is installed, I downloaded the zip file from GitHub containing the current release of the source code.
4.	I used the Import from archive option of the MCU IDE.
5.	When I did this, all options under the Project menu are grayed except Clean and Build All. Both of these options work and build the OpenGD77 firmware and put it in the DebugOpenGD77 folder under the firmware folder.
6.	In the makefile in the firmware folder, you can see how to change the build configuration to build for the DM1801 etc, but once imported, the IDE doesn’t seem to consult this again so changing and rebuilding doesn’t seem to help.

That is as far as I’ve gotten in terms of trying to build for other configurations. Since I don’t have an DM1801, I haven\t bothered, but others on the list do have one and would like the newer firmware.

 

Thanks for any help.

 

Thanks

Joe

**Pull request closed without merging**
