### PR TITLE
Restore previous settings on RED key event.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
It may be better to have the originalNonVolatileSettings in some central location, so it can be used by the DisplayOptions as well. This will save a small amount of RAM

**Comment by f1rmb** [comment]
True.
I will modify this PR accordingly.

**Comment by rogerclarkmelbourne** [comment]
Perhaps rename 

uiUtilityQSOData  to

uiUtilities 

and put originalNonVolatileSettings  in that file

**Comment by f1rmb** [comment]
Okay.

**Comment by f1rmb** [comment]
Closed as #361 as been raised

**Pull request closed without merging**
