### PR TITLE
Fix missing event introduced in last related mod.

### PR DESCRIPTION
**Pull request by f1rmb**
It's required to keep track of keys, no matter what. I will update that when the new Alex keypad code will be merged, and update accordingly.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Sorry. 

I merged Alex's PR, but there is now a merge conflict.

**Comment by f1rmb** [comment]
;-)

No problem, let me update.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I checked your other PR and I am now merging

**Comment by rogerclarkmelbourne** [comment]
I also just changed main because I noticed that the "LOW BATTERY!!!" text was not localised

**Comment by f1rmb** [comment]
Okay.

**Comment by rogerclarkmelbourne** [comment]
Is this now ready to merge ?

**Comment by f1rmb** [comment]
Okay, it's fixed, and I've translated low battery for french.
Also, I reverted fix in the first commit, because of the new keypad code, but handle new condition in uiTXScreen about DTMF.

Yes, you can merge.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by rogerclarkmelbourne** [comment]
Tested and DTMF is fixed.  I also double checked 1750Hz and that is also OK.

I will post to the Localisation topic and ask the other language contributers to provide the new translation

**Comment by f1rmb** [comment]
Okay for the 1750, that's good, it shares the same code (didn't tried that, BTW, I'm lucky ;-) ).

**Pull request merged**
