### PR TITLE
Correct Frequencies for Calibration table lookup. 

### PR DESCRIPTION
**Pull request by g4eml**
Change the frequencies used to look up calibration values to use 8 digits.  (were still using old 7 digit values so lookup would not work correctly)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Colin.

I may just recode this as an equation, I've no idea why Kai wrote it that way, it looks inefficient.

**Comment by rogerclarkmelbourne** [comment]
Colin

I've posted a test version which uses a calculation instead of the load of if/else statements to get the offset value

On UHF it should be identical.
On VHF, the value changes 500Khz lower than in the official version, because if I didnt do that, it would still need one IF statement,

For Amateur band operation, its not going to make any difference, as no one should be transmitting below 144Mhz anyway.



```
void trxCalcBandAndFrequencyOffset(int *band_offset, int *freq_offset)
{
// NOTE. For crossband duplex DMR, the calibration potentially needs to be changed every time the Tx/Rx is switched over on each 30ms cycle
// But at the moment this is an unnecessary complication and I'll just use the Rx frequency to get the calibration offsets

	if (trxCurrentBand[TRX_RX_FREQ_BAND] == RADIO_BAND_UHF)
	{
		*band_offset=0x00000000;

		*freq_offset = (currentRxFrequency - 40000000)/1000000;
		/*
		if (currentRxFrequency<41000000)
		{
			*freq_offset=0x00000000;
		}
		else if (currentRxFrequency<42000000)
		{
			*freq_offset=0x00000001;
		}
		else if (currentRxFrequency<43000000)
		{
			*freq_offset=0x00000002;
		}
		else if (currentRxFrequency<44000000)
		{
			*freq_offset=0x00000003;
		}
		else if (currentRxFrequency<45000000)
		{
			*freq_offset=0x00000004;
		}
		else if (currentRxFrequency<46000000)
		{
			*freq_offset=0x00000005;
		}
		else if (currentRxFrequency<47000000)
		{
			*freq_offset=0x00000006;
		}
		else
		{
			*freq_offset=0x00000007;
		}
		*/
	}
	else
	{
		*band_offset=0x00000070;

		*freq_offset = (currentRxFrequency - 13250000)/500000;
/*
		if (currentRxFrequency<13800000)
		{
			*freq_offset=0x00000000;
		}
		else if (currentRxFrequency<14250000)
		{
			*freq_offset=0x00000001;
		}
		else if (currentRxFrequency<14750000)
		{
			*freq_offset=0x00000002;
		}
		else if (currentRxFrequency<15250000)
		{
			*freq_offset=0x00000003;
		}
		else if (currentRxFrequency<15750000)
		{
			*freq_offset=0x00000004;
		}
		else if (currentRxFrequency<16250000)
		{
			*freq_offset=0x00000005;
		}
		else if (currentRxFrequency<16850000)
		{
			*freq_offset=0x00000006;
		}
		else
		{
			*freq_offset=0x00000007;
		}*/
	}
}
```

**Comment by g4eml** [comment]
Hi Roger, 

Ideally where the frequency is used as an offset the routine that looks up the calibration value should be rewritten to interpolate between the values in the calibration tables. Switching between discrete values is a bit of a compromise. For example if the calibration value for 144MHz is 150 and the value for 148MHz is 160 then setting the radio to 146MHz should really use a value of 155.

In order to achieve this maybe the freq_offset value calculated here needs to be a floating point number. Then the lookup routine could use the integer part to index the calibration table and the fractional part to calculate the interpolation. 

Having said all that most radios seem to have been working OK with the bug which would have resulted in a using single value for the whole band so maybe the calibration is not that critical. 

Colin. 



On 11 Dec 2019, at 06:13, Roger Clark <notifications@github.com> wrote:

Colin

I've posted a test version which uses a calculation instead of the load of if/else statements to get the offset value

On UHF it should be identical.
On VHF, the value changes 500Khz lower than in the official version, because if I didnt do that, it would still need one IF statement,

For Amateur band operation, its not going to make any difference, as no one should be transmitting below 144Mhz anyway.

void trxCalcBandAndFrequencyOffset(int *band_offset, int *freq_offset)
{
// NOTE. For crossband duplex DMR, the calibration potentially needs to be changed every time the Tx/Rx is switched over on each 30ms cycle
// But at the moment this is an unnecessary complication and I'll just use the Rx frequency to get the calibration offsets

	if (trxCurrentBand[TRX_RX_FREQ_BAND] == RADIO_BAND_UHF)
	{
		*band_offset=0x00000000;

		*freq_offset = (currentRxFrequency - 40000000)/1000000;
		/*
		if (currentRxFrequency<41000000)
		{
			*freq_offset=0x00000000;
		}
		else if (currentRxFrequency<42000000)
		{
			*freq_offset=0x00000001;
		}
		else if (currentRxFrequency<43000000)
		{
			*freq_offset=0x00000002;
		}
		else if (currentRxFrequency<44000000)
		{
			*freq_offset=0x00000003;
		}
		else if (currentRxFrequency<45000000)
		{
			*freq_offset=0x00000004;
		}
		else if (currentRxFrequency<46000000)
		{
			*freq_offset=0x00000005;
		}
		else if (currentRxFrequency<47000000)
		{
			*freq_offset=0x00000006;
		}
		else
		{
			*freq_offset=0x00000007;
		}
		*/
	}
	else
	{
		*band_offset=0x00000070;

		*freq_offset = (currentRxFrequency - 13250000)/500000;
/*
		if (currentRxFrequency<13800000)
		{
			*freq_offset=0x00000000;
		}
		else if (currentRxFrequency<14250000)
		{
			*freq_offset=0x00000001;
		}
		else if (currentRxFrequency<14750000)
		{
			*freq_offset=0x00000002;
		}
		else if (currentRxFrequency<15250000)
		{
			*freq_offset=0x00000003;
		}
		else if (currentRxFrequency<15750000)
		{
			*freq_offset=0x00000004;
		}
		else if (currentRxFrequency<16250000)
		{
			*freq_offset=0x00000005;
		}
		else if (currentRxFrequency<16850000)
		{
			*freq_offset=0x00000006;
		}
		else
		{
			*freq_offset=0x00000007;
		}*/
	}
}

**Comment by rogerclarkmelbourne** [comment]
I agree the value should be interpolated, but looking at the UHF calibration values they are  values like 54,53,52,51  so interpolation would not do anything.

On VHF there does seem to be a wider range of values, so interpolation would probably improve things a bit.  However we would have to presume that the value in the calibration is intended for the mid point of that frequency range

It would be pretty easy to do linear interpolation either using integer maths or floating point. 

BTW. I checked the assembler generated by the compiler for simple floating point calculations and I think its built into the MCU. However double precision probably isn’t.


There is however a bigger problem with the current code, as the Rx freq is used in the function to retrieve the offsets, but most of the time the values that use the offsets are related to the Tx freq.

So I think it would probably be better to change the code to use the Tx freq value rather than the Rx freq. I think this is a legacy from when Kai wrote the Tier 1 version and Rx and Tx frequencies were always the same.

We’d need to carefully look at what functions used the outputs from that function, and potentially pass into the function whether the offset required was for the Tx or Rx freq.

I changed the code recently to support 220Mhz squelch settings, which snowballed into loads of changes to tidy up the way the firmware supported the 3 bands that the AT1846 supports.
So I suspect that one of my new enums can be used to reference if it’s the Rx or Tx freq that is related to the function call.

But the output from that function may potentially be used by both Rx and Tx related functions, so we may need to end up calling the function twice to get the correct results for its intended use.

Its getting too late for me to start investigating this problem today, but  should have time to investigate it tomorrow.

**Comment by g4eml** [comment]
Maybe the routine needs to calculate two bands and two offsets, one for receive and one for transmit. Then the individual calibration routines could be called with the correct band and offset for their function. As you say most calibrations are probably for transmit but there will be some that are for receive. 

I agree interpolation on UHF is probably not necessary. VHF would probably benefit though. 
I would have thought the values in the table are the values at the calibration points rather than at the mid point. I would expect the mid point to be half way between the two values. Without seeing the original calibration routine we can’t be sure though. 

Colin. 




On 11 Dec 2019, at 10:44, Roger Clark <notifications@github.com> wrote:

I agree the value should be interpolated, but looking at the UHF calibration values they are values like 54,53,52,51 so interpolation would not do anything.

On VHF there does seem to be a wider range of values, so interpolation would probably improve things a bit. However we would have to presume that the value in the calibration is intended for the mid point of that frequency range

It would be pretty easy to do linear interpolation either using integer maths or floating point.

BTW. I checked the assembler generated by the compiler for simple floating point calculations and I think its built into the MCU. However double precision probably isn’t.

There is however a bigger problem with the current code, as the Rx freq is used in the function to retrieve the offsets, but most of the time the values that use the offsets are related to the Tx freq.

So I think it would probably be better to change the code to use the Tx freq value rather than the Rx freq. I think this is a legacy from when Kai wrote the Tier 1 version and Rx and Tx frequencies were always the same.

We’d need to carefully look at what functions used the outputs from that function, and potentially pass into the function whether the offset required was for the Tx or Rx freq.

I changed the code recently to support 220Mhz squelch settings, which snowballed into loads of changes to tidy up the way the firmware supported the 3 bands that the AT1846 supports.
So I suspect that one of my new enums can be used to reference if it’s the Rx or Tx freq that is related to the function call.

But the output from that function may potentially be used by both Rx and Tx related functions, so we may need to end up calling the function twice to get the correct results for its intended use.

Its getting too late for me to start investigating this problem today, but should have time to investigate it tomorrow.

**Pull request merged**
