### PR TITLE
French lang plus lang fixes

### PR DESCRIPTION
**Pull request by f1rmb**
Add French language (accented).
Remove duplicate .built entry in all other language files.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Does this PR supersede the other one, as they both seem to include the PTT stuff ??

**Comment by f1rmb** [comment]
Hi Roger,

   No, that's the weird thing GitHub does when inherited branches happens.


---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

**Comment by rogerclarkmelbourne** [comment]
umm

Strange

I know git will handled it... But it does look strange.

**Comment by rogerclarkmelbourne** [comment]
Merged.

Thanks

**Pull request merged**
