### PR TITLE
Localisation

### PR DESCRIPTION
**Pull request by MarthG**
Fix some words, add new items translated. This up to date to my forum post (I'm EA3IGM, Carlos)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK
Thanks

I'm just adding new items for

```
.brightness			= "Brightness",
.contrast			= "Contrast",
.colour_invert		= "Color:Invert",
.colour_normal		= "Color:Normal",
```

Can you update and I will pull when I have updated DisplayOptions.c

**Comment by MarthG** [comment]
Will add, omw

**Comment by MarthG** [comment]
Done, thanks again!

**Comment by rogerclarkmelbourne** [comment]
I think some of the options texts may be too long, e.g. Things like Mic Gain, have dBM at the end of the value at the moment.

I may need to include more of the overall text into some of these, so its clearer what the total length of the text would be.

You can check when I do the next build.

**Comment by MarthG** [comment]
In spanish, "Ganancia DMR" (DMR gain) will for sure be too long, I'll edit it now
as for other things, I'll testnew firms and update on the go as needed

**Comment by rogerclarkmelbourne** [comment]
I just noticed that I need a different text for backlight timout to Tx Timeout

Because Tx Timeout is in capital letters

`.backlight_timeout	= "Timeout",`

**Comment by rogerclarkmelbourne** [comment]
There is a merge conflict because of the 

.backlight_timeout = "Timeout",

Can you pull again

**Comment by MarthG** [comment]
I think this should be it

**Comment by rogerclarkmelbourne** [comment]
Thanks

No conflicts now

I have merged

**Comment by MarthG** [comment]
Thanks again!

**Pull request merged**
