### PR TITLE
Adds UC1701_drawChoice() that displays choices above GREEN and RED buttons

### PR DESCRIPTION
**Pull request by f1rmb**
Instead of cheating printCentered() ;-)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

I'm going to push some changes to the DMR monitor, and I will pull after I have finished

**Comment by rogerclarkmelbourne** [comment]
Umm.

I think I have broken something with the DMR monitor :-(

It will take some time to fix...

**Comment by f1rmb** [comment]
;-)

No problem at all Roger, it shouldn't conflict ;-)

I also got my bunch of disappointments, with the CPS and Wine... Even
serial support is incomplete, so I have no other choice to fix all the
stuff to make it work wirh Mono.

**Comment by rogerclarkmelbourne** [comment]
Merge was OK.  Thanks...

Re: CPS

Arrgghh. I'm surprised Serial does not work :-(

I thought perhaps only USB HID would be a problem

**Comment by f1rmb** [comment]
Me either, but the underlaying framework uses some features that aren't supported, for years, and probably never be (needs huge dirty hack inside kernel driver).

**Comment by alexernst** [comment]
Funny, did the same yesterday but didn't commit.

@f1rmb If you get the CPS to work with mono I hope it works with MacOS too.

**Comment by f1rmb** [comment]
**@alexernst** about the CPS, I hope so. So you're using OS-X ?, if it's the case, can you test a version of GD-77_FirmwareLoader ? On positive, I will send you latest binary version.

**Comment by alexernst** [comment]
@f1rmb Yes, MacOS. And I can test the FirmwareLoader.

**Comment by f1rmb** [comment]
Great :-)  I will update the post on the forum then.

**Pull request merged**
