### PR TITLE
CSharp flasher: make radio type argument mandatory.

### PR DESCRIPTION
**Pull request by f1rmb**
CSharp flasher: fully disable CursorPosition thing under Windows.
Update Linux/Darwin flasher script to set GD-77 model in command line.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel.

Sorry to be a pain,  but...

Can you replace DM5R with RD5R, because I'm trying to standardise on the model number of RD5R or "RD-5R", otherwise people with older DM-5R radios may think it works with that radio. Whereas it works with all RD-5R because its what Baofeng call the DM-5R Tier 2 version, and hopefully people with newer DM-5R know its the same as the RD-5R

**Comment by f1rmb** [comment]
Hi Roger,

   Yeah, sure. I was thinking you changed all the occurrence, so I didn't take care of.

**Comment by f1rmb** [comment]
Hi Roger,

Okay, done, everything has been rename to RD?5R.
As I commented in your commit about .cproject file and OpenRD.sgl, here it will create an OpenRD5R.sgl inside its Debug_RD-5R directory. I checked with rebuild bin2sgl and mono flasher, it works (with the exception I don't have the transceiver yet).

**Comment by rogerclarkmelbourne** [comment]
Thanks.
I'll test soon

**Comment by rogerclarkmelbourne** [comment]
I have merged this. But for some reason there is a minor difference in the .cproject files, where there seems to be an empty section  between two semicolons

I will close this, because I think it is actually merged OK

**Comment by f1rmb** [comment]
Hi Roger,

   No, except the .cproject, none of the diff has been merged and pushed ;-)

Cheers.

**Comment by f1rmb** [comment]
Leave it closed, I will raise another one in a second.

**Pull request closed without merging**
