### PR TITLE
Get name of receiving TG if in stored in contacts.

### PR DESCRIPTION
**Pull request by alexernst**
Lookup receiving TG in contacts.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

BTW.

I think we'll need to get the compiler optimisation working for the Flash memory, because at the moment its going to take much longer than necessary to lookup the contact or TG from the Flash memory

If compiler optimisation is enabled, the Flash read works OK, but the Flash write is too fast and fails on some radios.

Hence some delays need to be added into the Flash write functions, but I'm not sure if the delays are to the clocking of the data, or perhaps between the Erase and the Write commands.

**Comment by alexernst** [comment]
We could read all contacts into a sorted list with PCOrTG and index at bootup or if a contact is changed, added or deleted. 
Then we could search in this list (like DMRId) and load only the needed contact from flash.

**Comment by rogerclarkmelbourne** [comment]
If we can improve the Linker LD file, we can get access to about another 32k of RAM, which would be useful to use for this.

The MK22 has 2 banks of RAM, which although they are adjacent to each other, seem to have separate linker sections.

Kai modified the default linker settings so that the firmware only has access to the upper bank of RAM because the AMBE codec uses memory in the lower bank of RAM.

However the AMBE codec only uses around 16k in the middle of the lower bank, and we could modify the linker sections to allocate the memory above the AMBE block to the firmware, which would give us approximately 16k (or perhaps more), extra RAM

Ideally we need to have 4 linker RAM sections.  

Lower bank bottom 
Lower bank middle-AMBE
Lower bank upper
Upper bank

And allocate everything except for Lower bank middle-AMBE to the firmware.


BTW.

The DMR ID lookup is very efficient, because the data is sorted by ID number by the CPS, so that the firmware can perform a binary search.
Whereas the contacts and TGs are not in numerical order, hence the lookup is much less efficient. 

Unfortunately we can't sort the contacts by ID as it would effect the UI operation when changing TG via the left and right arrows and in the Contacts screen etc

**Comment by alexernst** [comment]
The complete contact list would take 24K ram. So I thought about just storing TG/PC and idx in a separate list. This list could be sorted by TG/PC after reading as this is only done once at bootup or after changes to the contacts. That would still need 6K RAM.But the lookup will be much faster. 
And it requires only a read from the flash if the TG/PC is found.

**Comment by rogerclarkmelbourne** [comment]
Thanks

BTW.

I think we'll need to get the compiler optimisation working for the Flash memory, because at the moment its going to take much longer than necessary to lookup the contact or TG from the Flash memory

If compiler optimisation is enabled, the Flash read works OK, but the Flash write is too fast and fails on some radios.

Hence some delays need to be added into the Flash write functions, but I'm not sure if the delays are to the clocking of the data, or perhaps between the Erase and the Write commands.

**Comment by rogerclarkmelbourne** [comment]
Ooops

Sorry. I pressed the wrong button

**Comment by rogerclarkmelbourne** [comment]
I have tested and merged.  Thanks.

**Comment by alexernst** [comment]
> However the AMBE codec only uses around 16k in the middle of the lower bank, and we could modify the linker sections to allocate the memory above the AMBE block to the firmware, which would give us approximately 16k (or perhaps more), extra RAM
> 
> Ideally we need to have 4 linker RAM sections.
> 
> Lower bank bottom
> Lower bank middle-AMBE
> Lower bank upper
> Upper bank
> 
> And allocate everything except for Lower bank middle-AMBE to the firmware.
> 
Do you know which part of the RAM is used by the AMBE codec?

**Comment by rogerclarkmelbourne** [comment]
I did some tests a few months ago to analyse what memory was used by the AMBE codec in both Rx and Tx, but at the moment I can't find that data :-(

If I can't find the RAM dump files from my test, I will need to re-run the test.

**Comment by rogerclarkmelbourne** [comment]
I've re-run the tests

The RAM used by the AMBE encoder and decoder code appears to be 

0x1FFF6B60 - 0x1FFF8D87

which us just over 8k

I don't have any experience authoring linker files but I think that firmware_memory.ld probably need to be changed to

```
MEMORY
{
  /* Define each memory region */
  PROGRAM_FLASH (rx) : ORIGIN = 0x4000, LENGTH = 0x7B800 /* 0x00004000-0x007f7ff (alias Flash) */  
  SRAM_UPPER (rwx) : ORIGIN = 0x20000000, LENGTH = 0x10000 /* 64K bytes (alias RAM) */  
  SRAM_LOWER_BASE (rwx) : ORIGIN = 0x1fff0000, LENGTH = 0x6B60 /*  bytes (alias RAM2_BASE) */  
  SRAM_LOWER_AMBE (rwx) : ORIGIN = 0x1fff6B60, LENGTH = 0x2228 /*  bytes (alias RAM2_AMBE) */ 
  SRAM_LOWER_TOP (rwx) : ORIGIN = 0x1fffF8D88, LENGTH = 0x7278 /* bytes (alias RAM2_TOP) */ 
}
```


Then in firmware.ld  , all references to SRAM_LOWER need to be changed to SRAM_LOWER_AMBE

I tried this and the firmware still runs, but many more things also need to be changed in firmware.ld so that the other memory can be used.

Probably the best way to know how the RAM sections are normally configured is to look in the SDK examples.

BTW. I noticed that the MCUExpresso project also defines the memory sections. But I think that the the MCUExpresso only initially generates the linker files using that data, and that Kai has subsequently edited the linker files after they were generated by the project.

So we can't simply modify the project memory sections and delete the linker files, because the AMBE program memory sections that have also been added by Kai would be removed.

One possible way however to generate the new RAM linker sections, is to modify a SDK example have 3 RAM sections for the lower bank of RAM and then make the project re-generate the linker file, and then use those sections (except the AMBE section) in the OpenGD77 firmware linker file.

**Comment by alexernst** [comment]
Thanks Roger

I've done some editing to the linkerscripts.

The lower SRAM is now divided in three sections. 
So far heap and stack are now in the lower SRAM freeing up some space in the upper SRAM. But i couldn't get the bss to be in two separate RAM sections. 
Only one sections is used. 

It seems to be possible to assign variables to specific sections but automatic assignment would be better.


BTW 
How did you read the sram? I couldn't find a function for this in MCUExpresso.

**Comment by rogerclarkmelbourne** [comment]
I don’t know how to access the SRAM. Did you look in the SDK examples ?

I can post a question on the NXP forum, but it’s not very active, so I may not get a reply

**Pull request merged**
